package flows

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"
)

// TypeAIStep is the single-call AI node.
const TypeAIStep = "ai.step"

// Limits of the AI node. Every one of them guards a cost or a memory risk: the
// prompt is sent to a paid model, the declared fields go into the schema and the
// system prompt, and the model's answer is parsed (json.Unmarshal cannot be
// cancelled and needs a multiple of the input in memory).
const (
	// maxAIFields caps the declared output fields of one node.
	maxAIFields = 50
	// maxAIFieldNameLen is the longest field name; aiFieldPattern enforces it too.
	maxAIFieldNameLen = 40
	// maxAIFieldDescRunes caps the description of one field, which goes to the model.
	maxAIFieldDescRunes = 500
	// maxAIPromptBytes caps the resolved prompt plus instructions. A template can
	// assemble up to 8 MiB; that would be sent to a paid model and fail there anyway.
	maxAIPromptBytes = 256 << 10
	// maxAIModelBytes caps the model name chosen by a parameter.
	maxAIModelBytes = 200
	// maxAIResponseBytes caps the text of the model's answer before it is parsed or
	// used as output.
	maxAIResponseBytes = 1 << 20
	// maxAIProblemRunes caps how much of a problem description goes back to the
	// model in the repair prompt and into the error message.
	maxAIProblemRunes = 300
	// maxAIJSONCandidates is how many opening braces extractJSONObject tries when it
	// looks for the answer's JSON object inside prose.
	maxAIJSONCandidates = 8
)

var (
	aiFieldPattern  = regexp.MustCompile(`^[a-z_][a-z0-9_]{0,39}$`)
	aiFieldTypes    = map[string]string{"text": "string", "number": "number", "bool": "boolean", "list": "array"}
	aiReservedNames = map[string]bool{"tokens": true, "model": true}
)

type aiField struct {
	Name        string
	Type        string
	Description string
}

// RegisterAINodes registers the AI nodes of phase 1.
func RegisterAINodes(reg *Registry) error {
	return reg.Register(aiStepDef())
}

// aiStepDef defines ai.step. Its output is generated by a model that reads whatever
// the flow feeds it, web pages and mails included, so a prompt injection can steer
// it: UntrustedOutput makes the lint treat the result like web data (the same
// decision as for the mission_completed trigger). The prompt itself is deliberately
// not a sensitive sink: summarising untrusted text is the node's main job, and a
// warning for it would be noise. The node has no outward effect of its own.
func aiStepDef() *NodeDef {
	def := &NodeDef{
		Type: TypeAIStep, Version: 1, Category: "ai", Icon: "sparkles", Color: "ai",
		LabelKey: "easydrag.node.ai_step.label", DescriptionKey: "easydrag.node.ai_step.description",
		SummaryKey: "easydrag.node.ai_step.summary", UntrustedOutput: true, DefaultTimeout: 300 * time.Second,
		PrimaryInput: "prompt",
		Params: []ParamSpec{
			{Name: "prompt", Kind: ParamTextarea, LabelKey: "easydrag.param.ai_prompt", Required: true, Templatable: true},
			{Name: "instructions", Kind: ParamTextarea, LabelKey: "easydrag.param.ai_instructions", Templatable: true},
			{Name: "output_mode", Kind: ParamSegmented, LabelKey: "easydrag.param.ai_output_mode", Default: "text",
				Options: []Option{option("text", "ai_output_text"), option("fields", "ai_output_fields")}},
			{Name: "fields", Kind: ParamFields, LabelKey: "easydrag.param.ai_fields", Required: true,
				VisibleIf: &Visibility{Param: "output_mode", Equals: []string{"fields"}},
				Fields: []ParamSpec{
					{Name: "name", Kind: ParamText, LabelKey: "easydrag.param.field_name", Required: true},
					{Name: "type", Kind: ParamSelect, LabelKey: "easydrag.param.field_type", Default: "text",
						Options: []Option{option("text", "type_text"), option("number", "type_number"), option("bool", "type_bool"), option("list", "type_list")}},
					{Name: "description", Kind: ParamText, LabelKey: "easydrag.param.field_description"},
				}},
			{Name: "model", Kind: ParamSelect, LabelKey: "easydrag.param.ai_model", OptionsSource: "ai_models", Default: ""},
		},
	}
	def.OutputFieldsFunc = func(n *Node) []FieldSpec {
		var params map[string]any
		if n != nil {
			params = n.Params
		}
		tail := []FieldSpec{{Name: "tokens", Type: "object"}, {Name: "model", Type: "text"}}
		if !aiFieldsMode(params) {
			return append([]FieldSpec{{Name: "text", Type: "text", Primary: true}}, tail...)
		}
		var out []FieldSpec
		for i, f := range aiFields(params["fields"]) {
			out = append(out, FieldSpec{Name: f.Name, Type: f.Type, Primary: i == 0})
		}
		return append(out, tail...)
	}
	def.Validate = validateAIFields
	def.Execute = executeAIStep
	return def
}

// aiFieldsMode reports whether the node returns structured fields. Anything but
// the text "fields" means text mode.
func aiFieldsMode(params map[string]any) bool {
	mode, _ := params["output_mode"].(string)
	return mode == "fields"
}

// aiScalar renders a scalar parameter value as text: nil is "", text stays text,
// booleans and numbers use their natural form. Lists, objects and every other type
// report false. The hooks see raw parameters of any type, and encoding a huge or
// cyclic value just to complain about it would cost more than the complaint is worth.
func aiScalar(v any) (string, bool) {
	switch x := v.(type) {
	case nil:
		return "", true
	case string:
		return x, true
	case bool, float64, float32, int, int64, json.Number:
		return Stringify(x), true
	}
	return "", false
}

// aiFields returns the output fields the node can really produce, for the editor's
// field list: at most maxAIFields entries, and not those without a usable name
// (blank, malformed, reserved or repeated; the validator reports them). A type
// that is not one of the four becomes text.
func aiFields(v any) []aiField {
	list, _ := v.([]any)
	if len(list) > maxAIFields {
		list = list[:maxAIFields]
	}
	out := make([]aiField, 0, len(list))
	seen := map[string]bool{}
	for _, item := range list {
		m, _ := item.(map[string]any)
		text, ok := aiScalar(m["name"])
		name := strings.TrimSpace(text)
		if !ok || !aiNameUsable(name) || seen[name] {
			continue
		}
		seen[name] = true
		typ, _ := aiScalar(m["type"])
		if aiFieldTypes[typ] == "" {
			typ = "text"
		}
		desc, _ := aiScalar(m["description"])
		out = append(out, aiField{Name: name, Type: typ, Description: strings.TrimSpace(desc)})
	}
	return out
}

// aiNameUsable reports whether name is a well-formed, unreserved field name.
func aiNameUsable(name string) bool {
	return name != "" && len(name) <= maxAIFieldNameLen && aiFieldPattern.MatchString(name) && !aiReservedNames[name]
}

// aiFieldProblem is one thing wrong with the declared output fields. code is
// IssueParamRequired or IssueParamInvalid and param a display path such as
// "fields[2].name".
type aiFieldProblem struct {
	code  string
	param string
	msg   string
}

// aiFieldProblems checks the declared fields of a node in fields mode. The
// validator turns the problems into issues and Execute fails on the first one, so
// a published flow and a test run of a draft follow the same rules. params is raw
// and may hold anything: the check looks at most at maxAIFields entries, never
// encodes a value, and echoes user text only through quoteForError.
func aiFieldProblems(params map[string]any) []aiFieldProblem {
	raw := params["fields"]
	if raw == nil {
		return nil
	}
	list, ok := raw.([]any)
	if !ok {
		return []aiFieldProblem{{IssueParamInvalid, "fields", "the output fields must be a list"}}
	}
	var out []aiFieldProblem
	if len(list) > maxAIFields {
		out = append(out, aiFieldProblem{IssueParamInvalid, "fields", fmt.Sprintf("at most %d output fields are allowed", maxAIFields)})
		list = list[:maxAIFields]
	}
	seen := map[string]bool{}
	for i, item := range list {
		m, _ := item.(map[string]any)
		add := func(code, field, msg string) {
			out = append(out, aiFieldProblem{code, fmt.Sprintf("fields[%d].%s", i, field), msg})
		}
		text, ok := aiScalar(m["name"])
		name := strings.TrimSpace(text)
		switch {
		case !ok:
			add(IssueParamInvalid, "name", "the field name must be text")
		case name == "":
			add(IssueParamRequired, "name", "field name is required")
		case len(name) > maxAIFieldNameLen || !aiFieldPattern.MatchString(name):
			add(IssueParamInvalid, "name", fmt.Sprintf("use lowercase letters, digits and _ in field names, at most %d characters", maxAIFieldNameLen))
		case aiReservedNames[name]:
			add(IssueParamInvalid, "name", quoteForError(name)+" is reserved")
		case seen[name]:
			add(IssueParamInvalid, "name", "duplicate field name "+quoteForError(name))
		default:
			seen[name] = true
		}
		if typ, ok := aiScalar(m["type"]); !ok {
			add(IssueParamInvalid, "type", "the field type must be one of text, number, bool or list")
		} else if typ != "" && aiFieldTypes[typ] == "" {
			add(IssueParamInvalid, "type", "unknown field type "+quoteForError(typ))
		}
		if desc, ok := aiScalar(m["description"]); !ok {
			add(IssueParamInvalid, "description", "the field description must be text")
		} else if utf8.RuneCountInString(strings.TrimSpace(desc)) > maxAIFieldDescRunes {
			add(IssueParamInvalid, "description", fmt.Sprintf("the field description may have at most %d characters", maxAIFieldDescRunes))
		}
	}
	return out
}

// aiModeKnown reports whether v is a usable output mode: absent or empty (text),
// "text" or "fields". Anything else would silently run as text.
func aiModeKnown(v any) bool {
	switch x := v.(type) {
	case nil:
		return true
	case string:
		return x == "" || x == "text" || x == "fields"
	}
	return false
}

func validateAIFields(n *Node, _ ValidateContext) []Issue {
	if n == nil {
		return nil
	}
	var issues []Issue
	// A template is resolved at run time and cannot be judged here.
	if mode := n.Params["output_mode"]; !aiModeKnown(mode) {
		if s, isText := mode.(string); !isText || !HasTemplate(s) {
			issues = append(issues, paramIssue(n, IssueParamInvalid, SeverityError, "output_mode", "the output mode must be text or fields"))
		}
	}
	if !aiFieldsMode(n.Params) {
		return issues
	}
	for _, p := range aiFieldProblems(n.Params) {
		issues = append(issues, paramIssue(n, p.code, SeverityError, p.param, p.msg))
	}
	return issues
}

func executeAIStep(ctx context.Context, in ExecInput) (ExecResult, error) {
	if in.Services == nil || in.Services.LLM == nil {
		return ExecResult{}, NewNodeError("FLOW_AI_UNAVAILABLE", "no AI model is configured")
	}
	prompt := strings.TrimSpace(Stringify(in.Params["prompt"]))
	if prompt == "" {
		return ExecResult{}, NewNodeError("FLOW_PARAM_INVALID", "the prompt is empty")
	}
	system := strings.TrimSpace(Stringify(in.Params["instructions"]))
	if size := len(prompt) + len(system); size > maxAIPromptBytes {
		return ExecResult{}, NewNodeError("FLOW_PARAM_INVALID", "the prompt and instructions together are %d bytes; the limit is %d", size, maxAIPromptBytes)
	}
	model := strings.TrimSpace(Stringify(in.Params["model"]))
	if len(model) > maxAIModelBytes {
		return ExecResult{}, NewNodeError("FLOW_PARAM_INVALID", "the model name is %d bytes; the limit is %d", len(model), maxAIModelBytes)
	}
	if !aiModeKnown(in.Params["output_mode"]) {
		return ExecResult{}, NewNodeError("FLOW_PARAM_INVALID", "output_mode must be text or fields")
	}
	llm := in.Services.LLM
	req := LLMRequest{
		FlowID: in.Run.FlowID, RunID: in.Run.ID, NodeID: nodeIDOf(in),
		System: system, Prompt: prompt, Model: model,
	}
	if !aiFieldsMode(in.Params) {
		resp, err := aiCall(ctx, llm, req)
		if err != nil {
			return ExecResult{}, err
		}
		text := strings.TrimSpace(resp.Text)
		if text == "" {
			return ExecResult{}, NewNodeError("FLOW_AI_OUTPUT_INVALID", "the model returned an empty answer")
		}
		return ExecResult{Output: aiOutput(map[string]any{"text": text}, resp)}, nil
	}
	if problems := aiFieldProblems(in.Params); len(problems) > 0 {
		return ExecResult{}, NewNodeError("FLOW_PARAM_INVALID", "%s: %s", problems[0].param, problems[0].msg)
	}
	fields := aiFields(in.Params["fields"])
	if len(fields) == 0 {
		return ExecResult{}, NewNodeError("FLOW_PARAM_INVALID", "define at least one output field")
	}
	req.JSONSchema = aiSchema(fields)
	names := make([]string, len(fields))
	for i, f := range fields {
		names[i] = f.Name
	}
	req.System = strings.TrimSpace(req.System + "\n\nAnswer with exactly one JSON object with the fields: " + strings.Join(names, ", ") + "." + aiFieldHints(fields))
	var lastErr error
	var inputTokens, outputTokens int // every attempt is paid for
	for attempt := 0; attempt < 2; attempt++ {
		resp, err := aiCall(ctx, llm, req)
		if err != nil {
			return ExecResult{}, err
		}
		inputTokens += resp.InputTokens
		outputTokens += resp.OutputTokens
		values, verr := coerceAIFields(resp, fields)
		if verr == nil {
			resp.InputTokens, resp.OutputTokens = inputTokens, outputTokens
			return ExecResult{Output: aiOutput(values, resp)}, nil
		}
		lastErr = verr
		req.Prompt = prompt + "\n\nYour previous answer was invalid (" + aiProblemText(verr) + "). Reply again with only the JSON object."
	}
	return ExecResult{}, NewNodeError("FLOW_AI_OUTPUT_INVALID", "%s", aiProblemText(lastErr))
}

// aiCall makes one LLM call. It fails on a cancelled context before spending
// anything, turns the stepper's error into a NodeError with a valid, cut message
// (a typed nil error included; the code of a NodeError is kept, for example
// FLOW_BUDGET_EXCEEDED), refuses answer text over maxAIResponseBytes with
// FLOW_OUTPUT_TOO_LARGE (a retry would cost the same again) and makes the text and
// the model name valid UTF-8. The error is nil or a non-nil *NodeError.
func aiCall(ctx context.Context, llm LLMStepper, req LLMRequest) (LLMResponse, error) {
	if err := ctx.Err(); err != nil {
		return LLMResponse{}, invokeError(err)
	}
	resp, err := llm.Step(ctx, req)
	if err != nil {
		return LLMResponse{}, invokeError(err)
	}
	if len(resp.Text) > maxAIResponseBytes {
		return LLMResponse{}, NewNodeError("FLOW_OUTPUT_TOO_LARGE", "the AI answer is %d bytes; the limit is %d", len(resp.Text), maxAIResponseBytes)
	}
	resp.Text = validUTF8(resp.Text)
	resp.Model = validUTF8(resp.Model)
	return resp, nil
}

// aiProblemText renders why an answer was invalid for the repair prompt and the
// error message: valid UTF-8 and at most maxAIProblemRunes runes, whatever the
// problem quotes.
func aiProblemText(err error) string {
	return truncateRunes(validUTF8(err.Error()), maxAIProblemRunes)
}

// aiFieldHints describes the declared fields to the model, one line each:
// "- name (type): description". The JSON schema alone does not reach every
// provider (an adapter may only use it to switch on JSON mode), so the system
// prompt carries the types and descriptions too. A description is flattened to one
// line. The field and description caps bound the result.
func aiFieldHints(fields []aiField) string {
	var sb strings.Builder
	for _, f := range fields {
		typ := aiFieldTypes[f.Type]
		if f.Type == "list" {
			typ = "array of strings"
		}
		sb.WriteString("\n- " + f.Name + " (" + typ + ")")
		if desc := strings.Join(strings.Fields(f.Description), " "); desc != "" {
			sb.WriteString(": " + desc)
		}
	}
	return sb.String()
}

// aiSchema is the JSON schema of the answer. The schema object is read-only and is
// shared by the attempts of one run.
func aiSchema(fields []aiField) map[string]any {
	props := map[string]any{}
	required := make([]any, 0, len(fields))
	for _, f := range fields {
		prop := map[string]any{"type": aiFieldTypes[f.Type]}
		if f.Type == "list" {
			prop["items"] = map[string]any{"type": "string"}
		}
		if f.Description != "" {
			prop["description"] = f.Description
		}
		props[f.Name] = prop
		required = append(required, f.Name)
	}
	return map[string]any{"type": "object", "properties": props, "required": required, "additionalProperties": false}
}

func coerceAIFields(resp LLMResponse, fields []aiField) (map[string]any, error) {
	obj := resp.JSON
	if obj == nil {
		parsed, ok := extractJSONObject(resp.Text)
		if !ok {
			return nil, fmt.Errorf("the answer is not a JSON object")
		}
		obj = parsed
	}
	out := make(map[string]any, len(fields)+2)
	for _, f := range fields {
		v, ok := obj[f.Name]
		if !ok || v == nil {
			return nil, fmt.Errorf("field %s is missing", quoteForError(f.Name))
		}
		switch f.Type {
		case "number":
			n, ok := toNumber(v)
			if !ok {
				return nil, fmt.Errorf("field %s is not a number", quoteForError(f.Name))
			}
			out[f.Name] = n
		case "bool":
			switch x := v.(type) {
			case bool:
				out[f.Name] = x
			case string:
				s := strings.ToLower(strings.TrimSpace(x))
				if s != "true" && s != "false" {
					return nil, fmt.Errorf("field %s is not true or false", quoteForError(f.Name))
				}
				out[f.Name] = s == "true"
			default:
				return nil, fmt.Errorf("field %s is not true or false", quoteForError(f.Name))
			}
		case "list":
			list, ok := v.([]any)
			if !ok {
				return nil, fmt.Errorf("field %s is not a list", quoteForError(f.Name))
			}
			out[f.Name] = list
		default:
			out[f.Name] = validUTF8(Stringify(v))
		}
	}
	return out, nil
}

// extractJSONObject finds the answer's JSON object in text that can hold prose, code
// fences, braces of its own and several objects. It decodes one JSON value at each of
// the first maxAIJSONCandidates opening braces and returns the first that is an object;
// whatever follows it is ignored. Trying only a few braces keeps the cost at a few
// scans of the text, which is capped at maxAIResponseBytes (longer text is not parsed).
func extractJSONObject(text string) (map[string]any, bool) {
	if len(text) > maxAIResponseBytes {
		return nil, false
	}
	s := strings.TrimSpace(text)
	pos := 0
	for tries := 0; tries < maxAIJSONCandidates; tries++ {
		i := strings.IndexByte(s[pos:], '{')
		if i < 0 {
			break
		}
		start := pos + i
		var m map[string]any
		if err := json.NewDecoder(strings.NewReader(s[start:])).Decode(&m); err == nil && m != nil {
			return m, true
		}
		pos = start + 1
	}
	return nil, false
}

func aiOutput(values map[string]any, resp LLMResponse) map[string]any {
	values["tokens"] = map[string]any{"input": float64(resp.InputTokens), "output": float64(resp.OutputTokens)}
	values["model"] = resp.Model
	return values
}
