package memory

import (
	"fmt"
	"regexp"
	"strings"
)

var (
	coreMemoryDatedEntryPattern = regexp.MustCompile(`^\[?\d+\]?\s*\d{4}-\d{2}-\d{2}\s*:`)
	coreMemoryPathArtifact      = regexp.MustCompile(`(?i)(^|\s)(/home/[^,\s]+|/data/audio/[^,\s]+|agent_workspace/[^,\s]+|apps/[a-z0-9_-]+\.html)(\s|,|$)`)
)

// ValidateCoreMemoryFact rejects facts that are useful history, logs, media
// registry metadata, tool state, or task context rather than durable profile or
// environment facts. Core memory is injected into every prompt, so this policy
// is intentionally a negative filter: legitimate durable facts remain allowed,
// while known transient classes are pushed to journal/LTM/episodic storage.
func ValidateCoreMemoryFact(fact string) error {
	normalized := strings.Join(strings.Fields(strings.TrimSpace(fact)), " ")
	if normalized == "" {
		return fmt.Errorf("core memory fact is empty")
	}
	lower := strings.ToLower(normalized)

	if coreMemoryDatedEntryPattern.MatchString(lower) {
		return fmt.Errorf("dated activity/history entries belong in the journal, not core memory")
	}
	if coreMemoryPathArtifact.MatchString(lower) {
		return fmt.Errorf("runtime file paths and app artifacts belong in operational memory, not core memory")
	}

	if hasAnyCoreMemoryMarker(lower, transientCoreMemoryCategoryMarkers) {
		return fmt.Errorf("transient memory category markers are not allowed in core memory")
	}
	if hasAnyCoreMemoryMarker(lower, transientCoreMemoryMediaMarkers) {
		return fmt.Errorf("media generation and registry events belong in the media registry or journal, not core memory")
	}
	if hasAnyCoreMemoryMarker(lower, transientCoreMemoryTaskMarkers) {
		return fmt.Errorf("task-local operational details belong in journal or episodic memory, not core memory")
	}
	if isCoreMemoryToolStateClaim(lower) {
		return fmt.Errorf("tool availability and transient failure state must not be stored in core memory")
	}
	return nil
}

var transientCoreMemoryCategoryMarkers = []string{
	"[recent_operational_details]",
	"[activity_entity]",
	"[operation]",
	"[tool]",
	"[project]",
	"[project_name]",
	"[git_repository_output]",
	"[test_file_output]",
}

var transientCoreMemoryMediaMarkers = []string{
	"media registry id",
	"uploaded to koofr",
	"hochgeladen auf koofr",
	"generated by minimax",
	"image generation failed",
	"weekly usage limit",
	"usage limit exceeded",
	"resets at ",
	"reset scheduled",
	"self-portrait",
	"music_",
	".mp3",
	".wav",
	".jpeg",
	".jpg",
	".png",
	"duration:",
	"dauer:",
}

var transientCoreMemoryTaskMarkers = []string{
	"app_id:",
	"widget_id:",
	"local:",
	"lokal:",
	"created \"",
	"created ai ",
	"erstellt \"",
	"previously existed",
	"rebuilt from scratch",
	"was rebuilt",
	"background agent loop failed",
	"context deadline exceeded",
	"context canceled",
	"no such file or directory",
	"not found",
}

func hasAnyCoreMemoryMarker(text string, markers []string) bool {
	for _, marker := range markers {
		if strings.Contains(text, marker) {
			return true
		}
	}
	return false
}

func isCoreMemoryToolStateClaim(text string) bool {
	hasToolSubject := strings.Contains(text, "tool") ||
		strings.Contains(text, "integration") ||
		strings.Contains(text, "virtual_desktop") ||
		strings.Contains(text, "native function") ||
		strings.Contains(text, "provider-invalid")
	if !hasToolSubject {
		return false
	}
	stateTerms := []string{
		"failed", "failing", "failure", "error", "unavailable", "not available",
		"unsupported", "invalid", "disabled", "enabled", "configured",
		"fehlgeschlagen", "fehler", "kaputt", "nicht verfügbar", "aktiviert", "konfiguriert",
	}
	return hasAnyCoreMemoryMarker(text, stateTerms)
}
