package memory

import (
	"fmt"
	"regexp"
	"strings"
)

var (
	coreMemoryDatedEntryPattern = regexp.MustCompile(`^\[?\d+\]?\s*\d{4}-\d{2}-\d{2}\s*:`)
	coreMemoryPathArtifact      = regexp.MustCompile(`(?i)(^|\s)(/home/[^,\s]+|/data/audio/[^,\s]+|agent_workspace/[^,\s]+|apps/[a-z0-9_-]+\.html)(\s|,|$)`)
	coreMemoryOperationalDate   = regexp.MustCompile(`(?i)\b(?:\d{4}-\d{2}-\d{2}|\d{1,2}\.\d{1,2}\.?(?:\d{2,4})?)\b`)
	coreMemoryOperationalID     = regexp.MustCompile(`(?i)\bmission_[a-z0-9_]+\b|\bsite-id:\s*[a-f0-9-]{8,}`)
	coreMemoryHTTPStatus        = regexp.MustCompile(`(?i)\bhttp\s+[45]\d\d\b`)
	coreMemoryIPv4              = regexp.MustCompile(`\b(?:\d{1,3}\.){3}\d{1,3}\b`)
)

// ValidateCoreMemoryFact rejects facts that are useful history, logs, media
// registry metadata, tool state, or task context rather than durable profile or
// environment facts. Core memory is injected into every prompt, so this policy
// is intentionally a negative filter: legitimate durable facts remain allowed,
// while known transient classes are pushed to journal/LTM/episodic storage.
func ValidateCoreMemoryFact(fact string) error {
	normalized := strings.Join(strings.Fields(strings.TrimSpace(fact)), " ")
	if normalized == "" {
		return fmt.Errorf("core memory fact is empty")
	}
	lower := strings.ToLower(normalized)

	if coreMemoryDatedEntryPattern.MatchString(lower) {
		return fmt.Errorf("dated activity/history entries belong in the journal, not core memory")
	}
	if coreMemoryPathArtifact.MatchString(lower) {
		return fmt.Errorf("runtime file paths and app artifacts belong in operational memory, not core memory")
	}

	if hasAnyCoreMemoryMarker(lower, transientCoreMemoryCategoryMarkers) {
		return fmt.Errorf("transient memory category markers are not allowed in core memory")
	}
	if hasAnyCoreMemoryMarker(lower, transientCoreMemoryMediaMarkers) {
		return fmt.Errorf("media generation and registry events belong in the media registry or journal, not core memory")
	}
	if hasAnyCoreMemoryMarker(lower, transientCoreMemoryTaskMarkers) {
		return fmt.Errorf("task-local operational details belong in journal or episodic memory, not core memory")
	}
	if isCoreMemoryOperationalSnapshot(lower) {
		return fmt.Errorf("operational run status and deployment snapshots belong in journal or activity memory, not core memory")
	}
	if isCoreMemoryNetworkDiscovery(lower) {
		return fmt.Errorf("network and device discoveries belong in inventory, knowledge graph, or journal, not core memory")
	}
	if isCoreMemoryToolStateClaim(lower) {
		return fmt.Errorf("tool availability and transient failure state must not be stored in core memory")
	}
	return nil
}

var transientCoreMemoryCategoryMarkers = []string{
	"[recent_operational_details]",
	"[activity_entity]",
	"[operation]",
	"[tool]",
	"[project]",
	"[project_name]",
	"[git_repository_output]",
	"[test_file_output]",
}

var transientCoreMemoryMediaMarkers = []string{
	"media registry id",
	"uploaded to koofr",
	"hochgeladen auf koofr",
	"generated by minimax",
	"image generation failed",
	"weekly usage limit",
	"usage limit exceeded",
	"resets at ",
	"reset scheduled",
	"self-portrait",
	"music_",
	".mp3",
	".wav",
	".jpeg",
	".jpg",
	".png",
	"duration:",
	"dauer:",
}

var transientCoreMemoryTaskMarkers = []string{
	"app_id:",
	"widget_id:",
	"local:",
	"lokal:",
	"created \"",
	"created ai ",
	"erstellt \"",
	"previously existed",
	"rebuilt from scratch",
	"was rebuilt",
	"background agent loop failed",
	"context deadline exceeded",
	"context canceled",
	"no such file or directory",
	"not found",
}

var transientCoreMemoryOperationalMarkers = []string{
	"aktualisiert am",
	"aktualisierung",
	"artikel mit quellen",
	"bot-token prüfen",
	"build erfolgreich",
	"build successful",
	"caddy reload",
	"caddy-container",
	"container neu geladen",
	"deploy state",
	"docker-leichen",
	"erfolgreich gesendet",
	"health-check",
	"heartbeat",
	"ki-news",
	"letzter lauf",
	"live-verifikation",
	"lokaler preview",
	"mission abgeschlossen",
	"mission completed",
	"netlify-deploy",
	"port-problem",
	"port-scan",
	"problem ist behoben",
	"state: ready",
	"tts-begr",
	"updated on",
	"zuletzt gesehen",
}

var transientCoreMemoryOperationalContextMarkers = []string{
	"api",
	"artikel",
	"build",
	"deploy",
	"geladen",
	"health",
	"ki news",
	"last run",
	"letzter lauf",
	"mission",
	"modell",
	"netlify",
	"ollama",
	"port ",
	"ready",
	"seite",
	"site",
	"stand ",
	"success",
	"reload",
}

var transientCoreMemoryNetworkDiscoveryMarkers = []string{
	"chromecast",
	"device",
	"erreichbar",
	"gerät",
	"google home",
	"ip ",
	"port ",
	"port-scan",
	"reachable",
	"smb",
	"tts",
	"windows",
}

func hasAnyCoreMemoryMarker(text string, markers []string) bool {
	for _, marker := range markers {
		if strings.Contains(text, marker) {
			return true
		}
	}
	return false
}

func isCoreMemoryOperationalSnapshot(text string) bool {
	if hasAnyCoreMemoryMarker(text, transientCoreMemoryOperationalMarkers) {
		return true
	}
	if coreMemoryOperationalID.MatchString(text) || coreMemoryHTTPStatus.MatchString(text) {
		return true
	}
	return coreMemoryOperationalDate.MatchString(text) &&
		hasAnyCoreMemoryMarker(text, transientCoreMemoryOperationalContextMarkers)
}

func isCoreMemoryNetworkDiscovery(text string) bool {
	return coreMemoryIPv4.MatchString(text) &&
		hasAnyCoreMemoryMarker(text, transientCoreMemoryNetworkDiscoveryMarkers)
}

func isCoreMemoryToolStateClaim(text string) bool {
	hasToolSubject := strings.Contains(text, "tool") ||
		strings.Contains(text, "integration") ||
		strings.Contains(text, "virtual_desktop") ||
		strings.Contains(text, "native function") ||
		strings.Contains(text, "provider-invalid") ||
		strings.Contains(text, "send_notification") ||
		strings.Contains(text, "ntfy") ||
		strings.Contains(text, "telegram") ||
		strings.Contains(text, "discord") ||
		strings.Contains(text, "pushover") ||
		strings.Contains(text, "rocketchat") ||
		strings.Contains(text, "ddg_search")
	if !hasToolSubject {
		return false
	}
	stateTerms := []string{
		"failed", "failing", "failure", "error", "unavailable", "not available",
		"unsupported", "invalid", "disabled", "enabled", "configured",
		"fehlgeschlagen", "fehler", "kaputt", "nicht verfügbar", "deaktiviert",
		"aktiviert", "konfiguriert", "verfügbar", "reachable", "immer aktiv",
	}
	return hasAnyCoreMemoryMarker(text, stateTerms)
}

type CoreMemoryReviewIssue struct {
	Index  int    `json:"index"`
	Fact   string `json:"fact"`
	Reason string `json:"reason"`
}

// ReviewCoreMemoryFacts identifies existing core-memory entries that should be
// manually cleaned up. It is report-only: callers must not delete or move data
// automatically based on this classification.
func ReviewCoreMemoryFacts(facts []string) []CoreMemoryReviewIssue {
	issues := make([]CoreMemoryReviewIssue, 0)
	for i, fact := range facts {
		if err := ValidateCoreMemoryFact(fact); err != nil {
			issues = append(issues, CoreMemoryReviewIssue{
				Index:  i,
				Fact:   fact,
				Reason: err.Error(),
			})
		}
	}
	return issues
}
