package memory

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

// JournalEntry represents a single event in the agent's journal timeline.
type JournalEntry struct {
	ID            int64    `json:"id"`
	EntryType     string   `json:"entry_type"` // milestone, learning, decision, error, preference, task_completed, integration
	Title         string   `json:"title"`
	Content       string   `json:"content"`
	Tags          []string `json:"tags"`
	Importance    int      `json:"importance"` // 1=low, 2=normal, 3=high, 4=critical
	Date          string   `json:"date"`       // YYYY-MM-DD
	SessionID     string   `json:"session_id"`
	AutoGenerated bool     `json:"auto_generated"`
	CreatedAt     string   `json:"created_at"`
}

// DailySummary is an LLM-generated end-of-day summary.
type DailySummary struct {
	Date        string         `json:"date"`
	Summary     string         `json:"summary"`
	KeyTopics   []string       `json:"key_topics"`
	ToolUsage   map[string]int `json:"tool_usage"`
	Sentiment   string         `json:"sentiment"` // positive, neutral, frustrated
	GeneratedAt string         `json:"generated_at"`
}

// InitJournalTables creates the journal tables if they do not exist.
func (s *SQLiteMemory) InitJournalTables() error {
	schema := `
	CREATE TABLE IF NOT EXISTS journal_entries (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		entry_type TEXT NOT NULL,
		title TEXT NOT NULL,
		content TEXT DEFAULT '',
		tags TEXT DEFAULT '[]',
		importance INTEGER DEFAULT 2,
		date TEXT NOT NULL,
		session_id TEXT DEFAULT '',
		auto_generated BOOLEAN DEFAULT 0,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);

	CREATE TABLE IF NOT EXISTS daily_summaries (
		date TEXT PRIMARY KEY,
		summary TEXT DEFAULT '',
		key_topics TEXT DEFAULT '[]',
		tool_usage TEXT DEFAULT '{}',
		sentiment TEXT DEFAULT 'neutral',
		generated_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);

	CREATE TABLE IF NOT EXISTS day_anchors (
		date TEXT PRIMARY KEY,
		anchor TEXT NOT NULL,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);

	CREATE TABLE IF NOT EXISTS episodic_memories (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		event_date TEXT NOT NULL,
		title TEXT NOT NULL,
		summary TEXT NOT NULL,
		details_json TEXT DEFAULT '{}',
		importance INTEGER DEFAULT 2,
		source TEXT DEFAULT 'consolidation',
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);

	CREATE INDEX IF NOT EXISTS idx_journal_date ON journal_entries(date);
	CREATE INDEX IF NOT EXISTS idx_journal_type ON journal_entries(entry_type);
	CREATE INDEX IF NOT EXISTS idx_journal_importance ON journal_entries(importance);
	CREATE INDEX IF NOT EXISTS idx_episodic_date_importance ON episodic_memories(event_date DESC, importance DESC);`

	if _, err := s.db.Exec(schema); err != nil {
		return fmt.Errorf("journal schema: %w", err)
	}
	return nil
}

// UpsertDayAnchor stores a single-sentence day anchor used for lightweight recent recall.
func (s *SQLiteMemory) UpsertDayAnchor(date, anchor string) error {
	if date == "" || anchor == "" {
		return nil
	}
	_, err := s.db.Exec(`
		INSERT INTO day_anchors (date, anchor, created_at)
		VALUES (?, ?, CURRENT_TIMESTAMP)
		ON CONFLICT(date) DO UPDATE SET
			anchor=excluded.anchor,
			created_at=CURRENT_TIMESTAMP
	`, date, anchor)
	if err != nil {
		return fmt.Errorf("upsert day anchor: %w", err)
	}
	return nil
}

// GetRecentDayAnchors returns the most recent day anchors.
func (s *SQLiteMemory) GetRecentDayAnchors(limit int) ([]string, error) {
	if limit <= 0 {
		limit = 3
	}
	rows, err := s.db.Query(`SELECT date, anchor FROM day_anchors ORDER BY date DESC LIMIT ?`, limit)
	if err != nil {
		return nil, fmt.Errorf("query day anchors: %w", err)
	}
	defer rows.Close()

	out := make([]string, 0, limit)
	for rows.Next() {
		var date, anchor string
		if err := rows.Scan(&date, &anchor); err != nil {
			return nil, fmt.Errorf("scan day anchor: %w", err)
		}
		out = append(out, fmt.Sprintf("%s: %s", date, anchor))
	}
	return out, rows.Err()
}

// InsertEpisodicMemory stores compact event cards for the recent-days memory layer.
func (s *SQLiteMemory) InsertEpisodicMemory(eventDate, title, summary string, details map[string]string, importance int, source string) error {
	if eventDate == "" {
		eventDate = time.Now().Format("2006-01-02")
	}
	if title == "" || summary == "" {
		return nil
	}
	if importance < 1 || importance > 4 {
		importance = 2
	}
	if source == "" {
		source = "consolidation"
	}
	detailsJSON, _ := json.Marshal(details)
	_, err := s.db.Exec(`
		INSERT INTO episodic_memories (event_date, title, summary, details_json, importance, source)
		VALUES (?, ?, ?, ?, ?, ?)
	`, eventDate, title, summary, string(detailsJSON), importance, source)
	if err != nil {
		return fmt.Errorf("insert episodic memory: %w", err)
	}
	return nil
}

// GetRecentEpisodicMemories returns recent event cards (default 72h) as compact prompt lines.
func (s *SQLiteMemory) GetRecentEpisodicMemories(hoursWindow int, limit int) ([]string, error) {
	if hoursWindow <= 0 {
		hoursWindow = 72
	}
	if limit <= 0 {
		limit = 5
	}
	rows, err := s.db.Query(`
		SELECT event_date, title, summary
		FROM episodic_memories
		WHERE datetime(created_at) >= datetime('now', '-' || ? || ' hours')
		ORDER BY created_at DESC, importance DESC
		LIMIT ?
	`, hoursWindow, limit)
	if err != nil {
		return nil, fmt.Errorf("query episodic memories: %w", err)
	}
	defer rows.Close()

	out := make([]string, 0, limit)
	for rows.Next() {
		var d, t, ssum string
		if err := rows.Scan(&d, &t, &ssum); err != nil {
			return nil, fmt.Errorf("scan episodic memory: %w", err)
		}
		out = append(out, fmt.Sprintf("%s | %s — %s", d, t, ssum))
	}
	return out, rows.Err()
}

// InsertJournalEntry adds a new journal entry.
func (s *SQLiteMemory) InsertJournalEntry(entry JournalEntry) (int64, error) {
	if entry.Title == "" {
		return 0, fmt.Errorf("title is required")
	}
	if entry.EntryType == "" {
		entry.EntryType = "learning"
	}
	if entry.Importance < 1 || entry.Importance > 4 {
		entry.Importance = 2
	}
	if entry.Date == "" {
		entry.Date = time.Now().Format("2006-01-02")
	}

	tagsJSON, _ := json.Marshal(entry.Tags)

	res, err := s.db.Exec(
		`INSERT INTO journal_entries (entry_type, title, content, tags, importance, date, session_id, auto_generated)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
		entry.EntryType, entry.Title, entry.Content, string(tagsJSON),
		entry.Importance, entry.Date, entry.SessionID, entry.AutoGenerated,
	)
	if err != nil {
		return 0, fmt.Errorf("insert journal entry: %w", err)
	}
	return res.LastInsertId()
}

// JournalEntryExists returns true if a journal entry with the given type and exact title already exists.
func (s *SQLiteMemory) JournalEntryExists(entryType, title string) (bool, error) {
	var count int
	err := s.db.QueryRow(
		`SELECT COUNT(*) FROM journal_entries WHERE entry_type = ? AND title = ? LIMIT 1`,
		entryType, title,
	).Scan(&count)
	if err != nil {
		return false, err
	}
	return count > 0, nil
}

// GetJournalEntries returns entries filtered by date range and optional types.
// If from/to are empty, returns all entries. types can be nil for all types.
func (s *SQLiteMemory) GetJournalEntries(from, to string, types []string, limit int) ([]JournalEntry, error) {
	var conditions []string
	var args []interface{}

	if from != "" {
		conditions = append(conditions, "date >= ?")
		args = append(args, from)
	}
	if to != "" {
		conditions = append(conditions, "date <= ?")
		args = append(args, to)
	}
	if len(types) > 0 {
		placeholders := make([]string, len(types))
		for i, t := range types {
			placeholders[i] = "?"
			args = append(args, t)
		}
		conditions = append(conditions, "entry_type IN ("+strings.Join(placeholders, ",")+")")
	}

	query := "SELECT id, entry_type, title, content, tags, importance, date, session_id, auto_generated, created_at FROM journal_entries"
	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}
	query += " ORDER BY date DESC, created_at DESC"
	if limit > 0 {
		query += fmt.Sprintf(" LIMIT %d", limit)
	}

	rows, err := s.db.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("query journal: %w", err)
	}
	defer rows.Close()

	var entries []JournalEntry
	for rows.Next() {
		var e JournalEntry
		var tagsJSON string
		if err := rows.Scan(&e.ID, &e.EntryType, &e.Title, &e.Content, &tagsJSON, &e.Importance, &e.Date, &e.SessionID, &e.AutoGenerated, &e.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan journal entry: %w", err)
		}
		_ = json.Unmarshal([]byte(tagsJSON), &e.Tags)
		entries = append(entries, e)
	}
	return entries, rows.Err()
}

// SearchJournalEntries searches journal entries by keyword in title and content.
func (s *SQLiteMemory) SearchJournalEntries(keyword string, limit int) ([]JournalEntry, error) {
	if keyword == "" {
		return s.GetJournalEntries("", "", nil, limit)
	}
	if limit <= 0 {
		limit = 20
	}

	pattern := "%" + keyword + "%"
	query := `SELECT id, entry_type, title, content, tags, importance, date, session_id, auto_generated, created_at
	          FROM journal_entries
	          WHERE title LIKE ? OR content LIKE ?
	          ORDER BY date DESC, created_at DESC
	          LIMIT ?`

	rows, err := s.db.Query(query, pattern, pattern, limit)
	if err != nil {
		return nil, fmt.Errorf("search journal: %w", err)
	}
	defer rows.Close()

	var entries []JournalEntry
	for rows.Next() {
		var e JournalEntry
		var tagsJSON string
		if err := rows.Scan(&e.ID, &e.EntryType, &e.Title, &e.Content, &tagsJSON, &e.Importance, &e.Date, &e.SessionID, &e.AutoGenerated, &e.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan journal search: %w", err)
		}
		_ = json.Unmarshal([]byte(tagsJSON), &e.Tags)
		entries = append(entries, e)
	}
	return entries, rows.Err()
}

// DeleteJournalEntry removes a journal entry by ID.
func (s *SQLiteMemory) DeleteJournalEntry(id int64) error {
	res, err := s.db.Exec("DELETE FROM journal_entries WHERE id = ?", id)
	if err != nil {
		return fmt.Errorf("delete journal entry: %w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("journal entry %d not found", id)
	}
	return nil
}

// InsertDailySummary stores or updates a daily summary.
func (s *SQLiteMemory) InsertDailySummary(summary DailySummary) error {
	if summary.Date == "" {
		summary.Date = time.Now().Format("2006-01-02")
	}

	topicsJSON, _ := json.Marshal(summary.KeyTopics)
	usageJSON, _ := json.Marshal(summary.ToolUsage)
	now := time.Now().UTC().Format(time.RFC3339)

	_, err := s.db.Exec(
		`INSERT INTO daily_summaries (date, summary, key_topics, tool_usage, sentiment, generated_at)
		 VALUES (?, ?, ?, ?, ?, ?)
		 ON CONFLICT(date) DO UPDATE SET
		   summary=excluded.summary, key_topics=excluded.key_topics,
		   tool_usage=excluded.tool_usage, sentiment=excluded.sentiment,
		   generated_at=excluded.generated_at`,
		summary.Date, summary.Summary, string(topicsJSON), string(usageJSON), summary.Sentiment, now,
	)
	if err != nil {
		return fmt.Errorf("insert daily summary: %w", err)
	}
	return nil
}

// GetDailySummary returns the summary for a specific date.
func (s *SQLiteMemory) GetDailySummary(date string) (*DailySummary, error) {
	row := s.db.QueryRow(
		"SELECT date, summary, key_topics, tool_usage, sentiment, generated_at FROM daily_summaries WHERE date = ?", date,
	)

	var d DailySummary
	var topicsJSON, usageJSON string
	if err := row.Scan(&d.Date, &d.Summary, &topicsJSON, &usageJSON, &d.Sentiment, &d.GeneratedAt); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get daily summary: %w", err)
	}
	_ = json.Unmarshal([]byte(topicsJSON), &d.KeyTopics)
	_ = json.Unmarshal([]byte(usageJSON), &d.ToolUsage)
	return &d, nil
}

// GetRecentDailySummaries returns the last N daily summaries.
func (s *SQLiteMemory) GetRecentDailySummaries(days int) ([]DailySummary, error) {
	if days <= 0 {
		days = 7
	}
	rows, err := s.db.Query(
		"SELECT date, summary, key_topics, tool_usage, sentiment, generated_at FROM daily_summaries ORDER BY date DESC LIMIT ?", days,
	)
	if err != nil {
		return nil, fmt.Errorf("get recent summaries: %w", err)
	}
	defer rows.Close()

	var summaries []DailySummary
	for rows.Next() {
		var d DailySummary
		var topicsJSON, usageJSON string
		if err := rows.Scan(&d.Date, &d.Summary, &topicsJSON, &usageJSON, &d.Sentiment, &d.GeneratedAt); err != nil {
			return nil, fmt.Errorf("scan daily summary: %w", err)
		}
		_ = json.Unmarshal([]byte(topicsJSON), &d.KeyTopics)
		_ = json.Unmarshal([]byte(usageJSON), &d.ToolUsage)
		summaries = append(summaries, d)
	}
	return summaries, rows.Err()
}

// GetJournalStats returns counts of journal entries by type for a date range.
func (s *SQLiteMemory) GetJournalStats(from, to string) (map[string]int, error) {
	var conditions []string
	var args []interface{}
	if from != "" {
		conditions = append(conditions, "date >= ?")
		args = append(args, from)
	}
	if to != "" {
		conditions = append(conditions, "date <= ?")
		args = append(args, to)
	}

	query := "SELECT entry_type, COUNT(*) FROM journal_entries"
	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}
	query += " GROUP BY entry_type"

	rows, err := s.db.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("journal stats: %w", err)
	}
	defer rows.Close()

	stats := make(map[string]int)
	for rows.Next() {
		var entryType string
		var count int
		if err := rows.Scan(&entryType, &count); err != nil {
			return nil, fmt.Errorf("scan journal stats: %w", err)
		}
		stats[entryType] = count
	}
	return stats, rows.Err()
}

// FormatJournalEntriesJSON marshals a slice of JournalEntry to JSON.
func FormatJournalEntriesJSON(entries []JournalEntry) string {
	b, err := json.Marshal(entries)
	if err != nil {
		return "[]"
	}
	return string(b)
}
