package memory

import (
	"testing"
	"time"
)

func TestJournalErrorRecentlyLogged(t *testing.T) {
	stm := newTestJournalDB(t)

	title := "Error in send_telegram"
	content := "message is required"
	if _, err := stm.InsertJournalEntry(JournalEntry{
		EntryType: "error_learned",
		Title:     title,
		Content:   content,
	}); err != nil {
		t.Fatalf("InsertJournalEntry: %v", err)
	}

	logged, err := stm.JournalErrorRecentlyLogged("error_learned", title, content, 24)
	if err != nil {
		t.Fatalf("JournalErrorRecentlyLogged: %v", err)
	}
	if !logged {
		t.Fatal("expected recent identical journal error to be detected")
	}

	logged, err = stm.JournalErrorRecentlyLogged("error_learned", title, "different error", 24)
	if err != nil {
		t.Fatalf("JournalErrorRecentlyLogged different content: %v", err)
	}
	if logged {
		t.Fatal("expected different content not to match")
	}
}

func TestConsolidateDuplicateAutoJournalErrorsDryRunAndApply(t *testing.T) {
	stm := newTestJournalDB(t)
	now := time.Date(2026, 6, 9, 12, 0, 0, 0, time.UTC)
	oldCreated := now.Add(-48 * time.Hour).Format("2006-01-02 15:04:05")

	ids := make([]int64, 0, 3)
	for range 3 {
		id, err := stm.InsertJournalEntry(JournalEntry{
			EntryType:     "error_learned",
			Title:         "Error in send_telegram",
			Content:       "message is required",
			Tags:          []string{"tool", "send_telegram"},
			AutoGenerated: true,
		})
		if err != nil {
			t.Fatalf("InsertJournalEntry duplicate: %v", err)
		}
		ids = append(ids, id)
		if _, err := stm.db.Exec(`UPDATE journal_entries SET created_at = ? WHERE id = ?`, oldCreated, id); err != nil {
			t.Fatalf("backdate duplicate: %v", err)
		}
	}
	manualID, err := stm.InsertJournalEntry(JournalEntry{
		EntryType:     "error_learned",
		Title:         "Error in send_telegram",
		Content:       "message is required",
		Tags:          []string{"tool", "send_telegram"},
		AutoGenerated: false,
	})
	if err != nil {
		t.Fatalf("InsertJournalEntry manual: %v", err)
	}
	if _, err := stm.db.Exec(`UPDATE journal_entries SET created_at = ? WHERE id = ?`, oldCreated, manualID); err != nil {
		t.Fatalf("backdate manual: %v", err)
	}

	dry, err := stm.ConsolidateDuplicateAutoJournalErrors(JournalConsolidationOptions{
		Now:           now,
		OlderThan:     24 * time.Hour,
		MinDuplicates: 2,
		DryRun:        true,
	})
	if err != nil {
		t.Fatalf("ConsolidateDuplicateAutoJournalErrors dry-run: %v", err)
	}
	if dry.Groups != 1 || dry.RemovedEntries != 2 || len(dry.Items) != 1 {
		t.Fatalf("dry report = %+v, want 1 group and 2 removable entries", dry)
	}
	entries, err := stm.GetJournalEntries("", "", []string{"error_learned"}, 10)
	if err != nil {
		t.Fatalf("GetJournalEntries after dry-run: %v", err)
	}
	if len(entries) != 4 {
		t.Fatalf("entries after dry-run = %d, want 4", len(entries))
	}

	applied, err := stm.ConsolidateDuplicateAutoJournalErrors(JournalConsolidationOptions{
		Now:           now,
		OlderThan:     24 * time.Hour,
		MinDuplicates: 2,
		Actor:         "test",
	})
	if err != nil {
		t.Fatalf("ConsolidateDuplicateAutoJournalErrors apply: %v", err)
	}
	if applied.Groups != 1 || applied.RemovedEntries != 2 || applied.Items[0].KeptEntryID != ids[0] {
		t.Fatalf("apply report = %+v, want oldest duplicate kept", applied)
	}
	entries, err = stm.GetJournalEntries("", "", []string{"error_learned"}, 10)
	if err != nil {
		t.Fatalf("GetJournalEntries after apply: %v", err)
	}
	if len(entries) != 2 {
		t.Fatalf("entries after apply = %d, want kept auto duplicate plus manual entry", len(entries))
	}
	events, err := stm.ListJournalCurationEvents(10)
	if err != nil {
		t.Fatalf("ListJournalCurationEvents: %v", err)
	}
	if len(events) != 1 || events[0].RemovedCount != 2 || events[0].DryRun {
		t.Fatalf("events = %+v, want one non-dry-run removal event", events)
	}
}

func TestConsolidateDuplicateAutoJournalErrorsDoesNotCountFailedApply(t *testing.T) {
	stm := newTestJournalDB(t)
	now := time.Date(2026, 6, 9, 12, 0, 0, 0, time.UTC)
	oldCreated := now.Add(-48 * time.Hour).Format("2006-01-02 15:04:05")

	for range 2 {
		id, err := stm.InsertJournalEntry(JournalEntry{
			EntryType:     "error_learned",
			Title:         "Error in send_telegram",
			Content:       "message is required",
			AutoGenerated: true,
		})
		if err != nil {
			t.Fatalf("InsertJournalEntry duplicate: %v", err)
		}
		if _, err := stm.db.Exec(`UPDATE journal_entries SET created_at = ? WHERE id = ?`, oldCreated, id); err != nil {
			t.Fatalf("backdate duplicate: %v", err)
		}
	}
	if _, err := stm.db.Exec(`DROP TABLE journal_curation_events`); err != nil {
		t.Fatalf("drop curation events table: %v", err)
	}

	report, err := stm.ConsolidateDuplicateAutoJournalErrors(JournalConsolidationOptions{
		Now:           now,
		OlderThan:     24 * time.Hour,
		MinDuplicates: 2,
		Actor:         "test",
	})
	if err == nil {
		t.Fatal("expected apply error when audit table is missing")
	}
	if report.Groups != 0 || report.RemovedEntries != 0 || len(report.Items) != 0 {
		t.Fatalf("failed apply report = %+v, want no applied counts", report)
	}
	entries, err := stm.GetJournalEntries("", "", []string{"error_learned"}, 10)
	if err != nil {
		t.Fatalf("GetJournalEntries after failed apply: %v", err)
	}
	if len(entries) != 2 {
		t.Fatalf("entries after failed apply = %d, want rollback to keep 2", len(entries))
	}
}
