package memory

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"time"
)

// JournalEntry represents a single event in the agent's journal timeline.
type JournalEntry struct {
	ID            int64    `json:"id"`
	EntryType     string   `json:"entry_type"` // activity, milestone, learning, decision, error, preference, task_completed, integration
	Title         string   `json:"title"`
	Content       string   `json:"content"`
	Tags          []string `json:"tags"`
	Importance    int      `json:"importance"` // 1=low, 2=normal, 3=high, 4=critical
	Date          string   `json:"date"`       // YYYY-MM-DD
	SessionID     string   `json:"session_id"`
	AutoGenerated bool     `json:"auto_generated"`
	CreatedAt     string   `json:"created_at"`
}

// DailySummary is an LLM-generated end-of-day summary.
type DailySummary struct {
	Date        string         `json:"date"`
	Summary     string         `json:"summary"`
	KeyTopics   []string       `json:"key_topics"`
	ToolUsage   map[string]int `json:"tool_usage"`
	Sentiment   string         `json:"sentiment"` // positive, neutral, frustrated
	GeneratedAt string         `json:"generated_at"`
}

// EpisodicMemory is a compact event card stored in the recent episodic layer.
type EpisodicMemory struct {
	ID               int64    `json:"id"`
	EventDate        string   `json:"event_date"`
	Title            string   `json:"title"`
	Summary          string   `json:"summary"`
	DetailsJSON      string   `json:"details_json"`
	Importance       int      `json:"importance"`
	Source           string   `json:"source"`
	SessionID        string   `json:"session_id"`
	HierarchyLevel   int      `json:"hierarchy_level"`
	ActionStatus     string   `json:"action_status"`
	TriggerQuery     string   `json:"trigger_query"`
	ResolvedAt       string   `json:"resolved_at"`
	Participants     []string `json:"participants,omitempty"`
	RelatedDocIDs    []string `json:"related_doc_ids,omitempty"`
	EmotionalValence float64  `json:"emotional_valence"`
	CreatedAt        string   `json:"created_at"`
}

// EpisodicMemoryDetails enriches episodic event cards with lightweight structured metadata.
type EpisodicMemoryDetails struct {
	SessionID        string
	HierarchyLevel   int
	ActionStatus     string
	TriggerQuery     string
	ResolvedAt       string
	Participants     []string
	RelatedDocIDs    []string
	EmotionalValence float64
}

// InitJournalTables creates the journal tables if they do not exist.
func (s *SQLiteMemory) InitJournalTables() error {
	schema := `
	CREATE TABLE IF NOT EXISTS journal_entries (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		entry_type TEXT NOT NULL,
		title TEXT NOT NULL,
		content TEXT DEFAULT '',
		tags TEXT DEFAULT '[]',
		importance INTEGER DEFAULT 2,
		date TEXT NOT NULL,
		session_id TEXT DEFAULT '',
		auto_generated BOOLEAN DEFAULT 0,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);

	CREATE TABLE IF NOT EXISTS daily_summaries (
		date TEXT PRIMARY KEY,
		summary TEXT DEFAULT '',
		key_topics TEXT DEFAULT '[]',
		tool_usage TEXT DEFAULT '{}',
		sentiment TEXT DEFAULT 'neutral',
		generated_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);

	CREATE TABLE IF NOT EXISTS day_anchors (
		date TEXT PRIMARY KEY,
		anchor TEXT NOT NULL,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);

	CREATE TABLE IF NOT EXISTS episodic_memories (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		event_date TEXT NOT NULL,
		title TEXT NOT NULL,
		summary TEXT NOT NULL,
		details_json TEXT DEFAULT '{}',
		importance INTEGER DEFAULT 2,
		source TEXT DEFAULT 'consolidation',
		session_id TEXT DEFAULT '',
		hierarchy_level INTEGER DEFAULT 1,
		action_status TEXT DEFAULT '',
		trigger_query TEXT DEFAULT '',
		resolved_at DATETIME DEFAULT '',
		participants_json TEXT DEFAULT '[]',
		related_doc_ids TEXT DEFAULT '[]',
		emotional_valence REAL DEFAULT 0,
		created_at DATETIME DEFAULT CURRENT_TIMESTAMP
	);

	CREATE INDEX IF NOT EXISTS idx_journal_date ON journal_entries(date);
	CREATE INDEX IF NOT EXISTS idx_journal_type ON journal_entries(entry_type);
	CREATE INDEX IF NOT EXISTS idx_journal_importance ON journal_entries(importance);
	CREATE INDEX IF NOT EXISTS idx_episodic_date_importance ON episodic_memories(event_date DESC, importance DESC);`

	if _, err := s.db.Exec(schema); err != nil {
		return fmt.Errorf("journal schema: %w", err)
	}

	for _, column := range []struct {
		Name    string
		TypeDef string
	}{
		{Name: "session_id", TypeDef: "TEXT DEFAULT ''"},
		{Name: "hierarchy_level", TypeDef: "INTEGER DEFAULT 1"},
		{Name: "action_status", TypeDef: "TEXT DEFAULT ''"},
		{Name: "trigger_query", TypeDef: "TEXT DEFAULT ''"},
		{Name: "resolved_at", TypeDef: "DATETIME DEFAULT ''"},
		{Name: "participants_json", TypeDef: "TEXT DEFAULT '[]'"},
		{Name: "related_doc_ids", TypeDef: "TEXT DEFAULT '[]'"},
		{Name: "emotional_valence", TypeDef: "REAL DEFAULT 0"},
	} {
		var hasColumn bool
		err := s.db.QueryRow("SELECT count(*) > 0 FROM pragma_table_info('episodic_memories') WHERE name = ?", column.Name).Scan(&hasColumn)
		if err != nil {
			return fmt.Errorf("check episodic_memories.%s column: %w", column.Name, err)
		}
		if !hasColumn {
			if _, err := s.db.Exec("ALTER TABLE episodic_memories ADD COLUMN " + column.Name + " " + column.TypeDef); err != nil {
				return fmt.Errorf("add episodic_memories.%s column: %w", column.Name, err)
			}
		}
	}

	return nil
}

// UpsertDayAnchor stores a single-sentence day anchor used for lightweight recent recall.
func (s *SQLiteMemory) UpsertDayAnchor(date, anchor string) error {
	if date == "" || anchor == "" {
		return nil
	}
	_, err := s.db.Exec(`
		INSERT INTO day_anchors (date, anchor, created_at)
		VALUES (?, ?, CURRENT_TIMESTAMP)
		ON CONFLICT(date) DO UPDATE SET
			anchor=excluded.anchor,
			created_at=CURRENT_TIMESTAMP
	`, date, anchor)
	if err != nil {
		return fmt.Errorf("upsert day anchor: %w", err)
	}
	return nil
}

// GetRecentDayAnchors returns the most recent day anchors.
func (s *SQLiteMemory) GetRecentDayAnchors(limit int) ([]string, error) {
	if limit <= 0 {
		limit = 3
	}
	rows, err := s.db.Query(`SELECT date, anchor FROM day_anchors ORDER BY date DESC LIMIT ?`, limit)
	if err != nil {
		return nil, fmt.Errorf("query day anchors: %w", err)
	}
	defer rows.Close()

	out := make([]string, 0, limit)
	for rows.Next() {
		var date, anchor string
		if err := rows.Scan(&date, &anchor); err != nil {
			return nil, fmt.Errorf("scan day anchor: %w", err)
		}
		out = append(out, fmt.Sprintf("%s: %s", date, anchor))
	}
	return out, rows.Err()
}

// InsertEpisodicMemory stores compact event cards for the recent-days memory layer.
func (s *SQLiteMemory) InsertEpisodicMemory(eventDate, title, summary string, details map[string]string, importance int, source string) error {
	return s.InsertEpisodicMemoryWithDetails(eventDate, title, summary, details, importance, source, EpisodicMemoryDetails{})
}

// InsertEpisodicMemoryWithDetails stores compact event cards with optional structured metadata.
func (s *SQLiteMemory) InsertEpisodicMemoryWithDetails(eventDate, title, summary string, details map[string]string, importance int, source string, meta EpisodicMemoryDetails) error {
	if eventDate == "" {
		eventDate = time.Now().Format("2006-01-02")
	}
	if title == "" || summary == "" {
		return nil
	}
	if importance < 1 || importance > 4 {
		importance = 2
	}
	if source == "" {
		source = "consolidation"
	}
	detailsJSON, _ := json.Marshal(details)
	participantsJSON, _ := json.Marshal(uniqueSortedStrings(meta.Participants))
	relatedDocIDsJSON, _ := json.Marshal(uniqueSortedStrings(meta.RelatedDocIDs))
	hierarchyLevel := meta.HierarchyLevel
	if hierarchyLevel <= 0 {
		hierarchyLevel = 1
	}
	actionStatus := strings.TrimSpace(meta.ActionStatus)
	triggerQuery := strings.TrimSpace(meta.TriggerQuery)
	resolvedAt := strings.TrimSpace(meta.ResolvedAt)
	if meta.EmotionalValence > 1 {
		meta.EmotionalValence = 1
	}
	if meta.EmotionalValence < -1 {
		meta.EmotionalValence = -1
	}
	_, err := s.db.Exec(`
		INSERT INTO episodic_memories (
			event_date, title, summary, details_json, importance, source,
			session_id, hierarchy_level, action_status, trigger_query, resolved_at,
			participants_json, related_doc_ids, emotional_valence
		)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	`, eventDate, title, summary, string(detailsJSON), importance, source, meta.SessionID, hierarchyLevel, actionStatus, triggerQuery, resolvedAt, string(participantsJSON), string(relatedDocIDsJSON), meta.EmotionalValence)
	if err != nil {
		return fmt.Errorf("insert episodic memory: %w", err)
	}
	return nil
}

// UpsertPendingEpisodicAction creates or refreshes a pending episodic follow-up item.
// The entire check-then-insert is wrapped in a single transaction to prevent TOCTOU races.
func (s *SQLiteMemory) UpsertPendingEpisodicAction(eventDate, title, summary, triggerQuery, sessionID string, importance int, relatedDocIDs []string) error {
	if title == "" || summary == "" {
		return nil
	}
	if eventDate == "" {
		eventDate = time.Now().Format("2006-01-02")
	}
	if importance < 2 || importance > 4 {
		importance = 3
	}
	if triggerQuery == "" {
		triggerQuery = title
	}
	relatedJSON, _ := json.Marshal(uniqueSortedStrings(relatedDocIDs))

	tx, err := s.db.Begin()
	if err != nil {
		return fmt.Errorf("upsert pending episodic action: %w", err)
	}
	defer tx.Rollback() //nolint:errcheck

	result, err := tx.Exec(`
		UPDATE episodic_memories
		SET summary = ?,
			importance = ?,
			event_date = ?,
			session_id = ?,
			trigger_query = ?,
			related_doc_ids = ?,
			resolved_at = '',
			action_status = 'pending'
		WHERE title = ? AND action_status = 'pending'
	`, summary, importance, eventDate, sessionID, triggerQuery, string(relatedJSON), title)
	if err != nil {
		return fmt.Errorf("update pending episodic action: %w", err)
	}

	affected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("pending episodic action rows affected: %w", err)
	}

	if affected == 0 {
		// No existing pending entry — insert a new one within the same transaction.
		_, err = tx.Exec(`
			INSERT INTO episodic_memories (
				event_date, title, summary, details_json, importance, source,
				session_id, hierarchy_level, action_status, trigger_query, resolved_at,
				participants_json, related_doc_ids, emotional_valence
			)
			VALUES (?, ?, ?, '{"kind":"pending_action"}', ?, 'pending_action', ?, 1, 'pending', ?, '', '[]', ?, 0)
		`, eventDate, title, summary, importance, sessionID, triggerQuery, string(relatedJSON))
		if err != nil {
			return fmt.Errorf("insert pending episodic action: %w", err)
		}
	}

	return tx.Commit()
}

// GetRecentEpisodicMemories returns recent event cards (default 72h) as compact prompt lines.
func (s *SQLiteMemory) GetRecentEpisodicMemories(hoursWindow int, limit int) ([]string, error) {
	cards, err := s.GetRecentEpisodicMemoryCards(hoursWindow, limit)
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(cards))
	for _, card := range cards {
		out = append(out, formatEpisodicCard(card))
	}
	return out, nil
}

// GetRecentEpisodicMemoryCards returns recent event cards with structured metadata.
func (s *SQLiteMemory) GetRecentEpisodicMemoryCards(hoursWindow int, limit int) ([]EpisodicMemory, error) {
	if hoursWindow <= 0 {
		hoursWindow = 72
	}
	if limit <= 0 {
		limit = 5
	}
	rows, err := s.db.Query(`
		SELECT id, event_date, title, summary, details_json, importance, source, session_id, hierarchy_level, action_status, trigger_query, COALESCE(resolved_at, ''), participants_json, related_doc_ids, emotional_valence, created_at
		FROM episodic_memories
		WHERE datetime(created_at) >= datetime('now', '-' || ? || ' hours')
		ORDER BY created_at DESC, importance DESC
		LIMIT ?
	`, hoursWindow, limit)
	if err != nil {
		return nil, fmt.Errorf("query episodic memories: %w", err)
	}
	defer rows.Close()

	out := make([]EpisodicMemory, 0, limit)
	for rows.Next() {
		var entry EpisodicMemory
		var participantsJSON, relatedDocIDsJSON string
		if err := rows.Scan(&entry.ID, &entry.EventDate, &entry.Title, &entry.Summary, &entry.DetailsJSON, &entry.Importance, &entry.Source, &entry.SessionID, &entry.HierarchyLevel, &entry.ActionStatus, &entry.TriggerQuery, &entry.ResolvedAt, &participantsJSON, &relatedDocIDsJSON, &entry.EmotionalValence, &entry.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan episodic memory: %w", err)
		}
		_ = json.Unmarshal([]byte(participantsJSON), &entry.Participants)
		_ = json.Unmarshal([]byte(relatedDocIDsJSON), &entry.RelatedDocIDs)
		out = append(out, entry)
	}
	return out, rows.Err()
}

// InsertJournalEntry adds a new journal entry.
func (s *SQLiteMemory) InsertJournalEntry(entry JournalEntry) (int64, error) {
	if entry.Title == "" {
		return 0, fmt.Errorf("title is required")
	}
	if entry.EntryType == "" {
		entry.EntryType = "learning"
	}
	if entry.Importance < 1 || entry.Importance > 4 {
		entry.Importance = 2
	}
	if entry.Date == "" {
		entry.Date = time.Now().Format("2006-01-02")
	}

	tagsJSON, _ := json.Marshal(entry.Tags)

	res, err := s.db.Exec(
		`INSERT INTO journal_entries (entry_type, title, content, tags, importance, date, session_id, auto_generated)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
		entry.EntryType, entry.Title, entry.Content, string(tagsJSON),
		entry.Importance, entry.Date, entry.SessionID, entry.AutoGenerated,
	)
	if err != nil {
		return 0, fmt.Errorf("insert journal entry: %w", err)
	}
	return res.LastInsertId()
}

// JournalEntryExists returns true if a journal entry with the given type and exact title already exists.
func (s *SQLiteMemory) JournalEntryExists(entryType, title string) (bool, error) {
	var count int
	err := s.db.QueryRow(
		`SELECT COUNT(*) FROM journal_entries WHERE entry_type = ? AND title = ? LIMIT 1`,
		entryType, title,
	).Scan(&count)
	if err != nil {
		return false, err
	}
	return count > 0, nil
}

// GetJournalEntries returns entries filtered by date range and optional types.
// If from/to are empty, returns all entries. types can be nil for all types.
func (s *SQLiteMemory) GetJournalEntries(from, to string, types []string, limit int) ([]JournalEntry, error) {
	var conditions []string
	var args []interface{}

	if from != "" {
		conditions = append(conditions, "date >= ?")
		args = append(args, from)
	}
	if to != "" {
		conditions = append(conditions, "date <= ?")
		args = append(args, to)
	}
	if len(types) > 0 {
		placeholders := make([]string, len(types))
		for i, t := range types {
			placeholders[i] = "?"
			args = append(args, t)
		}
		conditions = append(conditions, "entry_type IN ("+strings.Join(placeholders, ",")+")")
	}

	query := "SELECT id, entry_type, title, content, tags, importance, date, session_id, auto_generated, created_at FROM journal_entries"
	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}
	query += " ORDER BY date DESC, created_at DESC"
	if limit > 0 {
		query += fmt.Sprintf(" LIMIT %d", limit)
	}

	rows, err := s.db.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("query journal: %w", err)
	}
	defer rows.Close()

	var entries []JournalEntry
	for rows.Next() {
		var e JournalEntry
		var tagsJSON string
		if err := rows.Scan(&e.ID, &e.EntryType, &e.Title, &e.Content, &tagsJSON, &e.Importance, &e.Date, &e.SessionID, &e.AutoGenerated, &e.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan journal entry: %w", err)
		}
		_ = json.Unmarshal([]byte(tagsJSON), &e.Tags)
		entries = append(entries, e)
	}
	return entries, rows.Err()
}

// SearchJournalEntries searches journal entries by keyword in title and content.
func (s *SQLiteMemory) SearchJournalEntries(keyword string, limit int) ([]JournalEntry, error) {
	return s.SearchJournalEntriesInRange(keyword, "", "", limit)
}

// SearchJournalEntriesInRange searches journal entries by keyword in title/content,
// optionally restricted to an inclusive YYYY-MM-DD date window.
func (s *SQLiteMemory) SearchJournalEntriesInRange(keyword, fromDate, toDate string, limit int) ([]JournalEntry, error) {
	if keyword == "" {
		return s.GetJournalEntries(fromDate, toDate, nil, limit)
	}
	if limit <= 0 {
		limit = 20
	}

	pattern := "%" + escapeLike(keyword) + "%"
	query := `SELECT id, entry_type, title, content, tags, importance, date, session_id, auto_generated, created_at
	          FROM journal_entries
	          WHERE (title LIKE ? ESCAPE '\' OR content LIKE ? ESCAPE '\')`
	args := []interface{}{pattern, pattern}
	if fromDate != "" {
		query += ` AND date >= ?`
		args = append(args, fromDate)
	}
	if toDate != "" {
		query += ` AND date <= ?`
		args = append(args, toDate)
	}
	query += ` ORDER BY date DESC, created_at DESC LIMIT ?`
	args = append(args, limit)

	rows, err := s.db.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("search journal: %w", err)
	}
	defer rows.Close()

	var entries []JournalEntry
	for rows.Next() {
		var e JournalEntry
		var tagsJSON string
		if err := rows.Scan(&e.ID, &e.EntryType, &e.Title, &e.Content, &tagsJSON, &e.Importance, &e.Date, &e.SessionID, &e.AutoGenerated, &e.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan journal search: %w", err)
		}
		_ = json.Unmarshal([]byte(tagsJSON), &e.Tags)
		entries = append(entries, e)
	}
	return entries, rows.Err()
}

// SearchEpisodicMemoriesInRange searches episodic memories by summary/title and optional date range.
func (s *SQLiteMemory) SearchEpisodicMemoriesInRange(keyword, fromDate, toDate string, limit int) ([]EpisodicMemory, error) {
	if limit <= 0 {
		limit = 10
	}

	query := `
		SELECT id, event_date, title, summary, details_json, importance, source, session_id, hierarchy_level, action_status, trigger_query, COALESCE(resolved_at, ''), participants_json, related_doc_ids, emotional_valence, created_at
		FROM episodic_memories
		WHERE 1=1`
	args := make([]interface{}, 0, 4)
	if keyword != "" {
		pattern := "%" + escapeLike(keyword) + "%"
		query += ` AND (title LIKE ? ESCAPE '\' OR summary LIKE ? ESCAPE '\')`
		args = append(args, pattern, pattern)
	}
	if fromDate != "" {
		query += ` AND event_date >= ?`
		args = append(args, fromDate)
	}
	if toDate != "" {
		query += ` AND event_date <= ?`
		args = append(args, toDate)
	}
	query += ` ORDER BY event_date DESC, created_at DESC, importance DESC LIMIT ?`
	args = append(args, limit)

	rows, err := s.db.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("search episodic memories: %w", err)
	}
	defer rows.Close()

	var entries []EpisodicMemory
	for rows.Next() {
		var entry EpisodicMemory
		var participantsJSON, relatedDocIDsJSON string
		if err := rows.Scan(
			&entry.ID,
			&entry.EventDate,
			&entry.Title,
			&entry.Summary,
			&entry.DetailsJSON,
			&entry.Importance,
			&entry.Source,
			&entry.SessionID,
			&entry.HierarchyLevel,
			&entry.ActionStatus,
			&entry.TriggerQuery,
			&entry.ResolvedAt,
			&participantsJSON,
			&relatedDocIDsJSON,
			&entry.EmotionalValence,
			&entry.CreatedAt,
		); err != nil {
			return nil, fmt.Errorf("scan episodic memory search: %w", err)
		}
		_ = json.Unmarshal([]byte(participantsJSON), &entry.Participants)
		_ = json.Unmarshal([]byte(relatedDocIDsJSON), &entry.RelatedDocIDs)
		entries = append(entries, entry)
	}
	return entries, rows.Err()
}

// GetPendingEpisodicActionsForQuery returns unresolved follow-up items matching the current topic.
func (s *SQLiteMemory) GetPendingEpisodicActionsForQuery(query string, limit int) ([]EpisodicMemory, error) {
	if limit <= 0 {
		limit = 3
	}
	pattern := "%"
	if trimmed := strings.TrimSpace(query); trimmed != "" {
		pattern = "%" + escapeLike(trimmed) + "%"
	}
	rows, err := s.db.Query(`
		SELECT id, event_date, title, summary, details_json, importance, source, session_id, hierarchy_level, action_status, trigger_query, COALESCE(resolved_at, ''), participants_json, related_doc_ids, emotional_valence, created_at
		FROM episodic_memories
		WHERE action_status = 'pending'
		  AND (trigger_query LIKE ? ESCAPE '\' OR title LIKE ? ESCAPE '\' OR summary LIKE ? ESCAPE '\')
		ORDER BY importance DESC, event_date DESC, created_at DESC
		LIMIT ?
	`, pattern, pattern, pattern, limit)
	if err != nil {
		return nil, fmt.Errorf("query pending episodic actions: %w", err)
	}
	defer rows.Close()

	entries := make([]EpisodicMemory, 0, limit)
	for rows.Next() {
		var entry EpisodicMemory
		var participantsJSON, relatedDocIDsJSON string
		if err := rows.Scan(&entry.ID, &entry.EventDate, &entry.Title, &entry.Summary, &entry.DetailsJSON, &entry.Importance, &entry.Source, &entry.SessionID, &entry.HierarchyLevel, &entry.ActionStatus, &entry.TriggerQuery, &entry.ResolvedAt, &participantsJSON, &relatedDocIDsJSON, &entry.EmotionalValence, &entry.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan pending episodic action: %w", err)
		}
		_ = json.Unmarshal([]byte(participantsJSON), &entry.Participants)
		_ = json.Unmarshal([]byte(relatedDocIDsJSON), &entry.RelatedDocIDs)
		entries = append(entries, entry)
	}
	return entries, rows.Err()
}

// GetEpisodicMemoriesByHierarchyLevel returns non-pending episodic memories at the requested hierarchy level.
func (s *SQLiteMemory) GetEpisodicMemoriesByHierarchyLevel(level int, limit int) ([]EpisodicMemory, error) {
	if level <= 0 {
		level = 1
	}
	if limit <= 0 {
		limit = 25
	}
	rows, err := s.db.Query(`
		SELECT id, event_date, title, summary, details_json, importance, source, session_id, hierarchy_level, action_status, trigger_query, COALESCE(resolved_at, ''), participants_json, related_doc_ids, emotional_valence, created_at
		FROM episodic_memories
		WHERE hierarchy_level = ? AND action_status != 'pending'
		ORDER BY event_date DESC, created_at DESC, importance DESC
		LIMIT ?
	`, level, limit)
	if err != nil {
		return nil, fmt.Errorf("query episodic hierarchy level: %w", err)
	}
	defer rows.Close()

	entries := make([]EpisodicMemory, 0, limit)
	for rows.Next() {
		var entry EpisodicMemory
		var participantsJSON, relatedDocIDsJSON string
		if err := rows.Scan(&entry.ID, &entry.EventDate, &entry.Title, &entry.Summary, &entry.DetailsJSON, &entry.Importance, &entry.Source, &entry.SessionID, &entry.HierarchyLevel, &entry.ActionStatus, &entry.TriggerQuery, &entry.ResolvedAt, &participantsJSON, &relatedDocIDsJSON, &entry.EmotionalValence, &entry.CreatedAt); err != nil {
			return nil, fmt.Errorf("scan episodic hierarchy level: %w", err)
		}
		_ = json.Unmarshal([]byte(participantsJSON), &entry.Participants)
		_ = json.Unmarshal([]byte(relatedDocIDsJSON), &entry.RelatedDocIDs)
		entries = append(entries, entry)
	}
	return entries, rows.Err()
}

// MarkEpisodicMemoriesHierarchy updates the hierarchy level for the given episodic IDs.
func (s *SQLiteMemory) MarkEpisodicMemoriesHierarchy(ids []int64, newLevel int) error {
	if len(ids) == 0 {
		return nil
	}
	if newLevel <= 0 {
		newLevel = 1
	}
	placeholders := make([]string, len(ids))
	args := make([]interface{}, 0, len(ids)+1)
	args = append(args, newLevel)
	for i, id := range ids {
		placeholders[i] = "?"
		args = append(args, id)
	}
	_, err := s.db.Exec(`UPDATE episodic_memories SET hierarchy_level = ? WHERE id IN (`+strings.Join(placeholders, ",")+`)`, args...)
	if err != nil {
		return fmt.Errorf("mark episodic hierarchy: %w", err)
	}
	return nil
}

// ResolvePendingEpisodicAction marks a pending follow-up as resolved.
func (s *SQLiteMemory) ResolvePendingEpisodicAction(id int64) error {
	if id <= 0 {
		return nil
	}
	_, err := s.db.Exec(`
		UPDATE episodic_memories
		SET action_status = 'resolved', resolved_at = CURRENT_TIMESTAMP
		WHERE id = ?
	`, id)
	if err != nil {
		return fmt.Errorf("resolve pending episodic action: %w", err)
	}
	return nil
}

// GetEpisodicMemoryStats returns additive diagnostics for the episodic layer.
func (s *SQLiteMemory) GetEpisodicMemoryStats(hoursWindow int, recentLimit int) (map[string]interface{}, error) {
	if hoursWindow <= 0 {
		hoursWindow = 72
	}
	if recentLimit <= 0 {
		recentLimit = 5
	}

	var totalCount int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM episodic_memories`).Scan(&totalCount); err != nil {
		return nil, fmt.Errorf("count episodic memories: %w", err)
	}

	var recentCount int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM episodic_memories WHERE datetime(created_at) >= datetime('now', '-' || ? || ' hours')`, hoursWindow).Scan(&recentCount); err != nil {
		return nil, fmt.Errorf("count recent episodic memories: %w", err)
	}

	rows, err := s.db.Query(`SELECT source, COUNT(*) FROM episodic_memories GROUP BY source ORDER BY COUNT(*) DESC`)
	if err != nil {
		return nil, fmt.Errorf("group episodic sources: %w", err)
	}
	defer rows.Close()

	bySource := make(map[string]int)
	for rows.Next() {
		var source string
		var count int
		if err := rows.Scan(&source, &count); err != nil {
			return nil, fmt.Errorf("scan episodic source stats: %w", err)
		}
		bySource[source] = count
	}

	recentCards, err := s.GetRecentEpisodicMemoryCards(hoursWindow, recentLimit)
	if err != nil {
		return nil, err
	}
	recent := make([]map[string]interface{}, 0, len(recentCards))
	for _, card := range recentCards {
		recent = append(recent, map[string]interface{}{
			"event_date":         card.EventDate,
			"title":              card.Title,
			"summary":            card.Summary,
			"source":             card.Source,
			"session_id":         card.SessionID,
			"hierarchy_level":    card.HierarchyLevel,
			"action_status":      card.ActionStatus,
			"trigger_query":      card.TriggerQuery,
			"participants":       card.Participants,
			"related_doc_ids":    card.RelatedDocIDs,
			"emotional_valence":  card.EmotionalValence,
			"prompt_line":        formatEpisodicCard(card),
			"has_related_memory": len(card.RelatedDocIDs) > 0,
		})
	}

	return map[string]interface{}{
		"total_count":  totalCount,
		"recent_count": recentCount,
		"hours_window": hoursWindow,
		"by_source":    bySource,
		"recent_cards": recent,
	}, nil
}

// DeleteJournalEntry removes a journal entry by ID.
func (s *SQLiteMemory) DeleteJournalEntry(id int64) error {
	res, err := s.db.Exec("DELETE FROM journal_entries WHERE id = ?", id)
	if err != nil {
		return fmt.Errorf("delete journal entry: %w", err)
	}
	n, _ := res.RowsAffected()
	if n == 0 {
		return fmt.Errorf("journal entry %d not found", id)
	}
	return nil
}

// InsertDailySummary stores or updates a daily summary.
func (s *SQLiteMemory) InsertDailySummary(summary DailySummary) error {
	if summary.Date == "" {
		summary.Date = time.Now().Format("2006-01-02")
	}

	topicsJSON, _ := json.Marshal(summary.KeyTopics)
	usageJSON, _ := json.Marshal(summary.ToolUsage)
	now := time.Now().UTC().Format(time.RFC3339)

	_, err := s.db.Exec(
		`INSERT INTO daily_summaries (date, summary, key_topics, tool_usage, sentiment, generated_at)
		 VALUES (?, ?, ?, ?, ?, ?)
		 ON CONFLICT(date) DO UPDATE SET
		   summary=excluded.summary, key_topics=excluded.key_topics,
		   tool_usage=excluded.tool_usage, sentiment=excluded.sentiment,
		   generated_at=excluded.generated_at`,
		summary.Date, summary.Summary, string(topicsJSON), string(usageJSON), summary.Sentiment, now,
	)
	if err != nil {
		return fmt.Errorf("insert daily summary: %w", err)
	}
	return nil
}

// GetDailySummary returns the summary for a specific date.
func (s *SQLiteMemory) GetDailySummary(date string) (*DailySummary, error) {
	row := s.db.QueryRow(
		"SELECT date, summary, key_topics, tool_usage, sentiment, generated_at FROM daily_summaries WHERE date = ?", date,
	)

	var d DailySummary
	var topicsJSON, usageJSON string
	if err := row.Scan(&d.Date, &d.Summary, &topicsJSON, &usageJSON, &d.Sentiment, &d.GeneratedAt); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get daily summary: %w", err)
	}
	_ = json.Unmarshal([]byte(topicsJSON), &d.KeyTopics)
	_ = json.Unmarshal([]byte(usageJSON), &d.ToolUsage)
	return &d, nil
}

// GetRecentDailySummaries returns the last N daily summaries.
func (s *SQLiteMemory) GetRecentDailySummaries(days int) ([]DailySummary, error) {
	if days <= 0 {
		days = 7
	}
	rows, err := s.db.Query(
		"SELECT date, summary, key_topics, tool_usage, sentiment, generated_at FROM daily_summaries ORDER BY date DESC LIMIT ?", days,
	)
	if err != nil {
		return nil, fmt.Errorf("get recent summaries: %w", err)
	}
	defer rows.Close()

	var summaries []DailySummary
	for rows.Next() {
		var d DailySummary
		var topicsJSON, usageJSON string
		if err := rows.Scan(&d.Date, &d.Summary, &topicsJSON, &usageJSON, &d.Sentiment, &d.GeneratedAt); err != nil {
			return nil, fmt.Errorf("scan daily summary: %w", err)
		}
		_ = json.Unmarshal([]byte(topicsJSON), &d.KeyTopics)
		_ = json.Unmarshal([]byte(usageJSON), &d.ToolUsage)
		summaries = append(summaries, d)
	}
	return summaries, rows.Err()
}

// GetJournalStats returns counts of journal entries by type for a date range.
func (s *SQLiteMemory) GetJournalStats(from, to string) (map[string]int, error) {
	var conditions []string
	var args []interface{}
	if from != "" {
		conditions = append(conditions, "date >= ?")
		args = append(args, from)
	}
	if to != "" {
		conditions = append(conditions, "date <= ?")
		args = append(args, to)
	}

	query := "SELECT entry_type, COUNT(*) FROM journal_entries"
	if len(conditions) > 0 {
		query += " WHERE " + strings.Join(conditions, " AND ")
	}
	query += " GROUP BY entry_type"

	rows, err := s.db.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("journal stats: %w", err)
	}
	defer rows.Close()

	stats := make(map[string]int)
	for rows.Next() {
		var entryType string
		var count int
		if err := rows.Scan(&entryType, &count); err != nil {
			return nil, fmt.Errorf("scan journal stats: %w", err)
		}
		stats[entryType] = count
	}
	return stats, rows.Err()
}

// FormatJournalEntriesJSON marshals a slice of JournalEntry to JSON.
func FormatJournalEntriesJSON(entries []JournalEntry) string {
	b, err := json.Marshal(entries)
	if err != nil {
		return "[]"
	}
	return string(b)
}

func formatEpisodicCard(card EpisodicMemory) string {
	line := fmt.Sprintf("%s | %s — %s", card.EventDate, card.Title, card.Summary)
	if card.ActionStatus == "pending" {
		line += " | pending follow-up"
	}
	if len(card.Participants) > 0 {
		line += " | with " + strings.Join(card.Participants, ", ")
	}
	if card.EmotionalValence >= 0.45 {
		line += " | positive"
	} else if card.EmotionalValence <= -0.45 {
		line += " | tense"
	}
	return line
}

func uniqueSortedStrings(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	seen := make(map[string]struct{}, len(values))
	out := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" {
			continue
		}
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	sort.Strings(out)
	return out
}
