package server

import (
	"bytes"
	"encoding/json"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"testing"
	"time"

	"aurago/internal/config"
	"aurago/internal/dbutil"
	"aurago/internal/memory"
)

func TestHandleDashboardMemoryCurationDryRunAndApply(t *testing.T) {
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	stm, err := memory.NewSQLiteMemory(":memory:", logger)
	if err != nil {
		t.Fatalf("NewSQLiteMemory: %v", err)
	}
	t.Cleanup(func() { _ = stm.Close() })
	if err := stm.UpsertMemoryMetaWithDetails("doc-confirm", memory.MemoryMetaUpdate{
		ExtractionConfidence: 0.96,
		VerificationStatus:   "unverified",
		SourceReliability:    0.92,
	}); err != nil {
		t.Fatalf("UpsertMemoryMetaWithDetails: %v", err)
	}
	if err := stm.RecordMemoryUsage("doc-confirm", "ltm_retrieved", "sess-1", 0.9, true); err != nil {
		t.Fatalf("RecordMemoryUsage: %v", err)
	}

	cfg := &config.Config{}
	cfg.MemoryAnalysis.AutoConfirm = 0.92
	s := &Server{ShortTermMem: stm, Cfg: cfg, Logger: logger}

	dryReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/curation/dry-run", bytes.NewReader([]byte(`{"limit":100}`)))
	dryRec := httptest.NewRecorder()
	handleDashboardMemoryCuration(s).ServeHTTP(dryRec, dryReq)
	if dryRec.Code != http.StatusOK {
		t.Fatalf("dry-run status = %d, want 200; body=%s", dryRec.Code, dryRec.Body.String())
	}
	var dryBody map[string]interface{}
	if err := json.Unmarshal(dryRec.Body.Bytes(), &dryBody); err != nil {
		t.Fatalf("decode dry-run: %v", err)
	}
	if int(dryBody["auto_confirm_count"].(float64)) != 1 {
		t.Fatalf("auto_confirm_count = %v, want 1", dryBody["auto_confirm_count"])
	}

	badApply := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/curation/apply", bytes.NewReader([]byte(`{"limit":100}`)))
	badRec := httptest.NewRecorder()
	handleDashboardMemoryCuration(s).ServeHTTP(badRec, badApply)
	if badRec.Code != http.StatusBadRequest {
		t.Fatalf("apply without confirm status = %d, want 400", badRec.Code)
	}

	applyReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/curation/apply", bytes.NewReader([]byte(`{"limit":100,"confirm":"APPLY_MEMORY_CURATION"}`)))
	applyRec := httptest.NewRecorder()
	handleDashboardMemoryCuration(s).ServeHTTP(applyRec, applyReq)
	if applyRec.Code != http.StatusOK {
		t.Fatalf("apply status = %d, want 200; body=%s", applyRec.Code, applyRec.Body.String())
	}
	metas, err := stm.GetAllMemoryMeta(10, 0)
	if err != nil {
		t.Fatalf("GetAllMemoryMeta: %v", err)
	}
	if metas[0].VerificationStatus != "confirmed" {
		t.Fatalf("VerificationStatus = %q, want confirmed", metas[0].VerificationStatus)
	}
}

func TestHandleDashboardMemoryHygieneDryRunAndApply(t *testing.T) {
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	dbPath := filepath.Join(t.TempDir(), "stm.db")
	stm, err := memory.NewSQLiteMemory(dbPath, logger)
	if err != nil {
		t.Fatalf("NewSQLiteMemory: %v", err)
	}
	t.Cleanup(func() { _ = stm.Close() })
	if err := stm.InitJournalTables(); err != nil {
		t.Fatalf("InitJournalTables: %v", err)
	}
	if err := stm.InitNotesTables(); err != nil {
		t.Fatalf("InitNotesTables: %v", err)
	}

	old := time.Now().UTC().Add(-48 * time.Hour).Format("2006-01-02 15:04:05")
	for range 2 {
		id, err := stm.InsertJournalEntry(memory.JournalEntry{
			EntryType:     "error_learned",
			Title:         "Error in send_telegram",
			Content:       "message is required",
			AutoGenerated: true,
		})
		if err != nil {
			t.Fatalf("InsertJournalEntry: %v", err)
		}
		rawDB, err := dbutil.Open(dbPath)
		if err != nil {
			t.Fatalf("open raw stm db: %v", err)
		}
		if _, err := rawDB.Exec(`UPDATE journal_entries SET created_at = ? WHERE id = ?`, old, id); err != nil {
			rawDB.Close()
			t.Fatalf("backdate journal: %v", err)
		}
		rawDB.Close()
	}
	noteID, err := stm.AddNote("ops", "Old low priority cleanup", "", 1, "")
	if err != nil {
		t.Fatalf("AddNote: %v", err)
	}
	oldNote := time.Now().UTC().AddDate(0, 0, -100).Format(time.RFC3339)
	rawDB, err := dbutil.Open(dbPath)
	if err != nil {
		t.Fatalf("open raw stm db for note: %v", err)
	}
	if _, err := rawDB.Exec(`UPDATE notes SET updated_at = ?, created_at = ? WHERE id = ?`, oldNote, oldNote, noteID); err != nil {
		rawDB.Close()
		t.Fatalf("backdate note: %v", err)
	}
	rawDB.Close()

	s := &Server{ShortTermMem: stm, Cfg: &config.Config{}, Logger: logger}

	dryReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/hygiene/dry-run", bytes.NewReader([]byte(`{"limit":100}`)))
	dryRec := httptest.NewRecorder()
	handleDashboardMemoryHygiene(s).ServeHTTP(dryRec, dryReq)
	if dryRec.Code != http.StatusOK {
		t.Fatalf("dry-run status = %d, want 200; body=%s", dryRec.Code, dryRec.Body.String())
	}
	var dryBody map[string]interface{}
	if err := json.Unmarshal(dryRec.Body.Bytes(), &dryBody); err != nil {
		t.Fatalf("decode dry-run: %v", err)
	}
	totals := dryBody["totals"].(map[string]interface{})
	if int(totals["journal_duplicates"].(float64)) != 1 || int(totals["notes_auto_archive"].(float64)) != 1 {
		t.Fatalf("dry totals = %#v, want journal duplicate and notes archive", totals)
	}

	badApply := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/hygiene/apply", bytes.NewReader([]byte(`{"limit":100}`)))
	badRec := httptest.NewRecorder()
	handleDashboardMemoryHygiene(s).ServeHTTP(badRec, badApply)
	if badRec.Code != http.StatusBadRequest {
		t.Fatalf("apply without confirm status = %d, want 400", badRec.Code)
	}

	applyReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/hygiene/apply", bytes.NewReader([]byte(`{"limit":100,"confirm":"APPLY_MEMORY_HYGIENE"}`)))
	applyRec := httptest.NewRecorder()
	handleDashboardMemoryHygiene(s).ServeHTTP(applyRec, applyReq)
	if applyRec.Code != http.StatusOK {
		t.Fatalf("apply status = %d, want 200; body=%s", applyRec.Code, applyRec.Body.String())
	}
	entries, err := stm.GetJournalEntries("", "", []string{"error_learned"}, 10)
	if err != nil {
		t.Fatalf("GetJournalEntries: %v", err)
	}
	if len(entries) != 1 {
		t.Fatalf("journal entries after apply = %d, want 1", len(entries))
	}
	activeNotes, err := stm.ListNotes("ops", -1)
	if err != nil {
		t.Fatalf("ListNotes: %v", err)
	}
	if len(activeNotes) != 0 {
		t.Fatalf("active notes after apply = %+v, want none", activeNotes)
	}
}
