package server

import (
	"aurago/internal/config"
	"aurago/internal/llm"
	"strings"
)

// dashboardIntegrationFlags reports configuration, never inferred connection health.
func dashboardIntegrationFlags(cfg *config.Config) map[string]bool {
	return map[string]bool{
		"telegram":          cfg.Telegram.BotToken != "",
		"discord":           cfg.Discord.Enabled,
		"email":             cfg.Email.Enabled,
		"home_assistant":    cfg.HomeAssistant.Enabled,
		"docker":            cfg.Docker.Enabled,
		"co_agents":         cfg.CoAgents.Enabled,
		"webhooks":          cfg.Webhooks.Enabled,
		"webdav":            cfg.WebDAV.Enabled,
		"koofr":             cfg.Koofr.Enabled,
		"paperless_ngx":     cfg.PaperlessNGX.Enabled,
		"chromecast":        cfg.Chromecast.Enabled,
		"bluetooth":         cfg.Bluetooth.Enabled && cfg.Runtime.Bluetooth.Usable,
		"network_shares":    cfg.NetworkShares.Enabled && cfg.Runtime.NetworkShares.Usable,
		"proxmox":           cfg.Proxmox.Enabled,
		"ollama":            cfg.Ollama.Enabled,
		"ollama_managed":    cfg.Ollama.ManagedInstance.Enabled,
		"rocketchat":        cfg.RocketChat.Enabled,
		"tailscale":         cfg.Tailscale.Enabled,
		"cloudflare_tunnel": cfg.CloudflareTunnel.Enabled,
		"ansible":           cfg.Ansible.Enabled,
		"invasion":          cfg.InvasionControl.Enabled,
		"github":            cfg.GitHub.Enabled,
		"mqtt":              cfg.MQTT.Enabled,
		"cyd":               cfg.Cyd.Enabled,
		"budget":            cfg.Budget.Enabled,
		"indexing":          cfg.Indexing.Enabled,
		"auth":              cfg.Auth.Enabled,
		"fallback_llm":      cfg.FallbackLLM.Enabled,
		"helper_llm":        llm.IsHelperLLMAvailable(cfg),
		"personality_v2":    cfg.Personality.EngineV2,
		"user_profiling":    cfg.Personality.UserProfiling,
		"tts":               cfg.TTS.Provider != "" || cfg.TTS.Piper.Enabled,
		"piper_tts":         cfg.TTS.Piper.Enabled,
		"supertonic_tts":    strings.EqualFold(strings.TrimSpace(cfg.TTS.Provider), "supertonic"),
		// extended integrations
		"fritzbox":         cfg.FritzBox.Enabled,
		"meshcentral":      cfg.MeshCentral.Enabled,
		"a2a":              cfg.A2A.Server.Enabled,
		"adguard":          cfg.AdGuard.Enabled,
		"uptime_kuma":      cfg.UptimeKuma.Enabled,
		"grafana":          cfg.Grafana.Enabled,
		"s3":               cfg.S3.Enabled,
		"mcp":              cfg.MCP.Enabled,
		"mcp_server":       cfg.MCPServer.Enabled,
		"dograh":           cfg.Dograh.Enabled,
		"memory_analysis":  true,
		"llm_guardian":     cfg.LLMGuardian.Enabled,
		"security_proxy":   cfg.SecurityProxy.Enabled,
		"sandbox":          cfg.Sandbox.Enabled,
		"ai_gateway":       cfg.AIGateway.Enabled,
		"evomap":           cfg.Evomap.Enabled,
		"image_generation": cfg.ImageGeneration.Enabled,
		"video_generation": cfg.VideoGeneration.Enabled,
		"google_workspace": cfg.GoogleWorkspace.Enabled,
		"netlify":          cfg.Netlify.Enabled,
		"here_now":         cfg.HereNow.Enabled,
		"homepage":         cfg.Homepage.Enabled,
		"virustotal":       cfg.VirusTotal.Enabled,
		"brave_search":     cfg.BraveSearch.Enabled,
		"three_d_printers": cfg.ThreeDPrinters.Enabled,
		"go2rtc":           cfg.Go2RTC.Enabled,
		"firewall":         cfg.Firewall.Enabled,
		"remote_control":   cfg.RemoteControl.Enabled,
		"web_scraper":      cfg.Tools.WebScraper.Enabled,
		"skill_manager":    cfg.Tools.SkillManager.Enabled,
	}
}
