package server

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strconv"
	"testing"
	"time"

	"aurago/internal/config"
	"aurago/internal/dbutil"
	"aurago/internal/memory"

	openai "github.com/sashabaranov/go-openai"
)

type dashboardReflectionTestClient struct{}

func (dashboardReflectionTestClient) CreateChatCompletion(_ context.Context, _ openai.ChatCompletionRequest) (openai.ChatCompletionResponse, error) {
	return openai.ChatCompletionResponse{
		Choices: []openai.ChatCompletionChoice{{
			Message: openai.ChatCompletionMessage{
				Role:    openai.ChatMessageRoleAssistant,
				Content: `{"summary":"Weekly memory reflection found stale tool loops and memory review work.","action_items":["Review unverified memory backlog"],"contradictions":["Core memory and journal disagree"],"error_patterns":["filesystem retries repeated without adaptation"]}`,
			},
		}},
	}, nil
}

func (dashboardReflectionTestClient) CreateChatCompletionStream(_ context.Context, _ openai.ChatCompletionRequest) (*openai.ChatCompletionStream, error) {
	return nil, nil
}

func TestHandleDashboardMemoryCurationDryRunAndApply(t *testing.T) {
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	stm, err := memory.NewSQLiteMemory(":memory:", logger)
	if err != nil {
		t.Fatalf("NewSQLiteMemory: %v", err)
	}
	t.Cleanup(func() { _ = stm.Close() })
	if err := stm.UpsertMemoryMetaWithDetails("doc-confirm", memory.MemoryMetaUpdate{
		ExtractionConfidence: 0.96,
		VerificationStatus:   "unverified",
		SourceReliability:    0.92,
	}); err != nil {
		t.Fatalf("UpsertMemoryMetaWithDetails: %v", err)
	}
	if err := stm.RecordMemoryUsage("doc-confirm", "ltm_retrieved", "sess-1", 0.9, true); err != nil {
		t.Fatalf("RecordMemoryUsage: %v", err)
	}

	cfg := &config.Config{}
	cfg.MemoryAnalysis.AutoConfirm = 0.92
	s := &Server{ShortTermMem: stm, Cfg: cfg, Logger: logger}

	dryReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/curation/dry-run", bytes.NewReader([]byte(`{"limit":100}`)))
	dryRec := httptest.NewRecorder()
	handleDashboardMemoryCuration(s).ServeHTTP(dryRec, dryReq)
	if dryRec.Code != http.StatusOK {
		t.Fatalf("dry-run status = %d, want 200; body=%s", dryRec.Code, dryRec.Body.String())
	}
	var dryBody map[string]interface{}
	if err := json.Unmarshal(dryRec.Body.Bytes(), &dryBody); err != nil {
		t.Fatalf("decode dry-run: %v", err)
	}
	if int(dryBody["auto_confirm_count"].(float64)) != 1 {
		t.Fatalf("auto_confirm_count = %v, want 1", dryBody["auto_confirm_count"])
	}

	badApply := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/curation/apply", bytes.NewReader([]byte(`{"limit":100}`)))
	badRec := httptest.NewRecorder()
	handleDashboardMemoryCuration(s).ServeHTTP(badRec, badApply)
	if badRec.Code != http.StatusBadRequest {
		t.Fatalf("apply without confirm status = %d, want 400", badRec.Code)
	}

	applyReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/curation/apply", bytes.NewReader([]byte(`{"limit":100,"confirm":"APPLY_MEMORY_CURATION"}`)))
	applyRec := httptest.NewRecorder()
	handleDashboardMemoryCuration(s).ServeHTTP(applyRec, applyReq)
	if applyRec.Code != http.StatusOK {
		t.Fatalf("apply status = %d, want 200; body=%s", applyRec.Code, applyRec.Body.String())
	}
	metas, err := stm.GetAllMemoryMeta(10, 0)
	if err != nil {
		t.Fatalf("GetAllMemoryMeta: %v", err)
	}
	if metas[0].VerificationStatus != "confirmed" {
		t.Fatalf("VerificationStatus = %q, want confirmed", metas[0].VerificationStatus)
	}
}

func TestHandleDashboardMemoryHygieneDryRunAndApply(t *testing.T) {
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	dbPath := filepath.Join(t.TempDir(), "stm.db")
	stm, err := memory.NewSQLiteMemory(dbPath, logger)
	if err != nil {
		t.Fatalf("NewSQLiteMemory: %v", err)
	}
	t.Cleanup(func() { _ = stm.Close() })
	if err := stm.InitJournalTables(); err != nil {
		t.Fatalf("InitJournalTables: %v", err)
	}
	if err := stm.InitNotesTables(); err != nil {
		t.Fatalf("InitNotesTables: %v", err)
	}

	old := time.Now().UTC().Add(-48 * time.Hour).Format("2006-01-02 15:04:05")
	for range 2 {
		id, err := stm.InsertJournalEntry(memory.JournalEntry{
			EntryType:     "error_learned",
			Title:         "Error in send_telegram",
			Content:       "message is required",
			AutoGenerated: true,
		})
		if err != nil {
			t.Fatalf("InsertJournalEntry: %v", err)
		}
		rawDB, err := dbutil.Open(dbPath)
		if err != nil {
			t.Fatalf("open raw stm db: %v", err)
		}
		if _, err := rawDB.Exec(`UPDATE journal_entries SET created_at = ? WHERE id = ?`, old, id); err != nil {
			rawDB.Close()
			t.Fatalf("backdate journal: %v", err)
		}
		rawDB.Close()
	}
	noteID, err := stm.AddNote("ops", "Old low priority cleanup", "", 1, "")
	if err != nil {
		t.Fatalf("AddNote: %v", err)
	}
	oldNote := time.Now().UTC().AddDate(0, 0, -100).Format(time.RFC3339)
	rawDB, err := dbutil.Open(dbPath)
	if err != nil {
		t.Fatalf("open raw stm db for note: %v", err)
	}
	if _, err := rawDB.Exec(`UPDATE notes SET updated_at = ?, created_at = ? WHERE id = ?`, oldNote, oldNote, noteID); err != nil {
		rawDB.Close()
		t.Fatalf("backdate note: %v", err)
	}
	rawDB.Close()

	s := &Server{ShortTermMem: stm, Cfg: &config.Config{}, Logger: logger}

	dryReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/hygiene/dry-run", bytes.NewReader([]byte(`{"limit":100}`)))
	dryRec := httptest.NewRecorder()
	handleDashboardMemoryHygiene(s).ServeHTTP(dryRec, dryReq)
	if dryRec.Code != http.StatusOK {
		t.Fatalf("dry-run status = %d, want 200; body=%s", dryRec.Code, dryRec.Body.String())
	}
	var dryBody map[string]interface{}
	if err := json.Unmarshal(dryRec.Body.Bytes(), &dryBody); err != nil {
		t.Fatalf("decode dry-run: %v", err)
	}
	totals := dryBody["totals"].(map[string]interface{})
	if int(totals["journal_duplicates"].(float64)) != 1 || int(totals["notes_auto_archive"].(float64)) != 1 {
		t.Fatalf("dry totals = %#v, want journal duplicate and notes archive", totals)
	}

	badApply := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/hygiene/apply", bytes.NewReader([]byte(`{"limit":100}`)))
	badRec := httptest.NewRecorder()
	handleDashboardMemoryHygiene(s).ServeHTTP(badRec, badApply)
	if badRec.Code != http.StatusBadRequest {
		t.Fatalf("apply without confirm status = %d, want 400", badRec.Code)
	}

	applyReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/hygiene/apply", bytes.NewReader([]byte(`{"limit":100,"confirm":"APPLY_MEMORY_HYGIENE"}`)))
	applyRec := httptest.NewRecorder()
	handleDashboardMemoryHygiene(s).ServeHTTP(applyRec, applyReq)
	if applyRec.Code != http.StatusOK {
		t.Fatalf("apply status = %d, want 200; body=%s", applyRec.Code, applyRec.Body.String())
	}
	entries, err := stm.GetJournalEntries("", "", []string{"error_learned"}, 10)
	if err != nil {
		t.Fatalf("GetJournalEntries: %v", err)
	}
	if len(entries) != 1 {
		t.Fatalf("journal entries after apply = %d, want 1", len(entries))
	}
	activeNotes, err := stm.ListNotes("ops", -1)
	if err != nil {
		t.Fatalf("ListNotes: %v", err)
	}
	if len(activeNotes) != 0 {
		t.Fatalf("active notes after apply = %+v, want none", activeNotes)
	}
}

func TestHandleDashboardMemoryHygieneKGRequiresDedicatedConfirmation(t *testing.T) {
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	stm, err := memory.NewSQLiteMemory(":memory:", logger)
	if err != nil {
		t.Fatalf("NewSQLiteMemory: %v", err)
	}
	t.Cleanup(func() { _ = stm.Close() })
	if err := stm.InitJournalTables(); err != nil {
		t.Fatalf("InitJournalTables: %v", err)
	}
	if err := stm.InitNotesTables(); err != nil {
		t.Fatalf("InitNotesTables: %v", err)
	}
	kgPath := filepath.Join(t.TempDir(), "kg.db")
	kg, err := memory.NewKnowledgeGraph(kgPath, "", logger)
	if err != nil {
		t.Fatalf("NewKnowledgeGraph: %v", err)
	}
	t.Cleanup(func() { _ = kg.Close() })

	for _, id := range []string{"pending-a", "pending-b"} {
		if err := kg.AddNode(id, id, map[string]string{"type": "concept"}); err != nil {
			t.Fatalf("AddNode %s: %v", id, err)
		}
	}
	if err := kg.AddEdge("pending-a", "pending-b", "co_mentioned_with", map[string]string{"source": "pending", "weight": "1"}); err != nil {
		t.Fatalf("AddEdge pending: %v", err)
	}
	rawKGDB, err := dbutil.Open(kgPath)
	if err != nil {
		t.Fatalf("open raw kg db: %v", err)
	}
	if _, err := rawKGDB.Exec(`
		UPDATE kg_edges
		SET created_at = datetime('now', '-10 days'), updated_at = datetime('now', '-10 days')
		WHERE source = 'pending-a' AND target = 'pending-b' AND relation = 'co_mentioned_with'
	`); err != nil {
		rawKGDB.Close()
		t.Fatalf("age pending edge: %v", err)
	}
	rawKGDB.Close()

	cfg := &config.Config{}
	cfg.Tools.KnowledgeGraph.PendingCoMentionTTLDays = 7
	s := &Server{ShortTermMem: stm, KG: kg, Cfg: cfg, Logger: logger}

	dryReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/hygiene/dry-run", bytes.NewReader([]byte(`{"limit":100,"include_kg":true}`)))
	dryRec := httptest.NewRecorder()
	handleDashboardMemoryHygiene(s).ServeHTTP(dryRec, dryReq)
	if dryRec.Code != http.StatusOK {
		t.Fatalf("dry-run status = %d, want 200; body=%s", dryRec.Code, dryRec.Body.String())
	}
	var dryBody map[string]interface{}
	if err := json.Unmarshal(dryRec.Body.Bytes(), &dryBody); err != nil {
		t.Fatalf("decode dry-run: %v", err)
	}
	plan := dryBody["plan"].(map[string]interface{})
	if _, ok := plan["kg"]; !ok {
		t.Fatalf("dry-run plan missing kg section: %#v", plan)
	}

	badApply := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/hygiene/apply", bytes.NewReader([]byte(`{"limit":100,"confirm":"APPLY_MEMORY_HYGIENE","include_kg":true}`)))
	badRec := httptest.NewRecorder()
	handleDashboardMemoryHygiene(s).ServeHTTP(badRec, badApply)
	if badRec.Code != http.StatusBadRequest {
		t.Fatalf("apply without kg_confirm status = %d, want 400", badRec.Code)
	}

	applyReq := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/hygiene/apply", bytes.NewReader([]byte(`{"limit":100,"confirm":"APPLY_MEMORY_HYGIENE","include_kg":true,"kg_confirm":"APPLY_KG_HYGIENE"}`)))
	applyRec := httptest.NewRecorder()
	handleDashboardMemoryHygiene(s).ServeHTTP(applyRec, applyReq)
	if applyRec.Code != http.StatusOK {
		t.Fatalf("apply status = %d, want 200; body=%s", applyRec.Code, applyRec.Body.String())
	}
	_, edgeCount, err := kg.Stats()
	if err != nil {
		t.Fatalf("Stats: %v", err)
	}
	if edgeCount != 0 {
		t.Fatalf("edgeCount = %d, want stale KG edge removed", edgeCount)
	}
}

func TestHandleMemoryConflictResolve(t *testing.T) {
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	stm, err := memory.NewSQLiteMemory(":memory:", logger)
	if err != nil {
		t.Fatalf("NewSQLiteMemory: %v", err)
	}
	t.Cleanup(func() { _ = stm.Close() })
	for _, docID := range []string{"doc-a", "doc-b"} {
		if err := stm.UpsertMemoryMeta(docID); err != nil {
			t.Fatalf("UpsertMemoryMeta(%s): %v", docID, err)
		}
	}
	if err := stm.RegisterMemoryConflict("doc-a", "doc-b", "user|language", "english", "german", "conflicting language"); err != nil {
		t.Fatalf("RegisterMemoryConflict: %v", err)
	}
	conflicts, err := stm.GetOpenMemoryConflicts(10)
	if err != nil {
		t.Fatalf("GetOpenMemoryConflicts: %v", err)
	}
	if len(conflicts) != 1 {
		t.Fatalf("conflicts len = %d, want 1", len(conflicts))
	}
	s := &Server{ShortTermMem: stm, Logger: logger}

	badWinner := bytes.NewBufferString(`{"conflict_id":` + strconv.FormatInt(conflicts[0].ID, 10) + `,"winning_doc_id":"doc-x"}`)
	badReq := httptest.NewRequest(http.MethodPost, "/api/memory/conflicts/resolve", badWinner)
	badRec := httptest.NewRecorder()
	handleMemoryConflictResolve(s).ServeHTTP(badRec, badReq)
	if badRec.Code != http.StatusBadRequest {
		t.Fatalf("bad winner status = %d, want 400; body=%s", badRec.Code, badRec.Body.String())
	}

	body := bytes.NewBufferString(`{"conflict_id":` + strconv.FormatInt(conflicts[0].ID, 10) + `,"winning_doc_id":"doc-a","reason":"doc-a wins"}`)
	req := httptest.NewRequest(http.MethodPost, "/api/memory/conflicts/resolve", body)
	rec := httptest.NewRecorder()
	handleMemoryConflictResolve(s).ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("resolve status = %d, want 200; body=%s", rec.Code, rec.Body.String())
	}
	var payload struct {
		Status          string `json:"status"`
		ConflictID      int64  `json:"conflict_id"`
		WinningDocID    string `json:"winning_doc_id"`
		SupersededDocID string `json:"superseded_doc_id"`
	}
	if err := json.Unmarshal(rec.Body.Bytes(), &payload); err != nil {
		t.Fatalf("decode response: %v", err)
	}
	if payload.Status != "ok" || payload.ConflictID != conflicts[0].ID || payload.WinningDocID != "doc-a" || payload.SupersededDocID != "doc-b" {
		t.Fatalf("unexpected resolve payload: %+v", payload)
	}
}

func TestHandleDashboardMemoryReflectionRunCreatesLatestReflection(t *testing.T) {
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	stm, err := memory.NewSQLiteMemory(":memory:", logger)
	if err != nil {
		t.Fatalf("NewSQLiteMemory: %v", err)
	}
	t.Cleanup(func() { _ = stm.Close() })
	if err := stm.InitJournalTables(); err != nil {
		t.Fatalf("InitJournalTables: %v", err)
	}

	cfg := &config.Config{}
	cfg.MemoryAnalysis.Enabled = true
	cfg.LLM.Model = "test-model"
	s := &Server{
		Cfg:          cfg,
		Logger:       logger,
		ShortTermMem: stm,
		LLMClient:    dashboardReflectionTestClient{},
	}

	req := httptest.NewRequest(http.MethodPost, "/api/dashboard/memory/reflection/run", bytes.NewReader([]byte(`{}`)))
	rec := httptest.NewRecorder()
	handleDashboardMemoryReflectionRun(s).ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("reflection run status = %d, want 200; body=%s", rec.Code, rec.Body.String())
	}

	var body map[string]interface{}
	if err := json.Unmarshal(rec.Body.Bytes(), &body); err != nil {
		t.Fatalf("decode reflection run: %v", err)
	}
	latest, ok := body["latest_reflection"].(map[string]interface{})
	if !ok {
		t.Fatalf("latest_reflection has type %T", body["latest_reflection"])
	}
	if got := latest["summary"].(string); got != "Weekly memory reflection found stale tool loops and memory review work." {
		t.Fatalf("latest_reflection.summary = %q", got)
	}

	entries, err := stm.GetJournalEntries("", "", []string{"reflection"}, 5)
	if err != nil {
		t.Fatalf("GetJournalEntries: %v", err)
	}
	if len(entries) != 1 {
		t.Fatalf("journal reflection entries = %d, want 1", len(entries))
	}
}
