package agent

import (
	"io"
	"log/slog"
	"testing"
	"time"

	"aurago/internal/memory"
	"aurago/internal/services"
)

func TestTryClaimWeeklyReflectionSingleFlight(t *testing.T) {
	releaseWeeklyReflectionClaim()

	if !tryClaimWeeklyReflection(nil) {
		t.Fatal("expected first weekly reflection claim to succeed")
	}
	if tryClaimWeeklyReflection(nil) {
		t.Fatal("expected second weekly reflection claim to be rejected")
	}

	releaseWeeklyReflectionClaim()
	if !tryClaimWeeklyReflection(nil) {
		t.Fatal("expected claim to succeed after release")
	}
}

func TestLogFileKGSyncResultLogsErrorsWithoutPanic(t *testing.T) {
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	logFileKGSyncResult(logger, services.FileKGSyncResult{
		FilesProcessed: 2,
		Errors:         []string{"file-a: timeout"},
	})
	logFileKGSyncResult(logger, services.FileKGSyncResult{
		FilesProcessed: 1,
		NodesExtracted: 3,
	})
	logFileKGSyncResult(nil, services.FileKGSyncResult{})
}

func TestRunJournalDuplicateConsolidationProcessesBacklog(t *testing.T) {
	stm := newJournalHygieneTestDB(t)
	now := time.Date(2026, 6, 10, 12, 0, 0, 0, time.UTC)
	oldCreated := now.Add(-48 * time.Hour).Format("2006-01-02 15:04:05")

	for range 3 {
		id, err := stm.InsertJournalEntry(memory.JournalEntry{
			EntryType:     "error_learned",
			Title:         "Error in docker",
			Content:       "container not found",
			Tags:          []string{"tool", "docker"},
			AutoGenerated: true,
		})
		if err != nil {
			t.Fatalf("InsertJournalEntry: %v", err)
		}
		if err := stm.SetJournalEntryCreatedAt(id, oldCreated); err != nil {
			t.Fatalf("SetJournalEntryCreatedAt: %v", err)
		}
	}

	removed, err := runJournalDuplicateConsolidation(stm, memory.JournalConsolidationOptions{
		Now:           now,
		OlderThan:     24 * time.Hour,
		MinDuplicates: 2,
		Limit:         100,
		Actor:         "test",
	})
	if err != nil {
		t.Fatalf("runJournalDuplicateConsolidation: %v", err)
	}
	if removed != 2 {
		t.Fatalf("removed = %d, want 2", removed)
	}

	entries, err := stm.GetJournalEntries("", "", []string{"error_learned"}, 10)
	if err != nil {
		t.Fatalf("GetJournalEntries: %v", err)
	}
	if len(entries) != 1 {
		t.Fatalf("entries = %d, want 1 kept duplicate", len(entries))
	}
}

func newJournalHygieneTestDB(t *testing.T) *memory.SQLiteMemory {
	t.Helper()
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	stm, err := memory.NewSQLiteMemory(":memory:", logger)
	if err != nil {
		t.Fatalf("NewSQLiteMemory: %v", err)
	}
	if err := stm.InitJournalTables(); err != nil {
		t.Fatalf("InitJournalTables: %v", err)
	}
	t.Cleanup(func() { _ = stm.Close() })
	return stm
}