package agent

import (
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"strconv"
	"strings"
	"sync"
	"time"

	"aurago/internal/config"
	"aurago/internal/memory"
	"aurago/internal/planner"
)

const maxJournalHygieneIterations = 5
const maxNotesAutoArchivePerHygieneRun = 20
const knowledgeGraphDuplicateIssueThreshold = 3

const plannerMetaKGDroppedAccessHitsKey = "kg_dropped_access_hits_last_recorded"

var (
	lastRecordedKGDroppedAccessHits int64
	kgDroppedAccessHitsStateMu      sync.Mutex
	kgDroppedAccessHitsStateLoaded  bool
)

func runJournalDuplicateConsolidation(stm *memory.SQLiteMemory, opts memory.JournalConsolidationOptions) (int, error) {
	totalRemoved := 0
	var lastErr error
	for range maxJournalHygieneIterations {
		report, err := stm.ConsolidateDuplicateAutoJournalErrors(opts)
		if err != nil {
			return totalRemoved, err
		}
		totalRemoved += report.RemovedEntries
		if report.RemovedEntries == 0 {
			break
		}
		lastErr = nil
	}
	return totalRemoved, lastErr
}

func runAutomaticMemoryHygiene(cfg *config.Config, logger *slog.Logger, stm *memory.SQLiteMemory, ltm memory.VectorDB) memoryHygieneStats {
	if cfg == nil || stm == nil {
		return memoryHygieneStats{}
	}
	journalRemoved := 0
	if cfg.Tools.Journal.Enabled {
		removed, err := runJournalDuplicateConsolidation(stm, memory.JournalConsolidationOptions{
			Now:           time.Now().UTC(),
			OlderThan:     24 * time.Hour,
			MinDuplicates: 2,
			Limit:         100,
			Actor:         "maintenance",
		})
		if err != nil {
			logger.Warn("[MemoryHygiene] Failed to consolidate duplicate journal errors", "error", err)
		} else {
			journalRemoved = removed
		}
	}

	notesArchived := 0
	notesReview := 0
	if cfg.Tools.Notes.Enabled {
		plan, err := stm.BuildNotesCurationPlan(memory.NotesCurationOptions{Now: time.Now().UTC(), MaxActions: maxNotesAutoArchivePerHygieneRun})
		if err != nil {
			logger.Warn("[MemoryHygiene] Failed to build notes curation plan", "error", err)
		} else {
			notesReview = plan.ReviewRequiredCount
			for _, action := range plan.AutoArchive {
				targetID := fmt.Sprintf("note:%d", action.NoteID)
				if stm.ShouldSkipMemoryMaintenanceAction("note_archive", targetID, 3) {
					logger.Warn("[MemoryHygiene] Skipping stale note archive after repeated failures", "note_id", action.NoteID)
					continue
				}
				if err := stm.ApplyNoteCurationAction(action, "maintenance", false); err != nil {
					logger.Warn("[MemoryHygiene] Failed to archive stale note", "note_id", action.NoteID, "error", err)
					_ = stm.RecordMemoryMaintenanceFailure("note_archive", targetID, err)
					continue
				}
				_ = stm.ClearMemoryMaintenanceFailure("note_archive", targetID)
				notesArchived++
			}
		}
	}

	canonicalRepaired := 0
	if ltm != nil && !ltm.IsDisabled() && ltm.IsReady() {
		report, err := stm.RepairCanonicalMemoryNames(ltm, memory.CanonicalRepairOptions{
			Limit:  100,
			Actor:  "maintenance",
			DryRun: false,
		})
		if err != nil {
			logger.Warn("[MemoryHygiene] Failed to repair canonical memory names", "error", err)
			for _, item := range report.Items {
				if strings.TrimSpace(item.Error) == "" {
					continue
				}
				targetID := item.OldDocID
				if targetID == "" {
					targetID = strings.Join(item.NewDocIDs, ",")
				}
				_ = stm.RecordMemoryMaintenanceFailure("canonical_repair", targetID, errors.New(item.Error))
			}
		} else {
			canonicalRepaired = report.RepairedCount
			if canonicalRepaired > 0 {
				InvalidateMemoryMetaCache()
			}
			for _, item := range report.Items {
				if item.OldDocID != "" && strings.TrimSpace(item.Error) == "" {
					_ = stm.ClearMemoryMaintenanceFailure("canonical_repair", item.OldDocID)
				}
			}
		}
	}

	totalApplied := journalRemoved + notesArchived + canonicalRepaired
	if totalApplied == 0 && notesReview == 0 {
		return memoryHygieneStats{
			JournalRemoved:    journalRemoved,
			NotesArchived:     notesArchived,
			CanonicalRepaired: canonicalRepaired,
		}
	}
	logger.Info("[MemoryHygiene] Maintenance run complete",
		"journal_removed", journalRemoved,
		"notes_archived", notesArchived,
		"notes_review_required", notesReview,
		"canonical_repaired", canonicalRepaired)
	if cfg.Tools.Journal.Enabled && totalApplied > 0 {
		_, _ = stm.InsertJournalEntry(memory.JournalEntry{
			EntryType:     "system_event",
			Title:         "Memory hygiene maintenance",
			Content:       fmt.Sprintf("Applied memory hygiene: journal_duplicates_removed=%d, notes_archived=%d, canonical_repairs=%d, notes_review_required=%d.", journalRemoved, notesArchived, canonicalRepaired, notesReview),
			Tags:          []string{"memory", "maintenance", "hygiene"},
			Importance:    2,
			AutoGenerated: true,
		})
	}
	return memoryHygieneStats{
		JournalRemoved:    journalRemoved,
		NotesArchived:     notesArchived,
		CanonicalRepaired: canonicalRepaired,
	}
}

func recordMemoryReflectionReviewIssue(plannerDB *sql.DB, scope string, curator memory.MemoryCuratorDryRun, logger *slog.Logger) {
	issue, ok := buildMemoryReflectionReviewIssue(scope, curator)
	if !ok {
		return
	}
	recordOperationalIssue(RunConfig{PlannerDB: plannerDB, MessageSource: "memory_reflect"}, issue, logger)
}

func buildMemoryReflectionReviewIssue(scope string, curator memory.MemoryCuratorDryRun) (planner.OperationalIssue, bool) {
	scope = strings.ToLower(strings.TrimSpace(scope))
	if scope == "" {
		scope = "recent"
	}
	actionable := curator.Contradictions > 0 ||
		curator.StaleCandidates >= 25 ||
		curator.VerificationBacklog >= 50 ||
		curator.LowEffectiveness >= 10 ||
		curator.OverusedMemories >= 5
	if !actionable {
		return planner.OperationalIssue{}, false
	}
	detail := fmt.Sprintf(
		"Memory reflection found curator review work: stale_candidates=%d, verification_backlog=%d, contradictions=%d, low_confidence=%d, low_effectiveness=%d, overused_memories=%d.",
		curator.StaleCandidates,
		curator.VerificationBacklog,
		curator.Contradictions,
		curator.LowConfidence,
		curator.LowEffectiveness,
		curator.OverusedMemories,
	)
	if len(curator.Suggestions) > 0 {
		detail += " Suggestions: " + strings.Join(curator.Suggestions, "; ")
	}
	return planner.OperationalIssue{
		Source:      "memory_reflect",
		Context:     scope,
		Title:       "Memory review needed",
		Detail:      detail,
		Severity:    "warning",
		Reference:   "memory_reflect",
		Fingerprint: "memory_reflect|" + scope + "|curator_review",
		OccurredAt:  time.Now(),
	}, true
}

func recordKnowledgeGraphQualityIssues(plannerDB *sql.DB, kg *memory.KnowledgeGraph, logger *slog.Logger) {
	if kg == nil {
		return
	}
	report, err := kg.QualityReport(5)
	if err != nil {
		if logger != nil {
			logger.Warn("[MemoryHygiene] Failed to build knowledge graph quality report", "error", err)
		}
		return
	}
	if issue, ok := buildKnowledgeGraphDuplicateIssue(report); ok {
		recordOperationalIssue(RunConfig{PlannerDB: plannerDB, MessageSource: "maintenance", IsMaintenance: true}, issue, logger)
	}
	recordKnowledgeGraphDroppedAccessHitsIssue(plannerDB, kg, logger)
}

func buildKnowledgeGraphDuplicateIssue(report *memory.KnowledgeGraphQualityReport) (planner.OperationalIssue, bool) {
	if report == nil {
		return planner.OperationalIssue{}, false
	}
	if report.DuplicateGroups <= knowledgeGraphDuplicateIssueThreshold && report.IDDuplicateGroups <= knowledgeGraphDuplicateIssueThreshold {
		return planner.OperationalIssue{}, false
	}
	sampleIDs := make([]string, 0, 8)
	for _, candidate := range append(report.DuplicateCandidates, report.IDDuplicateCandidates...) {
		for _, id := range candidate.IDs {
			id = strings.TrimSpace(id)
			if id == "" {
				continue
			}
			sampleIDs = append(sampleIDs, id)
			if len(sampleIDs) >= 8 {
				break
			}
		}
		if len(sampleIDs) >= 8 {
			break
		}
	}
	detail := fmt.Sprintf(
		"Knowledge graph has label_duplicate_groups=%d label_duplicate_nodes=%d id_duplicate_groups=%d id_duplicate_nodes=%d. Review and merge manually in the dashboard; no auto-merge is performed.",
		report.DuplicateGroups,
		report.DuplicateNodes,
		report.IDDuplicateGroups,
		report.IDDuplicateNodes,
	)
	if len(sampleIDs) > 0 {
		detail += " Sample IDs: " + strings.Join(sampleIDs, ", ")
	}
	return planner.OperationalIssue{
		Source:      "maintenance",
		Context:     "knowledge_graph",
		Title:       "Knowledge graph duplicates detected",
		Detail:      detail,
		Severity:    "warning",
		Reference:   "kg_duplicates",
		Fingerprint: "maintenance|knowledge_graph|duplicates",
		OccurredAt:  time.Now(),
	}, true
}

func ensureKGDroppedAccessHitsBaseline(plannerDB *sql.DB, logger *slog.Logger) {
	kgDroppedAccessHitsStateMu.Lock()
	defer kgDroppedAccessHitsStateMu.Unlock()
	if kgDroppedAccessHitsStateLoaded {
		return
	}
	kgDroppedAccessHitsStateLoaded = true
	if plannerDB == nil {
		return
	}
	raw, err := planner.GetPlannerMeta(plannerDB, plannerMetaKGDroppedAccessHitsKey)
	if err != nil {
		if logger != nil {
			logger.Warn("[MemoryHygiene] Failed to load KG dropped-access baseline", "error", err)
		}
		return
	}
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return
	}
	parsed, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		if logger != nil {
			logger.Warn("[MemoryHygiene] Invalid KG dropped-access baseline", "value", raw, "error", err)
		}
		return
	}
	if parsed > 0 {
		lastRecordedKGDroppedAccessHits = parsed
	}
}

func persistKGDroppedAccessHitsBaseline(plannerDB *sql.DB, value int64, logger *slog.Logger) {
	if plannerDB == nil {
		return
	}
	if err := planner.SetPlannerMeta(plannerDB, plannerMetaKGDroppedAccessHitsKey, strconv.FormatInt(value, 10)); err != nil && logger != nil {
		logger.Warn("[MemoryHygiene] Failed to persist KG dropped-access baseline", "error", err)
	}
}

func recordKnowledgeGraphDroppedAccessHitsIssue(plannerDB *sql.DB, kg *memory.KnowledgeGraph, logger *slog.Logger) {
	if kg == nil {
		return
	}
	ensureKGDroppedAccessHitsBaseline(plannerDB, logger)

	current := kg.DroppedAccessHits()
	delta := current - lastRecordedKGDroppedAccessHits
	lastRecordedKGDroppedAccessHits = current
	persistKGDroppedAccessHitsBaseline(plannerDB, current, logger)

	issue, ok := buildKnowledgeGraphDroppedAccessHitsIssue(delta)
	if !ok {
		return
	}
	recordOperationalIssue(RunConfig{PlannerDB: plannerDB, MessageSource: "maintenance", IsMaintenance: true}, issue, logger)
}

func buildKnowledgeGraphDroppedAccessHitsIssue(delta int64) (planner.OperationalIssue, bool) {
	if delta <= 0 {
		return planner.OperationalIssue{}, false
	}
	return planner.OperationalIssue{
		Source:      "maintenance",
		Context:     "knowledge_graph",
		Title:       "Knowledge graph access updates were dropped",
		Detail:      fmt.Sprintf("Dropped %d knowledge graph access-counter updates since the previous maintenance run because the async queue was full. Importance scores may be slightly stale until load decreases.", delta),
		Severity:    "warning",
		Reference:   "kg_dropped_access_hits",
		Fingerprint: "maintenance|knowledge_graph|dropped_access_hits",
		OccurredAt:  time.Now(),
	}, true
}

func recordKnowledgeGraphSparseIssue(plannerDB *sql.DB, stm *memory.SQLiteMemory, kg *memory.KnowledgeGraph, logger *slog.Logger) {
	if stm == nil || kg == nil {
		return
	}
	facts, err := stm.GetCoreMemoryFacts()
	if err != nil {
		if logger != nil {
			logger.Warn("[MemoryHygiene] Failed to read core memory facts for KG health", "error", err)
		}
		return
	}
	nodes, edges, err := kg.Stats()
	if err != nil {
		if logger != nil {
			logger.Warn("[MemoryHygiene] Failed to read KG stats", "error", err)
		}
		return
	}
	factTexts := make([]string, 0, len(facts))
	for _, fact := range facts {
		factTexts = append(factTexts, fact.Fact)
	}
	if issue, ok := buildCoreMemoryReviewIssue(factTexts); ok {
		recordOperationalIssue(RunConfig{PlannerDB: plannerDB, MessageSource: "maintenance", IsMaintenance: true}, issue, logger)
	}
	issue, ok := buildKnowledgeGraphSparseIssue(factTexts, nodes, edges)
	if !ok {
		return
	}
	recordOperationalIssue(RunConfig{PlannerDB: plannerDB, MessageSource: "maintenance", IsMaintenance: true}, issue, logger)
}

func recordKnowledgeGraphSemanticReindexBacklogIssue(plannerDB *sql.DB, dirtyNodes, dirtyEdges int, logger *slog.Logger) {
	issue, ok := buildKnowledgeGraphSemanticReindexBacklogIssue(dirtyNodes, dirtyEdges)
	if !ok {
		return
	}
	recordOperationalIssue(RunConfig{PlannerDB: plannerDB, MessageSource: "maintenance", IsMaintenance: true}, issue, logger)
}

func buildKnowledgeGraphSemanticReindexBacklogIssue(dirtyNodes, dirtyEdges int) (planner.OperationalIssue, bool) {
	if dirtyNodes <= 5000 && dirtyEdges <= 5000 {
		return planner.OperationalIssue{}, false
	}
	return planner.OperationalIssue{
		Source:      "maintenance",
		Context:     "knowledge_graph",
		Title:       "Knowledge graph semantic reindex backlog is high",
		Detail:      fmt.Sprintf("Semantic reindex still has dirty_nodes=%d and dirty_edges=%d after the latest maintenance run. The nightly batch only processes 5000 dirty rows per pass.", dirtyNodes, dirtyEdges),
		Severity:    "warning",
		Reference:   "kg_semantic_reindex_backlog",
		Fingerprint: "maintenance|knowledge_graph|semantic_reindex_backlog",
		OccurredAt:  time.Now(),
	}, true
}

func buildKnowledgeGraphSparseIssue(coreFacts []string, nodes int, edges int) (planner.OperationalIssue, bool) {
	if len(coreFacts) == 0 || nodes >= 3 {
		return planner.OperationalIssue{}, false
	}
	return planner.OperationalIssue{
		Source:      "maintenance",
		Context:     "memory_hygiene",
		Title:       "Knowledge graph appears underpopulated",
		Detail:      fmt.Sprintf("Knowledge graph has core_facts=%d, nodes=%d, edges=%d. Check KG auto-extraction and core-memory sync.", len(coreFacts), nodes, edges),
		Severity:    "warning",
		Reference:   "knowledge_graph",
		Fingerprint: "memory_maintenance|kg_sparse|core_facts_present",
		OccurredAt:  time.Now(),
	}, true
}

func buildCoreMemoryReviewIssue(coreFacts []string) (planner.OperationalIssue, bool) {
	var lowSignal []string
	for _, issue := range memory.ReviewCoreMemoryFacts(coreFacts) {
		lowSignal = append(lowSignal, formatCoreMemoryReviewCandidate(issue.Fact, issue.Reason))
	}
	for _, fact := range coreFacts {
		trimmed := strings.TrimSpace(fact)
		if trimmed == "" {
			continue
		}
		lower := strings.ToLower(trimmed)
		if strings.Contains(lower, "test fact") || strings.Contains(lower, "test-fact") {
			lowSignal = append(lowSignal, formatCoreMemoryReviewCandidate(trimmed, "low-signal test fact"))
		}
	}
	if len(lowSignal) == 0 {
		return planner.OperationalIssue{}, false
	}
	if len(lowSignal) > 5 {
		lowSignal = append(lowSignal[:5], fmt.Sprintf("...%d more", len(lowSignal)-5))
	}
	return planner.OperationalIssue{
		Source:      "maintenance",
		Context:     "memory_hygiene",
		Title:       "Core memory review needed",
		Detail:      "Core memory contains low-signal candidate facts: " + strings.Join(lowSignal, "; "),
		Severity:    "warning",
		Reference:   "core_memory",
		Fingerprint: "memory_maintenance|core_memory_review|low_signal",
		OccurredAt:  time.Now(),
	}, true
}

func formatCoreMemoryReviewCandidate(fact, reason string) string {
	fact = strings.TrimSpace(fact)
	if len(fact) > 180 {
		fact = fact[:177] + "..."
	}
	reason = strings.TrimSpace(reason)
	if reason == "" {
		return fact
	}
	return fact + " (" + reason + ")"
}
