package agent

import (
	"fmt"
	"log/slog"
	"strings"

	"aurago/internal/config"
	"aurago/internal/memory"
)

// JournalAutoTrigger checks completed tool chains and creates appropriate journal entries.
// Called at the end of a successful agent loop iteration (after final response).
// lastUserMsg is used to enrich the entry title with the user's intent.
func JournalAutoTrigger(cfg *config.Config, stm *memory.SQLiteMemory, logger *slog.Logger, sessionID string, toolsUsed []string, lastUserMsg string) {
	if cfg == nil || stm == nil || !cfg.Tools.Journal.Enabled || !cfg.Journal.AutoEntries {
		return
	}
	// Skip maintenance and co-agent sessions
	if sessionID == "maintenance" || strings.HasPrefix(sessionID, "coagent-") {
		return
	}

	// Trigger: Tool chain with ≥3 unique tools = task_completed
	uniqueTools := uniqueStrings(toolsUsed)
	if len(uniqueTools) >= 3 {
		// Include a short preview of the user's request in the title for context
		titleSuffix := ""
		if lastUserMsg != "" {
			preview := lastUserMsg
			if len(preview) > 60 {
				preview = preview[:60] + "…"
			}
			titleSuffix = ": " + preview
		}
		title := fmt.Sprintf("Task completed (%d tools)%s", len(uniqueTools), titleSuffix)
		content := fmt.Sprintf("Tool chain: %s", strings.Join(uniqueTools, " → "))
		id, err := stm.InsertJournalEntry(memory.JournalEntry{
			EntryType:     "task_completed",
			Title:         title,
			Content:       content,
			Tags:          uniqueTools,
			Importance:    2,
			SessionID:     sessionID,
			AutoGenerated: true,
		})
		if err != nil {
			logger.Warn("[Journal] Failed to auto-create task_completed entry", "error", err)
		} else {
			logger.Debug("[Journal] Auto-created task_completed entry", "id", id, "tools", len(uniqueTools))
		}
	}

	// Trigger: Core memory was updated = preference
	for _, t := range toolsUsed {
		if t == "manage_memory" {
			id, err := stm.InsertJournalEntry(memory.JournalEntry{
				EntryType:     "preference",
				Title:         "Core memory updated",
				Content:       "Agent stored or updated a core memory entry during this session.",
				Importance:    2,
				SessionID:     sessionID,
				AutoGenerated: true,
			})
			if err != nil {
				logger.Warn("[Journal] Failed to auto-create preference entry", "error", err)
			} else {
				logger.Debug("[Journal] Auto-created preference entry", "id", id)
			}
			break // Only one entry per session
		}
	}

	// Trigger: First use of a new tool = integration
	checkFirstToolUse(cfg, stm, logger, sessionID, uniqueTools)

	// Trigger: Every user-requested turn gets a lightweight activity trace so
	// temporal recall ("what happened yesterday?") also works for short sessions.
	if entry := buildActivityEntry(sessionID, uniqueTools, lastUserMsg); entry != nil {
		id, err := stm.InsertJournalEntry(*entry)
		if err != nil {
			logger.Warn("[Journal] Failed to auto-create activity entry", "error", err)
		} else {
			logger.Debug("[Journal] Auto-created activity entry", "id", id, "tools", len(uniqueTools))
		}
	}
}

// checkFirstToolUse detects tools used for the first time based on interaction_patterns.
func checkFirstToolUse(cfg *config.Config, stm *memory.SQLiteMemory, logger *slog.Logger, sessionID string, tools []string) {
	for _, toolName := range tools {
		// Skip common tools that aren't interesting to journal
		if isCommonTool(toolName) {
			continue
		}
		// Check if this tool has ever been used before (count in interaction patterns)
		count, err := stm.GetToolUsageCount(toolName)
		if err != nil {
			continue
		}
		// count == 1 means this is the first use (UpsertToolUsage already ran before we check)
		if count == 1 {
			// Extra dedup guard: skip if an integration entry for this tool already exists
			// (protects against any future inconsistency in tool_usage_adaptive)
			if exists, _ := stm.JournalEntryExists("integration", fmt.Sprintf("First use of %s", toolName)); exists {
				continue
			}
			id, err := stm.InsertJournalEntry(memory.JournalEntry{
				EntryType:     "integration",
				Title:         fmt.Sprintf("First use of %s", toolName),
				Content:       fmt.Sprintf("Tool %q was used for the first time.", toolName),
				Tags:          []string{toolName},
				Importance:    2,
				SessionID:     sessionID,
				AutoGenerated: true,
			})
			if err != nil {
				logger.Warn("[Journal] Failed to auto-create integration entry", "error", err)
			} else {
				logger.Debug("[Journal] Auto-created integration entry", "id", id, "tool", toolName)
			}
		}
	}
}

// isCommonTool returns true for everyday tools that don't warrant a "first use" journal entry.
func isCommonTool(name string) bool {
	switch name {
	case "execute_shell", "execute_python", "manage_memory", "manage_notes",
		"file_system", "query_memory", "knowledge_graph", "http_request",
		"manage_journal", "follow_up":
		return true
	}
	return false
}

func uniqueStrings(in []string) []string {
	seen := make(map[string]bool, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

func buildActivityEntry(sessionID string, uniqueTools []string, lastUserMsg string) *memory.JournalEntry {
	preview := strings.TrimSpace(lastUserMsg)
	if preview == "" {
		return nil
	}
	if len(preview) > 80 {
		preview = preview[:80] + "…"
	}

	content := fmt.Sprintf("User request: %s", strings.TrimSpace(lastUserMsg))
	tags := make([]string, 0, len(uniqueTools)+1)
	tags = append(tags, "activity")
	if len(uniqueTools) == 0 {
		content += "\nTools used: none"
	} else {
		content += "\nTools used: " + strings.Join(uniqueTools, ", ")
		tags = append(tags, uniqueTools...)
	}

	return &memory.JournalEntry{
		EntryType:     "activity",
		Title:         "Activity: " + preview,
		Content:       content,
		Tags:          tags,
		Importance:    1,
		SessionID:     sessionID,
		AutoGenerated: true,
	}
}
