package agent

import (
	"database/sql"
	"fmt"
	"log/slog"
	"strings"
	"time"

	"aurago/internal/config"
	"aurago/internal/memory"
	"aurago/internal/planner"
)

func runAutomaticMemoryHygiene(cfg *config.Config, logger *slog.Logger, stm *memory.SQLiteMemory, ltm memory.VectorDB) {
	if cfg == nil || stm == nil {
		return
	}
	journalRemoved := 0
	if cfg.Tools.Journal.Enabled {
		report, err := stm.ConsolidateDuplicateAutoJournalErrors(memory.JournalConsolidationOptions{
			Now:           time.Now().UTC(),
			OlderThan:     24 * time.Hour,
			MinDuplicates: 2,
			Limit:         100,
			Actor:         "maintenance",
		})
		if err != nil {
			logger.Warn("[MemoryHygiene] Failed to consolidate duplicate journal errors", "error", err)
		} else {
			journalRemoved = report.RemovedEntries
		}
	}

	notesArchived := 0
	notesReview := 0
	if cfg.Tools.Notes.Enabled {
		plan, err := stm.BuildNotesCurationPlan(memory.NotesCurationOptions{Now: time.Now().UTC(), MaxActions: 100})
		if err != nil {
			logger.Warn("[MemoryHygiene] Failed to build notes curation plan", "error", err)
		} else {
			notesReview = plan.ReviewRequiredCount
			for _, action := range plan.AutoArchive {
				if err := stm.ApplyNoteCurationAction(action, "maintenance", false); err != nil {
					logger.Warn("[MemoryHygiene] Failed to archive stale note", "note_id", action.NoteID, "error", err)
					continue
				}
				notesArchived++
			}
		}
	}

	canonicalRepaired := 0
	if ltm != nil && !ltm.IsDisabled() && ltm.IsReady() {
		report, err := stm.RepairCanonicalMemoryNames(ltm, memory.CanonicalRepairOptions{
			Limit:  100,
			Actor:  "maintenance",
			DryRun: false,
		})
		if err != nil {
			logger.Warn("[MemoryHygiene] Failed to repair canonical memory names", "error", err)
		} else {
			canonicalRepaired = report.RepairedCount
			if canonicalRepaired > 0 {
				InvalidateMemoryMetaCache()
			}
		}
	}

	totalApplied := journalRemoved + notesArchived + canonicalRepaired
	if totalApplied == 0 && notesReview == 0 {
		return
	}
	logger.Info("[MemoryHygiene] Maintenance run complete",
		"journal_removed", journalRemoved,
		"notes_archived", notesArchived,
		"notes_review_required", notesReview,
		"canonical_repaired", canonicalRepaired)
	if cfg.Tools.Journal.Enabled && totalApplied > 0 {
		_, _ = stm.InsertJournalEntry(memory.JournalEntry{
			EntryType:     "system_event",
			Title:         "Memory hygiene maintenance",
			Content:       fmt.Sprintf("Applied memory hygiene: journal_duplicates_removed=%d, notes_archived=%d, canonical_repairs=%d, notes_review_required=%d.", journalRemoved, notesArchived, canonicalRepaired, notesReview),
			Tags:          []string{"memory", "maintenance", "hygiene"},
			Importance:    2,
			AutoGenerated: true,
		})
	}
}

func recordMemoryReflectionReviewIssue(plannerDB *sql.DB, scope string, curator memory.MemoryCuratorDryRun, logger *slog.Logger) {
	issue, ok := buildMemoryReflectionReviewIssue(scope, curator)
	if !ok {
		return
	}
	recordOperationalIssue(RunConfig{PlannerDB: plannerDB, MessageSource: "memory_reflect"}, issue, logger)
}

func buildMemoryReflectionReviewIssue(scope string, curator memory.MemoryCuratorDryRun) (planner.OperationalIssue, bool) {
	scope = strings.ToLower(strings.TrimSpace(scope))
	if scope == "" {
		scope = "recent"
	}
	actionable := curator.Contradictions > 0 ||
		curator.StaleCandidates >= 25 ||
		curator.VerificationBacklog >= 50 ||
		curator.LowEffectiveness >= 10 ||
		curator.OverusedMemories >= 5
	if !actionable {
		return planner.OperationalIssue{}, false
	}
	detail := fmt.Sprintf(
		"Memory reflection found curator review work: stale_candidates=%d, verification_backlog=%d, contradictions=%d, low_confidence=%d, low_effectiveness=%d, overused_memories=%d.",
		curator.StaleCandidates,
		curator.VerificationBacklog,
		curator.Contradictions,
		curator.LowConfidence,
		curator.LowEffectiveness,
		curator.OverusedMemories,
	)
	if len(curator.Suggestions) > 0 {
		detail += " Suggestions: " + strings.Join(curator.Suggestions, "; ")
	}
	return planner.OperationalIssue{
		Source:      "memory_reflect",
		Context:     scope,
		Title:       "Memory review needed",
		Detail:      detail,
		Severity:    "warning",
		Reference:   "memory_reflect",
		Fingerprint: "memory_reflect|" + scope + "|curator_review",
		OccurredAt:  time.Now(),
	}, true
}

func recordKnowledgeGraphSparseIssue(plannerDB *sql.DB, stm *memory.SQLiteMemory, kg *memory.KnowledgeGraph, logger *slog.Logger) {
	if stm == nil || kg == nil {
		return
	}
	facts, err := stm.GetCoreMemoryFacts()
	if err != nil {
		if logger != nil {
			logger.Warn("[MemoryHygiene] Failed to read core memory facts for KG health", "error", err)
		}
		return
	}
	nodes, edges, err := kg.Stats()
	if err != nil {
		if logger != nil {
			logger.Warn("[MemoryHygiene] Failed to read KG stats", "error", err)
		}
		return
	}
	factTexts := make([]string, 0, len(facts))
	for _, fact := range facts {
		factTexts = append(factTexts, fact.Fact)
	}
	if issue, ok := buildCoreMemoryReviewIssue(factTexts); ok {
		recordOperationalIssue(RunConfig{PlannerDB: plannerDB, MessageSource: "maintenance", IsMaintenance: true}, issue, logger)
	}
	issue, ok := buildKnowledgeGraphSparseIssue(factTexts, nodes, edges)
	if !ok {
		return
	}
	recordOperationalIssue(RunConfig{PlannerDB: plannerDB, MessageSource: "maintenance", IsMaintenance: true}, issue, logger)
}

func buildKnowledgeGraphSparseIssue(coreFacts []string, nodes int, edges int) (planner.OperationalIssue, bool) {
	if len(coreFacts) == 0 || nodes >= 3 {
		return planner.OperationalIssue{}, false
	}
	return planner.OperationalIssue{
		Source:      "maintenance",
		Context:     "memory_hygiene",
		Title:       "Knowledge graph appears underpopulated",
		Detail:      fmt.Sprintf("Knowledge graph has core_facts=%d, nodes=%d, edges=%d. Check KG auto-extraction and core-memory sync.", len(coreFacts), nodes, edges),
		Severity:    "warning",
		Reference:   "knowledge_graph",
		Fingerprint: "memory_maintenance|kg_sparse|core_facts_present",
		OccurredAt:  time.Now(),
	}, true
}

func buildCoreMemoryReviewIssue(coreFacts []string) (planner.OperationalIssue, bool) {
	var lowSignal []string
	for _, fact := range coreFacts {
		trimmed := strings.TrimSpace(fact)
		if trimmed == "" {
			continue
		}
		lower := strings.ToLower(trimmed)
		if strings.Contains(lower, "test fact") || strings.Contains(lower, "test-fact") {
			lowSignal = append(lowSignal, trimmed)
		}
	}
	if len(lowSignal) == 0 {
		return planner.OperationalIssue{}, false
	}
	return planner.OperationalIssue{
		Source:      "maintenance",
		Context:     "memory_hygiene",
		Title:       "Core memory review needed",
		Detail:      "Core memory contains low-signal candidate facts: " + strings.Join(lowSignal, "; "),
		Severity:    "warning",
		Reference:   "core_memory",
		Fingerprint: "memory_maintenance|core_memory_review|low_signal",
		OccurredAt:  time.Now(),
	}, true
}
