package agent

import (
	"fmt"
	"log/slog"
	"strings"

	"aurago/internal/config"
	"aurago/internal/memory"
	"aurago/internal/prompts"

	"github.com/sashabaranov/go-openai"
)

type toolExecutionResult struct {
	Content string
	Failed  bool
}

func augmentToolFailureContent(tc ToolCall, content string, errorSummary string) string {
	if errorSummary == "" {
		errorSummary = extractErrorMessage(content)
	}
	hint := recoveryHintForToolFailure(tc, errorSummary)
	if hint == "" {
		return content
	}
	if strings.Contains(content, "[Suggested next step]") {
		return content
	}
	return content + "\n\n[Suggested next step]\n" + hint
}

func blockedToolOutputFromRequest(req *openai.ChatCompletionRequest) string {
	if req != nil && len(req.Messages) > 0 {
		last := req.Messages[len(req.Messages)-1]
		if last.Role == openai.ChatMessageRoleSystem && strings.Contains(last.Content, "CIRCUIT BREAKER") {
			return "[TOOL BLOCKED]\n" + last.Content
		}
	}
	return "[TOOL BLOCKED]\nCIRCUIT BREAKER: This tool call was blocked because it would repeat the same failing action."
}

func finalizeToolExecution(
	tc ToolCall,
	rawContent string,
	cfg *config.Config,
	shortTermMem *memory.SQLiteMemory,
	sessionID string,
	recoveryState *toolRecoveryState,
	req *openai.ChatCompletionRequest,
	logger *slog.Logger,
	scope AgentTelemetryScope,
	promptVersion string,
	execTimeMs int64,
) toolExecutionResult {
	limit := 0
	if cfg != nil {
		limit = cfg.Agent.ToolOutputLimit
	}

	policyResult := applyToolOutputPolicy(rawContent, limit, scope)
	resultContent := policyResult.Content
	toolFailed := policyResult.WasError
	if toolFailed {
		resultContent = augmentToolFailureContent(tc, resultContent, policyResult.ErrorSummary)
	}

	prompts.RecordToolUsage(tc.Action, tc.Operation, !toolFailed)
	prompts.RecordAdaptiveToolUsage(tc.Action, !toolFailed)
	RecordScopedToolResultForTool(scope, tc.Action, !toolFailed)

	if shortTermMem != nil {
		if err := shortTermMem.UpsertToolUsage(tc.Action, !toolFailed); err != nil {
			logToolMemoryWarning(logger, "Failed to persist tool usage stats", tc.Action, err)
		}
	}

	if toolFailed && shortTermMem != nil {
		errMsg := policyResult.ErrorSummary
		if errMsg != "" {
			if err := shortTermMem.RecordError(tc.Action, errMsg); err != nil {
				logToolMemoryWarning(logger, "Failed to persist tool error pattern", tc.Action, err)
			}
			if recoveryState != nil && recoveryState.shouldRecordFirstErrorInChain() &&
				cfg != nil && cfg.Tools.Journal.Enabled && cfg.Journal.AutoEntries {
				if _, err := shortTermMem.InsertJournalEntry(memory.JournalEntry{
					EntryType:     "error_learned",
					Title:         fmt.Sprintf("Error in %s", tc.Action),
					Content:       errMsg,
					Tags:          []string{tc.Action},
					Importance:    2,
					SessionID:     sessionID,
					AutoGenerated: true,
				}); err != nil {
					logToolMemoryWarning(logger, "Failed to persist error journal entry", tc.Action, err)
				}
			}
		}
	}

	if strings.Contains(resultContent, "[TOOL BLOCKED]") && shortTermMem != nil &&
		cfg != nil && cfg.Tools.Journal.Enabled && cfg.Journal.AutoEntries {
		reason := resultContent
		if len(reason) > 150 {
			reason = truncateUTF8ToLimit(reason, 153, "...")
		}
		title := fmt.Sprintf("Tool blocked: %s", tc.Action)
		if strings.Contains(resultContent, "Guardian") {
			title = fmt.Sprintf("Guardian blocked: %s", tc.Action)
		}
		if _, err := shortTermMem.InsertJournalEntry(memory.JournalEntry{
			EntryType:     "security_event",
			Title:         title,
			Content:       reason,
			Tags:          []string{tc.Action, "security"},
			Importance:    4,
			SessionID:     sessionID,
			AutoGenerated: true,
		}); err != nil {
			logToolMemoryWarning(logger, "Failed to persist security journal entry", tc.Action, err)
		}
	}

	if !toolFailed && recoveryState != nil && recoveryState.shouldRecordResolution() && shortTermMem != nil {
		resolutionErr := extractErrorMessage(recoveryState.LastToolError)
		if resolutionErr == "" {
			resolutionErr = recoveryState.LastToolError
		}
		if err := shortTermMem.RecordResolution(tc.Action, resolutionErr, "Succeeded with adjusted parameters"); err != nil {
			logToolMemoryWarning(logger, "Failed to persist tool resolution", tc.Action, err)
		}
	}

	if recoveryState != nil && req != nil {
		_ = recoveryState.updateToolErrorState(tc, resultContent, req, logger, scope, promptVersion, execTimeMs)
	}

	return toolExecutionResult{
		Content: resultContent,
		Failed:  toolFailed,
	}
}

func logToolMemoryWarning(logger *slog.Logger, message string, action string, err error) {
	if logger == nil || err == nil {
		return
	}
	logger.Warn(message, "action", action, "error", err)
}
