package tools

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"aurago/internal/config"
	"aurago/internal/security"
)

var outgoingWebhookHTTPClient = security.NewSSRFProtectedHTTPClient(30 * time.Second)

// ExecuteOutgoingWebhook resolves variables and sends an HTTP request
func ExecuteOutgoingWebhook(ctx context.Context, hook config.OutgoingWebhook, params map[string]interface{}) (string, int, error) {
	// Resolve URL parameters
	url := hook.URL
	for k, v := range params {
		url = strings.ReplaceAll(url, "{{"+k+"}}", fmt.Sprintf("%v", v))
	}

	// Prepare payload
	var reqBody []byte
	var contentType string

	switch hook.PayloadType {
	case "json", "":
		contentType = "application/json"
		if len(params) > 0 {
			b, err := json.Marshal(params)
			if err != nil {
				return "", 0, fmt.Errorf("failed to encode JSON payload: %w", err)
			}
			reqBody = b
		}
	case "form":
		// Currently simple form-urlencoded support isn't implemented deeply, falling back to basic mapping or ignoring
		contentType = "application/x-www-form-urlencoded"
		// Not fully implementing x-www-form-urlencoded serialization here, but JSON is the main focus
		reqBody = []byte("")
	case "custom":
		// User has provided a template
		contentType = "application/json" // default assumption unless overridden in headers
		bodyString := hook.BodyTemplate
		for k, v := range params {
			bodyString = strings.ReplaceAll(bodyString, "{{"+k+"}}", fmt.Sprintf("%v", v))
		}
		reqBody = []byte(bodyString)
	}

	req, err := http.NewRequestWithContext(ctx, hook.Method, url, bytes.NewBuffer(reqBody))
	if err != nil {
		return "", 0, fmt.Errorf("failed to create request: %w", err)
	}

	// Set default content type
	if len(reqBody) > 0 {
		req.Header.Set("Content-Type", contentType)
	}

	// Apply custom headers and resolve variables in them
	for k, v := range hook.Headers {
		resolvedV := v
		for pk, pv := range params {
			resolvedV = strings.ReplaceAll(resolvedV, "{{"+pk+"}}", fmt.Sprintf("%v", pv))
		}
		req.Header.Set(k, resolvedV)
	}

	resp, err := outgoingWebhookHTTPClient.Do(req)
	if err != nil {
		return "", 0, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	bodyBytes, err := readHTTPResponseBody(resp.Body, maxHTTPResponseSize)
	if err != nil {
		return "", resp.StatusCode, fmt.Errorf("failed to read response body: %w", err)
	}
	bodyStr := strings.TrimSpace(string(bodyBytes))

	return bodyStr, resp.StatusCode, nil
}

// ManageOutgoingWebhooks provides a way for the LLM to CRUD outgoing webhooks
func ManageOutgoingWebhooks(tcOperation, webhookID, name, description, method, url, payloadType, bodyTemplate string, headers map[string]string, rawParameters []interface{}, cfg *config.Config) string {
	if tcOperation == "list" {
		if len(cfg.Webhooks.Outgoing) == 0 {
			return `Tool Output: {"status":"success", "message":"No outgoing webhooks configured."}`
		}
		b, err := json.MarshalIndent(cfg.Webhooks.Outgoing, "", "  ")
		if err != nil {
			return fmt.Sprintf(`Tool Output: {"status":"error", "message":"Failed to list webhooks: %v"}`, err)
		}
		return fmt.Sprintf(`Tool Output: {"status":"success", "webhooks": %s}`, string(b))
	}

	// Helper to extract parameters from interface array generated by tool schema
	var parsedParams []config.WebhookParameter
	for _, p := range rawParameters {
		pmap, ok := p.(map[string]interface{})
		if !ok {
			continue
		}

		wp := config.WebhookParameter{}
		if n, ok := pmap["name"].(string); ok {
			wp.Name = n
		}
		if t, ok := pmap["type"].(string); ok {
			wp.Type = t
		}
		if d, ok := pmap["description"].(string); ok {
			wp.Description = d
		}
		if r, ok := pmap["required"].(bool); ok {
			wp.Required = r
		}
		parsedParams = append(parsedParams, wp)
	}

	// Prepare the webhook to edit/add
	newHook := config.OutgoingWebhook{
		ID:           webhookID,
		Name:         name,
		Description:  description,
		Method:       method,
		URL:          url,
		Headers:      headers,
		Parameters:   parsedParams,
		PayloadType:  payloadType,
		BodyTemplate: bodyTemplate,
	}
	if newHook.ID == "" {
		newHook.ID = fmt.Sprintf("hook_%d", time.Now().UnixNano())
	}

	outgoing := append([]config.OutgoingWebhook{}, cfg.Webhooks.Outgoing...)

	switch tcOperation {
	case "create":
		outgoing = append(outgoing, newHook)
	case "update":
		found := false
		for i, w := range outgoing {
			if w.ID == webhookID {
				// Retain un-provided fields? The agent generally provides full struct
				outgoing[i] = newHook
				found = true
				break
			}
		}
		if !found {
			return fmt.Sprintf(`Tool Output: {"status":"error", "message":"Webhook with ID %s not found"}`, webhookID)
		}
	case "delete":
		found := false
		for i, w := range outgoing {
			if w.ID == webhookID {
				outgoing = append(outgoing[:i], outgoing[i+1:]...)
				found = true
				break
			}
		}
		if !found {
			return fmt.Sprintf(`Tool Output: {"status":"error", "message":"Webhook with ID %s not found"}`, webhookID)
		}
	default:
		return fmt.Sprintf(`Tool Output: {"status":"error", "message":"Unknown operation: %s"}`, tcOperation)
	}

	cfg.Webhooks.Outgoing = outgoing
	if strings.TrimSpace(cfg.ConfigPath) == "" {
		return fmt.Sprintf(`Tool Output: {"status":"success", "message":"Webhook %sd in memory. Config path is unavailable, so the change could not be persisted.", "persisted": false}`, tcOperation)
	}
	if err := cfg.Save(cfg.ConfigPath); err != nil {
		return fmt.Sprintf(`Tool Output: {"status":"error", "message":"Webhook %sd in memory, but failed to persist config: %s"}`, tcOperation, err.Error())
	}

	return fmt.Sprintf(`Tool Output: {"status":"success", "message":"Webhook %sd successfully.", "persisted": true}`, tcOperation)
}
