package tools

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"time"

	"aurago/internal/config"
	"aurago/internal/security"
)

var outgoingWebhookHTTPClient = security.NewSSRFProtectedHTTPClient(30 * time.Second)

const outgoingWebhookMaskedValue = "••••••••"

// ExecuteOutgoingWebhook resolves variables and sends an HTTP request
func ExecuteOutgoingWebhook(ctx context.Context, hook config.OutgoingWebhook, params map[string]interface{}) (string, int, error) {
	// Resolve URL parameters — values are URL-encoded to prevent injection of
	// additional query parameters or path components.
	urlStr := hook.URL
	for k, v := range params {
		urlStr = strings.ReplaceAll(urlStr, "{"+"{"+k+"}}", url.QueryEscape(fmt.Sprintf("%v", v)))
	}

	// Prepare payload
	var reqBody []byte
	var contentType string

	switch hook.PayloadType {
	case "json", "":
		contentType = "application/json"
		if len(params) > 0 {
			b, err := json.Marshal(params)
			if err != nil {
				return "", 0, fmt.Errorf("failed to encode JSON payload: %w", err)
			}
			reqBody = b
		}
	case "form":
		contentType = "application/x-www-form-urlencoded"
		values := url.Values{}
		for key, value := range params {
			values.Set(key, fmt.Sprintf("%v", value))
		}
		reqBody = []byte(values.Encode())
	case "custom":
		// User has provided a template
		contentType = "application/json" // default assumption unless overridden in headers
		bodyString := hook.BodyTemplate
		for k, v := range params {
			var safeVal string
			if sv, ok := v.(string); ok {
				b, _ := json.Marshal(sv)
				safeVal = string(b[1 : len(b)-1]) // escape JSON string content, strip outer quotes
			} else {
				b, _ := json.Marshal(v)
				safeVal = string(b)
			}
			bodyString = strings.ReplaceAll(bodyString, "{{"+k+"}}", safeVal)
		}
		reqBody = []byte(bodyString)
	}

	req, err := http.NewRequestWithContext(ctx, hook.Method, urlStr, bytes.NewBuffer(reqBody))
	if err != nil {
		return "", 0, fmt.Errorf("failed to create request: %w", err)
	}

	// Set default content type
	if len(reqBody) > 0 {
		req.Header.Set("Content-Type", contentType)
	}

	// Apply custom headers and resolve variables in them
	for k, v := range hook.Headers {
		resolvedV := v
		for pk, pv := range params {
			resolvedV = strings.ReplaceAll(resolvedV, "{{"+pk+"}}", fmt.Sprintf("%v", pv))
		}
		req.Header.Set(k, resolvedV)
	}

	resp, err := outgoingWebhookHTTPClient.Do(req)
	if err != nil {
		return "", 0, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	bodyBytes, err := readHTTPResponseBody(resp.Body, maxHTTPResponseSize)
	if err != nil {
		return "", resp.StatusCode, fmt.Errorf("failed to read response body: %w", err)
	}
	bodyStr := strings.TrimSpace(string(bodyBytes))

	return bodyStr, resp.StatusCode, nil
}

// ManageOutgoingWebhooks provides a way for the LLM to CRUD outgoing webhooks
func ManageOutgoingWebhooks(tcOperation, webhookID, name, description, method, url, payloadType, bodyTemplate string, headers map[string]string, rawParameters []interface{}, cfg *config.Config) string {
	if tcOperation == "list" {
		if len(cfg.Webhooks.Outgoing) == 0 {
			return `Tool Output: {"status":"success", "message":"No outgoing webhooks configured."}`
		}
		b, err := json.MarshalIndent(maskOutgoingWebhooksForTool(cfg.Webhooks.Outgoing), "", "  ")
		if err != nil {
			return fmt.Sprintf(`Tool Output: {"status":"error", "message":"Failed to list webhooks: %v"}`, err)
		}
		return fmt.Sprintf(`Tool Output: {"status":"success", "webhooks": %s}`, string(b))
	}
	if cfg.Webhooks.ReadOnly {
		return `Tool Output: {"status":"error","message":"Webhooks tool is set to Read-Only mode. Cannot modify."}`
	}

	// Helper to extract parameters from interface array generated by tool schema
	var parsedParams []config.WebhookParameter
	for _, p := range rawParameters {
		pmap, ok := p.(map[string]interface{})
		if !ok {
			continue
		}

		wp := config.WebhookParameter{}
		if n, ok := pmap["name"].(string); ok {
			wp.Name = n
		}
		if t, ok := pmap["type"].(string); ok {
			wp.Type = t
		}
		if d, ok := pmap["description"].(string); ok {
			wp.Description = d
		}
		if r, ok := pmap["required"].(bool); ok {
			wp.Required = r
		}
		parsedParams = append(parsedParams, wp)
	}

	// Prepare the webhook to edit/add
	newHook := config.OutgoingWebhook{
		ID:           webhookID,
		Name:         name,
		Description:  description,
		Method:       method,
		URL:          url,
		Headers:      headers,
		Parameters:   parsedParams,
		PayloadType:  payloadType,
		BodyTemplate: bodyTemplate,
	}
	if newHook.ID == "" {
		newHook.ID = fmt.Sprintf("hook_%d", time.Now().UnixNano())
	}

	outgoing := append([]config.OutgoingWebhook{}, cfg.Webhooks.Outgoing...)

	switch tcOperation {
	case "create":
		outgoing = append(outgoing, newHook)
	case "update":
		found := false
		for i, w := range outgoing {
			if w.ID == webhookID {
				// Retain un-provided fields? The agent generally provides full struct
				outgoing[i] = newHook
				found = true
				break
			}
		}
		if !found {
			return fmt.Sprintf(`Tool Output: {"status":"error", "message":"Webhook with ID %s not found"}`, webhookID)
		}
	case "delete":
		found := false
		for i, w := range outgoing {
			if w.ID == webhookID {
				outgoing = append(outgoing[:i], outgoing[i+1:]...)
				found = true
				break
			}
		}
		if !found {
			return fmt.Sprintf(`Tool Output: {"status":"error", "message":"Webhook with ID %s not found"}`, webhookID)
		}
	default:
		return fmt.Sprintf(`Tool Output: {"status":"error", "message":"Unknown operation: %s"}`, tcOperation)
	}

	cfg.Webhooks.Outgoing = outgoing
	if strings.TrimSpace(cfg.ConfigPath) == "" {
		return fmt.Sprintf(`Tool Output: {"status":"success", "message":"Webhook %sd in memory. Config path is unavailable, so the change could not be persisted.", "persisted": false}`, tcOperation)
	}
	if err := cfg.Save(cfg.ConfigPath); err != nil {
		return fmt.Sprintf(`Tool Output: {"status":"error", "message":"Webhook %sd in memory, but failed to persist config: %s"}`, tcOperation, err.Error())
	}

	return fmt.Sprintf(`Tool Output: {"status":"success", "message":"Webhook %sd successfully.", "persisted": true}`, tcOperation)
}

func maskOutgoingWebhooksForTool(outgoing []config.OutgoingWebhook) []config.OutgoingWebhook {
	masked := make([]config.OutgoingWebhook, len(outgoing))
	for i, hook := range outgoing {
		masked[i] = hook
		if hook.Headers != nil {
			masked[i].Headers = make(map[string]string, len(hook.Headers))
			for key, value := range hook.Headers {
				if value != "" && isSensitiveOutgoingWebhookHeader(key) {
					masked[i].Headers[key] = outgoingWebhookMaskedValue
					continue
				}
				masked[i].Headers[key] = value
			}
		}
		if strings.TrimSpace(hook.BodyTemplate) != "" {
			masked[i].BodyTemplate = outgoingWebhookMaskedValue
		}
	}
	return masked
}

func isSensitiveOutgoingWebhookHeader(name string) bool {
	lower := strings.ToLower(strings.TrimSpace(name))
	if lower == "" {
		return false
	}
	if lower == "authorization" || lower == "proxy-authorization" || lower == "cookie" || lower == "set-cookie" {
		return true
	}
	return strings.Contains(lower, "token") || strings.Contains(lower, "secret") || strings.Contains(lower, "api-key") || strings.Contains(lower, "apikey") || strings.Contains(lower, "password") || strings.Contains(lower, "credential")
}
