#!/usr/bin/env python3
"""Batch 12: More backend messages and config labels."""
import json, os
from pathlib import Path
from collections import defaultdict

LANG_DIR = Path("ui/lang")
LANGS = ["cs","da","de","el","es","fr","hi","it","ja","nl","no","pl","pt","sv","zh"]

T = {
    "Workspace path detected successfully.": {"cs":"Cesta pracovního prostoru úspěšně detekována.","da":"Arbejdsområde-sti registreret.","de":"Workspace-Pfad erfolgreich erkannt.","el":"Η διαδρομή χώρου εργασίας εντοπίστηκε επιτυχώς.","es":"Ruta del espacio de trabajo detectada correctamente.","fr":"Chemin de l'espace de travail détecté avec succès.","hi":"कार्यक्षेत्र पथ सफलतापूर्वक पहचाना गया।","it":"Percorso workspace rilevato con successo.","ja":"ワークスペースパスを正常に検出しました。","nl":"Werkruimtepad succesvol gedetecteerd.","no":"Arbeidsområde-sti oppdaget.","pl":"Ścieżka obszaru roboczego wykryta pomyślnie.","pt":"Caminho do espaço de trabalho detectado com sucesso.","sv":"Arbetsytesökväg upptäckt.","zh":"工作区路径检测成功。"},
    "Both 'concept' and 'content' are required": {"cs":"'concept' i 'content' jsou vyžadovány","da":"Både 'concept' og 'content' er påkrævede","de":"Sowohl 'concept' als auch 'content' sind erforderlich","el":"Τόσο το 'concept' όσο και το 'content' είναι απαραίτητα","es":"Tanto 'concept' como 'content' son obligatorios","fr":"'concept' et 'content' sont tous deux requis","hi":"'concept' और 'content' दोनों आवश्यक हैं","it":"Sia 'concept' che 'content' sono obbligatori","ja":"'concept'と'content'の両方が必要です","nl":"Zowel 'concept' als 'content' zijn vereist","no":"Både 'concept' og 'content' er påkrevd","pl":"Zarówno 'concept', jak i 'content' są wymagane","pt":"Tanto 'concept' quanto 'content' são obrigatórios","sv":"Både 'concept' och 'content' krävs","zh":"'concept' 和 'content' 都是必需的"},
    "Invalid feedback type. Use: positive, negative, angry, laughing, crying, amazed": {"cs":"Neplatný typ zpětné vazby. Použijte: positive, negative, angry, laughing, crying, amazed","da":"Ugyldig feedback-type. Brug: positive, negative, angry, laughing, crying, amazed","de":"Ungültiger Feedback-Typ. Verwenden Sie: positive, negative, angry, laughing, crying, amazed","el":"Μη έγκυρος τύπος ανατροφοδότησης. Χρησιμοποιήστε: positive, negative, angry, laughing, crying, amazed","es":"Tipo de comentario no válido. Use: positive, negative, angry, laughing, crying, amazed","fr":"Type de retour invalide. Utilisez : positive, negative, angry, laughing, crying, amazed","hi":"अमान्य प्रतिक्रिया प्रकार। उपयोग करें: positive, negative, angry, laughing, crying, amazed","it":"Tipo di feedback non valido. Usa: positive, negative, angry, laughing, crying, amazed","ja":"無効なフィードバックタイプ。使用可能: positive, negative, angry, laughing, crying, amazed","nl":"Ongeldig feedbacktype. Gebruik: positive, negative, angry, laughing, crying, amazed","no":"Ugyldig tilbakemeldingstype. Bruk: positive, negative, angry, laughing, crying, amazed","pl":"Nieprawidłowy typ opinii. Użyj: positive, negative, angry, laughing, crying, amazed","pt":"Tipo de feedback inválido. Use: positive, negative, angry, laughing, crying, amazed","sv":"Ogiltig feedbacktyp. Använd: positive, negative, angry, laughing, crying, amazed","zh":"无效的反馈类型。请使用：positive, negative, angry, laughing, crying, amazed"},
    "Invalid personality name: use letters, digits, - and _ only (max 64 chars)": {"cs":"Neplatný název osobnosti: použijte pouze písmena, číslice, - a _ (max 64 znaků)","da":"Ugyldigt personlighedsnavn: brug kun bogstaver, tal, - og _ (max 64 tegn)","de":"Ungültiger Persönlichkeitsname: nur Buchstaben, Ziffern, - und _ (max. 64 Zeichen)","el":"Μη έγκυρο όνομα προσωπικότητας: χρησιμοποιήστε μόνο γράμματα, ψηφία, - και _ (μέχρι 64 χαρακτήρες)","es":"Nombre de personalidad no válido: use solo letras, dígitos, - y _ (máx. 64 caracteres)","fr":"Nom de personnalité invalide : utilisez uniquement lettres, chiffres, - et _ (max 64 caractères)","hi":"अमान्य व्यक्तित्व नाम: केवल अक्षर, अंक, - और _ का उपयोग करें (अधिकतम 64 अक्षर)","it":"Nome personalità non valido: usa solo lettere, cifre, - e _ (max 64 caratteri)","ja":"無効なパーソナリティ名：文字、数字、-と_のみ使用可能（最大64文字）","nl":"Ongeldige persoonlijkheidsnaam: gebruik alleen letters, cijfers, - en _ (max 64 tekens)","no":"Ugyldig personlighetsnavn: bruk kun bokstaver, siffer, - og _ (maks 64 tegn)","pl":"Nieprawidłowa nazwa osobowości: użyj tylko liter, cyfr, - i _ (maks. 64 znaki)","pt":"Nome de personalidade inválido: use apenas letras, dígitos, - e _ (máx. 64 caracteres)","sv":"Ogiltigt personlighetsnamn: använd endast bokstäver, siffror, - och _ (max 64 tecken)","zh":"无效的人格名称：仅使用字母、数字、- 和 _（最多 64 个字符）"},
    "Invalid setup configuration": {"cs":"Neplatná konfigurace nastavení","da":"Ugyldig opsætningskonfiguration","de":"Ungültige Setup-Konfiguration","el":"Μη έγκυρη διαμόρφωση εγκατάστασης","es":"Configuración de instalación no válida","fr":"Configuration d'installation invalide","hi":"अमान्य सेटअप कॉन्फ़िगरेशन","it":"Configurazione setup non valida","ja":"無効なセットアップ設定","nl":"Ongeldige installatieconfiguratie","no":"Ugyldig oppsettkonfigurasjon","pl":"Nieprawidłowa konfiguracja instalacji","pt":"Configuração de instalação inválida","sv":"Ogiltig installationskonfiguration","zh":"无效的安装配置"},
    "Invalid upload destination": {"cs":"Neplatný cíl nahrávání","da":"Ugyldig upload-destination","de":"Ungültiges Upload-Ziel","el":"Μη έγκυρος προορισμός μεταφόρτωσης","es":"Destino de carga no válido","fr":"Destination de téléversement invalide","hi":"अमान्य अपलोड गंतव्य","it":"Destinazione upload non valida","ja":"無効なアップロード先","nl":"Ongeldig uploadbestemming","no":"Ugyldig opplastingsmål","pl":"Nieprawidłowy cel przesyłania","pt":"Destino de envio inválido","sv":"Ogiltigt uppladdningsmål","zh":"无效的上传目标"},
    "Invalid upload request": {"cs":"Neplatný požadavek na nahrání","da":"Ugyldig upload-anmodning","de":"Ungültige Upload-Anfrage","el":"Μη έγκυρο αίτημα μεταφόρτωσης","es":"Solicitud de carga no válida","fr":"Requête de téléversement invalide","hi":"अमान्य अपलोड अनुरोध","it":"Richiesta upload non valida","ja":"無効なアップロードリクエスト","nl":"Ongeldig uploadverzoek","no":"Ugyldig opplastingsforespørsel","pl":"Nieprawidłowe żądanie przesyłania","pt":"Solicitação de envio inválida","sv":"Ogiltig uppladdningsbegäran","zh":"无效的上传请求"},
    "Personality ID is required": {"cs":"ID osobnosti je vyžadováno","da":"Personligheds-ID er påkrævet","de":"Persönlichkeits-ID ist erforderlich","el":"Το ID προσωπικότητας είναι υποχρεωτικό","es":"El ID de personalidad es obligatorio","fr":"L'ID de personnalité est requis","hi":"व्यक्तित्व ID आवश्यक है","it":"L'ID personalità è obbligatorio","ja":"パーソナリティIDは必須です","nl":"Persoonlijkheids-ID is vereist","no":"Personlighets-ID er påkrevd","pl":"ID osobowości jest wymagane","pt":"O ID da personalidade é obrigatório","sv":"Personlighets-ID krävs","zh":"人格 ID 为必填项"},
    "Missing ?key= parameter": {"cs":"Chybí parametr ?key=","da":"Manglende ?key= parameter","de":"Parameter ?key= fehlt","el":"Λείπει η παράμετρος ?key=","es":"Falta el parámetro ?key=","fr":"Paramètre ?key= manquant","hi":"?key= पैरामीटर अनुपस्थित","it":"Parametro ?key= mancante","ja":"?key= パラメータが不足","nl":"Parameter ?key= ontbreekt","no":"Mangler ?key= parameter","pl":"Brak parametru ?key=","pt":"Parâmetro ?key= ausente","sv":"Parameter ?key= saknas","zh":"缺少 ?key= 参数"},
    "Missing contact ID": {"cs":"Chybí ID kontaktu","da":"Manglende kontakt-ID","de":"Kontakt-ID fehlt","el":"Λείπει το ID επαφής","es":"Falta el ID de contacto","fr":"ID de contact manquant","hi":"संपर्क ID अनुपस्थित","it":"ID contatto mancante","ja":"連絡先IDが不足","nl":"Contact-ID ontbreekt","no":"Mangler kontakt-ID","pl":"Brak ID kontaktu","pt":"ID de contato ausente","sv":"Kontakt-ID saknas","zh":"缺少联系人 ID"},
    "Missing file field": {"cs":"Chybí pole souboru","da":"Manglende filfelt","de":"Dateifeld fehlt","el":"Λείπει το πεδίο αρχείου","es":"Falta el campo de archivo","fr":"Champ de fichier manquant","hi":"फ़ाइल फ़ील्ड अनुपस्थित","it":"Campo file mancante","ja":"ファイルフィールドが不足","nl":"Bestandsveld ontbreekt","no":"Mangler filfelt","pl":"Brak pola pliku","pt":"Campo de arquivo ausente","sv":"Filsök saknas","zh":"缺少文件字段"},
    "Missing filename": {"cs":"Chybí název souboru","da":"Manglende filnavn","de":"Dateiname fehlt","el":"Λείπει το όνομα αρχείου","es":"Falta el nombre del archivo","fr":"Nom de fichier manquant","hi":"फ़ाइलनाम अनुपस्थित","it":"Nome file mancante","ja":"ファイル名が不足","nl":"Bestandsnaam ontbreekt","no":"Mangler filnavn","pl":"Brak nazwy pliku","pt":"Nome do arquivo ausente","sv":"Filnamn saknas","zh":"缺少文件名"},
    "Missing {0} ID": {"cs":"Chybí {0} ID","da":"Manglende {0} ID","de":"{0}-ID fehlt","el":"Λείπει το {0} ID","es":"Falta el ID de {0}","fr":"ID {0} manquant","hi":"{0} ID अनुपस्थित","it":"ID {0} mancante","ja":"{0} IDが不足","nl":"{0} ID ontbreekt","no":"Mangler {0} ID","pl":"Brak ID {0}","pt":"ID {0} ausente","sv":"{0} ID saknas","zh":"缺少 {0} ID"},
    "This file type is not allowed for the Knowledge Center": {"cs":"Tento typ souboru není pro Centrum znalostí povolen","da":"Denne filtype er ikke tilladt i Videnscenteret","de":"Dieser Dateityp ist für das Wissenszentrum nicht erlaubt","el":"Αυτός ο τύπος αρχείου δεν επιτρέπεται στο Κέντρο Γνώσεων","es":"Este tipo de archivo no está permitido en el Centro de conocimiento","fr":"Ce type de fichier n'est pas autorisé pour le Centre de connaissances","hi":"ज्ञान केंद्र के लिए यह फ़ाइल प्रकार अनुमत नहीं है","it":"Questo tipo di file non è consentito per il Centro conoscenza","ja":"ナレッジセンターではこのファイルタイプは許可されていません","nl":"Dit bestandstype is niet toegestaan voor het Kenniscentrum","no":"Denne filtypen er ikke tillatt i Kunnskapssenteret","pl":"Ten typ pliku nie jest dozwolony w Centrum wiedzy","pt":"Este tipo de arquivo não é permitido no Centro de conhecimento","sv":"Denna filtyp är inte tillåten för Kunskapscentret","zh":"知识中心不允许此文件类型"},
    "File \"{{name}}\" is too large (max {{size}})": {"cs":"Soubor \"{{name}}\" je příliš velký (max {{size}})","da":"Filen \"{{name}}\" er for stor (max {{size}})","de":"Datei \"{{name}}\" ist zu groß (max. {{size}})","el":"Το αρχείο \"{{name}}\" είναι πολύ μεγάλο (μέγ. {{size}})","es":"El archivo \"{{name}}\" es demasiado grande (máx. {{size}})","fr":"Le fichier \"{{name}}\" est trop volumineux (max {{size}})","hi":"फ़ाइल \"{{name}}\" बहुत बड़ी है (अधिकतम {{size}})","it":"Il file \"{{name}}\" è troppo grande (max {{size}})","ja":"ファイル \"{{name}}\" は大きすぎます（最大 {{size}}）","nl":"Bestand \"{{name}}\" is te groot (max {{size}})","no":"Filen \"{{name}}\" er for stor (maks {{size}})","pl":"Plik \"{{name}}\" jest za duży (maks. {{size}})","pt":"O arquivo \"{{name}}\" é muito grande (máx. {{size}})","sv":"Filen \"{{name}}\" är för stor (max {{size}})","zh":"文件 \"{{name}}\" 过大（最大 {{size}}）"},
    "File type \"{{type}}\" not allowed": {"cs":"Typ souboru \"{{type}}\" není povolen","da":"Filtype \"{{type}}\" ikke tilladt","de":"Dateityp \"{{type}}\" nicht erlaubt","el":"Ο τύπος αρχείου \"{{type}}\" δεν επιτρέπεται","es":"Tipo de archivo \"{{type}}\" no permitido","fr":"Type de fichier \"{{type}}\" non autorisé","hi":"फ़ाइल प्रकार \"{{type}}\" अनुमत नहीं","it":"Tipo di file \"{{type}}\" non consentito","ja":"ファイルタイプ \"{{type}}\" は許可されていません","nl":"Bestandstype \"{{type}}\" niet toegestaan","no":"Filtype \"{{type}}\" ikke tillatt","pl":"Typ pliku \"{{type}}\" niedozwolony","pt":"Tipo de arquivo \"{{type}}\" não permitido","sv":"Filtyp \"{{type}}\" inte tillåten","zh":"文件类型 \"{{type}}\" 不允许"},
    "Uploading {{count}} file(s)": {"cs":"Nahrávám {{count}} soubor(y)","da":"Uploader {{count}} fil(er)","de":"Lade {{count}} Datei(en) hoch","el":"Μεταφόρτωση {{count}} αρχείου(ων)","es":"Subiendo {{count}} archivo(s)","fr":"Téléversement de {{count}} fichier(s)","hi":"{{count}} फ़ाइलें अपलोड हो रही हैं","it":"Caricamento di {{count}} file","ja":"{{count}} ファイルをアップロード中","nl":"{{count}} bestand(en) uploaden","no":"Laster opp {{count}} fil(er)","pl":"Przesyłanie {{count}} pliku(ów)","pt":"Enviando {{count}} arquivo(s)","sv":"Laddar upp {{count}} fil(er)","zh":"正在上传 {{count}} 个文件"},
    "What should the skill do?": {"cs":"Co by měla dovednost dělat?","da":"Hvad skal færdigheden gøre?","de":"Was soll der Skill tun?","el":"Τι πρέπει να κάνει η δεξιότητα;","es":"¿Qué debería hacer la habilidad?","fr":"Que doit faire la compétence ?","hi":"कौशल क्या करना चाहिए?","it":"Cosa dovrebbe fare la skill?","ja":"スキルは何をすべきですか？","nl":"Wat moet de vaardigheid doen?","no":"Hva skal ferdigheten gjøre?","pl":"Co powinno robić umiejętność?","pt":"O que a habilidade deve fazer?","sv":"Vad ska färdigheten göra?","zh":"技能应该做什么？"},
    "Please describe the skill you want.": {"cs":"Popište prosím dovednost, kterou chcete.","da":"Beskriv venligst den færdighed du ønsker.","de":"Bitte beschreiben Sie den gewünschten Skill.","el":"Περιγράψτε τη δεξιότητα που θέλετε.","es":"Describa la habilidad que desea.","fr":"Décrivez la compétence que vous souhaitez.","hi":"कृपया वह कौशल वर्णन करें जो आप चाहते हैं।","it":"Descrivi la skill che desideri.","ja":"希望するスキルを説明してください。","nl":"Beschrijf de gewenste vaardigheid.","no":"Beskriv ferdigheten du ønsker.","pl":"Opisz umiejętność, której potrzebujesz.","pt":"Descreva a habilidade que deseja.","sv":"Beskriv färdigheten du vill ha.","zh":"请描述您想要的技能。"},
    "Choose an exported .aurago-skill.json bundle.": {"cs":"Vyberte exportovaný balíček .aurago-skill.json.","da":"Vælg en eksporteret .aurago-skill.json-pakke.","de":"Wählen Sie ein exportiertes .aurago-skill.json-Bundle.","el":"Επιλέξτε ένα εξαγμένο πακέτο .aurago-skill.json.","es":"Elija un paquete .aurago-skill.json exportado.","fr":"Choisissez un bundle .aurago-skill.json exporté.","hi":"एक निर्यात किया गया .aurago-skill.json बंडल चुनें।","it":"Scegli un bundle .aurago-skill.json esportato.","ja":"エクスポートされた.aurago-skill.jsonバンドルを選択。","nl":"Kies een geëxporteerd .aurago-skill.json-bestand.","no":"Velg en eksportert .aurago-skill.json-pakke.","pl":"Wybierz wyeksportowany pakiet .aurago-skill.json.","pt":"Escolha um pacote .aurago-skill.json exportado.","sv":"Välj ett exporterat .aurago-skill.json-paket.","zh":"选择一个导出的 .aurago-skill.json 包。"},
    "Import Skill Bundle": {"cs":"Importovat balíček dovedností","da":"Importér færdighedspakke","de":"Skill-Bundle importieren","el":"Εισαγωγή πακέτου δεξιοτήτων","es":"Importar paquete de habilidades","fr":"Importer un bundle de compétences","hi":"कौशल बंडल आयात करें","it":"Importa bundle skill","ja":"スキルバンドルをインポート","nl":"Vaardigheidspakket importeren","no":"Importer ferdighetspakke","pl":"Importuj pakiet umiejętności","pt":"Importar pacote de habilidades","sv":"Importera färdighetspaket","zh":"导入技能包"},
    "Open client link": {"cs":"Otevřít odkaz klienta","da":"Åbn klientlink","de":"Client-Link öffnen","el":"Άνοιγμα συνδέσμου πελάτη","es":"Abrir enlace del cliente","fr":"Ouvrir le lien client","hi":"क्लाइंट लिंक खोलें","it":"Apri link client","ja":"クライアントリンクを開く","nl":"Clientlink openen","no":"Åpne klientlenke","pl":"Otwórz link klienta","pt":"Abrir link do cliente","sv":"Öppna klientlänk","zh":"打开客户端链接"},
}

stats = defaultdict(int)
for d in sorted(str(p) for p in LANG_DIR.rglob("en.json")):
    direc = Path(d).parent
    en = json.loads(Path(d).read_text(encoding="utf-8-sig"))
    for lang in LANGS:
        lf = direc / f"{lang}.json"
        if not lf.exists():
            continue
        ld = json.loads(lf.read_text(encoding="utf-8-sig"))
        mod = False
        for k, ev in en.items():
            if k not in ld:
                continue
            if str(ld[k]).strip().lower() != str(ev).strip().lower():
                continue
            evs = ev.strip()
            if evs in T:
                t = T[evs].get(lang)
                if t:
                    ld[k] = t
                    mod = True
                    stats[lang] += 1
        if mod:
            lf.write_text(json.dumps(ld, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print("Fixed:", dict(stats))
print("Total:", sum(stats.values()))
