#!/usr/bin/env python3
"""Batch 8: Config sections, backend messages, and more UI terms."""
import json, os
from pathlib import Path
from collections import defaultdict

LANG_DIR = Path("ui/lang")
LANGS = ["cs","da","de","el","es","fr","hi","it","ja","nl","no","pl","pt","sv","zh"]

T = {
    "Embedding change detected": {"cs":"Změna embeddingů detekována","da":"Embedding-ændring registreret","de":"Embedding-Änderung erkannt","el":"Εντοπίστηκε αλλαγή ενσωμάτωσης","es":"Cambio de embeddings detectado","fr":"Changement d'embeddings détecté","hi":"एम्बेडिंग परिवर्तन पाया गया","it":"Cambiamento embedding rilevato","ja":"埋め込み変更を検出","nl":"Embedding-wijziging gedetecteerd","no":"Embedding-endring oppdaget","pl":"Wykryto zmianę osadzeń","pt":"Mudança de embeddings detectada","sv":"Embedding-ändring upptäckt","zh":"检测到嵌入变化"},
    "Embedding change aborted. Nothing was saved.": {"cs":"Změna embeddingů zrušena. Nic nebylo uloženo.","da":"Embedding-ændring afbrudt. Intet blev gemt.","de":"Embedding-Änderung abgebrochen. Nichts wurde gespeichert.","el":"Η αλλαγή ενσωμάτωσης ακυρώθηκε. Τίποτα δεν αποθηκεύτηκε.","es":"Cambio de embeddings cancelado. No se guardó nada.","fr":"Changement d'embeddings annulé. Rien n'a été sauvegardé.","hi":"एम्बेडिंग परिवर्तन रद्द। कुछ भी सहेजा नहीं गया।","it":"Cambiamento embedding annullato. Nulla è stato salvato.","ja":"埋め込み変更は中止されました。何も保存されていません。","nl":"Embedding-wijziging afgebroken. Niets opgeslagen.","no":"Embedding-endring avbrutt. Ingenting ble lagret.","pl":"Zmiana osadzeń anulowana. Nic nie zostało zapisane.","pt":"Mudança de embeddings cancelada. Nada foi salvo.","sv":"Embedding-ändring avbruten. Inget sparades.","zh":"嵌入更改已中止。未保存任何内容。"},
    "Embedding change saved. The old embeddings are still present until you confirm deletion and restart.": {"cs":"Změna embeddingů uložena. Staré embeddingy zůstávají, dokud nepotvrdíte smazání a restartujete.","da":"Embedding-ændring gemt. De gamle embeddings er stadig til stede, indtil du bekræfter sletning og genstarter.","de":"Embedding-Änderung gespeichert. Die alten Embeddings bleiben bestehen, bis Sie die Löschung bestätigen und neu starten.","el":"Η αλλαγή ενσωμάτωσης αποθηκεύτηκε. Τα παλιά embeddings παραμένουν μέχρι να επιβεβαιώσετε τη διαγραφή και κάνετε επανεκκίνηση.","es":"Cambio de embeddings guardado. Los embeddings antiguos siguen presentes hasta que confirme la eliminación y reinicie.","fr":"Changement d'embeddings sauvegardé. Les anciens embeddings sont toujours présents jusqu'à confirmation de suppression et redémarrage.","hi":"एम्बेडिंग परिवर्तन सहेजा गया। पुराने एम्बेडिंग तब तक मौजूद हैं जब तक आप हटाने की पुष्टि नहीं करते और पुनरारंभ नहीं करते।","it":"Cambiamento embedding salvato. I vecchi embeddings sono ancora presenti finché non confermi l'eliminazione e riavvii.","ja":"埋め込み変更を保存しました。削除を確認して再起動するまで、古い埋め込みは残ります。","nl":"Embedding-wijziging opgeslagen. De oude embeddings blijven aanwezig tot u verwijdering bevestigt en herstart.","no":"Embedding-endring lagret. De gamle embeddingene er fortsatt til stede inntil du bekrefter sletting og starter på nytt.","pl":"Zmiana osadzeń zapisana. Stare osadzenia pozostają, dopóki nie potwierdzisz usunięcia i nie uruchomisz ponownie.","pt":"Mudança de embeddings salva. Os embeddings antigos ainda estão presentes até você confirmar a exclusão e reiniciar.","sv":"Embedding-ändring sparad. De gamla embeddingarna finns kvar tills du bekräftar borttagning och startar om.","zh":"嵌入更改已保存。旧嵌入在您确认删除并重启之前仍然存在。"},
    "Delete old embeddings": {"cs":"Smazat staré embeddingy","da":"Slet gamle embeddings","de":"Alte Embeddings löschen","el":"Διαγραφή παλιών embeddings","es":"Eliminar embeddings antiguos","fr":"Supprimer les anciens embeddings","hi":"पुराने एम्बेडिंग हटाएं","it":"Elimina vecchi embeddings","ja":"古い埋め込みを削除","nl":"Oude embeddings verwijderen","no":"Slett gamle embeddinger","pl":"Usuń stare osadzenia","pt":"Excluir embeddings antigos","sv":"Ta bort gamla embeddingar","zh":"删除旧嵌入"},
    "Old embeddings scheduled for deletion. AuraGo is restarting now…": {"cs":"Staré embeddingy naplánovány ke smazání. AuraGo se nyní restartuje…","da":"Gamle embeddings planlagt til sletning. AuraGo genstarter nu…","de":"Alte Embeddings zur Löschung eingeplant. AuraGo wird jetzt neu gestartet…","el":"Τα παλιά embeddings προγραμματίστηκαν για διαγραφή. Το AuraGo επανεκκινείται τώρα…","es":"Embeddings antiguos programados para eliminación. AuraGo se está reiniciando…","fr":"Anciens embeddings programmés pour suppression. AuraGo redémarre maintenant…","hi":"पुराने एम्बेडिंग हटाने के लिए निर्धारित। AuraGo अब पुनरारंभ हो रहा है…","it":"Vecchi embeddings programmati per l'eliminazione. AuraGo si sta riavviando…","ja":"古い埋め込みの削除がスケジュールされました。AuraGoは再起動中です…","nl":"Oude embeddings ingepland voor verwijdering. AuraGo herstart nu…","no":"Gamle embeddinger planlagt for sletting. AuraGo starter på nytt nå…","pl":"Stare osadzenia zaplanowane do usunięcia. AuraGo uruchamia się ponownie…","pt":"Embeddings antigos agendados para exclusão. AuraGo está reiniciando agora…","sv":"Gamla embeddingar schemalagda för borttagning. AuraGo startar om nu…","zh":"旧嵌入已计划删除。AuraGo 正在重启…"},
    "Setup complete! Configuration saved and applied.": {"cs":"Nastavení dokončeno! Konfigurace uložena a aplikována.","da":"Opsætning fuldført! Konfiguration gemt og anvendt.","de":"Einrichtung abgeschlossen! Konfiguration gespeichert und angewendet.","el":"Η ρύθμιση ολοκληρώθηκε! Οι ρυθμίσεις αποθηκεύτηκαν και εφαρμόστηκαν.","es":"¡Configuración completada! Configuración guardada y aplicada.","fr":"Configuration terminée ! Paramètres sauvegardés et appliqués.","hi":"सेटअप पूरा! कॉन्फ़िगरेशन सहेजा और लागू किया गया।","it":"Configurazione completata! Impostazioni salvate e applicate.","ja":"セットアップ完了！設定が保存・適用されました。","nl":"Installatie voltooid! Configuratie opgeslagen en toegepast.","no":"Oppsett fullført! Konfigurasjon lagret og brukt.","pl":"Konfiguracja zakończona! Ustawienia zapisane i zastosowane.","pt":"Configuração concluída! Configurações salvas e aplicadas.","sv":"Installation klar! Konfiguration sparad och tillämpad.","zh":"设置完成！配置已保存并应用。"},
    "Skill created": {"cs":"Dovednost vytvořena","da":"Færdighed oprettet","de":"Skill erstellt","el":"Η δεξιότητα δημιουργήθηκε","es":"Habilidad creada","fr":"Compétence créée","hi":"कौशल बनाया गया","it":"Skill creata","ja":"スキルを作成しました","nl":"Vaardigheid aangemaakt","no":"Ferdighet opprettet","pl":"Umiejętność utworzona","pt":"Habilidade criada","sv":"Färdighet skapad","zh":"技能已创建"},
    "Skill imported": {"cs":"Dovednost importována","da":"Færdighed importeret","de":"Skill importiert","el":"Η δεξιότητα εισήχθη","es":"Habilidad importada","fr":"Compétence importée","hi":"कौशल आयात किया गया","it":"Skill importata","ja":"スキルをインポートしました","nl":"Vaardigheid geïmporteerd","no":"Ferdighet importert","pl":"Umiejętność zaimportowana","pt":"Habilidade importada","sv":"Färdighet importerad","zh":"技能已导入"},
    "Recording...": {"cs":"Nahrávání...","da":"Optager...","de":"Aufnahme...","el":"Εγγραφή...","es":"Grabando...","fr":"Enregistrement...","hi":"रिकॉर्डिंग...","it":"Registrazione...","ja":"録音中...","nl":"Opnemen...","no":"Tar opp...","pl":"Nagrywanie...","pt":"Gravando...","sv":"Inspelning...","zh":"正在录音..."},
    "Draft generated": {"cs":"Návrh vygenerován","da":"Udkast genereret","de":"Entwurf generiert","el":"Το προσχέδιο δημιουργήθηκε","es":"Borrador generado","fr":"Brouillon généré","hi":"ड्राफ्ट उत्पन्न किया गया","it":"Bozza generata","ja":"ドラフトを生成しました","nl":"Concept gegenereerd","no":"Utkast generert","pl":"Szkic wygenerowany","pt":"Rascunho gerado","sv":"Utkast genererat","zh":"草稿已生成"},
    "Creating AI draft. This can take a few moments.": {"cs":"Vytváření AI návrhu. Může to chvíli trvat.","da":"Opretter AI-udkast. Dette kan tage et øjeblik.","de":"KI-Entwurf wird erstellt. Dies kann einige Augenblicke dauern.","el":"Δημιουργία προχείρου AI. Μπορεί να χρειαστεί λίγος χρόνος.","es":"Creando borrador de IA. Esto puede tardar unos momentos.","fr":"Création du brouillon IA. Cela peut prendre quelques instants.","hi":"AI ड्राफ्ट बनाया जा रहा है। इसमें कुछ समय लग सकता है।","it":"Creazione bozza IA. Può richiedere alcuni istanti.","ja":"AIドラフトを作成中。しばらくお待ちください。","nl":"AI-concept maken. Dit kan even duren.","no":"Oppretter AI-utkast. Dette kan ta et øyeblikk.","pl":"Tworzenie szkicu AI. Może to chwilę potrwać.","pt":"Criando rascunho de IA. Isso pode levar alguns instantes.","sv":"Skapar AI-utkast. Detta kan ta en stund.","zh":"正在创建 AI 草稿。这可能需要一些时间。"},
    "The AI draft took too long. Please try again or shorten the prompt.": {"cs":"Vytváření AI návrhu trvalo příliš dlouho. Zkuste to znovu nebo zkrátíte prompt.","da":"AI-udkastet tog for lang tid. Prøv igen eller forkort prompten.","de":"Der KI-Entwurf hat zu lange gedauert. Bitte versuchen Sie es erneut oder kürzen Sie den Prompt.","el":"Το προσχέδιο AI χρειάστηκε πολύ χρόνο. Δοκιμάστε ξανά ή συντομεύστε την εντολή.","es":"El borrador de IA tardó demasiado. Inténtelo de nuevo o acorte el prompt.","fr":"Le brouillon IA a pris trop de temps. Veuillez réessayer ou raccourcir le prompt.","hi":"AI ड्राफ्ट में बहुत समय लगा। कृपया पुनः प्रयास करें या प्रॉम्प्ट छोटा करें।","it":"La bozza IA ha impiegato troppo tempo. Riprova o accorcia il prompt.","ja":"AIドラフトの生成に時間がかかりすぎました。再試行するか、プロンプトを短くしてください。","nl":"Het AI-concept duurde te lang. Probeer opnieuw of verkort de prompt.","no":"AI-utkastet tok for lang tid. Prøv igjen eller kort ned prompten.","pl":"Szkic AI trwał zbyt długo. Spróbuj ponownie lub skróć prompt.","pt":"O rascunho de IA demorou muito. Tente novamente ou encurte o prompt.","sv":"AI-utkastet tog för lång tid. Försök igen eller korta ner prompten.","zh":"AI 草稿耗时过长。请重试或缩短提示词。"},
    "Upload in Progress": {"cs":"Nahrávání probíhá","da":"Upload i gang","de":"Upload läuft","el":"Μεταφόρτωση σε εξέλιξη","es":"Carga en progreso","fr":"Téléversement en cours","hi":"अपलोड जारी","it":"Caricamento in corso","ja":"アップロード中","nl":"Upload bezig","no":"Opplasting pågår","pl":"Przesyłanie w toku","pt":"Envio em andamento","sv":"Uppladdning pågår","zh":"正在上传"},
    "Uploads in progress. Close anyway?": {"cs":"Nahrávání probíhá. Přesto zavřít?","da":"Uploads i gang. Luk alligevel?","de":"Uploads laufen noch. Trotzdem schließen?","el":"Μεταφορτώσεις σε εξέλιξη. Κλείσιμο ούτως ή άλλως;","es":"Cargas en progreso. ¿Cerrar de todos modos?","fr":"Téléversements en cours. Fermer quand même ?","hi":"अपलोड जारी है। फिर भी बंद करें?","it":"Caricamenti in corso. Chiudere comunque?","ja":"アップロード中です。それでも閉じますか？","nl":"Uploads bezig. Toch sluiten?","no":"Opplasting pågår. Lukke likevel?","pl":"Przesyłanie w toku. Zamknąć mimo to?","pt":"Envios em andamento. Fechar mesmo assim?","sv":"Uppladdning pågår. Stäng ändå?","zh":"上传正在进行中。仍然关闭？"},
    "Could not store uploaded file": {"cs":"Nelze uložit nahraný soubor","da":"Kunne ikke gemme uploadet fil","de":"Hochgeladene Datei konnte nicht gespeichert werden","el":"Δεν ήταν δυνατή η αποθήκευση του μεταφορτωμένου αρχείου","es":"No se pudo almacenar el archivo subido","fr":"Impossible de stocker le fichier téléversé","hi":"अपलोड की गई फ़ाइल संग्रहीत नहीं की जा सकी","it":"Impossibile salvare il file caricato","ja":"アップロードファイルを保存できませんでした","nl":"Kon geüpload bestand niet opslaan","no":"Kunne ikke lagre opplastet fil","pl":"Nie można zapisać przesłanego pliku","pt":"Não foi possível armazenar o arquivo enviado","sv":"Kunde inte spara uppladdad fil","zh":"无法存储上传的文件"},
    "Input must be valid JSON": {"cs":"Vstup musí být platný JSON","da":"Input skal være gyldig JSON","de":"Eingabe muss gültiges JSON sein","el":"Η είσοδος πρέπει να είναι έγκυρο JSON","es":"La entrada debe ser JSON válido","fr":"L'entrée doit être du JSON valide","hi":"इनपुट मान्य JSON होना चाहिए","it":"L'input deve essere JSON valido","ja":"入力は有効なJSONである必要があります","nl":"Invoer moet geldige JSON zijn","no":"Inndata må være gyldig JSON","pl":"Dane wejściowe muszą być prawidłowym JSON","pt":"A entrada deve ser JSON válido","sv":"Indata måste vara giltig JSON","zh":"输入必须是有效的 JSON"},
    "Invalid filename": {"cs":"Neplatný název souboru","da":"Ugyldigt filnavn","de":"Ungültiger Dateiname","el":"Μη έγκυρο όνομα αρχείου","es":"Nombre de archivo no válido","fr":"Nom de fichier invalide","hi":"अमान्य फ़ाइलनाम","it":"Nome file non valido","ja":"無効なファイル名","nl":"Ongeldige bestandsnaam","no":"Ugyldig filnavn","pl":"Nieprawidłowa nazwa pliku","pt":"Nome de arquivo inválido","sv":"Ogiltigt filnamn","zh":"无效的文件名"},
    "Invalid credentials.": {"cs":"Neplatné přihlašovací údaje.","da":"Ugyldige legitimationsoplysninger.","de":"Ungültige Anmeldeinformationen.","el":"Μη έγκυρα διαπιστευτήρια.","es":"Credenciales no válidas.","fr":"Identifiants invalides.","hi":"अमान्य क्रेडेंशियल।","it":"Credenziali non valide.","ja":"無効な認証情報。","nl":"Ongeldige inloggegevens.","no":"Ugyldige legitimasjon.","pl":"Nieprawidłowe poświadczenia.","pt":"Credenciais inválidas.","sv":"Ogiltiga inloggningsuppgifter.","zh":"无效的凭据。"},
    "Invalid code. Please try again.": {"cs":"Neplatný kód. Zkuste to prosím znovu.","da":"Ugyldig kode. Prøv igen.","de":"Ungültiger Code. Bitte versuchen Sie es erneut.","el":"Μη έγκυρος κωδικός. Δοκιμάστε ξανά.","es":"Código no válido. Inténtelo de nuevo.","fr":"Code invalide. Veuillez réessayer.","hi":"अमान्य कोड। कृपया पुनः प्रयास करें।","it":"Codice non valido. Riprova.","ja":"無効なコードです。もう一度お試しください。","nl":"Ongeldige code. Probeer opnieuw.","no":"Ugyldig kode. Prøv igjen.","pl":"Nieprawidłowy kod. Spróbuj ponownie.","pt":"Código inválido. Tente novamente.","sv":"Ogiltig kod. Försök igen.","zh":"无效的代码。请重试。"},
    "Password must be at least 8 characters.": {"cs":"Heslo musí mít alespoň 8 znaků.","da":"Adgangskoden skal være mindst 8 tegn.","de":"Passwort muss mindestens 8 Zeichen lang sein.","el":"Ο κωδικός πρέπει να έχει τουλάχιστον 8 χαρακτήρες.","es":"La contraseña debe tener al menos 8 caracteres.","fr":"Le mot de passe doit comporter au moins 8 caractères.","hi":"पासवर्ड कम से कम 8 अक्षर का होना चाहिए।","it":"La password deve essere di almeno 8 caratteri.","ja":"パスワードは8文字以上必要です。","nl":"Wachtwoord moet minimaal 8 tekens lang zijn.","no":"Passordet må være minst 8 tegn.","pl":"Hasło musi mieć co najmniej 8 znaków.","pt":"A senha deve ter pelo menos 8 caracteres.","sv":"Lösenordet måste vara minst 8 tecken.","zh":"密码必须至少为 8 个字符。"},
    "Password set.": {"cs":"Heslo nastaveno.","da":"Adgangskode indstillet.","de":"Passwort gesetzt.","el":"Ο κωδικός ορίστηκε.","es":"Contraseña establecida.","fr":"Mot de passe défini.","hi":"पासवर्ड सेट किया गया।","it":"Password impostata.","ja":"パスワードを設定しました。","nl":"Wachtwoord ingesteld.","no":"Passord satt.","pl":"Hasło ustawione.","pt":"Senha definida.","sv":"Lösenord inställt.","zh":"密码已设置。"},
    "Too many login attempts. Please wait a few minutes and try again.": {"cs":"Příliš mnoho pokusů o přihlášení. Počkejte prosím pár minut a zkuste to znovu.","da":"For mange loginforsøg. Vent venligst et par minutter og prøv igen.","de":"Zu viele Anmeldeversuche. Bitte warten Sie einige Minuten und versuchen Sie es erneut.","el":"Πάρα πολλές προσπάθειες σύνδεσης. Περιμένετε μερικά λεπτά και δοκιμάστε ξανά.","es":"Demasiados intentos de inicio de sesión. Espere unos minutos e inténtelo de nuevo.","fr":"Trop de tentatives de connexion. Veuillez attendre quelques minutes et réessayer.","hi":"बहुत अधिक लॉगिन प्रयास। कृपया कुछ मिनट प्रतीक्षा करें और पुनः प्रयास करें।","it":"Troppi tentativi di accesso. Attendi qualche minuto e riprova.","ja":"ログイン試行回数が多すぎます。数分待ってから再試行してください。","nl":"Te veel inlogpogingen. Wacht een paar minuten en probeer opnieuw.","no":"For mange innloggingsforsøk. Vent noen minutter og prøv igjen.","pl":"Zbyt wiele prób logowania. Poczekaj kilka minut i spróbuj ponownie.","pt":"Muitas tentativas de login. Aguarde alguns minutos e tente novamente.","sv":"För många inloggningsförsök. Vänta några minuter och försök igen.","zh":"登录尝试次数过多。请等待几分钟后重试。"},
    "Token expired": {"cs":"Token vypršel","da":"Token udløbet","de":"Token abgelaufen","el":"Το διακριτικό έληξε","es":"Token expirado","fr":"Jeton expiré","hi":"टोकन समाप्त","it":"Token scaduto","ja":"トークンの有効期限切れ","nl":"Token verlopen","no":"Token utløpt","pl":"Token wygasł","pt":"Token expirado","sv":"Token har löpt ut","zh":"令牌已过期"},
    "Token expired — please re-authorize": {"cs":"Token vypršel — prosím znovu autorizujte","da":"Token udløbet — godkend venligst igen","de":"Token abgelaufen — bitte erneut autorisieren","el":"Το διακριτικό έληξε — παρακαλώ επαναεξουσιοδοτήστε","es":"Token expirado — por favor reautorice","fr":"Jeton expiré — veuillez vous réauthentifier","hi":"टोकन समाप्त — कृपया पुनः अधिकृत करें","it":"Token scaduto — si prega di ri-autorizzare","ja":"トークンの有効期限切れ — 再認証してください","nl":"Token verlopen — autoriseer opnieuw","no":"Token utløpt — vennligst godkjenn på nytt","pl":"Token wygasł — proszę ponownie autoryzować","pt":"Token expirado — por favor reautorize","sv":"Token har löpt ut — vänligen auktorisera igen","zh":"令牌已过期 — 请重新授权"},
    "Token generated — copy it now, it won't be shown again": {"cs":"Token vygenerován — zkopírujte si ho nyní, nebude znovu zobrazen","da":"Token genereret — kopier den nu, den vises ikke igen","de":"Token generiert — kopieren Sie es jetzt, es wird nicht wieder angezeigt","el":"Το διακριτικό δημιουργήθηκε — αντιγράψτε το τώρα, δεν θα εμφανιστεί ξανά","es":"Token generado — cópielo ahora, no se volverá a mostrar","fr":"Jeton généré — copiez-le maintenant, il ne sera plus affiché","hi":"टोकन उत्पन्न — अभी कॉपी करें, यह दोबारा नहीं दिखाया जाएगा","it":"Token generato — copialo ora, non verrà mostrato di nuovo","ja":"トークンを生成しました — 今すぐコピーしてください。再表示されません","nl":"Token gegenereerd — kopieer het nu, het wordt niet opnieuw getoond","no":"Token generert — kopier det nå, det vises ikke igjen","pl":"Token wygenerowany — skopiuj go teraz, nie zostanie ponownie wyświetlony","pt":"Token gerado — copie-o agora, não será mostrado novamente","sv":"Token genererad — kopiera den nu, den visas inte igen","zh":"令牌已生成 — 请立即复制，不会再次显示"},
}

stats = defaultdict(int)
for d in sorted(str(p) for p in LANG_DIR.rglob("en.json")):
    direc = Path(d).parent
    en = json.loads(Path(d).read_text(encoding="utf-8-sig"))
    for lang in LANGS:
        lf = direc / f"{lang}.json"
        if not lf.exists():
            continue
        ld = json.loads(lf.read_text(encoding="utf-8-sig"))
        mod = False
        for k, ev in en.items():
            if k not in ld:
                continue
            if str(ld[k]).strip().lower() != str(ev).strip().lower():
                continue
            evs = ev.strip()
            if evs in T:
                t = T[evs].get(lang)
                if t:
                    ld[k] = t
                    mod = True
                    stats[lang] += 1
        if mod:
            lf.write_text(json.dumps(ld, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print("Fixed:", dict(stats))
print("Total:", sum(stats.values()))
