#!/usr/bin/env python3
"""Batch 5: More backend messages, error messages, and slash command help texts."""
import json, os
from pathlib import Path
from collections import defaultdict

LANG_DIR = Path("ui/lang")
LANGS = ["cs","da","de","el","es","fr","hi","it","ja","nl","no","pl","pt","sv","zh"]

T = {
    "Interrupts the current agent action.":{"cs":"Přeruší aktuální akci agenta.","da":"Afbryder den aktuelle agenthandling.","de":"Bricht die aktuelle Agent-Aktion ab.","el":"Διακόπτει την τρέχουσα ενέργεια του πράκτορα.","es":"Interrumpe la acción actual del agente.","fr":"Interrompt l'action actuelle de l'agent.","hi":"एजेंट की वर्तमान कार्रवाई को बाधित करता है।","it":"Interrompe l'azione corrente dell'agente.","ja":"現在のエージェントアクションを中断します。","nl":"Onderbreekt de huidige agentactie.","no":"Avbryter den gjeldende agenthandlingen.","pl":"Przerywa bieżącą akcję agenta.","pt":"Interrompe a ação atual do agente.","sv":"Avbryter den aktuella agentåtgärden.","zh":"中断当前代理操作。"},
    "Deletes the current chat history (short-term memory).":{"cs":"Smaže aktuální historii chatu (krátkodobá paměť).","da":"Sletter den aktuelle chat-historik (korttidshukommelse).","de":"Löscht den aktuellen Chatverlauf (Kurzzeitgedächtnis).","el":"Διαγράφει το τρέχον ιστορικό συνομιλίας (βραχυπρόθεσμη μνήμη).","es":"Elimina el historial de chat actual (memoria a corto plazo).","fr":"Supprime l'historique de chat actuel (mémoire à court terme).","hi":"वर्तमान चैट इतिहास को हटाता है (अल्पकालिक स्मृति)।","it":"Elimina la cronologia chat corrente (memoria a breve termine).","ja":"現在のチャット履歴を削除します（短期記憶）。","nl":"Verwijdert de huidige chatgeschiedenis (kortetermijngeheugen).","no":"Sletter gjeldende chathistorikk (korttidsminne).","pl":"Usuwa bieżącą historię czatu (pamięć krótkotrwała).","pt":"Exclui o histórico de chat atual (memória de curto prazo).","sv":"Tar bort den aktuella chathistoriken (korttidsminne).","zh":"删除当前聊天记录（短期记忆）。"},
    "Shows this help message.":{"cs":"Zobrazí tuto nápovědu.","da":"Viser denne hjælpemeddelelse.","de":"Zeigt diese Hilfemeldung an.","el":"Εμφανίζει αυτό το μήνυμα βοήθειας.","es":"Muestra este mensaje de ayuda.","fr":"Affiche ce message d'aide.","hi":"यह सहायता संदेश दिखाता है।","it":"Mostra questo messaggio di aiuto.","ja":"このヘルプメッセージを表示します。","nl":"Toont dit helpbericht.","no":"Viser denne hjelpemeldingen.","pl":"Wyświetla tę wiadomość pomocy.","pt":"Mostra esta mensagem de ajuda.","sv":"Visar detta hjälpmeddelande.","zh":"显示此帮助消息。"},
    "Shows the current budget status (daily costs, limit, models).":{"cs":"Zobrazí aktuální stav rozpočtu (denní náklady, limit, modely).","da":"Viser den aktuelle budgetstatus (daglige omkostninger, grænse, modeller).","de":"Zeigt den aktuellen Budgetstatus (tägliche Kosten, Limit, Modelle).","el":"Εμφανίζει την τρέχουσα κατάσταση προϋπολογισμού (ημερήσια έξοδα, όριο, μοντέλα).","es":"Muestra el estado actual del presupuesto (costos diarios, límite, modelos).","fr":"Affiche l'état actuel du budget (coûts quotidiens, limite, modèles).","hi":"वर्तमान बजट स्थिति दिखाता है (दैनिक लागत, सीमा, मॉडल)।","it":"Mostra lo stato attuale del budget (costi giornalieri, limite, modelli).","ja":"現在の予算ステータスを表示します（日次コスト、制限、モデル）。","nl":"Toont de huidige budgetstatus (dagelijkse kosten, limiet, modellen).","no":"Viser gjeldende budsjettstatus (daglige kostnader, grense, modeller).","pl":"Wyświetla bieżący status budżetu (koszty dzienne, limit, modele).","pt":"Mostra o status atual do orçamento (custos diários, limite, modelos).","sv":"Visar aktuell budgetstatus (dagliga kostnader, gräns, modeller).","zh":"显示当前预算状态（每日成本、限额、模型）。"},
    "Shows the current OpenRouter balance and usage.":{"cs":"Zobrazí aktuální zůstatek a využití OpenRouter.","da":"Viser den aktuelle OpenRouter-saldo og forbrug.","de":"Zeigt den aktuellen OpenRouter-Guthabenstand und die Nutzung an.","el":"Εμφανίζει το τρέχον υπόλοιπο και χρήση του OpenRouter.","es":"Muestra el saldo y uso actual de OpenRouter.","fr":"Affiche le solde et l'utilisation actuels d'OpenRouter.","hi":"वर्तमान OpenRouter शेष और उपयोग दिखाता है।","it":"Mostra il saldo e l'utilizzo attuali di OpenRouter.","ja":"現在のOpenRouter残高と使用量を表示します。","nl":"Toont het huidige OpenRouter-saldo en -verbruik.","no":"Viser gjeldende OpenRouter-saldo og bruk.","pl":"Wyświetla bieżące saldo i użycie OpenRouter.","pt":"Mostra o saldo e uso atual do OpenRouter.","sv":"Visar aktuellt OpenRouter-saldo och användning.","zh":"显示当前 OpenRouter 余额和使用情况。"},
    "Shows active system warnings and health issues.":{"cs":"Zobrazí aktivní systémová varování a zdravotní problémy.","da":"Viser aktive systemadvarsler og sundhedsproblemer.","de":"Zeigt aktive Systemwarnungen und Gesundheitsprobleme an.","el":"Εμφανίζει ενεργές προειδοποιήσεις συστήματος και προβλήματα υγείας.","es":"Muestra advertencias activas del sistema y problemas de salud.","fr":"Affiche les avertissements système actifs et les problèmes de santé.","hi":"सक्रिय सिस्टम चेतावनी और स्वास्थ्य समस्याएं दिखाता है।","it":"Mostra avvisi di sistema attivi e problemi di integrità.","ja":"アクティブなシステム警告と健全性の問題を表示します。","nl":"Toont actieve systeemwaarschuwingen en gezondheidsproblemen.","no":"Viser aktive systemadvarsler og helseproblemer.","pl":"Wyświetla aktywne ostrzeżenia systemowe i problemy zdrowotne.","pt":"Mostra avisos ativos do sistema e problemas de integridade.","sv":"Visar aktiva systemvarningar och hälsoproblem.","zh":"显示活动的系统警告和健康问题。"},
    "Stores the sudo password in the vault for the execute_sudo tool.":{"cs":"Uloží sudo heslo do trezoru pro nástroj execute_sudo.","da":"Gemmer sudo-adgangskoden i boksen til execute_sudo-værktøjet.","de":"Speichert das Sudo-Passwort im Vault für das execute_sudo-Werkzeug.","el":"Αποθηκεύει τον κωδικό sudo στο θησαυροφυλάκιο για το εργαλείο execute_sudo.","es":"Almacena la contraseña sudo en la bóveda para la herramienta execute_sudo.","fr":"Stocke le mot de passe sudo dans le coffre pour l'outil execute_sudo.","hi":"sudo पासवर्ड को vault में execute_sudo टूल के लिए संग्रहीत करता है।","it":"Memorizza la password sudo nel vault per lo strumento execute_sudo.","ja":"sudoパスワードをvaultに保存し、execute_sudoツールで使用します。","nl":"Slaat het sudo-wachtwoord op in de kluis voor het execute_sudo-hulpmiddel.","no":"Lagrer sudo-passordet i hvelvet for execute_sudo-verktøyet.","pl":"Przechowuje hasło sudo w sejfie dla narzędzia execute_sudo.","pt":"Armazena a senha sudo no cofre para a ferramenta execute_sudo.","sv":"Lagrar sudo-lösenordet i valvet för verktyget execute_sudo.","zh":"将 sudo 密码存储在保管库中供 execute_sudo 工具使用。"},
    "Lists or switches personalities (/personality <name>).":{"cs":"Vypíše nebo přepne osobnosti (/personality <jméno>).","da":"Viser eller skifter personligheder (/personality <navn>).","de":"Listet Persönlichkeiten auf oder wechselt sie (/personality <Name>).","el":"Παραθέτει ή αλλάζει προσωπικότητες (/personality <όνομα>).","es":"Lista o cambia personalidades (/personality <nombre>).","fr":"Liste ou change les personnalités (/personality <nom>).","hi":"व्यक्तित्वों को सूचीबद्ध या बदलता है (/personality <नाम>)।","it":"Elenca o cambia personalità (/personality <nome>).","ja":"パーソナリティを一覧表示または切り替えます (/personality <名前>)。","nl":"Toont of wisselt persoonlijkheden (/personality <naam>).","no":"Viser eller bytter personligheter (/personality <navn>).","pl":"Wyświetla lub przełącza osobowości (/personality <nazwa>).","pt":"Lista ou troca personalidades (/personality <nome>).","sv":"Listar eller byter personligheter (/personality <namn>).","zh":"列出或切换人格（/personality <名称>）。"},
    "Toggles voice output mode — when on, the agent uses TTS for short replies (/voice on|off).":{"cs":"Přepíná režim hlasového výstupu — když je zapnutý, agent používá TTS pro krátké odpovědi (/voice on|off).","da":"Skifter taleoutput-tilstand — når aktiveret, bruger agenten TTS til korte svar (/voice on|off).","de":"Schaltet den Sprachausgabemodus um — wenn aktiv, verwendet der Agent TTS für kurze Antworten (/voice on|off).","el":"Εναλλάσσει τη λειτουργία φωνητικής εξόδου — όταν είναι ενεργή, ο πράκτορας χρησιμοποιεί TTS για σύντομες απαντήσεις (/voice on|off).","es":"Alterna el modo de salida de voz — cuando está activado, el agente usa TTS para respuestas cortas (/voice on|off).","fr":"Bascule le mode de sortie vocale — quand activé, l'agent utilise TTS pour les réponses courtes (/voice on|off).","hi":"वॉइस आउटपुट मोड टॉगल करता है — चालू होने पर, एजेंट छोटे उत्तरों के लिए TTS का उपयोग करता है (/voice on|off)।","it":"Attiva/disattiva la modalità di output vocale — quando attiva, l'agente usa TTS per risposte brevi (/voice on|off).","ja":"音声出力モードを切り替え — オン時、エージェントは短い返答にTTSを使用します (/voice on|off)。","nl":"Schakelt spraakuitvoermodus — indien aan, gebruikt de agent TTS voor korte antwoorden (/voice on|off).","no":"Veksler talemodus — når på, bruker agenten TTS for korte svar (/voice on|off).","pl":"Przełącza tryb wyjścia głosowego — gdy włączony, agent używa TTS dla krótkich odpowiedzi (/voice on|off).","pt":"Alterna o modo de saída de voz — quando ativado, o agente usa TTS para respostas curtas (/voice on|off).","sv":"Växlar röstutmatningsläge — när aktiverat, använder agenten TTS för korta svar (/voice on|off).","zh":"切换语音输出模式 — 开启时，代理使用 TTS 进行简短回复（/voice on|off）。"},
    "Restarts the AuraGo server.":{"cs":"Restartuje server AuraGo.","da":"Genstarter AuraGo-serveren.","de":"Startet den AuraGo-Server neu.","el":"Επανεκκινεί τον διακομιστή AuraGo.","es":"Reinicia el servidor AuraGo.","fr":"Redémarre le serveur AuraGo.","hi":"AuraGo सर्वर को पुनरारंभ करता है।","it":"Riavvia il server AuraGo.","ja":"AuraGoサーバーを再起動します。","nl":"Herstart de AuraGo-server.","no":"Starter AuraGo-serveren på nytt.","pl":"Restartuje serwer AuraGo.","pt":"Reinicia o servidor AuraGo.","sv":"Startar om AuraGo-servern.","zh":"重启 AuraGo 服务器。"},
    "Registers a new SSH server.":{"cs":"Registruje nový SSH server.","da":"Registrerer en ny SSH-server.","de":"Registriert einen neuen SSH-Server.","el":"Καταχωρεί έναν νέο διακομιστή SSH.","es":"Registra un nuevo servidor SSH.","fr":"Enregistre un nouveau serveur SSH.","hi":"एक नया SSH सर्वर पंजीकृत करता है।","it":"Registra un nuovo server SSH.","ja":"新しいSSHサーバーを登録します。","nl":"Registreert een nieuwe SSH-server.","no":"Registrerer en ny SSH-server.","pl":"Rejestruje nowy serwer SSH.","pt":"Registra um novo servidor SSH.","sv":"Registrerar en ny SSH-server.","zh":"注册新的 SSH 服务器。"},
    "Daily budget exceeded. All LLM calls blocked until reset.":{"cs":"Denní rozpočet překročen. Všechna LLM volání blokována do resetu.","da":"Dagligt budget overskredet. Alle LLM-kald blokeret indtil nulstilling.","de":"Tagesbudget überschritten. Alle LLM-Aufrufe bis zum Reset blockiert.","el":"Ημερήσιο προϋπολογισμός υπερβαινόμενος. Όλες οι κλήσεις LLM αποκλείονται μέχρι την επαναφορά.","es":"Presupuesto diario excedido. Todas las llamadas LLM bloqueadas hasta el reinicio.","fr":"Budget quotidien dépassé. Tous les appels LLM bloqués jusqu'à la réinitialisation.","hi":"दैनिक बजट पार हो गया। रीसेट तक सभी LLM कॉल अवरुद्ध।","it":"Budget giornaliero superato. Tutte le chiamate LLM bloccate fino al reset.","ja":"日次予算超過。リセットまで全LLM呼び出しをブロック。","nl":"Dagelijks budget overschreden. Alle LLM-aanroepen geblokkeerd tot reset.","no":"Daglig budsjett overskredet. Alle LLM-kall blokkert til nullstilling.","pl":"Dzienny budżet przekroczony. Wszystkie wywołania LLM zablokowane do resetu.","pt":"Orçamento diário excedido. Todas as chamadas LLM bloqueadas até a redefinição.","sv":"Daglig budget överskriden. Alla LLM-anrop blockerade tills återställning.","zh":"每日预算已超支。所有 LLM 调用被阻止直到重置。"},
    "Knowledge storage is currently unavailable":{"cs":"Úložiště znalostí je momentálně nedostupné","da":"Videnlager er i øjeblikket utilgængeligt","de":"Wissensspeicher ist derzeit nicht verfügbar","el":"Η αποθήκη γνώσεων δεν είναι διαθέσιμη προς το παρόν","es":"El almacenamiento de conocimiento no está disponible actualmente","fr":"Le stockage de connaissances est actuellement indisponible","hi":"ज्ञान भंडार वर्तमान में अनुपलब्ध है","it":"L'archiviazione della conoscenza non è attualmente disponibile","ja":"ナレッジストレージは現在利用できません","nl":"Kennisopslag is momenteel niet beschikbaar","no":"Kunnskapslager er for øyeblikket utilgjengelig","pl":"Przechowywanie wiedzy jest obecnie niedostępne","pt":"Armazenamento de conhecimento está indisponível no momento","sv":"Kunskapslagring är för närvarande otillgänglig","zh":"知识存储当前不可用"},
    "Empty batch":{"cs":"Prázdná dávka","da":"Tom batch","de":"Leerer Batch","el":"Κενή παρτίδα","es":"Lote vacío","fr":"Lot vide","hi":"रिक्त बैच","it":"Batch vuoto","ja":"空のバッチ","nl":"Lege batch","no":"Tom batch","pl":"Pusta partia","pt":"Lote vazio","sv":"Tom batch","zh":"空批次"},
    "Vault not initialized (master key missing)":{"cs":"Trezor neinicializován (chybí hlavní klíč)","da":"Boks ikke initialiseret (manglende hovednøgle)","de":"Vault nicht initialisiert (Master-Key fehlt)","el":"Το θησαυροφυλάκιο δεν αρχικοποιήθηκε (λείπει το κύριο κλειδί)","es":"Cofre no inicializado (falta la clave maestra)","fr":"Coffre non initialisé (clé maîtresse manquante)","hi":"Vault प्रारंभ नहीं (मास्टर कुंजी अनुपस्थित)","it":"Vault non inizializzato (chiave master mancante)","ja":"Vault未初期化（マスターキー不足）","nl":"Kluis niet geïnitialiseerd (mastersleutel ontbreekt)","no":"Hvelv ikke initialisert (manglende hovednøkkel)","pl":"Sejf niezainicjalizowany (brak klucza głównego)","pt":"Cofre não inicializado (chave mestra ausente)","sv":"Valv inte initierat (masternyckel saknas)","zh":"保管库未初始化（缺少主密钥）"},
}

stats = defaultdict(int)
for d in sorted(str(p) for p in LANG_DIR.rglob("en.json")):
    direc = Path(d).parent
    en = json.loads(Path(d).read_text(encoding="utf-8-sig"))
    for lang in LANGS:
        lf = direc / f"{lang}.json"
        if not lf.exists():
            continue
        ld = json.loads(lf.read_text(encoding="utf-8-sig"))
        mod = False
        for k, ev in en.items():
            if k not in ld:
                continue
            if str(ld[k]).strip().lower() != str(ev).strip().lower():
                continue
            evs = ev.strip()
            if evs in T:
                t = T[evs].get(lang)
                if t:
                    ld[k] = t
                    mod = True
                    stats[lang] += 1
        if mod:
            lf.write_text(json.dumps(ld, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print("Fixed:", dict(stats))
print("Total:", sum(stats.values()))
