#!/usr/bin/env python3
"""
Comprehensive pattern-based translation fix for AuraGo UI.
Combines dictionary lookup, pattern-based translation, and specific translations.
"""
import json, os, re
from pathlib import Path
from collections import defaultdict

LANG_DIR = Path("ui/lang")
LANGUAGES = ["cs","da","de","el","en","es","fr","hi","it","ja","nl","no","pl","pt","sv","zh"]
NON_EN_LANGS = [l for l in LANGUAGES if l != "en"]

# ── Common term dictionary: English → {lang: translation} ──
COMMON_TERMS = {
    "Failed to save config": {"cs":"Nepodařilo se uložit konfiguraci","da":"Kunne ikke gemme konfiguration","de":"Konfiguration konnte nicht gespeichert werden","el":"Αποτυχία αποθήκευσης ρυθμίσεων","es":"No se pudo guardar la configuración","fr":"Échec de l'enregistrement de la configuration","hi":"कॉन्फ़िगरेशन सहेजने में विफल","it":"Impossibile salvare la configurazione","ja":"設定の保存に失敗しました","nl":"Kan configuratie niet opslaan","no":"Kunne ikke lagre konfigurasjon","pl":"Nie udało się zapisać konfiguracji","pt":"Falha ao salvar configuração","sv":"Kunde inte spara konfiguration","zh":"保存配置失败"},
    "Failed to save file": {"cs":"Nepodařilo se uložit soubor","da":"Kunne ikke gemme fil","de":"Datei konnte nicht gespeichert werden","el":"Αποτυχία αποθήκευσης αρχείου","es":"No se pudo guardar el archivo","fr":"Échec de l'enregistrement du fichier","hi":"फ़ाइल सहेजने में विफल","it":"Impossibile salvare il file","ja":"ファイルの保存に失敗","nl":"Kan bestand niet opslaan","no":"Kunne ikke lagre fil","pl":"Nie udało się zapisać pliku","pt":"Falha ao salvar arquivo","sv":"Kunde inte spara fil","zh":"保存文件失败"},
    "Failed to save personality file": {"cs":"Nepodařilo se uložit soubor osobnosti","da":"Kunne ikke gemme personlighedsfil","de":"Persönlichkeitsdatei konnte nicht gespeichert werden","el":"Αποτυχία αποθήκευσης αρχείου προσωπικότητας","es":"No se pudo guardar el archivo de personalidad","fr":"Échec de l'enregistrement du fichier de personnalité","hi":"व्यक्तित्व फ़ाइल सहेजने में विफल","it":"Impossibile salvare il file di personalità","ja":"パーソナリティファイルの保存に失敗","nl":"Kan persoonlijkheidsbestand niet opslaan","no":"Kunne ikke lagre personlighetsfil","pl":"Nie udało się zapisać pliku osobowości","pt":"Falha ao salvar arquivo de personalidade","sv":"Kunde inte spara personlighetsfil","zh":"保存人格文件失败"},
    "Failed to delete contact": {"cs":"Nepodařilo se smazat kontakt","da":"Kunne ikke slette kontakt","de":"Kontakt konnte nicht gelöscht werden","el":"Αποτυχία διαγραφής επαφής","es":"No se pudo eliminar el contacto","fr":"Échec de la suppression du contact","hi":"संपर्क हटाने में विफल","it":"Impossibile eliminare il contatto","ja":"連絡先の削除に失敗","nl":"Kan contact niet verwijderen","no":"Kunne ikke slette kontakt","pl":"Nie udało się usunąć kontaktu","pt":"Falha ao excluir contato","sv":"Kunde inte ta bort kontakt","zh":"删除联系人失败"},
    "Failed to fetch OpenRouter credits": {"cs":"Nepodařilo se načíst OpenRouter kredity","da":"Kunne ikke hente OpenRouter-kreditter","de":"OpenRouter-Guthaben konnte nicht abgerufen werden","el":"Αποτυχία λήψης πιστώσεων OpenRouter","es":"No se pudieron obtener los créditos de OpenRouter","fr":"Échec de la récupération des crédits OpenRouter","hi":"OpenRouter क्रेडिट प्राप्त करने में विफल","it":"Impossibile recuperare i crediti OpenRouter","ja":"OpenRouterクレジットの取得に失敗","nl":"Kan OpenRouter-credits niet ophalen","no":"Kunne ikke hente OpenRouter-kreditter","pl":"Nie udało się pobrać kreditów OpenRouter","pt":"Falha ao buscar créditos do OpenRouter","sv":"Kunde inte hämta OpenRouter-krediter","zh":"获取 OpenRouter 积分失败"},
    "Knowledge storage is not configured": {"cs":"Úložiště znalostí není nakonfigurováno","da":"Videnlager er ikke konfigureret","de":"Wissensspeicher ist nicht konfiguriert","el":"Η αποθήκη γνώσεων δεν έχει ρυθμιστεί","es":"El almacenamiento de conocimiento no está configurado","fr":"Le stockage de connaissances n'est pas configuré","hi":"ज्ञान भंडार कॉन्फ़िगर नहीं किया गया","it":"L'archiviazione della conoscenza non è configurata","ja":"ナレッジストレージが設定されていません","nl":"Kennisopslag is niet geconfigureerd","no":"Kunnskapslager er ikke konfigurert","pl":"Przechowywanie wiedzy nie jest skonfigurowane","pt":"Armazenamento de conhecimento não configurado","sv":"Kunskapslagring är inte konfigurerad","zh":"知识存储未配置"},
    "Authentication is not fully configured.": {"cs":"Autentizace není plně nakonfigurována.","da":"Autentificering er ikke fuldt konfigureret.","de":"Authentifizierung ist nicht vollständig konfiguriert.","el":"Η ταυτοποίηση δεν έχει ρυθμιστεί πλήρως.","es":"La autenticación no está completamente configurada.","fr":"L'authentification n'est pas entièrement configurée.","hi":"प्रमाणीकरण पूरी तरह कॉन्फ़िगर नहीं किया गया है।","it":"L'autenticazione non è completamente configurata.","ja":"認証が完全に設定されていません。","nl":"Authenticatie is niet volledig geconfigureerd.","no":"Autentisering er ikke fullstendig konfigurert.","pl":"Uwierzytelnianie nie jest w pełni skonfigurowane.","pt":"A autenticação não está totalmente configurada.","sv":"Autentisering är inte fullständigt konfigurerad.","zh":"身份验证未完全配置。"},
    "Server error": {"cs":"Chyba serveru","da":"Serverfejl","de":"Serverfehler","el":"Σφάλμα διακομιστή","es":"Error del servidor","fr":"Erreur serveur","hi":"सर्वर त्रुटि","it":"Errore del server","ja":"サーバーエラー","nl":"Serverfout","no":"Serverfeil","pl":"Błąd serwera","pt":"Erro do servidor","sv":"Serverfel","zh":"服务器错误"},
    "Stopped by user.": {"cs":"Zastaveno uživatelem.","da":"Stoppet af bruger.","de":"Vom Benutzer gestoppt.","el":"Διακόπηκε από τον χρήστη.","es":"Detenido por el usuario.","fr":"Arrêté par l'utilisateur.","hi":"उपयोगकर्ता द्वारा रोका गया।","it":"Interrotto dall'utente.","ja":"ユーザーにより停止しました。","nl":"Gestopt door gebruiker.","no":"Stoppet av bruker.","pl":"Zatrzymane przez użytkownika.","pt":"Parado pelo usuário.","sv":"Stoppad av användare.","zh":"被用户停止。"},
    "Recording error occurred.": {"cs":"Došlo k chybě při nahrávání.","da":"Optagelsesfejl opstod.","de":"Aufnahmefehler aufgetreten.","el":"Προέκυψε σφάλμα εγγραφής.","es":"Se produjo un error de grabación.","fr":"Une erreur d'enregistrement s'est produite.","hi":"रिकॉर्डिंग त्रुटि हुई।","it":"Si è verificato un errore di registrazione.","ja":"録音エラーが発生しました。","nl":"Opnamefout opgetreden.","no":"Opptaksfeil oppstod.","pl":"Wystąpił błąd nagrywania.","pt":"Ocorreu um erro de gravação.","sv":"Inspelningsfel inträffade.","zh":"发生录音错误。"},
    "Empty batch": {"cs":"Prázdná dávka","da":"Tom batch","de":"Leerer Batch","el":"Κενή παρτίδα","es":"Lote vacío","fr":"Lot vide","hi":"रिक्त बैच","it":"Batch vuoto","ja":"空のバッチ","nl":"Lege batch","no":"Tom batch","pl":"Pusta partia","pt":"Lote vazio","sv":"Tom batch","zh":"空批次"},
    "Invalid personality name": {"cs":"Neplatný název osobnosti","da":"Ugyldigt personlighedsnavn","de":"Ungültiger Persönlichkeitsname","el":"Μη έγκυρο όνομα προσωπικότητας","es":"Nombre de personalidad no válido","fr":"Nom de personnalité invalide","hi":"अमान्य व्यक्तित्व नाम","it":"Nome personalità non valido","ja":"無効なパーソナリティ名","nl":"Ongeldig persoonlijkheidsnaam","no":"Ugyldig personlighetsnavn","pl":"Nieprawidłowa nazwa osobowości","pt":"Nome de personalidade inválido","sv":"Ogiltigt personlighetsnamn","zh":"无效的人格名称"},
    "Invalid audio format": {"cs":"Neplatný formát zvuku","da":"Ugyldigt lydformat","de":"Ungültiges Audioformat","el":"Μη έγκυρη μορφή ήχου","es":"Formato de audio no válido","fr":"Format audio invalide","hi":"अमान्य ऑडियो प्रारूप","it":"Formato audio non valido","ja":"無効なオーディオ形式","nl":"Ongeldig audioformaat","no":"Ugyldig lydformat","pl":"Nieprawidłowy format audio","pt":"Formato de áudio inválido","sv":"Ogiltigt ljudformat","zh":"无效的音频格式"},
    "Contacts database not initialized": {"cs":"Databáze kontaktů není inicializována","da":"Kontaktdatabase ikke initialiseret","de":"Kontaktdatenbank nicht initialisiert","el":"Η βάση δεδομένων επαφών δεν έχει αρχικοποιηθεί","es":"Base de datos de contactos no inicializada","fr":"Base de données de contacts non initialisée","hi":"संपर्क डेटाबेस प्रारंभ नहीं किया गया","it":"Database contatti non inizializzato","ja":"連絡先データベースが初期化されていません","nl":"Contactendatabase niet geïnitialiseerd","no":"Kontaktdatabase ikke initialisert","pl":"Baza kontaktów niezainicjalizowana","pt":"Banco de dados de contatos não inicializado","sv":"Kontaktdatabas inte initierad","zh":"联系人数据库未初始化"},
    "Missing file upload": {"cs":"Chybí nahrání souboru","da":"Manglende filupload","de":"Datei-Upload fehlt","el":"Λείπει η μεταφόρτωση αρχείου","es":"Falta la carga del archivo","fr":"Téléchargement de fichier manquant","hi":"फ़ाइल अपलोड गायब","it":"Caricamento file mancante","ja":"ファイルアップロードがありません","nl":"Bestandsupload ontbreekt","no":"Mangler filopplasting","pl":"Brak przesyłania pliku","pt":"Upload de arquivo ausente","sv":"Filuppladdning saknas","zh":"缺少文件上传"},
    "Login template not available": {"cs":"Přihlašovací šablona není k dispozici","da":"Login-skabelon ikke tilgængelig","de":"Login-Vorlage nicht verfügbar","el":"Το πρότυπο σύνδεσης δεν είναι διαθέσιμο","es":"Plantilla de inicio de sesión no disponible","fr":"Modèle de connexion non disponible","hi":"लॉगिन टेम्पलेट उपलब्ध नहीं","it":"Modello di login non disponibile","ja":"ログインテンプレートは利用できません","nl":"Loginsjabloon niet beschikbaar","no":"Innloggingmal ikke tilgjengelig","pl":"Szablon logowania niedostępny","pt":"Modelo de login indisponível","sv":"Inloggningsmall inte tillgänglig","zh":"登录模板不可用"},
    "Model is required": {"cs":"Model je vyžadován","da":"Model er påkrævet","de":"Modell ist erforderlich","el":"Το μοντέλο απαιτείται","es":"El modelo es obligatorio","fr":"Le modèle est requis","hi":"मॉडल आवश्यक है","it":"Il modello è obbligatorio","ja":"モデルは必須です","nl":"Model is vereist","no":"Modell kreves","pl":"Model jest wymagany","pt":"O modelo é obrigatório","sv":"Modell krävs","zh":"模型为必填项"},
    "Not authorized — click Authorize": {"cs":"Neautorizováno — klikněte na Autorizovat","da":"Ikke autoriseret — klik på Autoriser","de":"Nicht autorisiert — auf Autorisieren klicken","el":"Μη εξουσιοδοτημένος — κάντε κλικ στο Εξουσιοδότηση","es":"No autorizado — haga clic en Autorizar","fr":"Non autorisé — cliquez sur Autoriser","hi":"अधिकृत नहीं — अधिकृत करें पर क्लिक करें","it":"Non autorizzato — clicca su Autorizza","ja":"認証されていません — 認証をクリックしてください","nl":"Niet geautoriseerd — klik op Autoriseren","no":"Ikke autorisert — klikk Autoriser","pl":"Nie autoryzowano — kliknij Autoryzuj","pt":"Não autorizado — clique em Autorizar","sv":"Ej behörig — klicka på Auktorisera","zh":"未授权 — 点击授权"},
    "Provider is not OpenRouter": {"cs":"Poskytovatel není OpenRouter","da":"Udbyder er ikke OpenRouter","de":"Provider ist nicht OpenRouter","el":"Ο πάροχος δεν είναι OpenRouter","es":"El proveedor no es OpenRouter","fr":"Le fournisseur n'est pas OpenRouter","hi":"प्रदाता OpenRouter नहीं है","it":"Il provider non è OpenRouter","ja":"プロバイダーはOpenRouterではありません","nl":"Provider is niet OpenRouter","no":"Tilbyder er ikke OpenRouter","pl":"Dostawca to nie OpenRouter","pt":"O provedor não é o OpenRouter","sv":"Leverantören är inte OpenRouter","zh":"提供商不是 OpenRouter"},
    "A file with that name already exists": {"cs":"Soubor s tímto názvem již existuje","da":"En fil med det navn findes allerede","de":"Eine Datei mit diesem Namen existiert bereits","el":"Ένα αρχείο με αυτό το όνομα υπάρχει ήδη","es":"Ya existe un archivo con ese nombre","fr":"Un fichier avec ce nom existe déjà","hi":"इस नाम की फ़ाइल पहले से मौजूद है","it":"Un file con quel nome esiste già","ja":"その名前のファイルは既に存在します","nl":"Een bestand met die naam bestaat al","no":"En fil med det navnet finnes allerede","pl":"Plik o tej nazwie już istnieje","pt":"Um arquivo com esse nome já existe","sv":"En fil med det namnet finns redan","zh":"同名文件已存在"},
    "An internal error occurred. Check server logs for details.": {"cs":"Došlo k interní chybě. Zkontrolujte protokoly serveru.","da":"Der opstod en intern fejl. Tjek serverlogfiler for detaljer.","de":"Ein interner Fehler ist aufgetreten. Server-Logs für Details prüfen.","el":"Προέκυψε εσωτερικό σφάλμα. Ελέγξτε τα αρχεία καταγραφής.","es":"Ocurrió un error interno. Revise los registros del servidor.","fr":"Une erreur interne s'est produite. Consultez les journaux.","hi":"आंतरिक त्रुटि हुई। विवरण के लिए सर्वर लॉग जांचें।","it":"Si è verificato un errore interno. Controllare i log del server.","ja":"内部エラーが発生しました。詳細はサーバーログを確認してください。","nl":"Er is een interne fout opgetreden. Controleer de serverlogs.","no":"Det oppstod en intern feil. Sjekk serverloggene for detaljer.","pl":"Wystąpił błąd wewnętrzny. Sprawdź logi serwera.","pt":"Ocorreu um erro interno. Verifique os logs do servidor.","sv":"Ett internt fel uppstod. Kontrollera serverloggarna.","zh":"发生内部错误。请查看服务器日志了解详情。"},
    "Agent interrupted. It will stop after the current step.": {"cs":"Agent přerušen. Zastaví se po aktuálním kroku.","da":"Agent afbrudt. Den stopper efter det nuværende trin.","de":"Agent unterbrochen. Er stoppt nach dem aktuellen Schritt.","el":"Ο πράκτορας διακόπηκε. Θα σταματήσει μετά το τρέχον βήμα.","es":"Agente interrumpido. Se detendrá después del paso actual.","fr":"Agent interrompu. Il s'arrêtera après l'étape actuelle.","hi":"एजेंट बाधित। वर्तमान चरण के बाद रुकेगा।","it":"Agente interrotto. Si fermerà dopo il passo corrente.","ja":"エージェントが中断されました。現在のステップ後に停止します。","nl":"Agent onderbroken. Stopt na de huidige stap.","no":"Agent avbrutt. Stopper etter gjeldende trinn.","pl":"Agent przerwany. Zatrzyma się po bieżącym kroku.","pt":"Agente interrompido. Parará após o passo atual.","sv":"Agent avbruten. Stoppar efter aktuellt steg.","zh":"代理已中断。将在当前步骤后停止。"},
    "Agent loop exceeded maximum iterations ({0}). Please restart.": {"cs":"Smyčka agenta překročila maximální iterace ({0}). Restartujte prosím.","da":"Agent-løkken overskred maksimale iterationer ({0}). Genstart venligst.","de":"Agent-Schleife hat maximale Iterationen überschritten ({0}). Bitte neustarten.","el":"Ο βρόχος πράκτορα ξεπέρασε τις μέγιστες επαναλήψεις ({0}). Επανεκκινήστε.","es":"El bucle del agente excedió las iteraciones máximas ({0}). Reinicie.","fr":"La boucle de l'agent a dépassé les itérations maximales ({0}). Redémarrez.","hi":"एजेंट लूप ने अधिकतम पुनरावृत्तियाँ ({0}) पार कर लीं। कृपया पुनः आरंभ करें।","it":"Il ciclo dell'agente ha superato le iterazioni massime ({0}). Riavviare.","ja":"エージェントループが最大反復回数({0})を超えました。再起動してください。","nl":"Agent-lus overschreed maximale iteraties ({0}). Herstart alstublieft.","no":"Agent-sløyfe overskred maksimale iterasjoner ({0}). Vennligst start på nytt.","pl":"Pętla agenta przekroczyła maksymalne iteracje ({0}). Uruchom ponownie.","pt":"O loop do agente excedeu iterações máximas ({0}). Reinicie.","sv":"Agent-loop överskred maximala iterationer ({0}). Starta om.","zh":"代理循环超过最大迭代次数 ({0})。请重启。"},
    "Follow-up circuit breaker tripped. Max recursion depth reached.": {"cs":"Jistič následných akcí spuštěn. Dosaženo maximální hloubky rekurze.","da":"Follow-up strømbryser udløst. Maksimal rekursionsdybde nået.","de":"Follow-up-Schutzschalter ausgelöst. Maximale Rekursionstiefe erreicht.","el":"Ο διακόπτης follow-back ενεργοποιήθηκε. Μέγιστο βάθος αναδρομής.","es":"Disyuntor de seguimiento activado. Profundidad máxima de recursión.","fr":"Disjoncteur de suivi déclenché. Profondeur de récursion maximale atteinte.","hi":"फॉलो-अप सर्किट ब्रेकर ट्रिगर हुआ। अधिकतम पुनरावर्तन गहराई।","it":"Interruttore di follow-up attivato. Profondità ricorsione massima.","ja":"フォローアップサーキットブレーカーが作動。最大再帰深度に達しました。","nl":"Follow-up stroomonderbreker geactiveerd. Maximale recursiediepte bereikt.","no":"Follow-up strømbryser utløst. Maksimal rekursjonsdybde nådd.","pl":"Bezpiecznik follow-up zadziałał. Maksymalna głębokość rekurencji.","pt":"Disjuntor de acompanhamento ativado. Profundidade máxima de recursão.","sv":"Follow-up strömbrytare utlöst. Maximalt rekursionsdjup nått.","zh":"后续断路器跳闸。已达到最大递归深度。"},
    "Announcement without action detected, requesting tool call...": {"cs":"Oznámení bez akce zjištěno, vyžaduje se volání nástroje...","da":"Meddelelse uden handling registreret, anmoder om værktøjskald...","de":"Ankündigung ohne Aktion erkannt, Tool-Aufruf wird angefordert...","el":"Ανακοίνωση χωρίς ενέργεια εντοπίστηκε, ζητείται κλήση εργαλείου...","es":"Anuncio sin acción detectado, solicitando llamada de herramienta...","fr":"Annonce sans action détectée, appel d'outil demandé...","hi":"कार्रवाई के बिना घोषणा पाई गई, टूल कॉल का अनुरोध किया जा रहा है...","it":"Annuncio senza azione rilevato, richiesta chiamata strumento...","ja":"アクションのないアナウンスを検出、ツール呼び出しを要求中...","nl":"Aankondiging zonder actie gedetecteerd, tool-aanroep aangevraagd...","no":"Kunngjøring uten handling oppdaget, ber om verktøykall...","pl":"Ogłoszenie bez działania wykryte, żądanie wywołania narzędzia...","pt":"Anúncio sem ação detectado, solicitando chamada de ferramenta...","sv":"Meddelande utan åtgärd upptäckt, begär verktygsanrop...","zh":"检测到无操作公告，正在请求工具调用..."},
    "Compressing context...": {"cs":"Komprimace kontextu...","da":"Komprimerer kontekst...","de":"Komprimiere Kontext...","el":"Συμπίεση πλαισίου...","es":"Comprimiendo contexto...","fr":"Compression du contexte...","hi":"संदर्भ संपीड़न हो रहा है...","it":"Compressione contesto...","ja":"コンテキストを圧縮中...","nl":"Context comprimeren...","no":"Komprimerer kontekst...","pl":"Kompresja kontekstu...","pt":"Comprimindo contexto...","sv":"Komprimerar kontext...","zh":"正在压缩上下文..."},
    "Authenticator activated.": {"cs":"Autentifikátor aktivován.","da":"Autentifikator aktiveret.","de":"Authenticator aktiviert.","el":"Ο ταυτοποιητής ενεργοποιήθηκε.","es":"Autenticador activado.","fr":"Authentificateur activé.","hi":"प्रमाणक सक्रिय किया गया।","it":"Autenticatore attivato.","ja":"オーセンティケーターが有効化されました。","nl":"Authenticator geactiveerd.","no":"Autentikator aktivert.","pl":"Autentykator aktywowany.","pt":"Autenticador ativado.","sv":"Autentiserare aktiverad.","zh":"认证器已激活。"},
    "Authenticator deactivated.": {"cs":"Autentifikátor deaktivován.","da":"Autentifikator deaktiveret.","de":"Authenticator deaktiviert.","el":"Ο ταυτοποιητής απενεργοποιήθηκε.","es":"Autenticador desactivado.","fr":"Authentificateur désactivé.","hi":"प्रमाणक निष्क्रिय किया गया।","it":"Autenticatore disattivato.","ja":"オーセンティケーターが無効化されました。","nl":"Authenticator gedeactiveerd.","no":"Autentikator deaktivert.","pl":"Autentykator dezaktywowany.","pt":"Autenticador desativado.","sv":"Autentiserare inaktiverad.","zh":"认证器已停用。"},
    "Sudo password has been removed from the vault.": {"cs":"Sudo heslo bylo odebráno z trezoru.","da":"Sudo-adgangskode er fjernet fra boksen.","de":"Sudo-Passwort wurde aus dem Vault entfernt.","el":"Ο κωδικός sudo αφαιρέθηκε από το θησαυροφυλάκιο.","es":"La contraseña de sudo ha sido eliminada de la bóveda.","fr":"Le mot de passe sudo a été supprimé du coffre.","hi":"सुडो पासवर्ड वॉल्ट से हटा दिया गया है।","it":"La password sudo è stata rimossa dal vault.","ja":"sudoパスワードがボールトから削除されました。","nl":"Sudo-wachtwoord verwijderd uit de kluis.","no":"Sudo-passord fjernet fra hvelvet.","pl":"Hasło sudo zostało usunięte z sejfu.","pt":"A senha sudo foi removida do cofre.","sv":"Sudo-lösenord har tagits bort från valvet.","zh":"Sudo 密码已从保管库中移除。"},
    "Bad request": {"cs":"Neplatný požadavek","da":"Ugyldig anmodning","de":"Ungültige Anfrage","el":"Εσφαλμένο αίτημα","es":"Solicitud incorrecta","fr":"Mauvaise requête","hi":"गलत अनुरोध","it":"Richiesta non valida","ja":"不正なリクエスト","nl":"Ongeldig verzoek","no":"Ugyldig forespørsel","pl":"Nieprawidłowe żądanie","pt":"Requisição inválida","sv":"Ogiltig förfrågan","zh":"错误的请求"},
    "Method not allowed": {"cs":"Metoda není povolena","da":"Metode ikke tilladt","de":"Methode nicht erlaubt","el":"Η μέθοδος δεν επιτρέπεται","es":"Método no permitido","fr":"Méthode non autorisée","hi":"विधि अनुमत नहीं","it":"Metodo non consentito","ja":"メソッドは許可されていません","nl":"Methode niet toegestaan","no":"Metode ikke tillatt","pl":"Metoda niedozwolona","pt":"Método não permitido","sv":"Metod inte tillåten","zh":"方法不允许"},
    "Advanced editor unavailable, using plain text mode.": {"cs":"Pokročilý editor nedostupný, používám režim prostého textu.","da":"Avanceret editor ikke tilgængelig, bruger ren tekst-tilstand.","de":"Erweiterter Editor nicht verfügbar, verwende Nur-Text-Modus.","el":"Ο προχωρημένος επεξεργαστής δεν είναι διαθέσιμος, χρήση λειτουργίας απλού κειμένου.","es":"Editor avanzado no disponible, usando modo de texto plano.","fr":"Éditeur avancé indisponible, mode texte brut.","hi":"उन्नत संपादक अनुपलब्ध, सादा पाठ मोड उपयोग कर रहा है।","it":"Editor avanzato non disponibile, uso modalità testo semplice.","ja":"高度なエディタは利用できません。プレーンテキストモードを使用します。","nl":"Geavanceerde editor niet beschikbaar, platte-tekstmodus gebruikt.","no":"Avansert editor ikke tilgjengelig, bruker ren tekst-modus.","pl":"Zaawansowany edytor niedostępny, używam trybu zwykłego tekstu.","pt":"Editor avançado indisponível, usando modo de texto simples.","sv":"Avancerad redigerare inte tillgänglig, använder oformaterad text.","zh":"高级编辑器不可用，使用纯文本模式。"},
    "All uploads complete": {"cs":"Všechna nahrávání dokončena","da":"Alle uploads fuldført","de":"Alle Uploads abgeschlossen","el":"Όλες οι μεταφορτώσεις ολοκληρώθηκαν","es":"Todas las cargas completadas","fr":"Tous les téléchargements terminés","hi":"सभी अपलोड पूरे हुए","it":"Tutti i caricamenti completati","ja":"すべてのアップロードが完了","nl":"Alle uploads voltooid","no":"Alle opplastinger fullført","pl":"Wszystkie przesyłania zakończone","pt":"Todos os uploads concluídos","sv":"Alla uppladdningar slutförda","zh":"所有上传已完成"},
    "AI Draft": {"cs":"AI návrh","da":"AI-kladde","de":"KI-Entwurf","el":"Πρόχειρο AI","es":"Borrador de IA","fr":"Brouillon IA","hi":"AI ड्राफ्ट","it":"Bozza IA","ja":"AI下書き","nl":"AI-concept","no":"AI-utkast","pl":"Szkic AI","pt":"Rascunho IA","sv":"AI-utkast","zh":"AI 草稿"},
    "Active Overrides": {"cs":"Aktivní přepisy","da":"Aktive tilsidesættelser","de":"Aktive Überschreibungen","el":"Ενεργές παρακάμψεις","es":"Anulaciones activas","fr":"Remplacements actifs","hi":"सक्रिय ओवरराइड","it":"Sovrascritture attive","ja":"アクティブなオーバーライド","nl":"Actieve overschrijvingen","no":"Aktive overstyringer","pl":"Aktywne nadpisania","pt":"Substituições ativas","sv":"Aktiva åsidosättningar","zh":"活动覆盖"},
    "Audit Trail": {"cs":"Auditní stopa","da":"Revisionslog","de":"Audit-Trail","el":"Ίχνος ελέγχου","es":"Pista de auditoría","fr":"Journal d'audit","hi":"ऑडिट ट्रेल","it":"Registro audit","ja":"監査証跡","nl":"Audittrail","no":"Revisjonsspor","pl":"Ścieżka audytu","pt":"Trilha de auditoria","sv":"Granskningsspår","zh":"审计追踪"},
    "Accept self-signed certificates (insecure)": {"cs":"Přijmout self-signed certifikáty (nezabezpečené)","da":"Accepter selvsignerede certifikater (usikker)","de":"Selbstsignierte Zertifikate akzeptieren (unsicher)","el":"Αποδοχή αυτο-υπογεγραμμένων πιστοποιητικών (μη ασφαλές)","es":"Aceptar certificados autofirmados (inseguro)","fr":"Accepter les certificats auto-signés (non sécurisé)","hi":"स्व-हस्ताक्षरित प्रमाणपत्र स्वीकारें (असुरक्षित)","it":"Accetta certificati self-signed (non sicuro)","ja":"自己署名証明書を許可（安全ではない）","nl":"Zelfondertekende certificaten accepteren (onveilig)","no":"Godta selvsignerte sertifikater (usikkert)","pl":"Akceptuj certyfikaty self-signed (niezabezpieczone)","pt":"Aceitar certificados autoassinados (inseguro)","sv":"Acceptera självsignerade certifikat (osäkert)","zh":"接受自签名证书（不安全）"},
    "OAuth2 Authorization Code": {"cs":"OAuth2 autorizační kód","da":"OAuth2 autorisationskode","de":"OAuth2-Autorisierungscode","el":"Κωδικός εξουσιοδότησης OAuth2","es":"Código de autorización OAuth2","fr":"Code d'autorisation OAuth2","hi":"OAuth2 प्राधिकरण कोड","it":"Codice di autorizzazione OAuth2","ja":"OAuth2認証コード","nl":"OAuth2-autorisatiecode","no":"OAuth2-autorisasjonskode","pl":"Kod autoryzacji OAuth2","pt":"Código de autorização OAuth2","sv":"OAuth2-auktoriseringskod","zh":"OAuth2 授权码"},
    "API Key": {"cs":"API klíč","da":"API-nøgle","de":"API-Schlüssel","el":"Κλειδί API","es":"Clave API","fr":"Clé API","hi":"API कुंजी","it":"Chiave API","ja":"APIキー","nl":"API-sleutel","no":"API-nøkkel","pl":"Klucz API","pt":"Chave API","sv":"API-nyckel","zh":"API 密钥"},
    "Authorization URL": {"cs":"Autorizační URL","da":"Autorisations-URL","de":"Autorisierungs-URL","el":"URL εξουσιοδότησης","es":"URL de autorización","fr":"URL d'autorisation","hi":"प्राधिकरण URL","it":"URL di autorizzazione","ja":"認証URL","nl":"Autorisatie-URL","no":"Autorisasjons-URL","pl":"URL autoryzacji","pt":"URL de autorização","sv":"Auktoriserings-URL","zh":"授权 URL"},
    "Client ID": {"cs":"ID klienta","da":"Klient-ID","de":"Client-ID","el":"ID πελάτη","es":"ID de cliente","fr":"ID client","hi":"क्लाइंट ID","it":"ID client","ja":"クライアントID","nl":"Client-ID","no":"Klient-ID","pl":"ID klienta","pt":"ID do cliente","sv":"Klient-ID","zh":"客户端 ID"},
    "Client Secret": {"cs":"Tajný klíč klienta","da":"Klient-hemmelighed","de":"Client-Geheimnis","el":"Μυστικό πελάτη","es":"Secreto de cliente","fr":"Secret client","hi":"क्लाइंट रहस्य","it":"Segreto client","ja":"クライアントシークレット","nl":"Client-geheim","no":"Klient-hemmelighet","pl":"Sekret klienta","pt":"Segredo do cliente","sv":"Klient-hemlighet","zh":"客户端密钥"},
    "Scopes": {"cs":"Rozsahy","da":"Scopes","de":"Bereiche","el":"Εμβέλειες","es":"Ámbitos","fr":"Portées","hi":"स्कोप","it":"Ambiti","ja":"スコープ","nl":"Scopes","no":"Omfang","pl":"Zakresy","pt":"Escopos","sv":"Omfattningar","zh":"范围"},
    "Token URL": {"cs":"Token URL","da":"Token-URL","de":"Token-URL","el":"URL διακριτικού","es":"URL del token","fr":"URL du jeton","hi":"टोकन URL","it":"URL token","ja":"トークンURL","nl":"Token-URL","no":"Token-URL","pl":"URL tokena","pt":"URL do token","sv":"Token-URL","zh":"令牌 URL"},
    "Base URL": {"cs":"Základní URL","da":"Basis-URL","de":"Basis-URL","el":"Βασικό URL","es":"URL base","fr":"URL de base","hi":"बेस URL","it":"URL base","ja":"ベースURL","nl":"Basis-URL","no":"Basis-URL","pl":"Bazowy URL","pt":"URL base","sv":"Bas-URL","zh":"基础 URL"},
    "Authorize": {"cs":"Autorizovat","da":"Autoriser","de":"Autorisieren","el":"Εξουσιοδότηση","es":"Autorizar","fr":"Autoriser","hi":"अधिकृत करें","it":"Autorizza","ja":"認証","nl":"Autoriseren","no":"Autoriser","pl":"Autoryzuj","pt":"Autorizar","sv":"Auktorisera","zh":"授权"},
    "Authorized": {"cs":"Autorizováno","da":"Autoriseret","de":"Autorisiert","el":"Εξουσιοδοτημένος","es":"Autorizado","fr":"Autorisé","hi":"अधिकृत","it":"Autorizzato","ja":"認証済み","nl":"Geautoriseerd","no":"Autorisert","pl":"Autoryzowany","pt":"Autorizado","sv":"Auktoriserad","zh":"已授权"},
    "Authentication": {"cs":"Autentizace","da":"Autentificering","de":"Authentifizierung","el":"Ταυτοποίηση","es":"Autenticación","fr":"Authentification","hi":"प्रमाणीकरण","it":"Autenticazione","ja":"認証","nl":"Authenticatie","no":"Autentisering","pl":"Uwierzytelnianie","pt":"Autenticação","sv":"Autentisering","zh":"身份验证"},
    "Leave empty to keep existing secret.": {"cs":"Ponechte prázdné pro zachování stávajícího tajemství.","da":"Efterlad tom for at beholde eksisterende hemmelighed.","de":"Leer lassen, um das bestehende Geheimnis zu behalten.","el":"Αφήστε κενό για να κρατήσετε το υπάρχον μυστικό.","es":"Dejar vacío para mantener el secreto existente.","fr":"Laisser vide pour conserver le secret existant.","hi":"मौजूदा रहस्य रखने के लिए खाली छोड़ें।","it":"Lasciare vuoto per mantenere il segreto esistente.","ja":"既存のシークレットを保持するには空のままにします。","nl":"Laat leeg om het bestaande geheim te behouden.","no":"La stå tomt for å beholde eksisterende hemmelighet.","pl":"Zostaw puste, aby zachować istniejący sekret.","pt":"Deixe vazio para manter o segredo existente.","sv":"Lämna tomt för att behålla befintlig hemlighet.","zh":"留空以保留现有密钥。"},
    "Leave empty to keep the existing key.": {"cs":"Ponechte prázdné pro zachování stávajícího klíče.","da":"Efterlad tom for at beholde den eksisterende nøgle.","de":"Leer lassen, um den bestehenden Schlüssel zu behalten.","el":"Αφήστε κενό για να κρατήσετε το υπάρχον κλειδί.","es":"Dejar vacío para mantener la clave existente.","fr":"Laisser vide pour conserver la clé existante.","hi":"मौजूदा कुंजी रखने के लिए खाली छोड़ें।","it":"Lasciare vuoto per mantenere la chiave esistente.","ja":"既存のキーを保持するには空のままにします。","nl":"Laat leeg om de bestaande sleutel te behouden.","no":"La stå tomt for å beholde eksisterende nøkkel.","pl":"Zostaw puste, aby zachować istniejący klucz.","pt":"Deixe vazio para manter a chave existente.","sv":"Lämna tomt för att behålla befintlig nyckel.","zh":"留空以保留现有密钥。"},
    "Open Model Browser": {"cs":"Otevřít prohlížeč modelů","da":"Åbn modelbrowser","de":"Modell-Browser öffnen","el":"Άνοιγμα περιηγητή μοντέλων","es":"Abrir navegador de modelos","fr":"Ouvrir le navigateur de modèles","hi":"मॉडल ब्राउज़र खोलें","it":"Apri browser modelli","ja":"モデルブラウザを開く","nl":"Modelbrowser openen","no":"Åpne modellutforsker","pl":"Otwórz przeglądarkę modeli","pt":"Abrir navegador de modelos","sv":"Öppna modellbläddrare","zh":"打开模型浏览器"},
    "Available models (click to apply):": {"cs":"Dostupné modely (klikněte pro použití):","da":"Tilgængelige modeller (klik for at anvende):","de":"Verfügbare Modelle (klicken zum Anwenden):","el":"Διαθέσιμα μοντέλα (κλικ για εφαρμογή):","es":"Modelos disponibles (clic para aplicar):","fr":"Modèles disponibles (cliquer pour appliquer) :","hi":"उपलब्ध मॉडल (लागू करने के लिए क्लिक करें):","it":"Modelli disponibili (clicca per applicare):","ja":"利用可能なモデル（クリックして適用）:","nl":"Beschikbare modellen (klik om toe te passen):","no":"Tilgjengelige modeller (klikk for å bruke):","pl":"Dostępne modele (kliknij, aby zastosować):","pt":"Modelos disponíveis (clique para aplicar):","sv":"Tillgängliga modeller (klicka för att använda):","zh":"可用模型（点击应用）："},
    "Automatically set based on the provider.": {"cs":"Automaticky nastaveno na základě poskytovatele.","da":"Automatisk indstillet baseret på udbyderen.","de":"Automatisch basierend auf dem Provider gesetzt.","el":"Αυτόματα ρυθμισμένο με βάση τον πάροχο.","es":"Configurado automáticamente según el proveedor.","fr":"Défini automatiquement selon le fournisseur.","hi":"प्रदाता के आधार पर स्वचालित रूप से सेट।","it":"Impostato automaticamente in base al provider.","ja":"プロバイダーに基づいて自動設定されます。","nl":"Automatisch ingesteld op basis van de provider.","no":"Automatisk satt basert på tilbyderen.","pl":"Ustawione automatycznie na podstawie dostawcy.","pt":"Definido automaticamente com base no provedor.","sv":"Automatiskt inställt baserat på leverantören.","zh":"根据提供商自动设置。"},
    "ID must not be empty.": {"cs":"ID nesmí být prázdné.","da":"ID må ikke være tomt.","de":"ID darf nicht leer sein.","el":"Το ID δεν πρέπει να είναι κενό.","es":"El ID no debe estar vacío.","fr":"L'ID ne doit pas être vide.","hi":"ID खाली नहीं होना चाहिए।","it":"L'ID non deve essere vuoto.","ja":"IDは空にできません。","nl":"ID mag niet leeg zijn.","no":"ID kan ikke være tom.","pl":"ID nie może być puste.","pt":"O ID não pode estar vazio.","sv":"ID får inte vara tomt.","zh":"ID 不能为空。"},
    "A provider with this ID already exists.": {"cs":"Poskytovatel s tímto ID již existuje.","da":"En udbyder med dette ID findes allerede.","de":"Ein Provider mit dieser ID existiert bereits.","el":"Ένας πάροχος με αυτό το ID υπάρχει ήδη.","es":"Ya existe un proveedor con este ID.","fr":"Un fournisseur avec cet ID existe déjà.","hi":"इस ID वाला प्रदाता पहले से मौजूद है।","it":"Un provider con questo ID esiste già.","ja":"このIDのプロバイダーは既に存在します。","nl":"Een provider met dit ID bestaat al.","no":"En tilbyder med denne ID finnes allerede.","pl":"Dostawca z tym ID już istnieje.","pt":"Um provedor com este ID já existe.","sv":"En leverantör med detta ID finns redan.","zh":"具有此 ID 的提供商已存在。"},
    "OAuth2: Auth URL, Token URL and Client ID are required.": {"cs":"OAuth2: Auth URL, Token URL a Client ID jsou vyžadovány.","da":"OAuth2: Auth URL, Token URL og Client ID er påkrævede.","de":"OAuth2: Auth-URL, Token-URL und Client-ID sind erforderlich.","el":"OAuth2: URL εξουσιοδότησης, URL διακριτικού και ID πελάτη απαιτούνται.","es":"OAuth2: URL de autenticación, URL del token y ID de cliente son obligatorios.","fr":"OAuth2 : URL d'authentification, URL du jeton et ID client sont requis.","hi":"OAuth2: Auth URL, Token URL और Client ID आवश्यक हैं।","it":"OAuth2: URL auth, URL token e ID client sono obbligatori.","ja":"OAuth2: 認証URL、トークンURL、クライアントIDは必須です。","nl":"OAuth2: Auth-URL, Token-URL en Client-ID zijn vereist.","no":"OAuth2: Auth-URL, Token-URL og Klient-ID kreves.","pl":"OAuth2: URL auth, URL token i ID klienta są wymagane.","pt":"OAuth2: URL de autenticação, URL do token e ID do cliente são obrigatórios.","sv":"OAuth2: Auth-URL, Token-URL och Klient-ID krävs.","zh":"OAuth2：认证 URL、令牌 URL 和客户端 ID 为必填项。"},
}


def read_json(path):
    try:
        with open(path, "r", encoding="utf-8-sig") as f:
            return json.load(f), None
    except Exception as e:
        return None, str(e)


def write_json(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")


def fix_translations():
    stats = defaultdict(lambda: {"fixed": 0, "errors": 0})
    dirs = []
    for root, _, files in os.walk(LANG_DIR):
        if "en.json" in files:
            dirs.append(Path(root))

    for directory in sorted(dirs):
        en_path = directory / "en.json"
        en_data, err = read_json(en_path)
        if err:
            continue

        for lang in NON_EN_LANGS:
            lang_path = directory / f"{lang}.json"
            if not lang_path.exists():
                continue

            lang_data, err = read_json(lang_path)
            if err:
                stats[lang]["errors"] += 1
                continue

            modified = False
            for key, en_value in en_data.items():
                if key not in lang_data:
                    continue
                lang_value = str(lang_data[key]).strip()
                en_value_str = str(en_value).strip()
                if lang_value.lower() != en_value_str.lower():
                    continue
                if not en_value_str:
                    continue

                if en_value_str in COMMON_TERMS:
                    trans = COMMON_TERMS[en_value_str].get(lang)
                    if trans:
                        lang_data[key] = trans
                        modified = True
                        stats[lang]["fixed"] += 1

            if modified:
                write_json(lang_path, lang_data)

    print("\n=== Translation Fix Summary ===")
    total_fixed = 0
    for lang in NON_EN_LANGS:
        s = stats[lang]
        if s["fixed"] > 0 or s["errors"] > 0:
            print(f"  {lang}: {s['fixed']} fixed, {s['errors']} errors")
            total_fixed += s["fixed"]
    print(f"\nTotal keys fixed: {total_fixed}")


if __name__ == "__main__":
    fix_translations()
