#!/usr/bin/env python3
"""Batch 16: Priority 1 user-facing UI labels - must translate."""
import json, os
from pathlib import Path
from collections import defaultdict

LANG_DIR = Path("ui/lang")
LANGS = ["cs","da","de","el","es","fr","hi","it","ja","nl","no","pl","pt","sv","zh"]

T = {
    "Online": {"cs":"Online","da":"Online","de":"Online","el":"Σε σύνδεση","es":"En línea","fr":"En ligne","hi":"ऑनलाइन","it":"Online","ja":"オンライン","nl":"Online","no":"Online","pl":"Online","pt":"Online","sv":"Online","zh":"在线"},
    "Offline": {"cs":"Offline","da":"Offline","de":"Offline","el":"Εκτός σύνδεσης","es":"Sin conexión","fr":"Hors ligne","hi":"ऑफ़लाइन","it":"Offline","ja":"オフライン","nl":"Offline","no":"Offline","pl":"Offline","pt":"Offline","sv":"Offline","zh":"离线"},
    "Pools": {"cs":"Pooly","da":"Pools","de":"Pools","el":"Ομάδες","es":"Grupos","fr":"Pools","hi":"पूल","it":"Pool","ja":"プール","nl":"Pools","no":"Pooler","pl":"Pule","pt":"Pools","sv":"Pooler","zh":"存储池"},
    "Start Scrub": {"cs":"Spustit scrub","da":"Start scrub","de":"Scrub starten","el":"Έναρξη scrub","es":"Iniciar scrub","fr":"Démarrer scrub","hi":"Scrub शुरू करें","it":"Avvia scrub","ja":"スクラブ開始","nl":"Scrub starten","no":"Start scrub","pl":"Uruchom scrub","pt":"Iniciar scrub","sv":"Starta scrub","zh":"开始清理"},
    "Invasion Control": {"cs":"Invasion Control","da":"Invasion Control","de":"Invasion Control","el":"Invasion Control","es":"Control de Invasión","fr":"Contrôle d'Invasion","hi":"Invasion Control","it":"Invasion Control","ja":"Invasion Control","nl":"Invasion Control","no":"Invasion Control","pl":"Invasion Control","pt":"Controle de Invasão","sv":"Invasion Control","zh":"入侵控制"},
    "Preset": {"cs":"Předvolba","da":"Forudindstilling","de":"Voreinstellung","el":"Προεπιλογή","es":"Predeterminado","fr":"Préréglage","hi":"प्रीसेट","it":"Preset","ja":"プリセット","nl":"Voorinstelling","no":"Forhåndsinnstilling","pl":"Preset","pt":"Predefinição","sv":"Förinställning","zh":"预设"},
    "Free": {"cs":"Zdarma","da":"Gratis","de":"Kostenlos","el":"Δωρεάν","es":"Gratis","fr":"Gratuit","hi":"मुफ़्त","it":"Gratuito","ja":"無料","nl":"Gratis","no":"Gratis","pl":"Darmowy","pt":"Gratuito","sv":"Gratis","zh":"免费"},
    "Manual": {"cs":"Ruční","da":"Manuel","de":"Manuell","el":"Χειροκίνητο","es":"Manual","fr":"Manuel","hi":"मैनुअल","it":"Manuale","ja":"マニュアル","nl":"Handmatig","no":"Manuell","pl":"Ręczny","pt":"Manual","sv":"Manuell","zh":"手动"},
    "(all blocked when exceeded)": {"cs":"(vše blokováno při překročení)","da":"(alt blokeret ved overskridelse)","de":"(alles gesperrt bei Überschreitung)","el":"(όλα αποκλείονται όταν ξεπεραστούν)","es":"(todo bloqueado al exceder)","fr":"(tout bloqué en cas de dépassement)","hi":"(अधिक होने पर सब अवरुद्ध)","it":"(tutto bloccato al superamento)","ja":"(超過時すべてブロック)","nl":"(alles geblokkeerd bij overschrijding)","no":"(alt blokkert ved overskridelse)","pl":"(wszystko zablokowane po przekroczeniu)","pt":"(tudo bloqueado ao exceder)","sv":"(allt blockerat vid överskridande)","zh":"（超出时全部阻止）"},
    "(co-agents + vision/STT blocked when exceeded)": {"cs":"(co-agenti + vision/STT blokovány při překročení)","da":"(co-agenter + vision/STT blokeret ved overskridelse)","de":"(Co-Agents + Vision/STT gesperrt bei Überschreitung)","el":"(συν-πράκτορες + όραση/STT αποκλείονται)","es":"(co-agentes + visión/STT bloqueados al exceder)","fr":"(co-agents + vision/STT bloqués en cas de dépassement)","hi":"(co-एजेंट + विज़न/STT अधिक होने पर अवरुद्ध)","it":"(co-agenti + vision/STT bloccati al superamento)","ja":"(超過時、co-agent + vision/STT ブロック)","nl":"(co-agenten + vision/STT geblokkeerd bij overschrijding)","no":"(co-agenter + vision/STT blokkert ved overskridelse)","pl":"(co-agenty + vision/STT zablokowane po przekroczeniu)","pt":"(co-agentes + visão/STT bloqueados ao exceder)","sv":"(co-agenter + vision/STT blockerade vid överskridande)","zh":"（超出时 co-agent + 视觉/STT 被阻止）"},
    "(warning only)": {"cs":"(pouze varování)","da":"(kun advarsel)","de":"(nur Warnung)","el":"(μόνο προειδοποίηση)","es":"(solo advertencia)","fr":"(avertissement uniquement)","hi":"(केवल चेतावनी)","it":"(solo avviso)","ja":"(警告のみ)","nl":"(alleen waarschuwing)","no":"(kun advarsel)","pl":"(tylko ostrzeżenie)","pt":"(apenas aviso)","sv":"(endast varning)","zh":"（仅警告）"},
    "NS lookup: {0}": {"cs":"NS dotaz: {0}","da":"NS-opslag: {0}","de":"NS-Abfrage: {0}","el":"Αναζήτηση NS: {0}","es":"Búsqueda NS: {0}","fr":"Recherche NS : {0}","hi":"NS लुकअप: {0}","it":"Ricerca NS: {0}","ja":"NSルックアップ: {0}","nl":"NS-zoekactie: {0}","no":"NS-oppslag: {0}","pl":"Wyszukiwanie NS: {0}","pt":"Pesquisa NS: {0}","sv":"NS-uppslag: {0}","zh":"NS 查询：{0}"},
    "TXT lookup: {0}": {"cs":"TXT dotaz: {0}","da":"TXT-opslag: {0}","de":"TXT-Abfrage: {0}","el":"Αναζήτηση TXT: {0}","es":"Búsqueda TXT: {0}","fr":"Recherche TXT : {0}","hi":"TXT लुकअप: {0}","it":"Ricerca TXT: {0}","ja":"TXTルックアップ: {0}","nl":"TXT-zoekactie: {0}","no":"TXT-oppslag: {0}","pl":"Wyszukiwanie TXT: {0}","pt":"Pesquisa TXT: {0}","sv":"TXT-uppslag: {0}","zh":"TXT 查询：{0}"},
    "PID 0 cannot be killed": {"cs":"PID 0 nelze ukončit","da":"PID 0 kan ikke dræbes","de":"PID 0 kann nicht beendet werden","el":"Το PID 0 δεν μπορεί να τερματιστεί","es":"PID 0 no puede ser terminado","fr":"PID 0 ne peut pas être tué","hi":"PID 0 को बंद नहीं किया जा सकता","it":"PID 0 non può essere terminato","ja":"PID 0は終了できません","nl":"PID 0 kan niet worden beëindigd","no":"PID 0 kan ikke termineres","pl":"PID 0 nie może zostać zakończony","pt":"PID 0 não pode ser encerrado","sv":"PID 0 kan inte dödas","zh":"PID 0 无法终止"},
    "Process {0} not found: {1}": {"cs":"Proces {0} nenalezen: {1}","da":"Proces {0} ikke fundet: {1}","de":"Prozess {0} nicht gefunden: {1}","el":"Διαδικασία {0} δεν βρέθηκε: {1}","es":"Proceso {0} no encontrado: {1}","fr":"Processus {0} introuvable : {1}","hi":"प्रक्रिया {0} नहीं मिली: {1}","it":"Processo {0} non trovato: {1}","ja":"プロセス {0} が見つかりません: {1}","nl":"Proces {0} niet gevonden: {1}","no":"Prosess {0} ikke funnet: {1}","pl":"Proces {0} nie znaleziony: {1}","pt":"Processo {0} não encontrado: {1}","sv":"Process {0} hittades inte: {1}","zh":"进程 {0} 未找到：{1}"},
    "{0} not found": {"cs":"{0} nenalezeno","da":"{0} ikke fundet","de":"{0} nicht gefunden","el":"Το {0} δεν βρέθηκε","es":"{0} no encontrado","fr":"{0} introuvable","hi":"{0} नहीं मिला","it":"{0} non trovato","ja":"{0} が見つかりません","nl":"{0} niet gevonden","no":"{0} ikke funnet","pl":"{0} nie znaleziono","pt":"{0} não encontrado","sv":"{0} hittades inte","zh":"{0} 未找到"},
    "SMB Shares": {"cs":"SMB sdílení","da":"SMB-delinger","de":"SMB-Freigaben","el":"Κοινές χρήσεις SMB","es":"Recursos compartidos SMB","fr":"Partages SMB","hi":"SMB शेयर","it":"Condivisioni SMB","ja":"SMB共有","nl":"SMB-delingen","no":"SMB-delinger","pl":"Udziały SMB","pt":"Compartilhamentos SMB","sv":"SMB-delningar","zh":"SMB 共享"},
    "Shares": {"cs":"Sdílení","da":"Delinger","de":"Freigaben","el":"Κοινές χρήσεις","es":"Recursos compartidos","fr":"Partages","hi":"शेयर","it":"Condivisioni","ja":"共有","nl":"Delingen","no":"Delinger","pl":"Udziały","pt":"Compartilhamentos","sv":"Delningar","zh":"共享"},
    "Nests": {"cs":"Hnízda","da":"Reder","de":"Nester","el":"Φωλιές","es":"Nidos","fr":"Nids","hi":"घोंसले","it":"Nidi","ja":"ネスト","nl":"Nesten","no":"Reir","pl":"Gniazda","pt":"Ninhos","sv":"Bon","zh":"巢"},
    "Eggs": {"cs":"Vejce","da":"Æg","de":"Eier","el":"Αυγά","es":"Huevos","fr":"Œufs","hi":"अंडे","it":"Uova","ja":"エッグ","nl":"Eieren","no":"Egg","pl":"Jaja","pt":"Ovos","sv":"Ägg","zh":"蛋"},
    "Firewall": {"cs":"Firewall","da":"Firewall","de":"Firewall","el":"Τείχος προστασίας","es":"Cortafuegos","fr":"Pare-feu","hi":"फ़ायरवॉल","it":"Firewall","ja":"ファイアウォール","nl":"Firewall","no":"Brannmur","pl":"Zapora","pt":"Firewall","sv":"Brandvägg","zh":"防火墙"},
    "Messenger": {"cs":"Messenger","da":"Messenger","de":"Messenger","el":"Μηνυματοφορέας","es":"Mensajería","fr":"Messagerie","hi":"मैसेंजर","it":"Messenger","ja":"メッセンジャー","nl":"Messenger","no":"Messenger","pl":"Komunikator","pt":"Mensageiro","sv":"Messenger","zh":"通讯"},
    "Web Scraper": {"cs":"Web Scraper","da":"Web-scraper","de":"Web-Scraper","el":"Εξαγωγή ιστοσελίδων","es":"Raspador web","fr":"Extracteur Web","hi":"वेब स्क्रैपर","it":"Web Scraper","ja":"Webスクレイパー","nl":"Webschraper","no":"Nettskrape","pl":"Pobieranie WWW","pt":"Extrator Web","sv":"Webbskrapare","zh":"网页抓取"},
    "Shell Sandbox (Landlock)": {"cs":"Shell Sandbox (Landlock)","da":"Shell-sandkasse (Landlock)","de":"Shell-Sandbox (Landlock)","el":"Φ sandbox shell (Landlock)","es":"Sandbox de Shell (Landlock)","fr":"Bac à sable Shell (Landlock)","hi":"शेल सैंडबॉक्स (Landlock)","it":"Sandbox Shell (Landlock)","ja":"Shellサンドボックス (Landlock)","nl":"Shell-sandbox (Landlock)","no":"Shell-sandkasse (Landlock)","pl":"Piaskownica Shell (Landlock)","pt":"Sandbox Shell (Landlock)","sv":"Sandlåda för Shell (Landlock)","zh":"Shell 沙盒 (Landlock)"},
    "Analytics Agent": {"cs":"Analytický agent","da":"Analytics-agent","de":"Analyse-Agent","el":"Πράκτορας αναλυτικών","es":"Agente de análisis","fr":"Agent analytique","hi":"विश्लेषण एजेंट","it":"Agente di analisi","ja":"分析エージェント","nl":"Analytics-agent","no":"Analyse-agent","pl":"Agent analityczny","pt":"Agente de análise","sv":"Analysagent","zh":"分析代理"},
    "Domain": {"cs":"Doména","da":"Domæne","de":"Domäne","el":"Τομέας","es":"Dominio","fr":"Domaine","hi":"डोमेन","it":"Dominio","ja":"ドメイン","nl":"Domein","no":"Domene","pl":"Domena","pt":"Domínio","sv":"Domän","zh":"域名"},
    "Fallbacks": {"cs":"Záložní","da":"Fallbacks","de":"Fallbacks","el":"Εναλλακτικά","es":"Alternativas","fr":"Replis","hi":"फ़ॉलबैक","it":"Fallback","ja":"フォールバック","nl":"Fallbacks","no":"Fallbacks","pl":"Awaryjne","pt":"Alternativas","sv":"Reservalternativ","zh":"回退"},
    "Geo-Blocking": {"cs":"Geoblokování","da":"Geo-blokering","de":"Geo-Blocking","el":"Γεωγραφικός αποκλεισμός","es":"Bloqueo geográfico","fr":"Blocage géographique","hi":"भू-अवरोधन","it":"Geo-blocking","ja":"ジオブロッキング","nl":"Geo-blokkering","no":"Geoblokkering","pl":"Blokada geograficzna","pt":"Bloqueio geográfico","sv":"Geoblockering","zh":"地理封锁"},
    "Journal": {"cs":"Deník","da":"Journal","de":"Journal","el":"Ημερολόγιο","es":"Diario","fr":"Journal","hi":"जर्नल","it":"Journal","ja":"ジャーナル","nl":"Journaal","no":"Journal","pl":"Dziennik","pt":"Diário","sv":"Journal","zh":"日志"},
    "Plan": {"cs":"Plán","da":"Plan","de":"Plan","el":"Σχέδιο","es":"Plan","fr":"Plan","hi":"योजना","it":"Piano","ja":"プラン","nl":"Plan","no":"Plan","pl":"Plan","pt":"Plano","sv":"Plan","zh":"计划"},
    "Image Generation": {"cs":"Generování obrázků","da":"Billedgenerering","de":"Bildgenerierung","el":"Δημιουργία εικόνων","es":"Generación de imágenes","fr":"Génération d'images","hi":"छवि जनरेशन","it":"Generazione immagini","ja":"画像生成","nl":"Afbeeldinggeneratie","no":"Bildegenerering","pl":"Generowanie obrazów","pt":"Geração de imagens","sv":"Bildgenerering","zh":"图像生成"},
    "Fallback LLM": {"cs":"Záložní LLM","da":"Fallback-LLM","de":"Fallback-LLM","el":"Εναλλακτικό LLM","es":"LLM alternativo","fr":"LLM de repli","hi":"फ़ॉलबैक LLM","it":"LLM di fallback","ja":"フォールバックLLM","nl":"Fallback-LLM","no":"Fallback-LLM","pl":"LLM zapasowy","pt":"LLM alternativo","sv":"Reserv-LLM","zh":"备用 LLM"},
    "Docker Host": {"cs":"Docker Host","da":"Docker-vært","de":"Docker-Host","el":"Κεντρικός Docker","es":"Host Docker","fr":"Hôte Docker","hi":"Docker होस्ट","it":"Host Docker","ja":"Dockerホスト","nl":"Docker-host","no":"Docker-vert","pl":"Host Docker","pt":"Host Docker","sv":"Docker-värd","zh":"Docker 主机"},
    "Public URL": {"cs":"Veřejná URL","da":"Offentlig URL","de":"Öffentliche URL","el":"Δημόσιο URL","es":"URL pública","fr":"URL publique","hi":"सार्वजनिक URL","it":"URL pubblica","ja":"パブリックURL","nl":"Openbare URL","no":"Offentlig URL","pl":"Publiczny URL","pt":"URL pública","sv":"Offentlig URL","zh":"公共 URL"},
    "Homepage URL": {"cs":"URL domovské stránky","da":"Hjemmeside-URL","de":"Homepage-URL","el":"URL αρχικής σελίδας","es":"URL de inicio","fr":"URL de la page d'accueil","hi":"होमपेज URL","it":"URL homepage","ja":"ホームページURL","nl":"Homepage-URL","no":"Hjemmeside-URL","pl":"URL strony głównej","pt":"URL da página inicial","sv":"Hemsida-URL","zh":"主页 URL"},
    "Global Success Rate": {"cs":"Globální úspěšnost","da":"Global succesrate","de":"Globale Erfolgsrate","el":"Παγκόσμιος ποσοστό επιτυχίας","es":"Tasa de éxito global","fr":"Taux de réussite global","hi":"वैश्विक सफलता दर","it":"Tasso di successo globale","ja":"グローバル成功率","nl":"Algemeen slagingspercentage","no":"Global suksessrate","pl":"Globalny wskaźnik sukcesu","pt":"Taxa de sucesso global","sv":"Global framgångsgrad","zh":"全局成功率"},
    "Bundle File": {"cs":"Soubor balíčku","da":"Bundle-fil","de":"Bundle-Datei","el":"Αρχείο πακέτου","es":"Archivo de paquete","fr":"Fichier de bundle","hi":"बंडल फ़ाइल","it":"File bundle","ja":"バンドルファイル","nl":"Bundlebestand","no":"Pakkefil","pl":"Plik pakietu","pt":"Arquivo de pacote","sv":"Paketfil","zh":"包文件"},
    "Play/Pause (Space)": {"cs":"Přehrát/Pozastavit (Mezerník)","da":"Afspil/Pause (Mellemrum)","de":"Abspielen/Pause (Leertaste)","el":"Αναπαραγωγή/Παύση (Κενό)","es":"Reproducir/Pausar (Espacio)","fr":"Lecture/Pause (Espace)","hi":"चलाएं/रोकें (Space)","it":"Riproduci/Pausa (Spazio)","ja":"再生/一時停止 (スペース)","nl":"Afspelen/Pauzeren (Spatie)","no":"Spill av/Pause (Mellomrom)","pl":"Odtwórz/Pauza (Spacja)","pt":"Reproduzir/Pausar (Espaço)","sv":"Spela/Pausa (Mellanslag)","zh":"播放/暂停（空格）"},
    "Playback speed": {"cs":"Rychlost přehrávání","da":"Afspilningshastighed","de":"Wiedergabegeschwindigkeit","el":"Ταχύτητα αναπαραγωγής","es":"Velocidad de reproducción","fr":"Vitesse de lecture","hi":"प्लेबैक गति","it":"Velocità riproduzione","ja":"再生速度","nl":"Afspeelsnelheid","no":"Avspillingshastighet","pl":"Prędkość odtwarzania","pt":"Velocidade de reprodução","sv":"Uppspelningshastighet","zh":"播放速度"},
    "Rate Limit (req/s)": {"cs":"Rychlostní limit (req/s)","da":"Hastighedsgrænse (req/s)","de":"Ratenlimit (Anf./s)","el":"Όριο ρυθμού (req/s)","es":"Límite de tasa (req/s)","fr":"Limite de débit (req/s)","hi":"दर सीमा (req/s)","it":"Limite di frequenza (req/s)","ja":"レート制限 (req/s)","nl":"Snelheidslimiet (req/s)","no":"Hastighetsgrense (req/s)","pl":"Limit żądań (req/s)","pt":"Limite de taxa (req/s)","sv":"Hastighetsgräns (req/s)","zh":"速率限制 (请求/秒)"},
    "S3 Storage": {"cs":"S3 úložiště","da":"S3-lagring","de":"S3-Speicher","el":"Αποθήκευση S3","es":"Almacenamiento S3","fr":"Stockage S3","hi":"S3 स्टोरेज","it":"Archiviazione S3","ja":"S3ストレージ","nl":"S3-opslag","no":"S3-lagring","pl":"Pamięć S3","pt":"Armazenamento S3","sv":"S3-lagring","zh":"S3 存储"},
    "S3-compatible object storage": {"cs":"S3-kompatibilní objektové úložiště","da":"S3-kompatibel objektlagring","de":"S3-kompatibler Objektspeicher","el":"Αποθήκευση αντικειμένων συμβατή με S3","es":"Almacenamiento de objetos compatible con S3","fr":"Stockage d'objets compatible S3","hi":"S3-संगत ऑब्जेक्ट स्टोरेज","it":"Archiviazione oggetti compatibile con S3","ja":"S3互換オブジェクトストレージ","nl":"S3-compatibele objectopslag","no":"S3-kompatibel objektlagring","pl":"Pamięć obiektowa kompatybilna z S3","pt":"Armazenamento de objetos compatível com S3","sv":"S3-kompatibel objektlagring","zh":"S3 兼容对象存储"},
    "Service Exposure": {"cs":"Vystavení služeb","da":"Tjenesteeksponering","de":"Dienstveröffentlichung","el":"Έκθεση υπηρεσιών","es":"Exposición de servicios","fr":"Exposition de services","hi":"सेवा प्रदर्शन","it":"Esposizione servizi","ja":"サービス公開","nl":"Serviceblootstelling","no":"Tjenesteeksponering","pl":"Ekspozycja usług","pt":"Exposição de serviços","sv":"Tjänsteexponering","zh":"服务暴露"},
    "Rejected Mutations": {"cs":"Zamítnuté mutace","da":"Afviste mutationer","de":"Abgelehnte Mutationen","el":"Απορριφθείσες μεταλλάξεις","es":"Mutaciones rechazadas","fr":"Mutations rejetées","hi":"अस्वीकृत म्यूटेशन","it":"Mutazioni rifiutate","ja":"拒否された変異","nl":"Afgewezen mutaties","no":"Avviste mutasjoner","pl":"Odrzucone mutacje","pt":"Mutações rejeitadas","sv":"Avvisade mutationer","zh":"已拒绝的变更"},
    "Running Shadows": {"cs":"Běžící stíny","da":"Kørende skygger","de":"Laufende Shadows","el":"Εκτελούμενες σκιές","es":"Sombras en ejecución","fr":"Shadows en cours","hi":"चल रही छायाएं","it":"Shadow in esecuzione","ja":"実行中のシャドウ","nl":"Actieve schaduwen","no":"Kjørende skygger","pl":"Uruchomione cienie","pt":"Sombras em execução","sv":"Körande skuggor","zh":"运行中的影子"},
    "Rollout Preset": {"cs":"Předvolba rolloutu","da":"Udrulnings-forudindstilling","de":"Rollout-Voreinstellung","el":"Προεπιλογή ανάπτυξης","es":"Predeterminado de despliegue","fr":"Préréglage de déploiement","hi":"रोलआउट प्रीसेट","it":"Preset di rollout","ja":"ロールアウトプリセット","nl":"Rollout-voorinstelling","no":"Utrullings-forhåndsinnstilling","pl":"Preset wdrożenia","pt":"Predefinição de implantação","sv":"Rullut-preset","zh":"推出预设"},
    "Total Trace Events": {"cs":"Celkem trasovacích událostí","da":"Total sporingshændelser","de":"Trace-Events gesamt","el":"Συνολικά συμβάντα ίχνους","es":"Total de eventos de rastreo","fr":"Total des événements de trace","hi":"कुल ट्रेस इवेंट","it":"Eventi di traccia totali","ja":"合計トレースイベント","nl":"Totaal traceergebeurtenissen","no":"Totalt sporingshendelser","pl":"Łączna liczba zdarzeń śledzenia","pt":"Total de eventos de rastreamento","sv":"Totalt spårningshändelser","zh":"跟踪事件总计"},
    "Recommended bridge tools": {"cs":"Doporučené mostní nástroje","da":"Anbefalede bro-værktøjer","de":"Empfohlene Bridge-Tools","el":"Συνιστώμενα εργαλεία γέφυρας","es":"Herramientas puente recomendadas","fr":"Outils pont recommandés","hi":"अनुशंसित ब्रिज टूल","it":"Strumenti bridge consigliati","ja":"推奨ブリッジツール","nl":"Aanbevolen brug-hulpmiddelen","no":"Anbefalte bro-verktøy","pl":"Zalecane narzędzia pomostowe","pt":"Ferramentas ponte recomendadas","sv":"Rekommenderade bryggningsverktyg","zh":"推荐的桥接工具"},
    "Test Skill": {"cs":"Otestovat dovednost","da":"Test færdighed","de":"Skill testen","el":"Δοκιμή δεξιότητας","es":"Probar habilidad","fr":"Tester la compétence","hi":"कौशल परीक्षण","it":"Testa skill","ja":"スキルをテスト","nl":"Vaardigheid testen","no":"Test ferdighet","pl":"Testuj umiejętność","pt":"Testar habilidade","sv":"Testa färdighet","zh":"测试技能"},
    "Require API Token": {"cs":"Vyžadovat API token","da":"Kræv API-token","de":"API-Token erforderlich","el":"Απαίτηση διακριτικού API","es":"Requerir token de API","fr":"Exiger un jeton API","hi":"API टोकन आवश्यक","it":"Richiedi token API","ja":"APIトークン必須","nl":"API-token vereist","no":"Krev API-token","pl":"Wymagaj tokenu API","pt":"Exigir token de API","sv":"Kräv API-token","zh":"需要 API 令牌"},
    "TrueNAS Settings": {"cs":"Nastavení TrueNAS","da":"TrueNAS-indstillinger","de":"TrueNAS-Einstellungen","el":"Ρυθμίσεις TrueNAS","es":"Configuración de TrueNAS","fr":"Paramètres TrueNAS","hi":"TrueNAS सेटिंग्स","it":"Impostazioni TrueNAS","ja":"TrueNAS設定","nl":"TrueNAS-instellingen","no":"TrueNAS-innstillinger","pl":"Ustawienia TrueNAS","pt":"Configurações do TrueNAS","sv":"TrueNAS-inställningar","zh":"TrueNAS 设置"},
    "TrueNAS Storage": {"cs":"TrueNAS úložiště","da":"TrueNAS-lagring","de":"TrueNAS-Speicher","el":"Αποθήκευση TrueNAS","es":"Almacenamiento TrueNAS","fr":"Stockage TrueNAS","hi":"TrueNAS स्टोरेज","it":"Archiviazione TrueNAS","ja":"TrueNASストレージ","nl":"TrueNAS-opslag","no":"TrueNAS-lagring","pl":"Pamięć TrueNAS","pt":"Armazenamento TrueNAS","sv":"TrueNAS-lagring","zh":"TrueNAS 存储"},
    "TrueNAS ZFS storage management (Pools, Datasets, Snapshots, Shares)": {"cs":"Správa úložiště TrueNAS ZFS (Pooly, datasety, snímky, sdílení)","da":"TrueNAS ZFS lagringshåndtering (Pools, Datasets, Øjebliksbilleder, Delinger)","de":"TrueNAS ZFS-Speicherverwaltung (Pools, Datasets, Snapshots, Freigaben)","el":"Διαχείριση αποθήκευσης TrueNAS ZFS (Ομάδες, Σύνολα, Στιγμιότυπα, Κοινές χρήσεις)","es":"Gestión de almacenamiento TrueNAS ZFS (Grupos, Conjuntos, Instantáneas, Recursos)","fr":"Gestion du stockage TrueNAS ZFS (Pools, Datasets, Instantanés, Partages)","hi":"TrueNAS ZFS स्टोरेज प्रबंधन (पूल, डेटासेट, स्नैपशॉट, शेयर)","it":"Gestione archiviazione TrueNAS ZFS (Pool, Dataset, Snapshot, Condivisioni)","ja":"TrueNAS ZFSストレージ管理（プール、データセット、スナップショット、共有）","nl":"TrueNAS ZFS-opslagbeheer (Pools, Datasets, Snapshots, Delingen)","no":"TrueNAS ZFS lagringshåndtering (Pooler, Datasett, Øyeblikksbilder, Delinger)","pl":"Zarządzanie pamięcią TrueNAS ZFS (Pule, Zestawy danych, Migawki, Udziały)","pt":"Gerenciamento de armazenamento TrueNAS ZFS (Pools, Conjuntos, Instantâneos, Compartilhamentos)","sv":"TrueNAS ZFS lagringshantering (Pooler, Dataset, Ögonblicksbilder, Delningar)","zh":"TrueNAS ZFS 存储管理（池、数据集、快照、共享）"},
    "Guest allowed": {"cs":"Host povolen","da":"Gæst tilladt","de":"Gast erlaubt","el":"Επισκέπτης επιτρέπεται","es":"Invitado permitido","fr":"Invité autorisé","hi":"अतिथि अनुमत","it":"Ospite consentito","ja":"ゲスト許可","nl":"Gast toegestaan","no":"Gjest tillatt","pl":"Gość dozwolony","pt":"Convidado permitido","sv":"Gäst tillåten","zh":"允许访客"},
    "Last 24h:": {"cs":"Posledních 24h:","da":"Sidste 24t:","de":"Letzte 24h:","el":"Τελευταίες 24ω:","es":"Últimas 24h:","fr":"Dernières 24h :","hi":"पिछले 24 घंटे:","it":"Ultime 24h:","ja":"過去24時間:","nl":"Afgelopen 24u:","no":"Siste 24t:","pl":"Ostatnie 24h:","pt":"Últimas 24h:","sv":"Senaste 24t:","zh":"过去 24 小时："},
    "Please select a dataset": {"cs":"Vyberte prosím dataset","da":"Vælg venligst et dataset","de":"Bitte ein Dataset auswählen","el":"Επιλέξτε ένα σύνολο δεδομένων","es":"Seleccione un conjunto de datos","fr":"Veuillez sélectionner un jeu de données","hi":"कृपया एक डेटासेट चुनें","it":"Seleziona un dataset","ja":"データセットを選択してください","nl":"Selecteer een dataset","no":"Velg et datasett","pl":"Wybierz zestaw danych","pt":"Selecione um conjunto de dados","sv":"Välj en dataset","zh":"请选择一个数据集"},
    "LZ4 (recommended)": {"cs":"LZ4 (doporučeno)","da":"LZ4 (anbefalet)","de":"LZ4 (empfohlen)","el":"LZ4 (συνιστάται)","es":"LZ4 (recomendado)","fr":"LZ4 (recommandé)","hi":"LZ4 (अनुशंसित)","it":"LZ4 (consigliato)","ja":"LZ4（推奨）","nl":"LZ4 (aanbevolen)","no":"LZ4 (anbefalt)","pl":"LZ4 (zalecany)","pt":"LZ4 (recomendado)","sv":"LZ4 (rekommenderat)","zh":"LZ4（推荐）"},
}

stats = defaultdict(int)
for d in sorted(str(p) for p in LANG_DIR.rglob("en.json")):
    direc = Path(d).parent
    en = json.loads(Path(d).read_text(encoding="utf-8-sig"))
    for lang in LANGS:
        lf = direc / f"{lang}.json"
        if not lf.exists():
            continue
        ld = json.loads(lf.read_text(encoding="utf-8-sig"))
        mod = False
        for k, ev in en.items():
            if k not in ld:
                continue
            if str(ld[k]).strip().lower() != str(ev).strip().lower():
                continue
            evs = ev.strip()
            if evs in T:
                t = T[evs].get(lang)
                if t:
                    ld[k] = t
                    mod = True
                    stats[lang] += 1
        if mod:
            lf.write_text(json.dumps(ld, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print("Fixed:", dict(stats))
print("Total:", sum(stats.values()))
