#!/usr/bin/env python3
"""Batch 9: More common UI terms, error messages, and config labels."""
import json, os
from pathlib import Path
from collections import defaultdict

LANG_DIR = Path("ui/lang")
LANGS = ["cs","da","de","el","es","fr","hi","it","ja","nl","no","pl","pt","sv","zh"]

T = {
    "Failed to persist configuration": {"cs":"Nepodařilo se uložit konfiguraci","da":"Kunne ikke gemme konfigurationen","de":"Konfiguration konnte nicht gespeichert werden","el":"Αποτυχία αποθήκευσης ρυθμίσεων","es":"No se pudo guardar la configuración","fr":"Échec de la sauvegarde de la configuration","hi":"कॉन्फ़िगरेशन सहेजने में विफल","it":"Impossibile salvare la configurazione","ja":"設定の保存に失敗しました","nl":"Kon configuratie niet opslaan","no":"Kunne ikke lagre konfigurasjonen","pl":"Nie udało się zapisać konfiguracji","pt":"Falha ao salvar configuração","sv":"Kunde inte spara konfigurationen","zh":"无法保存配置"},
    "Failed to render diagram": {"cs":"Nepodařilo se vykreslit diagram","da":"Kunne ikke gengive diagram","de":"Diagramm konnte nicht gerendert werden","el":"Αποτυχία απόδοσης διαγράμματος","es":"No se pudo renderizar el diagrama","fr":"Échec du rendu du diagramme","hi":"आरेख रेंडर करने में विफल","it":"Impossibile renderizzare il diagramma","ja":"ダイアグラムのレンダリングに失敗しました","nl":"Kon diagram niet weergeven","no":"Kunne ikke rendre diagrammet","pl":"Nie udało się wyrenderować diagramu","pt":"Falha ao renderizar diagrama","sv":"Kunde inte rendera diagrammet","zh":"无法渲染图表"},
    "Context error recovered — retrying...": {"cs":"Chyba kontextu obnovena — zkouším znovu...","da":"Kontekstfejl gendannet — prøver igen...","de":"Kontextfehler behoben — erneuter Versuch...","el":"Σφάλμα περιβάλλοντος ανακτήθηκε — επανάληψη...","es":"Error de contexto recuperado — reintentando...","fr":"Erreur de contexte récupérée — nouvelle tentative...","hi":"संदर्भ त्रुटि पहचान गई — पुनः प्रयास कर रहे हैं...","it":"Errore di contesto recuperato — nuovo tentativo...","ja":"コンテキストエラーから回復 — リトライ中...","nl":"Contextfout hersteld — opnieuw proberen...","no":"Kontekstfeil gjenopprettet — prøver på nytt...","pl":"Błąd kontekstu odzyskany — ponowna próba...","pt":"Erro de contexto recuperado — tentando novamente...","sv":"Kontextfel återställt — försöker igen...","zh":"上下文错误已恢复 — 正在重试..."},
    "Context too large, retrimming...": {"cs":"Kontext je příliš velký, znovu ořezávám...","da":"Kontekst for stor, trimmer igen...","de":"Kontext zu groß, erneutes Kürzen...","el":"Το περιβάλλον πολύ μεγάλο, επανακοπή...","es":"Contexto demasiado grande, retrimando...","fr":"Contexte trop grand, réélagage...","hi":"संदर्भ बहुत बड़ा, पुनः ट्रिम कर रहे हैं...","it":"Contesto troppo grande, ritaglio di nuovo...","ja":"コンテキストが大きすぎます。再トリミング中...","nl":"Context te groot, opnieuw bijsnijden...","no":"Kontekst for stor, beskjærer på nytt...","pl":"Kontekst zbyt duży, ponowne przycinanie...","pt":"Contexto muito grande, reaparando...","sv":"Kontext för stor, trimmar igen...","zh":"上下文过大，正在重新裁剪..."},
    "Trimming context window...": {"cs":"Ořezávání kontextového okna...","da":"Trimmer kontekstvindue...","de":"Kontextfenster wird gekürzt...","el":"Περικοπή παραθύρου περιβάλλοντος...","es":"Recortando ventana de contexto...","fr":"Élagage de la fenêtre de contexte...","hi":"संदर्भ विंडो ट्रिम कर रहे हैं...","it":"Riduzione finestra di contesto...","ja":"コンテキストウィンドウをトリミング中...","nl":"Contextvenster bijsnijden...","no":"Beskjærer kontekstvindu...","pl":"Przycinanie okna kontekstu...","pt":"Aparando janela de contexto...","sv":"Trimmar kontextfönster...","zh":"正在裁剪上下文窗口..."},
    "Incomplete tool call detected, requesting proper function call...": {"cs":"Neúplné volání nástroje detekováno, vyžaduji správné volání funkce...","da":"Ufuldstændigt værktøjskald opdaget, anmoder om korrekt funktionkald...","de":"Unvollständiger Tool-Aufruf erkannt, korrekten Funktionsaufruf wird angefordert...","el":"Εντοπίστηκε ελλιπής κλήση εργαλείου, ζητείται σωστή κλήση συνάρτησης...","es":"Llamada a herramienta incompleta detectada, solicitando llamada de función correcta...","fr":"Appel d'outil incomplet détecté, demande d'appel de fonction correct...","hi":"अपूर्ण टूल कॉल पाया गया, उचित फ़ंक्शन कॉल का अनुरोध किया जा रहा है...","it":"Chiamata strumento incompleta rilevata, richiesta chiamata di funzione corretta...","ja":"不完全なツール呼び出しを検出、適切な関数呼び出しを要求中...","nl":"Onvolledige tool-aanroep gedetecteerd, correcte functieaanroep aangevraagd...","no":"Ufullstendig verktøykall oppdaget, ber om korrekt funksjonskall...","pl":"Wykryto niepełne wywołanie narzędzia, żądanie poprawnego wywołania funkcji...","pt":"Chamada de ferramenta incompleta detectada, solicitando chamada de função correta...","sv":"Ofullständigt verktygsanrop upptäckt, begär korrekt funktionsanrop...","zh":"检测到不完整的工具调用，正在请求正确的函数调用..."},
    "Incomplete tool call tag detected, requesting proper tool call...": {"cs":"Neúplná značka volání nástroje detekována, vyžaduji správné volání nástroje...","da":"Ufuldstændig værktøjskald-tag opdaget, anmoder om korrekt værktøjskald...","de":"Unvollständiges Tool-Aufruf-Tag erkannt, korrekter Tool-Aufruf wird angefordert...","el":"Εντοπίστηκε ελλιπής ετικέτα κλήσης εργαλείου, ζητείται σωστή κλήση εργαλείου...","es":"Etiqueta de llamada a herramienta incompleta detectada, solicitando llamada correcta...","fr":"Balise d'appel d'outil incomplète détectée, demande d'appel d'outil correct...","hi":"अपूर्ण टूल कॉल टैग पाया गया, उचित टूल कॉल का अनुरोध किया जा रहा है...","it":"Tag chiamata strumento incompleto rilevato, richiesta chiamata strumento corretta...","ja":"不完全なツール呼び出しタグを検出、適切なツール呼び出しを要求中...","nl":"Onvolledige tool-aanroep-tag gedetecteerd, correcte tool-aanroep aangevraagd...","no":"Ufullstendig verktøykall-tag oppdaget, ber om korrekt verktøykall...","pl":"Wykryto niepełny tag wywołania narzędzia, żądanie poprawnego wywołania...","pt":"Tag de chamada de ferramenta incompleta detectada, solicitando chamada correta...","sv":"Ofullständig verktygsanrop-tagg upptäckt, begär korrekt verktygsanrop...","zh":"检测到不完整的工具调用标签，正在请求正确的工具调用..."},
    "Invalid native tool call detected, requesting corrected function call...": {"cs":"Neplatné nativní volání nástroje detekováno, vyžaduji opravené volání funkce...","da":"Ugyldigt native værktøjskald opdaget, anmoder om korrigeret funktionkald...","de":"Ungültiger nativer Tool-Aufruf erkannt, korrigierten Funktionsaufruf wird angefordert...","el":"Εντοπίστηκε μη έγκυρη εγγενής κλήση εργαλείου, ζητείται διορθωμένη κλήση...","es":"Llamada nativa a herramienta no válida detectada, solicitando llamada corregida...","fr":"Appel d'outil natif invalide détecté, demande d'appel de fonction corrigé...","hi":"अमान्य नेटिव टूल कॉल पाया गया, संशोधित फ़ंक्शन कॉल का अनुरोध किया जा रहा है...","it":"Chiamata strumento nativa non valida rilevata, richiesta chiamata corretta...","ja":"無効なネイティブツール呼び出しを検出、修正された関数呼び出しを要求中...","nl":"Ongeldige native tool-aanroep gedetecteerd, gecorrigeerde functieaanroep aangevraagd...","no":"Ugyldig native verktøykall oppdaget, ber om korrigert funksjonskall...","pl":"Wykryto nieprawidłowe natywne wywołanie narzędzia, żądanie skorygowanego wywołania...","pt":"Chamada nativa de ferramenta inválida detectada, solicitando chamada corrigida...","sv":"Ogiltigt nativt verktygsanrop upptäckt, begär korrigerat funktionsanrop...","zh":"检测到无效的原生工具调用，正在请求已纠正的函数调用..."},
    "Raw code detected, requesting JSON format...": {"cs":"Detekován raw kód, vyžaduji JSON formát...","da":"Rå kode opdaget, anmoder om JSON-format...","de":"Raw-Code erkannt, JSON-Format wird angefordert...","el":"Εντοπίστηκε ακατέργαστος κώδικας, ζητείται μορφή JSON...","es":"Código raw detectado, solicitando formato JSON...","fr":"Code brut détecté, demande de format JSON...","hi":"रॉ कोड पाया गया, JSON प्रारूप का अनुरोध किया जा रहा है...","it":"Codice raw rilevato, richiesta formato JSON...","ja":"Raw コードを検出、JSON形式を要求中...","nl":"Ruwe code gedetecteerd, JSON-formaat aangevraagd...","no":"Rå kode oppdaget, ber om JSON-format...","pl":"Wykryto surowy kod, żądanie formatu JSON...","pt":"Código raw detectado, solicitando formato JSON...","sv":"Råkod upptäckt, begär JSON-format...","zh":"检测到原始代码，正在请求 JSON 格式..."},
    "Tool call wrapped in fence, requesting raw JSON...": {"cs":"Volání nástroje zabaleno v plotu, vyžaduji raw JSON...","da":"Værktøjskald indpakket i hegn, anmoder om rå JSON...","de":"Tool-Aufruf in Code-Block eingeschlossen, Raw-JSON wird angefordert...","el":"Κλήση εργαλείου τυλιγμένη σε φράχτη, ζητείται ακατέργαστο JSON...","es":"Llamada a herramienta envuelta en cerca, solicitando JSON raw...","fr":"Appel d'outil encapsulé dans une clôture, demande de JSON brut...","hi":"टूल कॉल बाड़ में लिपटा हुआ, रॉ JSON का अनुरोध किया जा रहा है...","it":"Chiamata strumento racchiusa in recinto, richiesta JSON raw...","ja":"ツール呼び出しがフェンスで囲まれています、Raw JSONを要求中...","nl":"Tool-aanroep ingepakt in hek, ruwe JSON aangevraagd...","no":"Verktøykall pakket inn i gjerde, ber om rå JSON...","pl":"Wywołanie narzędzia opakowane w ogrodzenie, żądanie surowego JSON...","pt":"Chamada de ferramenta envolvida em cerca, solicitando JSON bruto...","sv":"Verktygsanrop inlindat i stängsel, begär rå JSON...","zh":"工具调用被包裹在围栏中，正在请求原始 JSON..."},
    "XML tool call format detected, requesting native API format...": {"cs":"XML formát volání nástroje detekován, vyžaduji nativní API formát...","da":"XML værktøjskald-format opdaget, anmoder om native API-format...","de":"XML-Tool-Aufruf-Format erkannt, natives API-Format wird angefordert...","el":"Μορφή κλήσης εργαλείου XML εντοπίστηκε, ζητείται εγγενής μορφή API...","es":"Formato de llamada a herramienta XML detectado, solicitando formato API nativo...","fr":"Format d'appel d'outil XML détecté, demande de format API natif...","hi":"XML टूल कॉल प्रारूप पाया गया, नेटिव API प्रारूप का अनुरोध किया जा रहा है...","it":"Formato chiamata strumento XML rilevato, richiesta formato API nativo...","ja":"XML ツール呼び出し形式を検出、ネイティブAPI形式を要求中...","nl":"XML tool-aanroepformaat gedetecteerd, native API-formaat aangevraagd...","no":"XML verktøykall-format oppdaget, ber om native API-format...","pl":"Wykryto format wywołania narzędzia XML, żądanie natywnego formatu API...","pt":"Formato de chamada de ferramenta XML detectado, solicitando formato de API nativo...","sv":"XML-verktygsanropsformat upptäckt, begär nativt API-format...","zh":"检测到 XML 工具调用格式，正在请求原生 API 格式..."},
    "Saved. Restart required for: {0}": {"cs":"Uloženo. Vyžaduje restart pro: {0}","da":"Gemt. Genstart påkrævet for: {0}","de":"Gespeichert. Neustart erforderlich für: {0}","el":"Αποθηκεύτηκε. Απαιτείται επανεκκίνηση για: {0}","es":"Guardado. Requiere reinicio para: {0}","fr":"Sauvegardé. Redémarrage requis pour : {0}","hi":"सहेजा गया। इसके लिए पुनरारंभ आवश्यक: {0}","it":"Salvato. Riavvio necessario per: {0}","ja":"保存しました。再起動が必要です: {0}","nl":"Opgeslagen. Herstart vereist voor: {0}","no":"Lagret. Omstart kreves for: {0}","pl":"Zapisano. Wymagany restart dla: {0}","pt":"Salvo. Reinicialização necessária para: {0}","sv":"Sparat. Omstart krävs för: {0}","zh":"已保存。以下项目需要重启：{0}"},
    "Microphone access denied. Please allow microphone permissions.": {"cs":"Přístup k mikrofonu odepřen. Povolte prosím oprávnění k mikrofonu.","da":"Mikrofonadgang nægtet. Tillad venligst mikrofontilladelser.","de":"Mikrofonzugriff verweigert. Bitte Mikrofonberechtigungen erteilen.","el":"Η πρόσβαση στο μικρόφωνο απορρίφθηκε. Επιτρέψτε τα δικαιώματα μικροφώνου.","es":"Acceso al micrófono denegado. Permita los permisos del micrófono.","fr":"Accès au microphone refusé. Veuillez autoriser les permissions du microphone.","hi":"माइक्रोफ़ोन एक्सेस अस्वीकृत। कृपया माइक्रोफ़ोन अनुमतियां दें।","it":"Accesso al microfono negato. Si prega di consentire i permessi del microfono.","ja":"マイクアクセスが拒否されました。マイクの許可を有効にしてください。","nl":"Microfoontoegang geweigerd. Sta microfoonrechten toe.","no":"Mikrofontilgang nektet. Vennligst tillat mikrofontillatelser.","pl":"Odmowa dostępu do mikrofonu. Proszę nadać uprawnienia mikrofonu.","pt":"Acesso ao microfone negado. Permita as permissões do microfone.","sv":"Mikrofonåtkomst nekad. Vänligen tillåt mikrofonrättigheter.","zh":"麦克风访问被拒绝。请允许麦克风权限。"},
    "No audio file uploaded": {"cs":"Žádný zvukový soubor nebyl nahrán","da":"Ingen lydfil uploadet","de":"Keine Audiodatei hochgeladen","el":"Δεν μεταφορτώθηκε αρχείο ήχου","es":"No se subió ningún archivo de audio","fr":"Aucun fichier audio téléversé","hi":"कोई ऑडियो फ़ाइल अपलोड नहीं की गई","it":"Nessun file audio caricato","ja":"音声ファイルがアップロードされていません","nl":"Geen audiobestand geüpload","no":"Ingen lydfil opplastet","pl":"Nie przesłano pliku audio","pt":"Nenhum arquivo de áudio enviado","sv":"Ingen ljudfil uppladdad","zh":"未上传音频文件"},
    "No messages provided": {"cs":"Žádné zprávy nebyly poskytnuty","da":"Ingen beskeder angivet","de":"Keine Nachrichten angegeben","el":"Δεν παρέχονται μηνύματα","es":"No se proporcionaron mensajes","fr":"Aucun message fourni","hi":"कोई संदेश प्रदान नहीं किया गया","it":"Nessun messaggio fornito","ja":"メッセージが提供されていません","nl":"Geen berichten opgegeven","no":"Ingen meldinger oppgitt","pl":"Nie podano wiadomości","pt":"Nenhuma mensagem fornecida","sv":"Inga meddelanden angivna","zh":"未提供消息"},
    "No token set": {"cs":"Není nastaven žádný token","da":"Ingen token angivet","de":"Kein Token gesetzt","el":"Δεν έχει οριστεί διακριτικό","es":"No se ha establecido ningún token","fr":"Aucun jeton défini","hi":"कोई टोकन सेट नहीं","it":"Nessun token impostato","ja":"トークンが設定されていません","nl":"Geen token ingesteld","no":"Ingen token satt","pl":"Nie ustawiono tokenu","pt":"Nenhum token definido","sv":"Ingen token inställd","zh":"未设置令牌"},
    "Secret key must not be empty": {"cs":"Tajný klíč nesmí být prázdný","da":"Hemmelig nøgle må ikke være tom","de":"Geheimer Schlüssel darf nicht leer sein","el":"Το μυστικό κλειδί δεν πρέπει να είναι κενό","es":"La clave secreta no debe estar vacía","fr":"La clé secrète ne doit pas être vide","hi":"गुप्त कुंजी खाली नहीं होनी चाहिए","it":"La chiave segreta non deve essere vuota","ja":"シークレットキーは空にできません","nl":"Geheime sleutel mag niet leeg zijn","no":"Hemmelig nøkkel kan ikke være tom","pl":"Tajny klucz nie może być pusty","pt":"A chave secreta não deve estar vazia","sv":"Hemlig nyckel får inte vara tom","zh":"密钥不能为空"},
    "Secret value must not be empty": {"cs":"Tajná hodnota nesmí být prázdná","da":"Hemmelig værdi må ikke være tom","de":"Geheimer Wert darf nicht leer sein","el":"Η μυστική τιμή δεν πρέπει να είναι κενή","es":"El valor secreto no debe estar vacío","fr":"La valeur secrète ne doit pas être vide","hi":"गुप्त मान खाली नहीं होना चाहिए","it":"Il valore segreto non deve essere vuoto","ja":"シークレット値は空にできません","nl":"Geheime waarde mag niet leeg zijn","no":"Hemmelig verdi kan ikke være tom","pl":"Tajna wartość nie może być pusta","pt":"O valor secreto não deve estar vazio","sv":"Hemligt värde får inte vara tomt","zh":"秘密值不能为空"},
    "Invalid request": {"cs":"Neplatný požadavek","da":"Ugyldig anmodning","de":"Ungültige Anfrage","el":"Μη έγκυρο αίτημα","es":"Solicitud no válida","fr":"Requête invalide","hi":"अमान्य अनुरोध","it":"Richiesta non valida","ja":"無効なリクエスト","nl":"Ongeldig verzoek","no":"Ugyldig forespørsel","pl":"Nieprawidłowe żądanie","pt":"Solicitação inválida","sv":"Ogiltig begäran","zh":"无效请求"},
    "Too many requests": {"cs":"Příliš mnoho požadavků","da":"For mange anmodninger","de":"Zu viele Anfragen","el":"Πάρα πολλά αιτήματα","es":"Demasiadas solicitudes","fr":"Trop de requêtes","hi":"बहुत अधिक अनुरोध","it":"Troppe richieste","ja":"リクエストが多すぎます","nl":"Te veel verzoeken","no":"For mange forespørsler","pl":"Zbyt wiele żądań","pt":"Muitas solicitações","sv":"För många begäranden","zh":"请求过多"},
    "Not authorized": {"cs":"Nepovoleno","da":"Ikke autoriseret","de":"Nicht autorisiert","el":"Μη εξουσιοδοτημένο","es":"No autorizado","fr":"Non autorisé","hi":"अनधिकृत","it":"Non autorizzato","ja":"認証されていません","nl":"Niet geautoriseerd","no":"Ikke autorisert","pl":"Nieautoryzowany","pt":"Não autorizado","sv":"Ej behörig","zh":"未授权"},
    "Fact not found in core memory.": {"cs":"Fakt nenalezen v základní paměti.","da":"Fakta ikke fundet i kernehukommelsen.","de":"Fakt nicht im Kerngedächtnis gefunden.","el":"Το γεγονός δεν βρέθηκε στη βασική μνήμη.","es":"Hecho no encontrado en la memoria central.","fr":"Fait introuvable dans la mémoire centrale.","hi":"तथ्य मूख्य स्मृति में नहीं मिला।","it":"Fatto non trovato nella memoria principale.","ja":"コアメモリに事実が見つかりません。","nl":"Feit niet gevonden in kerngeheugen.","no":"Fakta ikke funnet i kjerneminnet.","pl":"Fakt nie znaleziony w pamięci głównej.","pt":"Fato não encontrado na memória principal.","sv":"Fakta hittades inte i kärnminnet.","zh":"在核心记忆中未找到事实。"},
    "Fact permanently removed from core memory.": {"cs":"Fakt trvale odstraněn ze základní paměti.","da":"Fakta permanent fjernet fra kernehukommelsen.","de":"Fakt dauerhaft aus dem Kerngedächtnis entfernt.","el":"Το γεγονός αφαιρέθηκε οριστικά από τη βασική μνήμη.","es":"Hecho eliminado permanentemente de la memoria central.","fr":"Fait définitivement supprimé de la mémoire centrale.","hi":"तथ्य स्थायी रूप से मूख्य स्मृति से हटाया गया।","it":"Fatto rimosso permanentemente dalla memoria principale.","ja":"コアメモリから事実を永久に削除しました。","nl":"Feit permanent verwijderd uit kerngeheugen.","no":"Fakta permanent fjernet fra kjerneminnet.","pl":"Fakt trwale usunięty z pamięci głównej.","pt":"Fato removido permanentemente da memória principal.","sv":"Fakta permanent borttaget från kärnminnet.","zh":"事实已从核心记忆中永久删除。"},
}

stats = defaultdict(int)
for d in sorted(str(p) for p in LANG_DIR.rglob("en.json")):
    direc = Path(d).parent
    en = json.loads(Path(d).read_text(encoding="utf-8-sig"))
    for lang in LANGS:
        lf = direc / f"{lang}.json"
        if not lf.exists():
            continue
        ld = json.loads(lf.read_text(encoding="utf-8-sig"))
        mod = False
        for k, ev in en.items():
            if k not in ld:
                continue
            if str(ld[k]).strip().lower() != str(ev).strip().lower():
                continue
            evs = ev.strip()
            if evs in T:
                t = T[evs].get(lang)
                if t:
                    ld[k] = t
                    mod = True
                    stats[lang] += 1
        if mod:
            lf.write_text(json.dumps(ld, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print("Fixed:", dict(stats))
print("Total:", sum(stats.values()))
