#!/usr/bin/env python3
"""
Fix untranslated English values in Greek (el) and Dutch (nl) translation files.
Compares each translation file with its English reference and fills in missing translations.
"""

import json
import os
from pathlib import Path

# Base translation directory
LANG_DIR = Path("ui/lang")

# Greek translations dictionary (hardcoded for accuracy)
GREEK_TRANSLATIONS = {
    # General/Common
    "Unknown command": "Άγνωστη εντολή",
    "Username": "Όνομα χρήστη",
    "Password": "Κωδικός πρόσβασης",
    "Email": "Email",
    "Name": "Όνομα",
    "Description": "Περιγραφή",
    "Status": "Κατάσταση",
    "Enabled": "Ενεργοποιημένο",
    "Disabled": "Απενεργοποιημένο",
    "Save": "Αποθήκευση",
    "Cancel": "Ακύρωση",
    "Delete": "Διαγραφή",
    "Edit": "Επεξεργασία",
    "Add": "Προσθήκη",
    "Close": "Κλείσιμο",
    "Search": "Αναζήτηση",
    "Filter": "Φιλτράρισμα",
    "Refresh": "Ανανέωση",
    "Loading": "Φόρτωση",
    "Error": "Σφάλμα",
    "Success": "Επιτυχία",
    "Warning": "Προειδοποίηση",
    "Info": "Πληροφορία",
    "Settings": "Ρυθμίσεις",
    "General": "Γενικά",
    "Advanced": "Για προχωρημένους",
    "Help": "Βοήθεια",
    "Documentation": "Τεκμηρίωση",
    "Version": "Έκδοση",
    "ID": "Αναγνωριστικό",
    "Type": "Τύπος",
    "Value": "Τιμή",
    "Default": "Προεπιλογή",
    "Required": "Απαιτείται",
    "Optional": "Προαιρετικό",
    "Host": "Διακομιστής",
    "Port": "Θύρα",
    "URL": "URL",
    "API Key": "Κλειδί API",
    "API key": "Κλειδί API",
    "Token": "Διακριτικό",
    "Key": "Κλειδί",
    "Secret": "Μυστικό",
    "Connection": "Σύνδεση",
    "Connected": "Συνδεδεμένο",
    "Disconnected": "Αποσυνδεδεμένο",
    "Online": "Σε σύνδεση",
    "Offline": "Εκτός σύνδεσης",
    "Active": "Ενεργό",
    "Inactive": "Αδρανές",
    "Running": "Σε εκτέλεση",
    "Stopped": "Σταματημένο",
    "Restart": "Επανεκκίνηση",
    "Start": "Έναρξη",
    "Stop": "Διακοπή",
    "Test": "Δοκιμή",
    "Test connection": "Δοκιμή σύνδεσης",
    "Reset": "Επαναφορά",
    "Clear": "Καθαρισμός",
    "Copy": "Αντιγραφή",
    "Paste": "Επικόλληση",
    "Upload": "Μεταφόρτωση",
    "Download": "Λήψη",
    "Import": "Εισαγωγή",
    "Export": "Εξαγωγή",
    "Select": "Επιλογή",
    "Select file": "Επιλογή αρχείου",
    "Select folder": "Επιλογή φακέλου",
    "Browse": "Περιήγηση",
    "Back": "Επιστροφή",
    "Next": "Επόμενο",
    "Previous": "Προηγούμενο",
    "Confirm": "Επιβεβαίωση",
    "Yes": "Ναι",
    "No": "Όχι",
    "OK": "Εντάξει",
    "Apply": "Εφαρμογή",
    "Created": "Δημιουργήθηκε",
    "Updated": "Ενημερώθηκε",
    "Deleted": "Διαγράφηκε",
    "Modified": "Τροποποιήθηκε",
    "Last updated": "Τελευταία ενημέρωση",
    "Date": "Ημερομηνία",
    "Time": "Ώρα",
    "Duration": "Διάρκεια",
    "Size": "Μέγεθος",
    "Length": "Μήκος",
    "Width": "Πλάτος",
    "Height": "Ύψος",
    "Depth": "Βάθος",
    "Weight": "Βάρος",
    "Temperature": "Θερμοκρασία",
    "Pressure": "Πίεση",
    "Humidity": "Υγρασία",
    "Level": "Επίπεδο",
    "Speed": "Ταχύτητα",
    "Rate": "Ρυθμός",
    "Frequency": "Συχνότητα",
    "Voltage": "Τάση",
    "Current": "Ρεύμα",
    "Power": "Ισχύς",
    "Energy": "Ενέργεια",
    "Memory": "Μνήμη",
    "Storage": "Αποθήκευση",
    "Disk": "Δίσκος",
    "CPU": "CPU",
    "RAM": "RAM",
    "Network": "Δίκτυο",
    "Interface": "Διεπαφή",
    "Protocol": "Πρωτόκολλο",
    "Timeout": "Χρονικό όριο",
    "Retry": "Επανάληψη",
    "Max retries": "Μέγιστες επαναλήψεις",
    "Interval": "Διάστημα",
    "Delay": "Καθυστέρηση",
    "Threshold": "Όριο",
    "Limit": "Όριο",
    "Min": "Ελάχ",
    "Max": "Μέγ",
    "Average": "Μέσος όρος",
    "Total": "Σύνολο",
    "Used": "Χρησιμοποιημένο",
    "Free": "Ελεύθερο",
    "Available": "Διαθέσιμο",
    "Allocated": "Κατανεμημένο",
    "Reserved": "Δεσμευμένο",
    "Pending": "Εκκρεμές",
    "Failed": "Απέτυχε",
    "Completed": "Ολοκληρώθηκε",
    "In progress": "Σε εξέλιξη",
    "Waiting": "Αναμονή",
    "Ready": "Έτοιμο",
    "Not ready": "Μη έτοιμο",
    "Initialized": "Αρχικοποιήθηκε",
    "Not initialized": "Δεν αρχικοποιήθηκε",
    "Configured": "Διαμορφωμένο",
    "Not configured": "Δεν διαμορφώθηκε",
    "Invalid": "Μη έγκυρο",
    "Valid": "Έγκυρο",
    "Missing": "Λείπει",
    "Found": "Βρέθηκε",
    "Not found": "Δεν βρέθηκε",
    "Exists": "Υπάρχει",
    "Not exists": "Δεν υπάρχει",
    "Empty": "Κενό",
    "Not empty": "Όχι κενό",
    "Full": "Πλήρες",
    "Not full": "Όχι πλήρες",
    "True": "Αληθές",
    "False": "Ψευδές",
    "All": "Όλα",
    "None": "Κανένα",
    "Any": "Οποιοδήποτε",
    "Custom": "Προσαρμοσμένο",
    "Auto": "Αυτόματο",
    "Manual": "Χειροκίνητο",
    "Automatic": "Αυτόματο",
    "Manual": "Χειροκίνητο",
    "Normal": "Κανονικό",
    "Warning": "Προειδοποίηση",
    "Critical": "Κρίσιμο",
    "Emergency": "Έκτακτη ανάγκη",
    "Alert": "Ειδοποίηση",
    "Notice": "Σημείωση",
    "Debug": "Αποσφαλμάτωση",
    "Trace": "Ιχνηλάτηση",
    "Info": "Πληροφορία",
    "Notice": "Σημείωση",
    "Log": "Καταγραφή",
    "Logs": "Αρχεία καταγραφής",
    "Log level": "Επίπεδο καταγραφής",
    "Log file": "Αρχείο καταγραφής",
    "Log path": "Διαδρομή καταγραφής",
    "Rotate": "Περιστροφή",
    "Backup": "Αντίγραφο ασφαλείας",
    "Restore": "Επαναφορά",
    "Archive": "Αρχείο",
    "Compressed": "Συμπιεσμένο",
    "Encrypted": "Κρυπτογραφημένο",
    "Decrypted": "Αποκρυπτογραφημένο",
    "Compressed": "Συμπιεσμένο",
    "Uncompressed": "Μη συμπιεσμένο",
    "Zipped": "Συμπιεσμένο (ZIP)",
    "Unzipped": "Αποσυμπιεσμένο",
    "Encoded": "Κωδικοποιημένο",
    "Decoded": "Αποκωδικοποιημένο",
    "Base64": "Base64",
    "JSON": "JSON",
    "XML": "XML",
    "CSV": "CSV",
    "HTML": "HTML",
    "Text": "Κείμενο",
    "Binary": "Δυαδικό",
    "File": "Αρχείο",
    "Files": "Αρχεία",
    "Folder": "Φάκελος",
    "Directory": "Κατάλογος",
    "Path": "Διαδρομή",
    "Filename": "Όνομα αρχείου",
    "Filepath": "Διαδρομή αρχείου",
    "Extension": "Επέκταση",
    " MIME type": "Τύπος MIME",
    "Permissions": "Δικαιώματα",
    "Owner": "Κάτοχος",
    "Group": "Ομάδα",
    "User": "Χρήστης",
    "Users": "Χρήστες",
    "Admin": "Διαχειριστής",
    "Administrator": "Διαχειριστής",
    "Guest": "Επισκέπτης",
    "Superuser": "Υπερχρήστης",
    "Role": "Ρόλος",
    "Permission": "Δικαίωμα",
    "Access": "Πρόσβαση",
    "Grant": "Χορήγηση",
    "Revoke": "Ανάκληση",
    "Allow": "Επίτρεψη",
    "Deny": "Άρνηση",
    "Block": "Αποκλεισμός",
    "Unblock": "Ξεμπλοκάρισμα",
    "Accept": "Αποδοχή",
    "Reject": "Απόρριψη",
    "Ignore": "Αγνόηση",
    "Handle": "Χειρισμός",
    "Process": "Επεξεργασία",
    "Handle": "Χειρισμός",
    "Action": "Ενέργεια",
    "Event": "Γεγονός",
    "Events": "Γεγονότα",
    "Trigger": "Ενεργοποιητής",
    "Condition": "Συνθήκη",
    "Rule": "Κανόνας",
    "Schedule": "Πρόγραμμα",
    "Scheduler": "Προγραμματιστής",
    "Cron": "Cron",
    "Task": "Εργασία",
    "Tasks": "Εργασίες",
    "Job": "Εργασία",
    "Jobs": "Εργασίες",
    "Worker": "Εργάτης",
    "Queue": "Ουρά",
    "Message": "Μήνυμα",
    "Messages": "Μηνύματα",
    "Notification": "Ειδοποίηση",
    "Notifications": "Ειδοποιήσεις",
    "Alert": "Ειδοποίηση",
    "Alerts": "Ειδοποιήσεις",
    "Alarm": "Συναγερμός",
    "Alarms": "Συναγερμοί",
    "Report": "Αναφορά",
    "Reports": "Αναφορές",
    "Dashboard": "Πίνακας ελέγχου",
    "Overview": "Επισκόπηση",
    "Summary": "Σύνοψη",
    "Details": "Λεπτομέρειες",
    "Statistics": "Στατιστικά",
    "Metrics": "Μετρικές",
    "Graphs": "Γραφήματα",
    "Charts": "Διαγράμματα",
    "Visualization": "Οπτικοποίηση",
    "Table": "Πίνακας",
    "List": "Λίστα",
    "Grid": "Πλέγμα",
    "Tree": "Δέντρο",
    "Map": "Χάρτης",
    "Calendar": "Ημερολόγιο",
    "Timeline": "Χρονοδιάγραμμα",
    "History": "Ιστορικό",
    "Recent": "Πρόσφατα",
    "Oldest": "Παλαιότερα",
    "Newest": "Νεότερα",
    "Featured": "Προτεινόμενα",
    "Popular": "Δημοφιλή",
    "Trending": "Τάσεις",
    "Recommended": "Προτεινόμενα",
    "Related": "Σχετικά",
    "Similar": "Παρόμοια",
    "Other": "Άλλα",
    "More": "Περισσότερα",
    "Less": "Λιγότερα",
    "Other": "Άλλο",
    "Additional": "Πρόσθετο",
    "Extra": "Επιπλέον",
    "Optional": "Προαιρετικό",
    "Mandatory": "Υποχρεωτικό",
    "Required": "Απαιτούμενο",
    "Conditional": "Υπό συνθήκη",
    "Experimental": "Πειραματικό",
    "Deprecated": "Ξεπερασμένο",
    "Preview": "Προεπισκόπηση",
    "Beta": "Beta",
    "Alpha": "Alpha",
    "Stable": "Σταθερό",
    "Development": "Ανάπτυξη",
    "Production": "Παραγωγή",
    "Staging": "Ενδιάμεσο περιβάλλον",
    "Testing": "Δοκιμή",
    "QA": "QA",
    "Debug": "Αποσφαλμάτωση",
    "Release": "Έκδοση",
    "Channel": "Κανάλι",
    "Branch": "Κλάδος",
    "Tag": "Ετικέτα",
    "Commit": "Commit",
    "Build": "Κατασκευή",
    "Compile": "Μεταγλώττιση",
    "Package": "Πακέτο",
    "Install": "Εγκατάσταση",
    "Uninstall": "Απεγκατάσταση",
    "Update": "Ενημέρωση",
    "Upgrade": "Αναβάθμιση",
    "Downgrade": "Υποβάθμιση",
    "Patch": "Διόρθωση",
    "Fix": "Διόρθωση",
    "Hotfix": "Hotfix",
    "Change": "Αλλαγή",
    "Modify": "Τροποποίηση",
    "Replace": "Αντικατάσταση",
    "Merge": "Συγχώνευση",
    "Split": "Διαχωρισμός",
    "Clone": "Κλωνοποίηση",
    "Copy": "Αντιγραφή",
    "Move": "Μετακίνηση",
    "Rename": "Μετονομασία",
    "Lock": "Κλείδωμα",
    "Unlock": "Ξεκλείδωμα",
    "Enable": "Ενεργοποίηση",
    "Disable": "Απενεργοποίηση",
    "Toggle": "Εναλλαγή",
    "Switch": "Εναλλαγή",
    "Select": "Επιλογή",
    "Deselect": "Αποεπιλογή",
    "Check": "Έλεγχος",
    "Uncheck": "Αποεπιλογή",
    "Select all": "Επιλογή όλων",
    "Deselect all": "Αποεπιλογή όλων",
    "Select none": "Επιλογή κανενός",
    "Invert selection": "Αντιστροφή επιλογής",
    "Toggle all": "Εναλλαγή όλων",
    "Expand": "Ανάπτυξη",
    "Collapse": "Σύμπτυξη",
    "Expand all": "Ανάπτυξη όλων",
    "Collapse all": "Σύμπτυξη όλων",
    "Show": "Εμφάνιση",
    "Hide": "Απόκρυψη",
    "Display": "Εμφάνιση",
    "View": "Προβολή",
    "Navigate": "Πλοήγηση",
    "Go to": "Μετάβαση σε",
    "Jump to": "Μετάβαση σε",
    "Scroll to": "Κύλιση σε",
    "Link": "Σύνδεσμος",
    "Unlink": "Κατάργηση συνδέσμου",
    "URL": "URL",
    "Website": "Ιστοσελίδα",
    "Page": "Σελίδα",
    "Pages": "Σελίδες",
    "Home": "Αρχική",
    "Start": "Έναρξη",
    "Index": "Ευρετήριο",
    "Main": "Κύριο",
    "Root": "Ριζικό",
    "Parent": "Γονικό",
    "Child": "Θυγατρικό",
    "Sibling": "Αδελφικό",
    "Breadcrumb": "Διαδρομή",
    "Menu": "Μενού",
    "Toolbar": "Γραμμή εργαλείων",
    "Sidebar": "Πλευρική γραμμή",
    "Header": "Κεφαλίδα",
    "Footer": "Υποσέλιδο",
    "Content": "Περιεχόμενο",
    "Body": "Σώμα",
    "Title": "Τίτλος",
    "Heading": "Επικεφαλίδα",
    "Subheading": "Υποεπικεφαλίδα",
    "Label": "Ετικέτα",
    "Tag": "Ετικέτα",
    "Badge": "Σήμα",
    "Tooltip": "Συμβουλή",
    "Placeholder": "Κενό πλαίσιο",
    "Hint": "Υπόδειξη",
    "Caption": "Λεζάντα",
    "Legend": "Υπόμνημα",
    "Text": "Κείμενο",
    "Title": "Τίτλος",
    "Subtitle": "Υπότιτλος",
    "Description": "Περιγραφή",
    "Summary": "Σύνοψη",
    "Abstract": "Περίληψη",
    "Introduction": "Εισαγωγή",
    "Conclusion": "Συμπέρασμα",
    "References": "Αναφορές",
    "Appendix": "Παράρτημα",
    "Glossary": "Γλωσσάρι",
    "FAQ": "Συχνές ερωτήσεις",
    "TOS": "Όροι χρήσης",
    "Privacy": "Απόρρητο",
    "Terms": "Όροι",
    "Policy": "Πολιτική",
    "License": "Άδεια",
    "Copyright": "Πνευματικά δικαιώματα",
    "Trademark": "Εμπορικό σήμα",
    "About": "Σχετικά",
    "Contact": "Επικοινωνία",
    "Support": "Υποστήριξη",
    "Feedback": "Σχόλια",
    "Bug": "Σφάλμα",
    "Feature": "Λειτουργία",
    "Request": "Αίτημα",
    "Suggestion": "Πρόταση",
    "Question": "Ερώτηση",
    "Answer": "Απάντηση",
    "Problem": "Πρόβλημα",
    "Solution": "Λύση",
    "Issue": "Ζήτημα",
    "Topic": "Θέμα",
    "Category": "Κατηγορία",
    "Categories": "Κατηγορίες",
    "Tag": "Ετικέτα",
    "Tags": "Ετικέτες",
    "Keyword": "Λέξη-κλειδί",
    "Keywords": "Λέξεις-κλειδιά",
    "Search": "Αναζήτηση",
    "Find": "Εύρεση",
    "Replace": "Αντικατάσταση",
    "Match": "Αντιστοίχιση",
    "Pattern": "Μοτίβο",
    "Regex": "Regex",
    "Query": "Ερώτημα",
    "Filter": "Φιλτράρισμα",
    "Sort": "Ταξινόμηση",
    "Order": "Σειρά",
    "Ascending": "Αύξουσα",
    "Descending": "Φθίνουσα",
    "Random": "Τυχαία",
    "Group": "Ομάδα",
    "Ungroup": "Κατάργηση ομαδοποίησης",
    "Aggregate": "Συνάθροιση",
    "Sum": "Άθροισμα",
    "Count": "Πλήθος",
    "Average": "Μέσος όρος",
    "Min": "Ελάχιστο",
    "Max": "Μέγιστο",
    "Range": "Εύρος",
    "First": "Πρώτο",
    "Last": "Τελευταίο",
    "Previous": "Προηγούμενο",
    "Next": "Επόμενο",
    "Range": "Εύρος",
    "Step": "Βήμα",
    "Page": "Σελίδα",
    "Pages": "Σελίδες",
    "Page size": "Μέγεθος σελίδας",
    "Per page": "Ανά σελίδα",
    "Total pages": "Σύνολο σελίδων",
    "Current page": "Τρέχουσα σελίδα",
    "Go to page": "Μετάβαση σε σελίδα",
    "Pagination": "Σελιδοποίηση",
    "Loading": "Φόρτωση",
    "Processing": "Επεξεργασία",
    "Sending": "Αποστολή",
    "Receiving": "Λήψη",
    "Saving": "Αποθήκευση",
    "Deleting": "Διαγραφή",
    "Updating": "Ενημέρωση",
    "Creating": "Δημιουργία",
    "Editing": "Επεξεργασία",
    "Copying": "Αντιγραφή",
    "Moving": "Μετακίνηση",
    "Renaming": "Μετονομασία",
    "Uploading": "Μεταφόρτωση",
    "Downloading": "Λήψη",
    "Installing": "Εγκατάσταση",
    "Uninstalling": "Απεγκατάσταση",
    "Starting": "Εκκίνηση",
    "Stopping": "Διακοπή",
    "Restarting": "Επανεκκίνηση",
    "Reloading": "Επαναφόρτωση",
    "Refreshing": "Ανανέωση",
    "Initializing": "Αρχικοποίηση",
    "Configuring": "Διαμόρφωση",
    "Validating": "Επικύρωση",
    "Checking": "Έλεγχος",
    "Testing": "Δοκιμή",
    "Scanning": "Σάρωση",
    "Searching": "Αναζήτηση",
    "Indexing": "Ευρετηρίαση",
    "Backing up": "Δημιουργία αντιγράφου ασφαλείας",
    "Restoring": "Επαναφορά",
    "Exporting": "Εξαγωγή",
    "Importing": "Εισαγωγή",
    "Synchronizing": "Συγχρονισμός",
    "Connecting": "Σύνδεση",
    "Disconnecting": "Αποσύνδεση",
    "Authenticating": "Ταυτοποίηση",
    "Authorizing": "Εξουσιοδότηση",
    "Logging in": "Σύνδεση",
    "Logging out": "Αποσύνδεση",
    "Signing in": "Είσοδος",
    "Signing out": "Έξοδος",
    "Signing up": "Εγγραφή",
    "Registering": "Εγγραφή",
    "Recovering": "Ανάκτηση",
    "Resetting": "Επαναφορά",
    "Changing": "Αλλαγή",
    "Setting": "Ρύθμιση",
    "Applying": "Εφαρμογή",
    "Submitting": "Υποβολή",
    "Canceling": "Ακύρωση",
    "Closing": "Κλείσιμο",
    "Finishing": "Ολοκλήρωση",
    "Done": "Ολοκληρώθηκε",
    "Finished": "Ολοκληρώθηκε",
    "Completed": "Ολοκληρώθηκε",
    "Succeeded": "Επιτυχής",
    "Failed": "Απέτυχε",
    "Error": "Σφάλμα",
    "Errors": "Σφάλματα",
    "Warnings": "Προειδοποιήσεις",
    "Success": "Επιτυχία",
    "Failure": "Αποτυχία",
    "Pending": "Εκκρεμής",
    "Canceled": "Ακυρώθηκε",
    "Timed out": "Έληξε το χρονικό όριο",
    "Connection refused": "Η σύνδεση απορρίφθηκε",
    "Connection reset": "Η σύνδεση επαναφέρθηκε",
    "Connection closed": "Η σύνδεση έκλεισε",
    "No data": "Χωρίς δεδομένα",
    "No results": "Χωρίς αποτελέσματα",
    "Not found": "Δεν βρέθηκε",
    "Not implemented": "Δεν υλοποιήθηκε",
    "Not supported": "Δεν υποστηρίζεται",
    "Not available": "Μη διαθέσιμο",
    "Not applicable": "Μη εφαρμόσιμο",
    "Invalid format": "Μη έγκυρη μορφή",
    "Invalid value": "Μη έγκυρη τιμή",
    "Invalid input": "Μη έγκυρη είσοδος",
    "Invalid request": "Μη έγκυρο αίτημα",
    "Invalid response": "Μη έγκυρη απόκριση",
    "Invalid configuration": "Μη έγκυρη διαμόρφωση",
    "Invalid credentials": "Μη έγκυρα διαπιστευτήρια",
    "Invalid token": "Μη έγκυρο διακριτικό",
    "Invalid API key": "Μη έγκυρο κλειδί API",
    "Invalid signature": "Μη έγκυρη υπογραφή",
    "Invalid certificate": "Μη έγκυρο πιστοποιητικό",
    "Invalid license": "Μη έγκυρη άδεια",
    "Missing required field": "Λείπει υποχρεωτικό πεδίο",
    "Missing parameter": "Λείπει παράμετρος",
    "Missing argument": "Λείπει όρισμα",
    "Missing value": "Λείπει τιμή",
    "Missing file": "Λείπει αρχείο",
    "Missing data": "Λείπουν δεδομένα",
    "Too many requests": "Πάρα πολλά αιτήματα",
    "Too many attempts": "Πάρα πολλές προσπάθειες",
    "Rate limit exceeded": "Υπέρβαση ορίου ρυθμού",
    "Quota exceeded": "Υπέρβαση ορίου",
    "Limit exceeded": "Υπέρβαση ορίου",
    "Threshold exceeded": "Υπέρβαση κατωφλίου",
    "Budget exceeded": "Υπέρβαση προϋπολογισμού",
    "Capacity exceeded": "Υπέρβαση χωρητικότητας",
    "Size exceeded": "Υπέρβαση μεγέθους",
    "Length exceeded": "Υπέρβαση μήκους",
    "Depth exceeded": "Υπέρβαση βάθους",
    "Width exceeded": "Υπέρβαση πλάτους",
    "Height exceeded": "Υπέρβαση ύψους",
    "Weight exceeded": "Υπέρβαση βάρους",
    "Time exceeded": "Υπέρβαση χρόνου",
    "Memory exceeded": "Υπέρβαση μνήμης",
    "Disk space exceeded": "Υπέρβαση χώρου δίσκου",
    "Network bandwidth exceeded": "Υπέρβαση εύρους ζώνης δικτύου",
    "Session expired": "Η συνεδρία έληξε",
    "Token expired": "Το διακριτικό έληξε",
    "Session invalid": "Μη έγκυρη συνεδρία",
    "Token invalid": "Μη έγκυρο διακριτικό",
    "Session not found": "Η συνεδρία δεν βρέθηκε",
    "Token not found": "Το διακριτικό δεν βρέθηκε",
    "Session already exists": "Η συνεδρία υπάρχει ήδη",
    "Token already exists": "Το διακριτικό υπάρχει ήδη",
    "Session not initialized": "Η συνεδρία δεν αρχικοποιήθηκε",
    "Session expired": "Η συνεδρία έληξε",
    "Session revoked": "Η συνεδρία ανακλήθηκε",
    "Session terminated": "Η συνεδρία τερματίστηκε",
    "Access denied": "Η πρόσβαση απορρίφθηκε",
    "Permission denied": "Το δικαίωμα απορρίφθηκε",
    "Unauthorized": "Μη εξουσιοδοτημένο",
    "Forbidden": "Απαγορευμένο",
    "Not allowed": "Μη επιτρεπόμενο",
    "Not permitted": "Μη επιτρεπόμενο",
    "Read-only": "Μόνο για ανάγνωση",
    "Write-protected": "Προστατευμένο εγγραφής",
    "Locked": "Κλειδωμένο",
    "Protected": "Προστατευμένο",
    "Secure": "Ασφαλές",
    "Insecure": "Μη ασφαλές",
    "Encrypted": "Κρυπτογραφημένο",
    "Unencrypted": "Μη κρυπτογραφημένο",
    "Authenticated": "Ταυτοποιημένο",
    "Unauthenticated": "Μη ταυτοποιημένο",
    "Anonymous": "Ανώνυμο",
    "Identified": "Ταυτοποιημένο",
    "Verified": "Επαληθευμένο",
    "Unverified": "Μη επαληθευμένο",
    "Confirmed": "Επιβεβαιωμένο",
    "Unconfirmed": "Μη επιβεβαιωμένο",
    "Approved": "Εγκεκριμένο",
    "Rejected": "Απορριφθέν",
    "Pending": "Εκκρεμές",
    "Resolved": "Επιλυμένο",
    "Unresolved": "Μη επιλυμένο",
    "Closed": "Κλειστό",
    "Open": "Ανοιχτό",
    "Reopened": "Ξανανοίχθηκε",
    "Archived": "Αρχειοθετημένο",
    "Pinned": "Καρφιτσωμένο",
    "Starred": "Με αστέρι",
    "Flagged": "Σημαδεμένο",
    "Tagged": "Ετικεταρισμένο",
    "Untagged": "Χωρίς ετικέτα",
    "Marked": "Σημασμένο",
    "Unmarked": "Μη σημασμένο",
    "Selected": "Επιλεγμένο",
    "Unselected": "Μη επιλεγμένο",
    "Focused": "Εστιασμένο",
    "Blurred": "Θολό",
    "Visible": "Ορατό",
    "Hidden": "Κρυφό",
    "Shown": "Εμφανισμένο",
    "Invisible": "Αόρατο",
    "Displayed": "Προβαλλόμενο",
    "Undrawn": "Μη σχεδιασμένο",
    "Rendered": "Αποδοσμένο",
    "Unrendered": "Μη αποδοσμένο",
    "Loaded": "Φορτωμένο",
    "Unloaded": "Μη φορτωμένο",
    "Cached": "Στην κρυφή μνήμη",
    "Uncached": "Όχι στην κρυφή μνήμη",
    "Stored": "Αποθηκευμένο",
    "Retrieved": "Ανακτημένο",
    "Cached": "Στην κρυφή μνήμη",
    "Indexed": "Ευρετηριασμένο",
    "Unindexed": "Μη ευρετηριασμένο",
    "Archived": "Αρχειοθετημένο",
    "Unarchived": "Μη αρχειοθετημένο",
    "Compressed": "Συμπιεσμένο",
    "Uncompressed": "Μη συμπιεσμένο",
    "Encoded": "Κωδικοποιημένο",
    "Decoded": "Αποκωδικοποιημένο",
    "Serialized": "Σειριοποιημένο",
    "Deserialized": "Αποσειριοποιημένο",
    "Parsed": "Αναλυμένο",
    "Unparsed": "Μη αναλυμένο",
    "Formatted": "Μορφοποιημένο",
    "Unformatted": "Μη μορφοποιημένο",
    "Validated": "Επικυρωμένο",
    "Invalidated": "Ακυρωμένο",
    "Verified": "Επαληθευμένο",
    "Unverified": "Μη επαληθευμένο",
    "Authenticated": "Ταυτοποιημένο",
    "Unauthorized": "Μη εξουσιοδοτημένο",
    "Authorized": "Εξουσιοδοτημένο",
    "Restricted": "Περιορισμένο",
    "Unrestricted": "Μη περιορισμένο",
    "Filtered": "Φιλτραρισμένο",
    "Unfiltered": "Μη φιλτραρισμένο",
    "Sorted": "Ταξινομημένο",
    "Unsorted": "Μη ταξινομημένο",
    "Grouped": "Ομαδοποιημένο",
    "Ungrouped": "Μη ομαδοποιημένο",
    "Aggregated": "Συναθροισμένο",
    "Disaggregated": "Διαχωρισμένο",
    "Merged": "Συγχωνευμένο",
    "Unmerged": "Μη συγχωνευμένο",
    "Split": "Διαχωρισμένο",
    "Joined": "Συνδεδεμένο",
    "Left": "Αριστερά",
    "Right": "Δεξιά",
    "Inner": "Εσωτερικό",
    "Outer": "Εξωτερικό",
    "Full": "Πλήρες",
    "Cross": "Σταυρωτό",
    "Union": "Ένωση",
    "Intersection": "Τομή",
    "Difference": "Διαφορά",
    "Symmetric": "Συμμετρικό",
    "Asymmetric": "Ασύμμετρο",
    "Transitive": "Μεταβατικό",
    "Reflexive": "Ανακλαστικό",
    "Symmetric": "Συμμετρικό",
    "Inverse": "Αντίστροφο",
    "Complement": "Συμπλήρωμα",
    "Identity": "Ταυτότητα",
    "Empty": "Κενό",
    "Non-empty": "Μη κενό",
    "Null": "Κενό",
    "Not null": "Όχι κενό",
    "Nil": "Μηδενικό",
    "None": "Κανένα",
    "Something": "Κάτι",
    "Anything": "Οτιδήποτε",
    "Everything": "Τα πάντα",
    "Nothing": "Τίποτα",
    "Default": "Προεπιλογή",
    "Custom": "Προσαρμοσμένο",
    "Preset": "Προκαθορισμένο",
    "Standard": "Τυπικό",
    "Typical": "Τυπικό",
    "Usual": "Συνηθισμένο",
    "Common": "Κοινό",
    "General": "Γενικό",
    "Specific": "Συγκεκριμένο",
    "Exact": "Ακριβές",
    "Approximate": "Κατά προσέγγιση",
    "Precise": "Ακριβές",
    "Accurate": "Ακριβές",
    "Rough": "Χονδρικό",
    "Detailed": "Λεπτομερές",
    "Brief": "Συνοπτικό",
    "Short": "Σύντομο",
    "Long": "Μακρύ",
    "Wide": "Πλατύ",
    "Narrow": "Στενό",
    "Tall": "Ψηλό",
    "Low": "Χαμηλό",
    "High": "Υψηλό",
    "Deep": "Βαθύ",
    "Shallow": "Ρηχό",
    "Thick": "Παχύ",
    "Thin": "Λεπτό",
    "Heavy": "Βαρύ",
    "Light": "Ελαφρύ",
    "Hard": "Σκληρό",
    "Soft": "Μαλακό",
    "Strong": "Ισχυρό",
    "Weak": "Αδύναμο",
    "Fast": "Γρήγορο",
    "Slow": "Αργό",
    "Hot": "Ζεστό",
    "Cold": "Κρύο",
    "Warm": "Χλιαρό",
    "Cool": "Δροσερό",
    "Wet": "Υγρό",
    "Dry": "Στεγνό",
    "Dark": "Σκοτεινό",
    "Bright": "Φωτεινό",
    "Dim": "Θολό",
    "Loud": "Δυνατό",
    "Quiet": "Σιωπηλό",
    "Loud": "Δυνατό",
    "Silent": "Σιωπηλό",
    "Noisy": "Θορυβώδες",
    "Clean": "Καθαρό",
    "Dirty": "Βρώμικο",
    "Neat": "Τακτοποιημένο",
    "Messy": "Ατημέλητο",
    "Tidy": "Τακτοποιημένο",
    "Untidy": "Ατημέλητο",
    "Organized": "Οργανωμένο",
    "Disorganized": "Αδιάτακτο",
    "Simple": "Απλό",
    "Complex": "Πολύπλοκο",
    "Easy": "Εύκολο",
    "Difficult": "Δύσκολο",
    "Hard": "Δύσκολο",
    "Challenging": "Προκλητικό",
    "Straightforward": "Απλό",
    "Complicated": "Περίπλοκο",
    "Straight": "Ευθεία",
    "Curved": "Καμπύλη",
    "Round": "Στρογγυλό",
    "Square": "Τετράγωνο",
    "Rectangular": "Ορθογώνιο",
    "Triangular": "Τριγωνικό",
    "Circular": "Κυκλικό",
    "Spherical": "Σφαιρικό",
    "Cubic": "Κυβικό",
    "Flat": "Επίπεδο",
    "Vertical": "Κατακόρυφο",
    "Horizontal": "Οριζόντιο",
    "Diagonal": "Διαγώνιο",
    "Parallel": "Παράλληλο",
    "Perpendicular": "Κάθετο",
    "Angled": "Γωνιώδες",
    "Solid": "Συμπαγές",
    "Hollow": "Κούφιο",
    "Liquid": "Υγρό",
    "Gas": "Αέριο",
    "Plasma": "Πλάσμα",
    "Fluid": "Ρευστό",
    "Powder": "Κόνες",
    "Granular": "Κοκκώδες",
    "Crystalline": "Κρυσταλλικό",
    "Amorphous": "Άμορφο",
    "Organic": "Οργανικό",
    "Inorganic": "Ανόργανο",
    "Natural": "Φυσικό",
    "Synthetic": "Συνθετικό",
    "Artificial": "Τεχνητό",
    "Biological": "Βιολογικό",
    "Chemical": "Χημικό",
    "Physical": "Φυσικό",
    "Mechanical": "Μηχανικό",
    "Electrical": "Ηλεκτρικό",
    "Electronic": "Ηλεκτρονικό",
    "Digital": "Ψηφιακό",
    "Analog": "Αναλογικό",
    "Virtual": "Εικονικό",
    "Physical": "Φυσικό",
    "Real": "Πραγματικό",
    "Actual": "Πραγματικό",
    "Concrete": "Συγκεκριμένο",
    "Abstract": "Αφηρημένο",
    "Theoretical": "Θεωρητικό",
    "Practical": "Πρακτικό",
    "Applied": "Εφαρμοσμένο",
    "Empirical": "Εμπειρικό",
    "Experimental": "Πειραματικό",
    "Observational": "Παρατηρησιακό",
    "Statistical": "Στατιστικό",
    "Deterministic": "Ντετερμινιστικό",
    "Probabilistic": "Πιθανοτικό",
    "Random": "Τυχαίο",
    "Ordered": "Ταξινομημένο",
    "Chaotic": "Χαοτικό",
    "Linear": "Γραμμικό",
    "Nonlinear": "Μη γραμμικό",
    "Quadratic": "Τετραγωνικό",
    "Exponential": "Εκθετικό",
    "Logarithmic": "Λογαριθμικό",
    "Polynomial": "Πολυωνυμικό",
    "Trigonometric": "Τριγωνομετρικό",
    "Geometric": "Γεωμετρικό",
    "Algebraic": "Αλγεβρικό",
    "Analytic": "Αναλυτικό",
    "Numeric": "Αριθμητικό",
    "Symbolic": "Συμβολικό",
    "Explicit": "Ρητό",
    "Implicit": "Σιωπηρό",
    "Direct": "Άμεσο",
    "Indirect": "Έμμεσο",
    "Local": "Τοπικό",
    "Global": "Καθολικό",
    "Regional": "Περιφερειακό",
    "National": "Εθνικό",
    "International": "Διεθνές",
    "Continental": "Ηπειρωτικό",
    "Global": "Παγκόσμιο",
    "Worldwide": "Παγκόσμιο",
    "Planetary": "Πλανητικό",
    "Solar": "Ηλιακό",
    "Stellar": "Αστρικό",
    "Galactic": "Γαλαξιακό",
    "Cosmic": "Κοσμικό",
    "Universal": "Καθολικό",
    "Public": "Δημόσιο",
    "Private": "Ιδιωτικό",
    "Protected": "Προστατευμένο",
    "Shared": "Κοινόχρηστο",
    "Exclusive": "Αποκλειστικό",
    "Common": "Κοινό",
    "Individual": "Ατομικό",
    "Personal": "Προσωπικό",
    "Collective": "Συλλογικό",
    "Team": "Ομάδα",
    "Group": "Ομάδα",
    "Organizational": "Οργανωτικό",
    "Corporate": "Εταιρικό",
    "Business": "Επιχειρηματικό",
    "Commercial": "Εμπορικό",
    "Industrial": "Βιομηχανικό",
    "Government": "Κυβερνητικό",
    "Political": "Πολιτικό",
    "Social": "Κοινωνικό",
    "Cultural": "Πολιτιστικό",
    "Educational": "Εκπαιδευτικό",
    "Academic": "Ακαδημαϊκό",
    "Scientific": "Επιστημονικό",
    "Research": "Έρευνα",
    "Development": "Ανάπτυξη",
    "Innovation": "Καινοτομία",
    "Technology": "Τεχνολογία",
    "Engineering": "Μηχανική",
    "Architecture": "Αρχιτεκτονική",
    "Design": "Σχεδιασμός",
    "Art": "Τέχνη",
    "Music": "Μουσική",
    "Literature": "Λογοτεχνία",
    "Film": "Κινηματογράφος",
    "Photography": "Φωτογραφία",
    "Theater": "Θέατρο",
    "Dance": "Χορός",
    "Sports": "Αθλήματα",
    "Health": "Υγεία",
    "Medical": "Ιατρικό",
    "Healthcare": "Υγειονομική περίθαλψη",
    "Wellness": "Ευεξία",
    "Fitness": "Φυσική κατάσταση",
    "Nutrition": "Διατροφή",
    "Mental": "Ψυχικό",
    "Physical": "Σωματικό",
    "Emotional": "Συναισθηματικό",
    "Social": "Κοινωνικό",
    "Spiritual": "Πνευματικό",
    "Environmental": "Περιβαλλοντικό",
    "Ecological": "Οικολογικό",
    "Geographical": "Γεωγραφικό",
    "Geological": "Γεωλογικό",
    "Meteorological": "Μετεωρολογικό",
    "Astronomical": "Αστρονομικό",
    "Physics": "Φυσική",
    "Chemistry": "Χημεία",
    "Biology": "Βιολογία",
    "Mathematics": "Μαθηματικά",
    "Statistics": "Στατιστική",
    "Computer Science": "Επιστήμη υπολογιστών",
    "Information Technology": "Πληροφορική",
    "Software": "Λογισμικό",
    "Hardware": "Υλικό",
    "Firmware": "Υλισμικό",
    "Middleware": "Ενδιάμεσο λογισμικό",
    "Operating system": "Λειτουργικό σύστημα",
    "Application": "Εφαρμογή",
    "System": "Σύστημα",
    "Platform": "Πλατφόρμα",
    "Framework": "Πλαίσιο",
    "Library": "Βιβλιοθήκη",
    "Tool": "Εργαλείο",
    "Utility": "Βοηθητικό πρόγραμμα",
    "Service": "Υπηρεσία",
    "Server": "Διακομιστής",
    "Client": "Πελάτης",
    "Agent": "Πράκτορας",
    "Bot": "Bot",
    "Robot": "Ρομπότ",
    "Device": "Συσκευή",
    "Machine": "Μηχανή",
    "Computer": "Υπολογιστής",
    "Laptop": "Φορητός υπολογιστής",
    "Desktop": "Επιτραπέζιος",
    "Server": "Διακομιστής",
    "Workstation": "Σταθμός εργασίας",
    "Terminal": "Τερματικό",
    "Console": "Κονσόλα",
    "Display": "Οθόνη",
    "Monitor": "Οθόνη",
    "Screen": "Οθόνη",
    "Keyboard": "Πληκτρολόγιο",
    "Mouse": "Ποντίκι",
    "Touchpad": "Τυχερό πάγκο",
    "Touchscreen": "Οθόνη αφής",
    "Printer": "Εκτυπωτής",
    "Scanner": "Σαρωτής",
    "Camera": "Κάμερα",
    "Microphone": "Μικρόφωνο",
    "Speaker": "Ηχείο",
    "Headphone": "Ακουστικά",
    "Router": "Δρομολογητής",
    "Switch": "Μεταγωγέας",
    "Modem": "Modem",
    "Firewall": "Τείχος προστασίας",
    "Gateway": "Πύλη",
    "Proxy": "Διαμεσολαβητής",
    "Bridge": "Γέφυρα",
    "Hub": "Hub",
    "Repeater": "Επαναλήπτης",
    "Amplifier": "Ενισχυτής",
    "Converter": "Μετατροπέας",
    "Transceiver": "Πομποδέκτης",
    "Sensor": "Αισθητήρας",
    "Actuator": "Ενεργοποιητής",
    "Controller": "Ελεγκτής",
    "Regulator": "Ρυθμιστής",
    "Indicator": "Δείκτης",
    "Detector": "Ανιχνευτής",
    "Meter": "Μετρητής",
    "Gauge": "Μετρητής",
    "Monitor": "Οθόνη",
    "Display": "Ενδείκτης",
    "Panel": "Πίνακας",
    "Board": "Πλακέτα",
    "Card": "Κάρτα",
    "Chip": "Chip",
    "Circuit": "Κύκλωμα",
    "Component": "Στοιχείο",
    "Part": "Μέρος",
    "Module": "Μονάδα",
    "Unit": "Μονάδα",
    "Element": "Στοιχείο",
    "Assembly": "Συγκρότημα",
    "System": "Σύστημα",
    "Subsystem": "Υποσύστημα",
    "Network": "Δίκτυο",
    "Cluster": "Συστοιχία",
    "Grid": "Πλέγμα",
    "Mesh": "Πλέγμα",
    "Ring": "Δακτύλιος",
    "Star": "Αστέρι",
    "Bus": "Δίαυλος",
    "Tree": "Δέντρο",
    "Graph": "Γράφημα",
    "Topology": "Τοπολογία",
    "Protocol": "Πρωτόκολλο",
    "Standard": "Πρότυπο",
    "Specification": "Προδιαγραφή",
    "Format": "Μορφή",
    "Schema": "Σχήμα",
    "Structure": "Δομή",
    "Model": "Μοντέλο",
    "Template": "Πρότυπο",
    "Pattern": "Μοτίβο",
    "Style": "Στυλ",
    "Theme": "Θέμα",
    "Layout": "Διάταξη",
    "Configuration": "Διαμόρφωση",
    "Setup": "Εγκατάσταση",
    "Installation": "Εγκατάσταση",
    "Deployment": "Ανάπτυξη",
    "Implementation": "Υλοποίηση",
    "Integration": "Ενσωμάτωση",
    "Testing": "Δοκιμή",
    "Quality assurance": "Διασφάλιση ποιότητας",
    "Verification": "Επαλήθευση",
    "Validation": "Επικύρωση",
    "Certification": "Πιστοποίηση",
    "Accreditation": "Διαπίστευση",
    "Authorization": "Εξουσιοδότηση",
    "Authentication": "Ταυτοποίηση",
    "Identification": "Αναγνώριση",
    "Classification": "Ταξινόμηση",
    "Categorization": "Κατηγοριοποίηση",
    "Organization": "Οργάνωση",
    "Management": "Διαχείριση",
    "Administration": "Διοίκηση",
    "Coordination": "Συντονισμός",
    "Collaboration": "Συνεργασία",
    "Communication": "Επικοινωνία",
    "Negotiation": "Διαπραγμάτευση",
    "Mediation": "Διαμεσολάβηση",
    "Arbitration": "Διαιτησία",
    "Judgment": "Κρίση",
    "Decision": "Απόφαση",
    "Planning": "Σχεδιασμός",
    "Strategy": "Στρατηγική",
    "Policy": "Πολιτική",
    "Procedure": "Διαδικασία",
    "Process": "Διαδικασία",
    "Workflow": "Ροή εργασίας",
    "Operation": "Λειτουργία",
    "Transaction": "Συναλλαγή",
    "Interaction": "Αλληλεπίδραση",
    "Relationship": "Σχέση",
    "Association": "Σύνδεση",
    "Connection": "Σύνδεση",
    "Link": "Σύνδεσμος",
    "Bond": "Δεσμός",
    "Bridge": "Γέφυρα",
    "Interface": "Διεπαφή",
    "Boundary": "Όριο",
    "Border": "Σύνορο",
    "Edge": "Ακμή",
    "Node": "Κόμβος",
    "Vertex": "Κορυφή",
    "Point": "Σημείο",
    "Line": "Γραμμή",
    "Curve": "Καμπύλη",
    "Surface": "Επιφάνεια",
    "Volume": "Όγκος",
    "Space": "Χώρος",
    "Area": "Περιοχή",
    "Region": "Περιοχή",
    "Zone": "Ζώνη",
    "Sector": "Τομέας",
    "Domain": "Τομέας",
    "Field": "Πεδίο",
    "Scope": "Εύρος",
    "Range": "Εύρος",
    "Span": "Άνοιγμα",
    "Reach": "Εμβέλεια",
    "Coverage": "Κάλυψη",
    "Extent": "Έκταση",
    "Scale": "Κλίμακα",
    "Magnitude": "Μέγεθος",
    "Intensity": "Ένταση",
    "Level": "Επίπεδο",
    "Degree": "Βαθμός",
    "Grade": "Βαθμός",
    "Rank": "Βαθμός",
    "Class": "Κατηγορία",
    "Type": "Τύπος",
    "Kind": "Είδος",
    "Sort": "Είδος",
    "Variety": "Ποικιλία",
    "Diversity": "Ποικιλομορφία",
    "Difference": "Διαφορά",
    "Similarity": "Ομοιότητα",
    "Analogy": "Αναλογία",
    "Correlation": "Συσχέτιση",
