#!/usr/bin/env python3
"""Batch 15: Emoji-prefixed backend messages and more labels."""
import json, os
from pathlib import Path
from collections import defaultdict

LANG_DIR = Path("ui/lang")
LANGS = ["cs","da","de","el","es","fr","hi","it","ja","nl","no","pl","pt","sv","zh"]

T = {
    "⚠️ **Budget warning!**": {"cs":"⚠️ **Varování rozpočtu!**","da":"⚠️ **Budgetadvarsel!**","de":"⚠️ **Budget-Warnung!**","el":"⚠️ **Προειδοποίηση προϋπολογισμού!**","es":"⚠️ **¡Advertencia de presupuesto!**","fr":"⚠️ **Avertissement de budget !**","hi":"⚠️ **बजट चेतावनी!**","it":"⚠️ **Avviso budget!**","ja":"⚠️ **予算警告！**","nl":"⚠️ **Budgetwaarschuwing!**","no":"⚠️ **Budsjettadvarsel!**","pl":"⚠️ **Ostrzeżenie budżetu!**","pt":"⚠️ **Aviso de orçamento!**","sv":"⚠️ **Budgetvarning!**","zh":"⚠️ **预算警告！**"},
    "⛔ **Budget exceeded!**": {"cs":"⛔ **Rozpočet překročen!**","da":"⛔ **Budget overskredet!**","de":"⛔ **Budget überschritten!**","el":"⛔ **Υπέρβαση προϋπολογισμού!**","es":"⛔ **¡Presupuesto excedido!**","fr":"⛔ **Budget dépassé !**","hi":"⛔ **बजट पार हो गया!**","it":"⛔ **Budget superato!**","ja":"⛔ **予算超過！**","nl":"⛔ **Budget overschreden!**","no":"⛔ **Budsjett overskredet!**","pl":"⛔ **Budżet przekroczony!**","pt":"⛔ **Orçamento excedido!**","sv":"⛔ **Budget överskridet!**","zh":"⛔ **预算已超支！**"},
    "✅ (active)": {"cs":"✅ (aktivní)","da":"✅ (aktiv)","de":"✅ (aktiv)","el":"✅ (ενεργό)","es":"✅ (activo)","fr":"✅ (actif)","hi":"✅ (सक्रिय)","it":"✅ (attivo)","ja":"✅ (アクティブ)","nl":"✅ (actief)","no":"✅ (aktiv)","pl":"✅ (aktywny)","pt":"✅ (ativo)","sv":"✅ (aktiv)","zh":"✅（活动）"},
    "✅ No active warnings. Everything looks good!": {"cs":"✅ Žádná aktivní varování. Vše vypadá dobře!","da":"✅ Ingen aktive advarsler. Alt ser godt ud!","de":"✅ Keine aktiven Warnungen. Alles sieht gut aus!","el":"✅ Καμία ενεργή προειδοποίηση. Όλα φαίνονται καλά!","es":"✅ Sin advertencias activas. ¡Todo está bien!","fr":"✅ Aucun avertissement actif. Tout va bien !","hi":"✅ कोई सक्रिय चेतावनी नहीं। सब ठीक है!","it":"✅ Nessun avviso attivo. Tutto a posto!","ja":"✅ アクティブな警告はありません。すべて正常です！","nl":"✅ Geen actieve waarschuwingen. Alles ziet er goed uit!","no":"✅ Ingen aktive varsler. Alt ser bra ut!","pl":"✅ Brak aktywnych ostrzeżeń. Wszystko w porządku!","pt":"✅ Sem avisos ativos. Tudo está bem!","sv":"✅ Inga aktiva varningar. Allt ser bra ut!","zh":"✅ 没有活动的警告。一切正常！"},
    "✅ Server {0} successfully registered with ID: {1}": {"cs":"✅ Server {0} úspěšně registrován s ID: {1}","da":"✅ Server {0} registreret med ID: {1}","de":"✅ Server {0} erfolgreich registriert mit ID: {1}","el":"✅ Ο διακομιστής {0} καταχωρήθηκε με ID: {1}","es":"✅ Servidor {0} registrado con ID: {1}","fr":"✅ Serveur {0} enregistré avec l'ID : {1}","hi":"✅ सर्वर {0} सफलतापूर्वक पंजीकृत, ID: {1}","it":"✅ Server {0} registrato con ID: {1}","ja":"✅ サーバー {0} がID {1} で登録されました","nl":"✅ Server {0} geregistreerd met ID: {1}","no":"✅ Server {0} registrert med ID: {1}","pl":"✅ Serwer {0} pomyślnie zarejestrowany z ID: {1}","pt":"✅ Servidor {0} registrado com ID: {1}","sv":"✅ Server {0} registrerad med ID: {1}","zh":"✅ 服务器 {0} 已成功注册，ID：{1}"},
    "✅ Sudo password stored in vault successfully.": {"cs":"✅ Sudo heslo úspěšně uloženo v trezoru.","da":"✅ Sudo-adgangskode gemt i boksen.","de":"✅ Sudo-Passwort erfolgreich im Vault gespeichert.","el":"✅ Ο κωδικός sudo αποθηκεύτηκε στο θησαυροφυλάκιο.","es":"✅ Contraseña sudo guardada en el cofre.","fr":"✅ Mot de passe sudo stocké dans le coffre.","hi":"✅ Sudo पासवर्ड vault में संग्रहीत किया गया।","it":"✅ Password sudo salvata nel vault.","ja":"✅ sudoパスワードをvaultに保存しました。","nl":"✅ Sudo-wachtwoord opgeslagen in de kluis.","no":"✅ Sudo-passord lagret i hvelvet.","pl":"✅ Hasło sudo zapisane w sejfie.","pt":"✅ Senha sudo armazenada no cofre.","sv":"✅ Sudo-lösenord sparat i valvet.","zh":"✅ Sudo 密码已成功存储在保管库中。"},
    "❌ Error fetching OpenRouter credits: {0}": {"cs":"❌ Chyba při načítání OpenRouter kreditů: {0}","da":"❌ Fejl ved hentning af OpenRouter-kredit: {0}","de":"❌ Fehler beim Abrufen der OpenRouter-Guthaben: {0}","el":"❌ Σφάλμα ανάκτησης πίστωσης OpenRouter: {0}","es":"❌ Error al obtener créditos de OpenRouter: {0}","fr":"❌ Erreur de récupération des crédits OpenRouter : {0}","hi":"❌ OpenRouter क्रेडिट प्राप्त करने में त्रुटि: {0}","it":"❌ Errore nel recuperare crediti OpenRouter: {0}","ja":"❌ OpenRouterクレジット取得エラー: {0}","nl":"❌ Fout bij ophalen OpenRouter-credits: {0}","no":"❌ Feil ved henting av OpenRouter-kreditter: {0}","pl":"❌ Błąd pobierania kredytów OpenRouter: {0}","pt":"❌ Erro ao buscar créditos do OpenRouter: {0}","sv":"❌ Fel vid hämtning av OpenRouter-krediter: {0}","zh":"❌ 获取 OpenRouter 积分时出错：{0}"},
    "❌ Error: 'host' and 'user' are required. Example: `/addssh host=1.2.3.4 user=root pass=secret`": {"cs":"❌ Chyba: 'host' a 'user' jsou vyžadovány. Příklad: `/addssh host=1.2.3.4 user=root pass=secret`","da":"❌ Fejl: 'host' og 'user' er påkrævede. Eksempel: `/addssh host=1.2.3.4 user=root pass=secret`","de":"❌ Fehler: 'host' und 'user' sind erforderlich. Beispiel: `/addssh host=1.2.3.4 user=root pass=secret`","el":"❌ Σφάλμα: τα 'host' και 'user' είναι απαραίτητα. Παράδειγμα: `/addssh host=1.2.3.4 user=root pass=secret`","es":"❌ Error: 'host' y 'user' son obligatorios. Ejemplo: `/addssh host=1.2.3.4 user=root pass=secret`","fr":"❌ Erreur : 'host' et 'user' sont requis. Exemple : `/addssh host=1.2.3.4 user=root pass=secret`","hi":"❌ त्रुटि: 'host' और 'user' आवश्यक हैं। उदाहरण: `/addssh host=1.2.3.4 user=root pass=secret`","it":"❌ Errore: 'host' e 'user' sono obbligatori. Esempio: `/addssh host=1.2.3.4 user=root pass=secret`","ja":"❌ エラー：'host'と'user'は必須です。例：`/addssh host=1.2.3.4 user=root pass=secret`","nl":"❌ Fout: 'host' en 'user' zijn vereist. Voorbeeld: `/addssh host=1.2.3.4 user=root pass=secret`","no":"❌ Feil: 'host' og 'user' er påkrevd. Eksempel: `/addssh host=1.2.3.4 user=root pass=secret`","pl":"❌ Błąd: 'host' i 'user' są wymagane. Przykład: `/addssh host=1.2.3.4 user=root pass=secret`","pt":"❌ Erro: 'host' e 'user' são obrigatórios. Exemplo: `/addssh host=1.2.3.4 user=root pass=secret`","sv":"❌ Fel: 'host' och 'user' krävs. Exempel: `/addssh host=1.2.3.4 user=root pass=secret`","zh":"❌ 错误：'host' 和 'user' 为必填项。示例：`/addssh host=1.2.3.4 user=root pass=secret`"},
    "❌ Error: Either 'pass' or 'keypath' must be specified.": {"cs":"❌ Chyba: Musí být zadáno buď 'pass' nebo 'keypath'.","da":"❌ Fejl: Enten 'pass' eller 'keypath' skal angives.","de":"❌ Fehler: Entweder 'pass' oder 'keypath' muss angegeben werden.","el":"❌ Σφάλμα: Πρέπει να καθοριστεί είτε 'pass' είτε 'keypath'.","es":"❌ Error: Debe especificarse 'pass' o 'keypath'.","fr":"❌ Erreur : 'pass' ou 'keypath' doit être spécifié.","hi":"❌ त्रुटि: या तो 'pass' या 'keypath' निर्दिष्ट करना आवश्यक है।","it":"❌ Errore: Specificare 'pass' oppure 'keypath'.","ja":"❌ エラー：'pass'または'keypath'を指定してください。","nl":"❌ Fout: 'pass' of 'keypath' moet worden opgegeven.","no":"❌ Feil: Enten 'pass' eller 'keypath' må angis.","pl":"❌ Błąd: Należy podać 'pass' lub 'keypath'.","pt":"❌ Erro: 'pass' ou 'keypath' deve ser especificado.","sv":"❌ Fel: Antingen 'pass' eller 'keypath' måste anges.","zh":"❌ 错误：必须指定 'pass' 或 'keypath'。"},
    "❌ Invalid argument. Use `/debug on` or `/debug off`.": {"cs":"❌ Neplatný argument. Použijte `/debug on` nebo `/debug off`.","da":"❌ Ugyldigt argument. Brug `/debug on` eller `/debug off`.","de":"❌ Ungültiges Argument. Verwenden Sie `/debug on` oder `/debug off`.","el":"❌ Μη έγκυρο όρισμα. Χρησιμοποιήστε `/debug on` ή `/debug off`.","es":"❌ Argumento no válido. Use `/debug on` o `/debug off`.","fr":"❌ Argument invalide. Utilisez `/debug on` ou `/debug off`.","hi":"❌ अमान्य तर्क। `/debug on` या `/debug off` का उपयोग करें।","it":"❌ Argomento non valido. Usa `/debug on` o `/debug off`.","ja":"❌ 無効な引数。`/debug on` または `/debug off` を使用してください。","nl":"❌ Ongeldig argument. Gebruik `/debug on` of `/debug off`.","no":"❌ Ugyldig argument. Bruk `/debug on` eller `/debug off`.","pl":"❌ Nieprawidłowy argument. Użyj `/debug on` lub `/debug off`.","pt":"❌ Argumento inválido. Use `/debug on` ou `/debug off`.","sv":"❌ Ogiltigt argument. Använd `/debug on` eller `/debug off`.","zh":"❌ 无效参数。请使用 `/debug on` 或 `/debug off`。"},
    "❌ Invalid argument. Use `/voice on` or `/voice off`.": {"cs":"❌ Neplatný argument. Použijte `/voice on` nebo `/voice off`.","da":"❌ Ugyldigt argument. Brug `/voice on` eller `/voice off`.","de":"❌ Ungültiges Argument. Verwenden Sie `/voice on` oder `/voice off`.","el":"❌ Μη έγκυρο όρισμα. Χρησιμοποιήστε `/voice on` ή `/voice off`.","es":"❌ Argumento no válido. Use `/voice on` o `/voice off`.","fr":"❌ Argument invalide. Utilisez `/voice on` ou `/voice off`.","hi":"❌ अमान्य तर्क। `/voice on` या `/voice off` का उपयोग करें।","it":"❌ Argomento non valido. Usa `/voice on` o `/voice off`.","ja":"❌ 無効な引数。`/voice on` または `/voice off` を使用してください。","nl":"❌ Ongeldig argument. Gebruik `/voice on` of `/voice off`.","no":"❌ Ugyldig argument. Bruk `/voice on` eller `/voice off`.","pl":"❌ Nieprawidłowy argument. Użyj `/voice on` lub `/voice off`.","pt":"❌ Argumento inválido. Use `/voice on` ou `/voice off`.","sv":"❌ Ogiltigt argument. Använd `/voice on` eller `/voice off`.","zh":"❌ 无效参数。请使用 `/voice on` 或 `/voice off`。"},
    "❌ Password must not be empty.": {"cs":"❌ Heslo nesmí být prázdné.","da":"❌ Adgangskoden må ikke være tom.","de":"❌ Passwort darf nicht leer sein.","el":"❌ Ο κωδικός δεν πρέπει να είναι κενός.","es":"❌ La contraseña no debe estar vacía.","fr":"❌ Le mot de passe ne doit pas être vide.","hi":"❌ पासवर्ड खाली नहीं होना चाहिए।","it":"❌ La password non deve essere vuota.","ja":"❌ パスワードは空にできません。","nl":"❌ Wachtwoord mag niet leeg zijn.","no":"❌ Passordet kan ikke være tomt.","pl":"❌ Hasło nie może być puste.","pt":"❌ A senha não deve estar vazia.","sv":"❌ Lösenordet får inte vara tomt.","zh":"❌ 密码不能为空。"},
    "❌ Please provide password: `/sudopwd <password>`\nTo delete: `/sudopwd --clear`": {"cs":"❌ Zadejte heslo: `/sudopwd <heslo>`\nPro smazání: `/sudopwd --clear`","da":"❌ Angiv adgangskode: `/sudopwd <password>`\nFor at slette: `/sudopwd --clear`","de":"❌ Bitte Passwort angeben: `/sudopwd <Passwort>`\nZum Löschen: `/sudopwd --clear`","el":"❌ Παρέχετε κωδικό: `/sudopwd <κωδικός>`\nΓια διαγραφή: `/sudopwd --clear`","es":"❌ Proporcione la contraseña: `/sudopwd <contraseña>`\nPara eliminar: `/sudopwd --clear`","fr":"❌ Veuillez fournir le mot de passe : `/sudopwd <motdepasse>`\nPour supprimer : `/sudopwd --clear`","hi":"❌ कृपया पासवर्ड दें: `/sudopwd <password>`\nहटाने के लिए: `/sudopwd --clear`","it":"❌ Fornisci la password: `/sudopwd <password>`\nPer eliminare: `/sudopwd --clear`","ja":"❌ パスワードを入力してください：`/sudopwd <password>`\n削除する場合：`/sudopwd --clear`","nl":"❌ Geef wachtwoord op: `/sudopwd <password>`\nOm te verwijderen: `/sudopwd --clear`","no":"❌ Oppgi passord: `/sudopwd <password>`\nFor å slette: `/sudopwd --clear`","pl":"❌ Podaj hasło: `/sudopwd <hasło>`\nAby usunąć: `/sudopwd --clear`","pt":"❌ Forneça a senha: `/sudopwd <senha>`\nPara excluir: `/sudopwd --clear`","sv":"❌ Ange lösenord: `/sudopwd <password>`\nFör att ta bort: `/sudopwd --clear`","zh":"❌ 请提供密码：`/sudopwd <password>`\n删除：`/sudopwd --clear`"},
    "❌ Unknown command. Type /help for a list of commands.": {"cs":"❌ Neznámý příkaz. Napište /help pro seznam příkazů.","da":"❌ Ukendt kommando. Skriv /help for en liste over kommandoer.","de":"❌ Unbekannter Befehl. Geben Sie /help für eine Befehlsliste ein.","el":"❌ Άγνωστη εντολή. Πληκτρολογήστε /help για λίστα εντολών.","es":"❌ Comando desconocido. Escriba /help para ver la lista de comandos.","fr":"❌ Commande inconnue. Tapez /help pour la liste des commandes.","hi":"❌ अज्ञात कमांड। कमांड सूची के लिए /help टाइप करें।","it":"❌ Comando sconosciuto. Digita /help per l'elenco dei comandi.","ja":"❌ 不明なコマンド。コマンド一覧は /help を入力してください。","nl":"❌ Onbekend commando. Typ /help voor een lijst met commando's.","no":"❌ Ukjent kommando. Skriv /help for en liste over kommandoer.","pl":"❌ Nieznana komenda. Wpisz /help, aby wyświetlić listę komend.","pt":"❌ Comando desconhecido. Digite /help para a lista de comandos.","sv":"❌ Okänt kommando. Skriv /help för en lista över kommandon.","zh":"❌ 未知命令。输入 /help 查看命令列表。"},
    "🎭 **Available Personalities:**": {"cs":"🎭 **Dostupné osobnosti:**","da":"🎭 **Tilgængelige personligheder:**","de":"🎭 **Verfügbare Persönlichkeiten:**","el":"🎭 **Διαθέσιμες προσωπικότητες:**","es":"🎭 **Personalidades disponibles:**","fr":"🎭 **Personnalités disponibles :**","hi":"🎭 **उपलब्ध व्यक्तित्व:**","it":"🎭 **Personalità disponibili:**","ja":"🎭 **利用可能なパーソナリティ：**","nl":"🎭 **Beschikbare persoonlijkheden:**","no":"🎭 **Tilgjengelige personligheter:**","pl":"🎭 **Dostępne osobowości:**","pt":"🎭 **Personalidades disponíveis:**","sv":"🎭 **Tillgängliga personligheter:**","zh":"🎭 **可用的人格：**"},
    "📜 **Available Commands:**": {"cs":"📜 **Dostupné příkazy:**","da":"📜 **Tilgængelige kommandoer:**","de":"📜 **Verfügbare Befehle:**","el":"📜 **Διαθέσιμες εντολές:**","es":"📜 **Comandos disponibles:**","fr":"📜 **Commandes disponibles :**","hi":"📜 **उपलब्ध कमांड:**","it":"📜 **Comandi disponibili:**","ja":"📜 **利用可能なコマンド：**","nl":"📜 **Beschikbare commando's:**","no":"📜 **Tilgjengelige kommandoer:**","pl":"📜 **Dostępne komendy:**","pt":"📜 **Comandos disponíveis:**","sv":"📜 **Tillgängliga kommandon:**","zh":"📜 **可用命令：**"},
    "🔄 AuraGo is restarting...": {"cs":"🔄 AuraGo se restartuje...","da":"🔄 AuraGo genstarter...","de":"🔄 AuraGo wird neu gestartet...","el":"🔄 Το AuraGo επανεκκινείται...","es":"🔄 AuraGo se está reiniciando...","fr":"🔄 AuraGo redémarre...","hi":"🔄 AuraGo पुनरारंभ हो रहा है...","it":"🔄 AuraGo si sta riavviando...","ja":"🔄 AuraGoを再起動中...","nl":"🔄 AuraGo herstart...","no":"🔄 AuraGo starter på nytt...","pl":"🔄 AuraGo uruchamia się ponownie...","pt":"🔄 AuraGo está reiniciando...","sv":"🔄 AuraGo startar om...","zh":"🔄 AuraGo 正在重启..."},
    "🔇 **Agent debug mode disabled.** The agent behaves normally.": {"cs":"🔇 **Ladicí režim agenta deaktivován.** Agent se chová normálně.","da":"🔇 **Agent debug-tilstand deaktiveret.** Agenten opfører sig normalt.","de":"🔇 **Agent-Debug-Modus deaktiviert.** Der Agent verhält sich normal.","el":"🔇 **Λειτουργία αποσφαλμάτωσης απενεργοποιήθηκε.** Ο πράκτορας συμπεριφέρεται κανονικά.","es":"🔇 **Modo depuración del agente desactivado.** El agente funciona con normalidad.","fr":"🔇 **Mode debug de l'agent désactivé.** L'agent se comporte normalement.","hi":"🔇 **एजेंट डीबग मोड अक्षम।** एजेंट सामान्य रूप से कार्य करता है।","it":"🔇 **Modalità debug agente disabilitata.** L'agente funziona normalmente.","ja":"🔇 **エージェントデバッグモード無効。** エージェントは通常動作します。","nl":"🔇 **Agent debug-modus uitgeschakeld.** De agent gedraagt zich normaal.","no":"🔇 **Agent debug-modus deaktivert.** Agenten oppfører seg normalt.","pl":"🔇 **Tryb debugowania agenta wyłączony.** Agent działa normalnie.","pt":"🔇 **Modo de depuração do agente desativado.** O agente se comporta normalmente.","sv":"🔇 **Agent debug-läge inaktiverat.** Agenten beter sig normalt.","zh":"🔇 **代理调试模式已禁用。** 代理正常运行。"},
    "🔇 **Voice mode disabled.** Audio will not auto-play.": {"cs":"🔇 **Hlasový režim deaktivován.** Zvuk se nepřehraje automaticky.","da":"🔇 **Stemmetilstand deaktiveret.** Lyd afspilles ikke automatisk.","de":"🔇 **Sprachmodus deaktiviert.** Audio wird nicht automatisch abgespielt.","el":"🔇 **Φωνητική λειτουργία απενεργοποιήθηκε.** Ο ήχος δεν θα αναπαραχθεί αυτόματα.","es":"🔇 **Modo de voz desactivado.** El audio no se reproducirá automáticamente.","fr":"🔇 **Mode vocal désactivé.** L'audio ne se lira pas automatiquement.","hi":"🔇 **वॉइस मोड अक्षम।** ऑडियो स्वतः चलेगा नहीं।","it":"🔇 **Modalità vocale disabilitata.** L'audio non si riprodurrà automaticamente.","ja":"🔇 **音声モード無効。** 音声は自動再生されません。","nl":"🔇 **Spraakmodus uitgeschakeld.** Audio wordt niet automatisch afgespeeld.","no":"🔇 **Stemmemodus deaktivert.** Lyd spilles ikke av automatisk.","pl":"🔇 **Tryb głosowy wyłączony.** Dźwięk nie będzie odtwarzany automatycznie.","pt":"🔇 **Modo de voz desativado.** O áudio não será reproduzido automaticamente.","sv":"🔇 **Röstläge inaktiverat.** Ljud spelas inte upp automatiskt.","zh":"🔇 **语音模式已禁用。** 音频不会自动播放。"},
    "🔊 **Voice mode enabled.** Short replies will be spoken via TTS.": {"cs":"🔊 **Hlasový režim aktivován.** Krátké odpovědi budou přečteny přes TTS.","da":"🔊 **Stemmetilstand aktiveret.** Korte svar læses op via TTS.","de":"🔊 **Sprachmodus aktiviert.** Kurze Antworten werden per TTS gesprochen.","el":"🔊 **Φωνητική λειτουργία ενεργοποιήθηκε.** Σύντομες απαντήσεις θα εκφωνούνται μέσω TTS.","es":"🔊 **Modo de voz activado.** Las respuestas cortas se leerán mediante TTS.","fr":"🔊 **Mode vocal activé.** Les réponses courtes seront lues via TTS.","hi":"🔊 **वॉइस मोड सक्षम।** छोटे उत्तर TTS द्वारा बोले जाएंगे।","it":"🔊 **Modalità vocale abilitata.** Le risposte brevi saranno lette tramite TTS.","ja":"🔊 **音声モード有効。** 短い返信はTTSで読み上げられます。","nl":"🔊 **Spraakmodus ingeschakeld.** Korte antwoorden worden via TTS voorgelezen.","no":"🔊 **Stemmemodus aktivert.** Korte svar leses opp via TTS.","pl":"🔊 **Tryb głosowy włączony.** Krótkie odpowiedzi będą odczytywane przez TTS.","pt":"🔊 **Modo de voz ativado.** Respostas curtas serão faladas via TTS.","sv":"🔊 **Röstläge aktiverat.** Korta svar läses upp via TTS.","zh":"🔊 **语音模式已启用。** 简短回复将通过 TTS 朗读。"},
    "🔍 **Agent debug mode enabled.** The agent will now report errors with detailed information.": {"cs":"🔍 **Ladicí režim agenta aktivován.** Agent bude nyní hlásit chyby s podrobnostmi.","da":"🔍 **Agent debug-tilstand aktiveret.** Agenten rapporterer nu fejl med detaljer.","de":"🔍 **Agent-Debug-Modus aktiviert.** Der Agent meldet nun Fehler mit Detailinformationen.","el":"🔍 **Λειτουργία αποσφαλμάτωσης ενεργοποιήθηκε.** Ο πράκτορας θα αναφέρει σφάλματα με λεπτομέρειες.","es":"🔍 **Modo depuración del agente activado.** El agente informará de errores con detalles.","fr":"🔍 **Mode debug de l'agent activé.** L'agent signalera les erreurs avec des détails.","hi":"🔍 **एजेंट डीबग मोड सक्षम।** एजेंट अब त्रुटियों को विस्तार से रिपोर्ट करेगा।","it":"🔍 **Modalità debug agente abilitata.** L'agente segnalerà gli errori con dettagli.","ja":"🔍 **エージェントデバッグモード有効。** エージェントはエラーを詳細に報告します。","nl":"🔍 **Agent debug-modus ingeschakeld.** De agent rapporteert fouten nu met details.","no":"🔍 **Agent debug-modus aktivert.** Agenten rapporterer nå feil med detaljer.","pl":"🔍 **Tryb debugowania agenta włączony.** Agent będzie raportował błędy ze szczegółami.","pt":"🔍 **Modo de depuração do agente ativado.** O agente relatará erros com informações detalhadas.","sv":"🔍 **Agent debug-läge aktiverat.** Agenten rapporterar fel med detaljerad information.","zh":"🔍 **代理调试模式已启用。** 代理现在将报告带有详细信息的错误。"},
    "🧹 Chat history and short-term memory have been deleted.": {"cs":"🧹 Historie chatu a krátkodobá paměť byly smazány.","da":"🧹 Chat-historik og korttidshukommelse er slettet.","de":"🧹 Chatverlauf und Kurzzeitgedächtnis wurden gelöscht.","el":"🧹 Το ιστορικό συνομιλίας και η βραχυπρόθεσμη μνήμη διαγράφηκαν.","es":"🧹 El historial de chat y la memoria a corto plazo han sido eliminados.","fr":"🧹 L'historique de chat et la mémoire à court terme ont été supprimés.","hi":"🧹 चैट इतिहास और अल्पकालिक स्मृति हटा दी गई।","it":"🧹 La cronologia chat e la memoria a breve termine sono state eliminate.","ja":"🧹 チャット履歴と短期記憶が削除されました。","nl":"🧹 Chatgeschiedenis en kortetermijngeheugen zijn verwijderd.","no":"🧹 Chathistorikk og korttidsminne er slettet.","pl":"🧹 Historia czatu i pamięć krótkotrwała zostały usunięte.","pt":"🧹 O histórico de chat e a memória de curto prazo foram excluídos.","sv":"🧹 Chathistorik och korttidsminne har raderats.","zh":"🧹 聊天记录和短期记忆已被删除。"},
    "🛑 AuraGo has been instructed to interrupt the current action.": {"cs":"🛑 AuraGo obdržel pokyn k přerušení aktuální akce.","da":"🛑 AuraGo er blevet bedt om at afbryde den aktuelle handling.","de":"🛑 AuraGo wurde angewiesen, die aktuelle Aktion abzubrechen.","el":"🛑 Το AuraGo έλαβε εντολή να διακόψει την τρέχουσα ενέργεια.","es":"🛑 AuraGo ha recibido la orden de interrumpir la acción actual.","fr":"🛑 AuraGo a reçu l'ordre d'interrompre l'action en cours.","hi":"🛑 AuraGo को वर्तमान कार्रवाई बाधित करने का निर्देश मिला है।","it":"🛑 AuraGo ha ricevuto l'istruzione di interrompere l'azione corrente.","ja":"🛑 AuraGoは現在のアクションを中断するよう指示されました。","nl":"🛑 AuraGo is geïnstrueerd de huidige actie te onderbreken.","no":"🛑 AuraGo har fått beskjed om å avbryte den gjeldende handlingen.","pl":"🛑 AuraGo otrzymał instrukcję przerwania bieżącej akcji.","pt":"🛑 AuraGo foi instruído a interromper a ação atual.","sv":"🛑 AuraGo har instruerats att avbryta den aktuella åtgärden.","zh":"🛑 AuraGo 已被指示中断当前操作。"},
    "🗑️ Sudo password has been removed from the vault.": {"cs":"🗑️ Sudo heslo bylo odstraněno z trezoru.","da":"🗑️ Sudo-adgangskode er fjernet fra boksen.","de":"🗑️ Sudo-Passwort wurde aus dem Vault entfernt.","el":"🗑️ Ο κωδικός sudo αφαιρέθηκε από το θησαυροφυλάκιο.","es":"🗑️ La contraseña sudo ha sido eliminada del cofre.","fr":"🗑️ Le mot de passe sudo a été supprimé du coffre.","hi":"🗑️ Sudo पासवर्ड vault से हटा दिया गया है।","it":"🗑️ La password sudo è stata rimossa dal vault.","ja":"🗑️ sudoパスワードがvaultから削除されました。","nl":"🗑️ Sudo-wachtwoord is uit de kluis verwijderd.","no":"🗑️ Sudo-passordet er fjernet fra hvelvet.","pl":"🗑️ Hasło sudo zostało usunięte z sejfu.","pt":"🗑️ A senha sudo foi removida do cofre.","sv":"🗑️ Sudo-lösenordet har tagits bort från valvet.","zh":"🗑️ Sudo 密码已从保管库中移除。"},
    "🎭 Personality changed to **{0}**. The change is permanent.": {"cs":"🎭 Osobnost změněna na **{0}**. Změna je trvalá.","da":"🎭 Personlighed ændret til **{0}**. Ændringen er permanent.","de":"🎭 Persönlichkeit geändert zu **{0}**. Die Änderung ist dauerhaft.","el":"🎭 Η προσωπικότητα άλλαξε σε **{0}**. Η αλλαγή είναι μόνιμη.","es":"🎭 Personalidad cambiada a **{0}**. El cambio es permanente.","fr":"🎭 Personnalité changée en **{0}**. Le changement est permanent.","hi":"🎭 व्यक्तित्व **{0}** में बदला गया। परिवर्तन स्थायी है।","it":"🎭 Personalità cambiata in **{0}**. La modifica è permanente.","ja":"🎭 パーソナリティを **{0}** に変更しました。変更は永続的です。","nl":"🎭 Persoonlijkheid gewijzigd naar **{0}**. De wijziging is permanent.","no":"🎭 Personlighet endret til **{0}**. Endringen er permanent.","pl":"🎭 Osobowość zmieniona na **{0}**. Zmiana jest trwała.","pt":"🎭 Personalidade alterada para **{0}**. A alteração é permanente.","sv":"🎭 Personlighet ändrad till **{0}**. Ändringen är permanent.","zh":"🎭 人格已更改为 **{0}**。更改是永久性的。"},
    "💰 Budget system is disabled.": {"cs":"💰 Systém rozpočtu je zakázán.","da":"💰 Budgetsystem er deaktiveret.","de":"💰 Budgetsystem ist deaktiviert.","el":"💰 Το σύστημα προϋπολογισμού είναι απενεργοποιημένο.","es":"💰 El sistema de presupuesto está desactivado.","fr":"💰 Le système de budget est désactivé.","hi":"💰 बजट प्रणाली अक्षम है।","it":"💰 Il sistema budget è disabilitato.","ja":"💰 予算システムは無効です。","nl":"💰 Budgetsysteem is uitgeschakeld.","no":"💰 Budsjettssystemet er deaktivert.","pl":"💰 System budżetu jest wyłączony.","pt":"💰 O sistema de orçamento está desativado.","sv":"💰 Budgetsystemet är inaktiverat.","zh":"💰 预算系统已禁用。"},
}

stats = defaultdict(int)
for d in sorted(str(p) for p in LANG_DIR.rglob("en.json")):
    direc = Path(d).parent
    en = json.loads(Path(d).read_text(encoding="utf-8-sig"))
    for lang in LANGS:
        lf = direc / f"{lang}.json"
        if not lf.exists():
            continue
        ld = json.loads(lf.read_text(encoding="utf-8-sig"))
        mod = False
        for k, ev in en.items():
            if k not in ld:
                continue
            if str(ld[k]).strip().lower() != str(ev).strip().lower():
                continue
            evs = ev.strip()
            if evs in T:
                t = T[evs].get(lang)
                if t:
                    ld[k] = t
                    mod = True
                    stats[lang] += 1
        if mod:
            lf.write_text(json.dumps(ld, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print("Fixed:", dict(stats))
print("Total:", sum(stats.values()))
