#!/usr/bin/env python3
"""Batch 13: TrueNAS labels, remaining UI terms, and config descriptions."""
import json, os
from pathlib import Path
from collections import defaultdict

LANG_DIR = Path("ui/lang")
LANGS = ["cs","da","de","el","es","fr","hi","it","ja","nl","no","pl","pt","sv","zh"]

T = {
    "All Datasets": {"cs":"Všechny datasety","da":"Alle datasets","de":"Alle Datasets","el":"Όλα τα σύνολα δεδομένων","es":"Todos los conjuntos de datos","fr":"Tous les jeux de données","hi":"सभी डेटासेट","it":"Tutti i dataset","ja":"全データセット","nl":"Alle datasets","no":"Alle datasett","pl":"Wszystkie zestawy danych","pt":"Todos os conjuntos de dados","sv":"Alla dataset","zh":"所有数据集"},
    "All OK": {"cs":"Vše OK","da":"Alt OK","de":"Alles OK","el":"Όλα καλά","es":"Todo correcto","fr":"Tout est OK","hi":"सब ठीक","it":"Tutto OK","ja":"すべてOK","nl":"Alles OK","no":"Alt OK","pl":"Wszystko OK","pt":"Tudo OK","sv":"Allt OK","zh":"一切正常"},
    "Allocated": {"cs":"Přiděleno","da":"Allokeret","de":"Zugewiesen","el":"Εκχωρημένο","es":"Asignado","fr":"Alloué","hi":"आवंटित","it":"Allocato","ja":"割り当て済み","nl":"Toegewezen","no":"Allokert","pl":"Przydzielone","pt":"Alocado","sv":"Allokerat","zh":"已分配"},
    "Create SMB Share": {"cs":"Vytvořit SMB sdílení","da":"Opret SMB-deling","de":"SMB-Freigabe erstellen","el":"Δημιουργία κοινής χρήσης SMB","es":"Crear recurso compartido SMB","fr":"Créer un partage SMB","hi":"SMB शेयर बनाएं","it":"Crea condivisione SMB","ja":"SMB共有を作成","nl":"SMB-delings maken","no":"Opprett SMB-deling","pl":"Utwórz udział SMB","pt":"Criar compartilhamento SMB","sv":"Skapa SMB-delning","zh":"创建 SMB 共享"},
    "Create Skill": {"cs":"Vytvořit dovednost","da":"Opret færdighed","de":"Skill erstellen","el":"Δημιουργία δεξιότητας","es":"Crear habilidad","fr":"Créer une compétence","hi":"कौशल बनाएं","it":"Crea skill","ja":"スキルを作成","nl":"Vaardigheid aanmaken","no":"Opprett ferdighet","pl":"Utwórz umiejętność","pt":"Criar habilidade","sv":"Skapa färdighet","zh":"创建技能"},
    "Daemon": {"cs":"Démon","da":"Daemon","de":"Daemon","el":"Δαίμονας","es":"Demonio","fr":"Démon","hi":"डेमन","it":"Demone","ja":"デーモン","nl":"Daemon","no":"Daemon","pl":"Demon","pt":"Daemon","sv":"Daemon","zh":"守护进程"},
    "DEGRADED": {"cs":"DEGRADOVÁNO","da":"DEGRADERET","de":"DEGRADIERT","el":"ΥΠΟΒΑΘΜΙΣΜΕΝΟ","es":"DEGRADADO","fr":"DÉGRADÉ","hi":"क्षतिग्रस्त","it":"DEGRADATO","ja":"縮退","nl":"GEDEGRADEERD","no":"DEGRADERT","pl":"ZDEGRADOWANY","pt":"DEGRADADO","sv":"DEGRADERAT","zh":"已降级"},
    "Host / IP": {"cs":"Hostitel / IP","da":"Vært / IP","de":"Host / IP","el":"Κεντρικός υπολογιστής / IP","es":"Host / IP","fr":"Hôte / IP","hi":"होस्ट / IP","it":"Host / IP","ja":"ホスト / IP","nl":"Host / IP","no":"Vert / IP","pl":"Host / IP","pt":"Host / IP","sv":"Värd / IP","zh":"主机 / IP"},
    "Hostname or IP address of your TrueNAS server": {"cs":"Název hostitele nebo IP adresa vašeho TrueNAS serveru","da":"Værtsnavn eller IP-adresse på din TrueNAS-server","de":"Hostname oder IP-Adresse Ihres TrueNAS-Servers","el":"Όνομα κεντρικού υπολογιστή ή διεύθυνση IP του διακομιστή TrueNAS","es":"Nombre de host o dirección IP de su servidor TrueNAS","fr":"Nom d'hôte ou adresse IP de votre serveur TrueNAS","hi":"आपके TrueNAS सर्वर का होस्टनाम या IP पता","it":"Nome host o indirizzo IP del server TrueNAS","ja":"TrueNASサーバーのホスト名またはIPアドレス","nl":"Hostnaam of IP-adres van uw TrueNAS-server","no":"Vertsnavn eller IP-adresse for din TrueNAS-server","pl":"Nazwa hosta lub adres IP serwera TrueNAS","pt":"Nome do host ou endereço IP do seu servidor TrueNAS","sv":"Värdnamn eller IP-adress för din TrueNAS-server","zh":"TrueNAS 服务器的主机名或 IP 地址"},
    "Name (e.g. tank/share)": {"cs":"Název (např. tank/share)","da":"Navn (f.eks. tank/share)","de":"Name (z.B. tank/share)","el":"Όνομα (π.χ. tank/share)","es":"Nombre (ej. tank/share)","fr":"Nom (p.ex. tank/share)","hi":"नाम (उदा. tank/share)","it":"Nome (es. tank/share)","ja":"名前（例: tank/share）","nl":"Naam (bijv. tank/share)","no":"Navn (f.eks. tank/share)","pl":"Nazwa (np. tank/share)","pt":"Nome (ex. tank/share)","sv":"Namn (t.ex. tank/share)","zh":"名称（例如 tank/share）"},
    "Name (optional, auto-generated)": {"cs":"Název (volitelný, automaticky generovaný)","da":"Navn (valgfrit, auto-genereret)","de":"Name (optional, automatisch generiert)","el":"Όνομα (προαιρετικό, αυτόματη δημιουργία)","es":"Nombre (opcional, autogenerado)","fr":"Nom (facultatif, généré automatiquement)","hi":"नाम (वैकल्पिक, स्वतः उत्पन्न)","it":"Nome (opzionale, generato automaticamente)","ja":"名前（オプション、自動生成）","nl":"Naam (optioneel, automatisch gegenereerd)","no":"Navn (valgfritt, automatisk generert)","pl":"Nazwa (opcjonalna, generowana automatycznie)","pt":"Nome (opcional, gerado automaticamente)","sv":"Namn (valfritt, autogenererat)","zh":"名称（可选，自动生成）"},
    "Path": {"cs":"Cesta","da":"Sti","de":"Pfad","el":"Διαδρομή","es":"Ruta","fr":"Chemin","hi":"पथ","it":"Percorso","ja":"パス","nl":"Pad","no":"Sti","pl":"Ścieżka","pt":"Caminho","sv":"Sökväg","zh":"路径"},
    "Quota (GB, optional - 0 = unlimited)": {"cs":"Kvóta (GB, volitelné - 0 = neomezeno)","da":"Kvote (GB, valgfrit - 0 = ubegrænset)","de":"Quota (GB, optional - 0 = unbegrenzt)","el":"Ποσόστωση (GB, προαιρετικό - 0 = απεριόριστο)","es":"Cuota (GB, opcional - 0 = ilimitado)","fr":"Quota (Go, facultatif - 0 = illimité)","hi":"कोटा (GB, वैकल्पिक - 0 = असीमित)","it":"Quota (GB, opzionale - 0 = illimitato)","ja":"クォータ (GB、オプション - 0 = 無制限)","nl":"Quota (GB, optioneel - 0 = onbeperkt)","no":"Kvote (GB, valgfritt - 0 = ubegrenset)","pl":"Przydział (GB, opcjonalnie - 0 = bez limitu)","pt":"Cota (GB, opcional - 0 = ilimitado)","sv":"Kvot (GB, valfritt - 0 = obegränsat)","zh":"配额 (GB，可选 - 0 = 无限制)"},
    "Really delete dataset \"{{name}}\"? All data will be lost!": {"cs":"Opravdu smazat dataset \"{{name}}\"? Všechna data budou ztracena!","da":"Slet virkelig dataset \"{{name}}\"? Al data vil gå tabt!","de":"Dataset \"{{name}}\" wirklich löschen? Alle Daten gehen verloren!","el":"Διαγραφή συνόλου δεδομένων \"{{name}}\"; Όλα τα δεδομένα θα χαθούν!","es":"¿Eliminar realmente el conjunto de datos \"{{name}}\"? ¡Se perderán todos los datos!","fr":"Supprimer vraiment le jeu de données \"{{name}}\" ? Toutes les données seront perdues !","hi":"वास्तव में डेटासेट \"{{name}}\" हटाएं? सभी डेटा खो जाएगा!","it":"Eliminare davvero il dataset \"{{name}}\"? Tutti i dati saranno persi!","ja":"データセット \"{{name}}\" を削除しますか？すべてのデータが失われます！","nl":"Dataset \"{{name}}\" echt verwijderen? Alle data gaat verloren!","no":"Slett datasett \"{{name}}\" for ekte? All data vil gå tapt!","pl":"Naprawdę usunąć zestaw danych \"{{name}}\"? Wszystkie dane zostaną utracone!","pt":"Realmente excluir o conjunto de dados \"{{name}}\"? Todos os dados serão perdidos!","sv":"Verkligen ta bort dataset \"{{name}}\"? All data går förlorad!","zh":"确定删除数据集 \"{{name}}\" 吗？所有数据将丢失！"},
    "Really delete share? Data will be preserved.": {"cs":"Opravdu smazat sdílení? Data budou zachována.","da":"Slet virkelig deling? Data bevares.","de":"Freigabe wirklich löschen? Daten bleiben erhalten.","el":"Διαγραφή κοινής χρήσης; Τα δεδομένα θα διατηρηθούν.","es":"¿Eliminar realmente el recurso compartido? Los datos se conservarán.","fr":"Supprimer vraiment le partage ? Les données seront préservées.","hi":"वास्तव में शेयर हटाएं? डेटा संरक्षित रहेगा।","it":"Eliminare davvero la condivisione? I dati saranno preservati.","ja":"共有を削除しますか？データは保持されます。","nl":"Deling echt verwijderen? Data blijft behouden.","no":"Slett deling for ekte? Data bevares.","pl":"Naprawdę usunąć udział? Dane zostaną zachowane.","pt":"Realmente excluir o compartilhamento? Os dados serão preservados.","sv":"Verkligen ta bort delning? Data bevaras.","zh":"确定删除共享吗？数据将被保留。"},
    "REALLY rollback to \"{{name}}\"? ALL data after this snapshot will be deleted!": {"cs":"OPRAVDU se vrátit k \"{{name}}\"? VŠECHNA data po tomto snímku budou smazána!","da":"VIRKELIG tilbagefør til \"{{name}}\"? AL data efter dette øjebliksbillede slettes!","de":"WIRKLICH zu \"{{name}}\" zurückrollen? ALLE Daten nach diesem Snapshot werden gelöscht!","el":"ΠΡΑΓΜΑΤΙΚΗ επαναφορά στο \"{{name}}\"; ΟΛΑ τα δεδομένα μετά από αυτό το στιγμιότυπο θα διαγραφούν!","es":"¿REALMENTE revertir a \"{{name}}\"? ¡TODOS los datos después de esta instantánea serán eliminados!","fr":"VRAIMENT restaurer vers \"{{name}}\" ? TOUTES les données après cet instantané seront supprimées !","hi":"वास्तव में \"{{name}}\" पर वापस जाएं? इस स्नैपशॉट के बाद का सारा डेटा हटा दिया जाएगा!","it":"DAVVERO ripristinare a \"{{name}}\"? TUTTI i dati dopo questo snapshot saranno eliminati!","ja":"本当に\"{{name}}\"にロールバックしますか？このスナップショット以降の全データが削除されます！","nl":"WERKELIJK terugdraaien naar \"{{name}}\"? ALLE data na dit snapshot wordt verwijderd!","no":"VIRKELIG tilbakerulle til \"{{name}}\"? ALL data etter dette øyeblikksbildet slettes!","pl":"NAPRAWDĘ wycofać do \"{{name}}\"? WSZYSTKIE dane po tej migawce zostaną usunięte!","pt":"REALMENTE reverter para \"{{name}}\"? TODOS os dados após este instantâneo serão excluídos!","sv":"VERKLIGEN återställa till \"{{name}}\"? ALL data efter denna ögonblicksbild raderas!","zh":"确定回滚到 \"{{name}}\" 吗？此快照之后的所有数据将被删除！"},
    "Recursive (incl. sub-datasets)": {"cs":"Rekurzivní (včetně pod-datasetů)","da":"Rekursiv (inkl. under-datasets)","de":"Rekursiv (inkl. Sub-Datasets)","el":"Αναδρομικό (συμπ. υπο-σύνολα δεδομένων)","es":"Recursivo (incl. subconjuntos)","fr":"Récursif (incl. sous-jeux de données)","hi":"पुनरावर्ती (उप-डेटासेट सहित)","it":"Ricorsivo (incl. sub-dataset)","ja":"再帰的（サブデータセット含む）","nl":"Recursief (incl. subdatasets)","no":"Rekursiv (inkl. underdatasett)","pl":"Rekursywnie (w tym podzestawy danych)","pt":"Recursivo (incl. subconjuntos)","sv":"Rekursivt (inkl. underdataset)","zh":"递归（包括子数据集）"},
    "Read-only mode (no changes allowed)": {"cs":"Režim pouze pro čtení (změny nejsou povoleny)","da":"Skrivebeskyttet tilstand (ingen ændringer tilladt)","de":"Nur-Lese-Modus (keine Änderungen erlaubt)","el":"Λειτουργία μόνο ανάγνωσης (δεν επιτρέπονται αλλαγές)","es":"Modo de solo lectura (no se permiten cambios)","fr":"Mode lecture seule (aucune modification autorisée)","hi":"केवल पढ़ने का मोड (कोई परिवर्तन अनुमत नहीं)","it":"Modalità sola lettura (nessuna modifica consentita)","ja":"読み取り専用モード（変更不可）","nl":"Alleen-lezen modus (geen wijzigingen toegestaan)","no":"Skrivebeskyttet modus (ingen endringer tillatt)","pl":"Tryb tylko do odczytu (zmiany niedozwolone)","pt":"Modo somente leitura (alterações não permitidas)","sv":"Skrivskyddat läge (inga ändringar tillåtna)","zh":"只读模式（不允许更改）"},
    "Retention (days, 0 = forever)": {"cs":"Uchování (dny, 0 = navždy)","da":"Opbevaring (dage, 0 = for evigt)","de":"Aufbewahrung (Tage, 0 = für immer)","el":"Διατήρηση (ημέρες, 0 = για πάντα)","es":"Retención (días, 0 = para siempre)","fr":"Rétention (jours, 0 = indéfiniment)","hi":"प्रतिधारण (दिन, 0 = हमेशा)","it":"Conservazione (giorni, 0 = per sempre)","ja":"保持期間（日数、0 = 無期限）","nl":"Bewaartermijn (dagen, 0 = voor altijd)","no":"Oppbevaring (dager, 0 = for alltid)","pl":"Przechowywanie (dni, 0 = bezterminowo)","pt":"Retenção (dias, 0 = para sempre)","sv":"Lagring (dagar, 0 = för evigt)","zh":"保留（天，0 = 永久）"},
    "Scrub running...": {"cs":"Scrub běží...","da":"Scrub kører...","de":"Scrub läuft...","el":"Scrub σε εξέλιξη...","es":"Scrub en ejecución...","fr":"Scrub en cours...","hi":"Scrub चल रहा है...","it":"Scrub in esecuzione...","ja":"スクラブ実行中...","nl":"Scrub bezig...","no":"Scrub kjører...","pl":"Scrub w toku...","pt":"Scrub em execução...","sv":"Scrub körs...","zh":"清理正在运行..."},
    "Scrub started": {"cs":"Scrub spuštěn","da":"Scrub startet","de":"Scrub gestartet","el":"Scrub ξεκίνησε","es":"Scrub iniciado","fr":"Scrub démarré","hi":"Scrub शुरू हुआ","it":"Scrub avviato","ja":"スクラブ開始","nl":"Scrub gestart","no":"Scrub startet","pl":"Scrub uruchomiony","pt":"Scrub iniciado","sv":"Scrub startad","zh":"清理已启动"},
    "Storage Pools": {"cs":"Úložné pooly","da":"Lagringspools","de":"Storage-Pools","el":"Ομάδες αποθήκευσης","es":"Grupos de almacenamiento","fr":"Pools de stockage","hi":"स्टोरेज पूल","it":"Pool di archiviazione","ja":"ストレージプール","nl":"Opslagpools","no":"Lagringspooler","pl":"Pule pamięci masowej","pt":"Pools de armazenamento","sv":"Lagringspooler","zh":"存储池"},
    "System Alerts": {"cs":"Systémová upozornění","da":"Systemadvarsler","de":"Systemwarnungen","el":"Ειδοποιήσεις συστήματος","es":"Alertas del sistema","fr":"Alertes système","hi":"सिस्टम अलर्ट","it":"Avvisi di sistema","ja":"システムアラート","nl":"Systeemwaarschuwingen","no":"Systemvarsler","pl":"Ostrzeżenia systemowe","pt":"Alertas do sistema","sv":"Systemvarningar","zh":"系统警报"},
    "The snapshot rollback was completed successfully.": {"cs":"Návrat ke snímku byl úspěšně dokončen.","da":"Tilbageføring til øjebliksbillede fuldført.","de":"Snapshot-Rollback wurde erfolgreich abgeschlossen.","el":"Η επαναφορά στιγμιότυπου ολοκληρώθηκε επιτυχώς.","es":"La reversión de la instantánea se completó con éxito.","fr":"La restauration de l'instantané a été effectuée avec succès.","hi":"स्नैपशॉट रोलबैक सफलतापूर्वक पूरा हुआ।","it":"Il ripristino dello snapshot è stato completato con successo.","ja":"スナップショットのロールバックが正常に完了しました。","nl":"Terugdraaien naar snapshot is succesvol voltooid.","no":"Tilbakerulling til øyeblikksbilde fullført.","pl":"Wycofanie do migawki zakończone pomyślnie.","pt":"A reversão do instantâneo foi concluída com sucesso.","sv":"Återställning till ögonblicksbild har slutförts.","zh":"快照回滚已成功完成。"},
    "This may affect performance.": {"cs":"Toto může ovlivnit výkon.","da":"Dette kan påvirke ydeevnen.","de":"Dies kann die Leistung beeinträchtigen.","el":"Αυτό μπορεί να επηρεάσει την απόδοση.","es":"Esto puede afectar al rendimiento.","fr":"Cela peut affecter les performances.","hi":"इससे प्रदर्शन प्रभावित हो सकता है।","it":"Questo può influire sulle prestazioni.","ja":"パフォーマンスに影響する可能性があります。","nl":"Dit kan de prestaties beïnvloeden.","no":"Dette kan påvirke ytelsen.","pl":"Może to wpłynąć na wydajność.","pt":"Isso pode afetar o desempenho.","sv":"Detta kan påverka prestandan.","zh":"这可能会影响性能。"},
    "Use HTTPS": {"cs":"Použít HTTPS","da":"Brug HTTPS","de":"HTTPS verwenden","el":"Χρήση HTTPS","es":"Usar HTTPS","fr":"Utiliser HTTPS","hi":"HTTPS का उपयोग करें","it":"Usa HTTPS","ja":"HTTPSを使用","nl":"HTTPS gebruiken","no":"Bruk HTTPS","pl":"Użyj HTTPS","pt":"Usar HTTPS","sv":"Använd HTTPS","zh":"使用 HTTPS"},
}

stats = defaultdict(int)
for d in sorted(str(p) for p in LANG_DIR.rglob("en.json")):
    direc = Path(d).parent
    en = json.loads(Path(d).read_text(encoding="utf-8-sig"))
    for lang in LANGS:
        lf = direc / f"{lang}.json"
        if not lf.exists():
            continue
        ld = json.loads(lf.read_text(encoding="utf-8-sig"))
        mod = False
        for k, ev in en.items():
            if k not in ld:
                continue
            if str(ld[k]).strip().lower() != str(ev).strip().lower():
                continue
            evs = ev.strip()
            if evs in T:
                t = T[evs].get(lang)
                if t:
                    ld[k] = t
                    mod = True
                    stats[lang] += 1
        if mod:
            lf.write_text(json.dumps(ld, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

print("Fixed:", dict(stats))
print("Total:", sum(stats.values()))
