// Package xapian reads the Xapian 1.4 "glass" full-text and title indexes
// that libzim embeds in ZIM files (X/fulltext/xapian, X/title/xapian) and
// ranks results the way libzim's Searcher and SuggestionSearcher do.
//
// Everything here is an original Go implementation. The on-disk format and
// libzim's analysis rules were learned by reading Xapian and libzim sources
// (both GPL); no code was copied. The byte layouts and analysis rules are
// documented in FORMAT.md next to this file, and golden tests generated by
// scripts/localwiki/fixtures/ (real libzim 9.8.2 / Xapian 1.4.23 output) pin
// the behaviour.
//
// Supported: single-file (compacted) glass databases, format 2016-03-14,
// block sizes 2-64 KiB, compressed and multi-component items. Anything this
// reader does not implement (another backend such as Honey, another glass
// format, a block size outside 2-64 KiB) fails Open with ErrUnsupportedFormat;
// structurally damaged data, including B-tree keys that are not strictly
// increasing, fails with ErrCorrupt (test both with errors.Is). Index data
// never causes a panic, and memory use is bounded (tags 16 MiB, block cache
// 4 MiB per Database). Callers treat any Open error as "full-text
// unavailable" and use title search only.
//
// Known, deliberate differences from libzim:
//   - Suggest treats quotes, brackets and +/- prefixes as separators (libzim's
//     query parser would build phrase, group and love/hate queries from them).
//   - Suggest reads at most 4,194,304 terms (maxPartialScan) per prefix
//     expansion before keeping the 100 most frequent; libzim reads every term
//     with the prefix. Real word prefixes have far fewer terms.
//   - A query without word characters expands to the 100 most frequent terms
//     starting with it; libzim's OP_WILDCARD takes all of them (such prefixes
//     match only titles without word characters, a handful at most).
//   - Phrase checks re-tokenise the stored title (value slot 0) instead of
//     reading the position table; for libzim-built title indexes this gives
//     the same positions.
//   - Search is a faithful Xapian AND/OR; dropping unknown query words is the
//     caller's job (ExistingTerms).
//   - Search returns hits only from the MaxSearchWindow (10,000) best-ranked
//     documents; libzim pages through any number. estimatedTotal is exact.
//   - Normalisation and tokenisation use Go's Unicode tables (Go 1.27 and
//     golang.org/x/text: Unicode 17.0), libzim 9.8 uses ICU 73.2 (Unicode
//     15.0) and Xapian 1.4.23's own tables. Code points added or reclassified
//     since can lowercase, lose marks or split into words differently, so a
//     query containing them may miss documents libzim would find. A
//     comparison over all 1.1M code points found two such differences
//     (U+0295 and U+1171E).
//   - When more than 100 terms start with the partial word of a suggestion
//     query and several tie at the cut-off term frequency, libzim picks among
//     them with std::nth_element; this package keeps the earliest in term
//     order.
package xapian
