//go:build ignore

// generate_model_registry.go fetches the latest models.dev API data and generates
// internal/llm/model_registry_data.go with static model metadata.
//
// Usage:
//
//	go run scripts/generate_model_registry.go
//
// This will:
//  1. Fetch https://models.dev/api.json
//  2. Parse model metadata (context window, pricing, capabilities)
//  3. Filter for providers known to AuraGo
//  4. Write internal/llm/model_registry_data.go
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// Mapping from AuraGo provider type to models.dev provider ID
var providerMapping = map[string]string{
	"openai":      "openai",
	"anthropic":   "anthropic",
	"google":      "google",
	"deepseek":    "deepseek",
	"groq":        "groq",
	"mistral":     "mistral",
	"xai":         "xai",
	"moonshot":    "moonshotai",
	"qwen":        "alibaba",
	"zai":         "zai",
	"copilot":     "github-copilot",
	"minimax":     "minimax",
	"lmstudio":    "lmstudio",
	"workers-ai":  "cloudflare-workers-ai",
	"openrouter":  "openrouter",
	"opencode-go": "opencode-go",
	// Local providers not in models.dev
	"ollama":   "",
	"llamacpp": "",
}

type ModelInfo struct {
	ID                       string
	Name                     string
	Provider                 string
	ContextWindow            int
	MaxOutputTokens          int
	SupportsToolCall         bool
	SupportsReasoning        bool
	SupportsStructuredOutput bool
	InputPricePer1M          float64
	OutputPricePer1M         float64
	CacheReadPricePer1M      float64
	CacheWritePricePer1M     float64
}

func main() {
	// Fetch from models.dev API
	fmt.Fprintln(os.Stderr, "Fetching models.dev API...")
	data, err := fetchModelsDevAPI()
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error fetching models.dev API:", err)
		os.Exit(1)
	}

	var allProviders map[string]interface{}
	if err := json.Unmarshal(data, &allProviders); err != nil {
		fmt.Fprintln(os.Stderr, "Error parsing JSON:", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Loaded %d providers from models.dev\n", len(allProviders))

	var allModels []ModelInfo

	for auraProvider, modelsDevID := range providerMapping {
		if modelsDevID == "" {
			continue
		}
		provider, ok := allProviders[modelsDevID].(map[string]interface{})
		if !ok {
			fmt.Fprintf(os.Stderr, "Warning: provider %s (AuraGo: %s) not found in models.dev\n", modelsDevID, auraProvider)
			continue
		}

		models, ok := provider["models"].(map[string]interface{})
		if !ok {
			continue
		}

		for modelID, modelData := range models {
			model := modelData.(map[string]interface{})
			info := ModelInfo{
				ID:       modelID,
				Provider: auraProvider,
			}
			if name, ok := model["name"].(string); ok {
				info.Name = name
			}
			if toolCall, ok := model["tool_call"].(bool); ok {
				info.SupportsToolCall = toolCall
			}
			if reasoning, ok := model["reasoning"].(bool); ok {
				info.SupportsReasoning = reasoning
			}
			if so, ok := model["structured_output"].(bool); ok {
				info.SupportsStructuredOutput = so
			}

			// Parse limits
			if limit, ok := model["limit"].(map[string]interface{}); ok {
				if ctx, ok := limit["context"]; ok {
					switch v := ctx.(type) {
					case float64:
						info.ContextWindow = int(v)
					}
				}
				if out, ok := limit["output"]; ok {
					switch v := out.(type) {
					case float64:
						info.MaxOutputTokens = int(v)
					}
				}
			}

			// Parse cost
			if cost, ok := model["cost"].(map[string]interface{}); ok {
				if input, ok := cost["input"]; ok {
					switch v := input.(type) {
					case float64:
						info.InputPricePer1M = v
					}
				}
				if output, ok := cost["output"]; ok {
					switch v := output.(type) {
					case float64:
						info.OutputPricePer1M = v
					}
				}
				if cr, ok := cost["cache_read"]; ok {
					switch v := cr.(type) {
					case float64:
						info.CacheReadPricePer1M = v
					}
				}
				if cw, ok := cost["cache_write"]; ok {
					switch v := cw.(type) {
					case float64:
						info.CacheWritePricePer1M = v
					}
				}
			}

			allModels = append(allModels, info)
		}
	}

	// Sort by provider, then by ID
	sort.Slice(allModels, func(i, j int) bool {
		if allModels[i].Provider != allModels[j].Provider {
			return allModels[i].Provider < allModels[j].Provider
		}
		return allModels[i].ID < allModels[j].ID
	})

	fmt.Fprintf(os.Stderr, "Total models extracted: %d\n", len(allModels))

	// Generate Go file
	var b strings.Builder
	b.WriteString(`// Code generated by scripts/generate_model_registry.go from models.dev API. DO NOT EDIT.
package llm

// ModelRegistryEntry holds static metadata for a model from models.dev.
type ModelRegistryEntry struct {
	ID                       string  ` + "`json:\"id\"`" + `
	Name                     string  ` + "`json:\"name\"`" + `
	Provider                 string  ` + "`json:\"provider\"`" + `
	ContextWindow            int     ` + "`json:\"context_window\"`" + `
	MaxOutputTokens          int     ` + "`json:\"max_output_tokens\"`" + `
	SupportsToolCall         bool    ` + "`json:\"supports_tool_call\"`" + `
	SupportsReasoning        bool    ` + "`json:\"supports_reasoning\"`" + `
	SupportsStructuredOutput bool    ` + "`json:\"supports_structured_output\"`" + `
	InputPricePer1M          float64 ` + "`json:\"input_price_per_1m\"`" + `   // USD per 1M tokens
	OutputPricePer1M         float64 ` + "`json:\"output_price_per_1m\"`" + `  // USD per 1M tokens
	CacheReadPricePer1M      float64 ` + "`json:\"cache_read_price_per_1m\"`" + `
	CacheWritePricePer1M     float64 ` + "`json:\"cache_write_price_per_1m\"`" + `
}

// KnownModelRegistry is the authoritative model metadata from models.dev.
// It maps "provider/model_id" → ModelRegistryEntry.
var KnownModelRegistry = map[string]ModelRegistryEntry{
`)

	for _, m := range allModels {
		key := fmt.Sprintf("%s/%s", m.Provider, m.ID)
		b.WriteString(fmt.Sprintf(`	%q: {
		ID: %q,
		Name: %q,
		Provider: %q,
		ContextWindow: %d,
		MaxOutputTokens: %d,
		SupportsToolCall: %v,
		SupportsReasoning: %v,
		SupportsStructuredOutput: %v,
		InputPricePer1M: %g,
		OutputPricePer1M: %g,
		CacheReadPricePer1M: %g,
		CacheWritePricePer1M: %g,
	},
`, key, m.ID, m.Name, m.Provider, m.ContextWindow, m.MaxOutputTokens,
			m.SupportsToolCall, m.SupportsReasoning, m.SupportsStructuredOutput,
			m.InputPricePer1M, m.OutputPricePer1M, m.CacheReadPricePer1M, m.CacheWritePricePer1M))
	}

	b.WriteString("}\n")

	outFile := "internal/llm/model_registry_data.go"
	if err := os.WriteFile(outFile, []byte(b.String()), 0644); err != nil {
		fmt.Fprintln(os.Stderr, "Error writing file:", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "Wrote %d entries to %s (%d bytes)\n", len(allModels), outFile, b.Len())
}

func fetchModelsDevAPI() ([]byte, error) {
	// Use a simple HTTP GET with Go's net/http
	// We import this inline to avoid external dependencies for the generator
	const code = `
package main
import (
	"fmt"
	"io"
	"net/http"
	"os"
	"time"
)
func main() {
	client := &http.Client{Timeout: 30 * time.Second}
	req, _ := http.NewRequest("GET", "https://models.dev/api.json", nil)
	req.Header.Set("User-Agent", "AuraGo-ModelSync/1.0")
	resp, err := client.Do(req)
	if err != nil { fmt.Fprintln(os.Stderr, "Error:", err); os.Exit(1) }
	defer resp.Body.Close()
	if resp.StatusCode != 200 { fmt.Fprintf(os.Stderr, "HTTP %d\n", resp.StatusCode); os.Exit(1) }
	body, _ := io.ReadAll(resp.Body)
	os.Stdout.Write(body)
}
`
	// Write temp file
	tmpFile := "/tmp/fetch_models_dev.go"
	if err := os.WriteFile(tmpFile, []byte(code), 0644); err != nil {
		return nil, err
	}
	defer os.Remove(tmpFile)

	// Run it
	out, err := os.ReadFile("disposable/models_dev_raw.json")
	if err == nil && len(out) > 0 {
		fmt.Fprintln(os.Stderr, "Using cached disposable/models_dev_raw.json")
		return out, nil
	}

	return nil, fmt.Errorf("please run the fetch script manually: go run %s > disposable/models_dev_raw.json", tmpFile)
}
